### ISSUE TITLE
Philips Hue Outdoor Motion Sensor Sensitivy

### ISSUE THREAD

**Issue by x2005254** [dresden-elektronik/phoscon-app-beta#100]
Hi,

I added 2 Outdoor motion sensor, but one of them is too sensitive when trees moved with the wind and I saw that wi can change sensitivy on Deconz Gui, but I don't know the possible Value :

![image](https://user-images.githubusercontent.com/63404676/79448316-80977480-7fe1-11ea-8e31-1b6093d904b6.png)

someone know what is the possible value, on Hue app I saw in videos that there is 3 level :

![image](https://user-images.githubusercontent.com/63404676/79448449-bc323e80-7fe1-11ea-8e24-a475c61b9091.png)

But I don't have hue gateway and app

Thanks in advance.

**Comment by YKO-de** [comment]
I will consider the idea in future planning.

**Comment by Ltek** [comment]
Why is this closed when people are still asking for this feature a year later?

Please add this feature, I cant imagine its that difficult since it exists in the API, yes?!
