### ISSUE TITLE
The Tradfri remote does not work as expected.

### ISSUE THREAD

**Issue by Kristian8606** [dresden-elektronik/phoscon-app-beta#101]
The left and right arrows on the remote control do not change the color of the bulb all other buttons function correctly.
The bulb has white and warm light.
Is it possible to repair it?

**Comment by morfei1** [comment]
Left and right arrow does not work. You have to pre-configure scenes and map the left and right  buttons to switch scenes in a row or switch to a specific scene. On/off and brightness up/down are ok. They don't need mapping.
