### ISSUE TITLE
Develco Door/window sensor with temperature not added correctly to deConz (conbee2)

### ISSUE THREAD

**Issue by FredrikNas** [dresden-elektronik/phoscon-app-beta#102]
Hi guys! 

I found this thread regarding my issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1667

I have the same problem, the Develco magnet sensor for door / window that i bought cant be added to deconz. 

When i set the sensor in pairing mode (red rapid flashing light) Deconz seems to notice it, and says a device has been found, and lets me pair it to Deconz. But when the pairing is done, the sensor is not added to the list of sensors, nor switches or lights. 

Altought when i move into home assistant, i can see my door/window sensor with 3 entities open/close, temperature and battery status.

Battery and temperature seems to be working, but it does not pickup on the magnet-activity regarding open/close. 

(Sidenote) my Develco smoke sensors added correctly to Deconz, but are registrered as lights.

**Comment by fl0pp** [comment]
> Which deconz version are you running?
> 
> Can you run deconz with `--dbg-info=2 > dbg`, trigger the sensor a few times and provide the debug log? Also, please trigger the device and directly read the IAS zone attributes. It should be enrolled...

I set the dbg-info = 2, restarted deCONZ, and triggered the sensor multiple times.
I did a search on IEEE "0x0015bc001e008a82", and the line

`22:21:41:915 update ZCL value 0x0023/0x0500 for ep: 0x02 0x0015BC001E008A82 after 0 s`

appear only when I put the magnet on the sensor. No update ZCL value when I remove the magnet.

Log:
https://pastebin.com/DgeiD9hK
