### ISSUE TITLE
Feature request: 1) time dependent sensor control, 2) individual scene cycle sets

### ISSUE THREAD

**Issue by Kugelfang666** [dresden-elektronik/phoscon-app-beta#109]
I really like deCONZ running on my home assistant. Currently the system takes care only of my aqara sensors. However, moving forward I'd really like to also move all my hue switches, sensors and bulbs over to deCONZ. Unfortunately, there are two features wich are currently missing for me:

**Time dependent sensor control:**
It would be great if one could specify different scenes to be activated upon motion depending on the time. E.g. 07:00-23:00 Scene A, 23:00-07:00 Scene B

**Scene sets for each switch in one group**
I could not manage to make two dimmer switches within one group cycle through different sets of scenes. Switch 1 Scene 1,2,3 , Switch 2 Scene 3,1,2,6,7

I was about to move my whole setup over but not having a way to specify the scene to be loaded by a sensor as a function of time is deal breaker for me. Currently im using the iOS App iconnecthue to manage my hue bridge which actually allows for both these functions.

**Comment by YKO-de** [comment]
Time control is in progress ;)

**Comment by Kugelfang666** [comment]
Fantastic news, I’m ready to dump my two hue bridges the first second the time control is launched 🥳
