### ISSUE TITLE
Motion sensors doesn't work correctly

### ISSUE THREAD

**Issue by banjohb** [dresden-elektronik/phoscon-app-beta#11]
Hello Guys. When I try to set rules for my motion sensors (Philips and Ikea) the "dimm" and "turn off" function doesn't work - nothing happens after the configured time. The "presence state" and "turn on" works fine. I use the http://ip-adress/pwa for configuration. Any ideas?

**Comment by manup** [comment]
Can you please provide a screenshot of the motion sensor control configuration?

**Comment by banjohb** [comment]
<img width="467" alt="screenshot_16" src="https://user-images.githubusercontent.com/33402492/37253496-adcbfe0a-2532-11e8-949a-fc4ccfb052e3.png">
<img width="886" alt="screenshot_17" src="https://user-images.githubusercontent.com/33402492/37253497-b0807cc0-2532-11e8-80e7-9c8323519d3f.png">
<img width="1092" alt="screenshot_18" src="https://user-images.githubusercontent.com/33402492/37253498-b2ac4290-2532-11e8-8ae7-41b6867f64fe.png">

**Comment by banjohb** [comment]
Solved!!! Safari on macOS was the problem! Worked for me with Firefox!
