### ISSUE TITLE
Sonoff Zigbee device (SONOFF BASICZBR3) is not visible in Phoscon.

### ISSUE THREAD

**Issue by AbDhops** [dresden-elektronik/phoscon-app-beta#110]
Recently I got [SONOFF BASICZBR3 DIY Smart Switch](https://sonoff.tech/product/zigbee-diy-smart-switches/basiczbr3). 
Its visible in deconz over VNC. Could also control the relay over the cluster. However, I am not able to see it in Phoscon app. Even after multiple scanning. 
Could it be because this is not yet supported and newly launched ?

Phoscon Version : 2.05.71 / 11/17/2019
Firmware version : 26490700

**Comment by Ghitafjorback** [comment]
I had the same issue with IKEA blinds, and zladukas solution worked for me as well! I am not sure which one of the toggles helped, I just clicked all of them and then it connected in Phoscon! Thanks @zladukas!

**Comment by sunshineautomate** [comment]
I battled with this today on verson 2.15.03. Inspite of toggling the descriptors buttons I could not get the switch listed in Phoscon. I have several others that I've joined in previous versions. There doesn't seem to be a Permit Join option in DeConz anymore?
