### ISSUE TITLE
Alexa does not detect Conbee gateway 

### ISSUE THREAD

**Issue by funbben** [dresden-elektronik/phoscon-app-beta#112]
Hello, 
I run a conbee II on a TV box with armbian / Debian Stretch (Version : 2.05.71 / 17/11/2019 - Firmware : 26490700)

There is also a Jeedom server installed on the same box. I've set jeedom to run on port 81. and launch a new instance of deconz on port 80 (Jeedom deconz is running on port 8484, And I don't know how to get control over this instance, but controlling device from port web app on 80 is fine)

I used "Upnp Analyzer" that show that deconz expose on port 80 (see below) but no success to get Alexa to find the gateway. 
Also, It seems weird that the serial are "0000000000000000" 

Any idea, on what to look for to solve this ?

```
NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.1.16:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.26.0
GWID.phoscon.de: 0000000000000000
hue-bridgeid: 0000000000000000
NTS: ssdp:alive
NT: urn:schemas-upnp-org:device:basic:1
USN: uuid:df430cc6-7dcc-4a21-ab9e-cbe6c95ec3b6::urn:schemas-upnp-org:device:basic:1

```

**Comment by kangaroo72** [comment]
I have also that issue. My Conbee is on "192.168.200.5" on Port 80 on a AVM Fritz!Box 7590 Router.
Alexa did not find Conbee II. Help would be much appreciated.
