### ISSUE TITLE
Contact Sensor Rules - Door OPEN or CLOSED

### ISSUE THREAD

**Issue by gomensa** [dresden-elektronik/phoscon-app-beta#114]
Hi 
I am a newbie so not sure if this is the right place to address this. 

Is there contact sensor rule support in Phoscon?

I have added a Xiaomi door / window sensor to Phoscon. It shows up in the sensors list and displays when the door is open or closed. However, I cant add a sesnsor rule to a group for the door sensor to control lights.

**Comment by YKO-de** [comment]
Contact and vibration sensor control can now be tested via beta.
