### ISSUE TITLE
Phoscon app Aqara button mapping is wrong

### ISSUE THREAD

**Issue by jfhenriques** [dresden-elektronik/phoscon-app-beta#115]
The button mapping in the Aqara Switch image in phoscon app is all wrong.

- Selecting "1x" button, adds empty icon of the switch, and doesn't appear to do any action
- Selecting "2x" button, adds "1" icon and does single click action
- Selecting shake button, adds "2" icon and does double click action

I can see the events arriving correctly to home assistant tho.

Version 2.05.69 / 06/09/2019
Firmware 26330500

**Comment by YKO-de** [comment]
I'm working on it. Ordered the device.

**Comment by StephanStS** [comment]
I think it's identical to #70
@jfhenriques: Which firmware do you have within the Aqara buttons? I have Xiaomi Smart Switch Aqara WXKG12LM, Version 20180629 and I'd like to find out whether the Aquara devices are also updatable via an Aqara gateway like the Philips Hue devices can be updated via the Hue gateway.

**Comment by jfhenriques** [comment]
@StephanStS yes it seems is the same issue.

Mine are WXKG12LM and same version of yours: 20180629.

**Comment by StephanStS** [comment]
Tested successful with phoscon 2.05.86 / 15.10.2020.  
Tested with phoscon.de/pwa and phoscon.de/pwabeta from 25.10.2020.

Issue can be closed.

**Comment by jfhenriques** [comment]
@StephanStS thank you for the heads up. I tested with pwabeta and in fact I was able to configure the switch correctly.

I'll wait until 2.05.86 goes out of "pre-release" for final confirmation and close the ticket.

**Comment by psaggiomo** [comment]
Hi, I have the same issue with WXKG11LM Rev.2. Short single press leads to No operation

**Comment by StephanStS** [comment]
@psaggiomo: Hello Paolo, which versions do you run?
- Conbee firmware
- Phoscon / deconz

See there:
<img src="https://user-images.githubusercontent.com/57687516/101679657-ed271e00-3a5f-11eb-8b35-1a8446ce1332.png" alt="drawing" width="400"/>

**Comment by psaggiomo** [comment]
hi Stephan;
![image](https://user-images.githubusercontent.com/51875380/101695070-59138180-3a74-11eb-94e7-6512ba28b8b9.png)

**Comment by StephanStS** [comment]
At my setup this is working. Possibly you could check to reassign the single press after you did the update to version 2.07.01.  
I.e. removing the button, adding it again and adding the mapping again.

**Comment by psaggiomo** [comment]
Hello. I have removed and added, and it doesn't work again. I have another one and it works.

The not working switch does not show the version:
![image](https://user-images.githubusercontent.com/51875380/101988423-c7855900-3c99-11eb-9caf-93b152976a30.png)
![image](https://user-images.githubusercontent.com/51875380/101988427-cd7b3a00-3c99-11eb-9777-8c0b7c3f4176.png)

**Comment by StephanStS** [comment]
Hello @psaggiomo: Could it be that the switch is defect. 
I could imagine that the value '2' is a sticky value, e.g. due to a shortcircuit on the p.c.b. or due to a firmware error.

My proposal would be to remove the battery of the switch for about 1 minute and then test again. Otherwise disassemble the switch and look for shortcircuits. Possibly the mechanics of the press button has a mechanical damage.

**Comment by psaggiomo** [comment]
Hi @StephanStS. With Home Assistant I receive deconz_event 1002 when I single press the button. The issue is only on Phoscon Switch editor.

**Comment by manup** [comment]
Hi in case the switch is reported as lumi.sensor_switch.aq2 the upcoming beta has a fix https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3918

I've testet also `lumi.sensor_switch.aq3` and `lumi.remote.b186acn01` which look the same physically.

**Comment by psaggiomo** [comment]
Hi, is it normal in the log?

No button handler for: lumi.remote.b1acn01 endpoint: 0x01 cluster: BASIC (0x0000) command: 0x0A payload[0]: 001
