### ISSUE TITLE
Tradfri 5 button remote < > buttons not working

### ISSUE THREAD

**Issue by repiuk** [dresden-elektronik/phoscon-app-beta#116]
The < and > buttons do not work. All others can be setup with the phoscon app. I would prefer a standard binding to a light like ikea does. A simple cycling of the colours.
Upgraded the remote firmware without effect. Removing it and repairing with conbee has no effect. 
Tried the standard ikea setup by pairing the light to conbee and pairing the remote to the light results in a light not responding to conbee. This workaround worked with Hue. 
I'm using home assistant. 
I do see the deconz_events for the buttons (400x and 500x) in home assistant
Also remarkable: On the Main Page of Phoscon this remote is listed on the bottom of the list (I have one paired) and it can't be selected like Philips Dimmers and or connected directly to a light

**Comment by YKO-de** [comment]
Please try again with version 77. The problem should no longer occur. Otherwise open issue again.

**Comment by j4c013** [comment]
FYI: The deCONZ version within home assistant has been downgraded to 2.05.75

"since it has been reported that 2.05.77, and possibly also 2.05.76, is causing issues for several users."

**Comment by repiuk** [comment]
Yes, since I'm using Home Assistant (like so many others I guess), I can't test this. deCONZ was downgraded.

**Comment by j4c013** [comment]
Well, you can test it, but do you want to? I will wait (for now).

**Comment by repiuk** [comment]
Sure I can wait but this issue has been closed. I can't open it again... I'll just wait, would be very nice if this would work.

**Comment by j4c013** [comment]
Got an update in Home Assistant and now running on 2.05.78.
I re-assigned my buttons after they didn't work anymore.
Now all of the buttons work except for assigning a button to the 'cold' function.
All of the other functions like warmer, dimming etc work.

**Comment by cool-RR** [comment]
I'm on 2.11.05 and this problem is still happening. I can use the dim-up and dim-down buttons on my Tradfri remote, but not the other 3 buttons. Can you please reopen this issue?

**Comment by cool-RR** [comment]
After a restart, the middle button started working. But the < and > buttons still don't work.
