### ISSUE TITLE
Phoscon - specific time for motion sensor

### ISSUE THREAD

**Issue by maikkoe** [dresden-elektronik/phoscon-app-beta#118]
Hi all,

I configured a Tradfri Motion Sensor for one of my groups. It works correctly, but i want to use a specific time for eg. from 8pm till 11pm and not 'all time' or 'from dusk till dawn'. Are there any possibilities?

**Comment by YKO-de** [comment]
A colleague is currently working on this topic.

**Comment by morfei1** [comment]
+1
