### ISSUE TITLE
Support for Aqara Smart Vibration Sensor DJT11LM

### ISSUE THREAD

**Issue by Cavemanz** [dresden-elektronik/phoscon-app-beta#119]
This seems to be a new item just released. Model: DJT11LM.
Any plans to get support for it in Deconz?

https://www.gearbest.com/smart-home-controls/pp_009661787808.html?wid=1433363
https://www.aliexpress.com/store/product/Xiaomi-Aqara-Smart-Motion-Sensor-International-Edition/329388_32912246474.html

https://www.youtube.com/watch?v=odnaG2I387U

**Comment by YKO-de** [comment]
It could be that the sensor has not yet delivered all attributes. I didn't see any vibration just after I learned it. A little shaken. Now it works. 
![image](https://user-images.githubusercontent.com/55535297/84253589-6b862000-ab10-11ea-93b1-dd342fa1217b.png)

**Comment by damajor** [comment]
I have some issues to use this sensor on my system (rpi3+raspbee2) with latest firmware.

![vncviewer_2020-10-25_23-47-54](https://user-images.githubusercontent.com/1475820/97121190-a8982b00-171c-11eb-92a1-e6bd96417a41.png)

After some time it appears like this:

![image](https://user-images.githubusercontent.com/1475820/97121205-c36a9f80-171c-11eb-845a-ab6882ca6967.png)

On the webgui:

![image](https://user-images.githubusercontent.com/1475820/97121226-e1d09b00-171c-11eb-919d-3f1adba45a89.png)

Node info:

![image](https://user-images.githubusercontent.com/1475820/97121232-ef862080-171c-11eb-8d08-b353a18f4908.png)

Cluster info "Basic"

![image](https://user-images.githubusercontent.com/1475820/97121236-ff9e0000-171c-11eb-8ac3-5cfe6958481c.png)

Cluster info "Identity"

![image](https://user-images.githubusercontent.com/1475820/97121243-117fa300-171d-11eb-92a6-587e1f9191ce.png)

Cluster info "Door Lock"

![image](https://user-images.githubusercontent.com/1475820/97121257-278d6380-171d-11eb-8aa6-3b4db0f7ad16.png)
![image](https://user-images.githubusercontent.com/1475820/97121262-31af6200-171d-11eb-9395-49cae1384e7b.png)
![image](https://user-images.githubusercontent.com/1475820/97121266-3bd16080-171d-11eb-8d6c-c34ba7909bb0.png)


In the log I can see some "tilt", "shake" & "drop" events:

```
APS-DATA.indication srcAddr: 0xc9b7, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0101, lqi: 255, rssi: -46
   asdu: 181a0a5500210100
[INFO] - Button 1007 Shake
ZCL attribute report 0x00158D00032CB168 for cluster: 0x0101, ep: 0x01, frame control: 0x18, mfcode: 0x0000
APS-DATA.indication srcAddr: 0xc9b7, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0101, lqi: 255, rssi: -46
   asdu: 181b0a5500210300
[INFO] - Button 1008 Drop
ZCL attribute report 0x00158D00032CB168 for cluster: 0x0101, ep: 0x01, frame control: 0x18, mfcode: 0x0000
skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
skip binding for attribute reporting of ep: 0x00 cluster 0x1000 (end-device might sleep)
APS-DATA.indication srcAddr: 0xc9b7, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0101, lqi: 255, rssi: -40
   asdu: 181c0a0805251a00f5ffaf04
[INFO] - No button handler for: lumi.vibration.aq1 endpoint: 0x01 cluster: DOOR_LOCK (0x0101) command: 0x0A payload[0]: 008
ZCL attribute report 0x00158D00032CB168 for cluster: 0x0101, ep: 0x01, frame control: 0x18, mfcode: 0x0000
```

Any help to get it working ?

**Comment by ebaauw** [comment]
From the log it is working.  What’s your issue?

**Comment by Mimiix** [comment]
Yep, broken since 86. Fix is already merged. Waiting on new release.
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3455

**Comment by damajor** [comment]
I just figured it out :) Thank you.
