### ISSUE TITLE
Phoscon, doubleclick events for Xiaomi WXKG02LM Rev.2

### ISSUE THREAD

**Issue by sjostrand** [dresden-elektronik/phoscon-app-beta#122]
ConBee on Raspberry 3b+
Firmware: 26350500
Version: 2.05.77
OS: Raspbian Buster
Switch: Xiaomi Aqara WXKG02LM Rev.2

I'm trying to set up actions for double click (and maybe even hold). But I cannot find a way to do in the switch editor. 
I verified in HA that events are being sent (1001, 1002, 1004, 2001, 2002, 2004, 3001....) when clicking, double clicking and holding, so it's probably just be that the settings are not available in the switch editor?

**Comment by Mimiix** [comment]
I moved it :)

**Comment by tomillr** [comment]
Same goes for the 1-button wireless switch from Aqara as well:
https://github.com/dresden-elektronik/phoscon-app-beta/issues/72

I've also raised this issue of the missing "double-press"- and "hold"-action also. Maybe you can combine the two issues?
https://github.com/dresden-elektronik/phoscon-app-beta/issues/73

**Comment by YKO-de** [comment]
Right now, this is really not working. But we're already working on fixing it.
