### ISSUE TITLE
Xiaomi WXKG02LM first press not registering

### ISSUE THREAD

**Issue by cappadanna** [dresden-elektronik/phoscon-app-beta#123]
Hi. I’m using two Xiaomi WXKG02LM switches controlling a couple of Ikea bulbs using a RPi with Raspbee. I have them setup for toggling the bulbs on/off in the Phoscon app.

The problem is that often the first press won’t register to turn on/off the lights. I often have to press them a second time.

However, i can see the Xiaomi switches sending commands the first time since i see them ”bouncing” in the Apple home app (using homebridge hue)

Anyone have had any similar problem?

2.05.57 with fw. 26300500

**Comment by ausminternet** [comment]
> However, the problem still occurs when using the "Toggle dimming up/down, on/off" functionality. I was using this, very nifty, feature when I "still was not able to get it working" in my comments above and have now stopped using that.

Same here, still not working for the combined toggle/dimming action.

**Comment by YKO-de** [comment]
@ausminternet I think I have found the mistake. Could you please test it once at phoscon.de/pwabeta and give me some feedback? Just delete the rule again and create a new one. Thanks

**Comment by ausminternet** [comment]
Sorry for the delay. @YKO-de it worked like a charm, thx.
