### ISSUE TITLE
Feature Request: Ability to create rules based on temp sensor

### ISSUE THREAD

**Issue by frederikbay** [dresden-elektronik/phoscon-app-beta#125]
Would love the ability to create rules based on temp sensor (and humidity), so that if a room hits a set temp then I cloud turn on a smartplug.

Below temp - turn plug off 

Thanks for a great and solid product

**Comment by morfei1** [comment]
+1, it would be great, if can control based on temp & humidity!

**Comment by tomillr** [comment]
+1 rules based on temp and/or humidity would be useful addition indeed. Would love to use those to automatically control the ventilation in my bath- or laundry-room.

**Comment by frederikbay** [comment]
As the temp and humidity sensors AFAIK only report in every 30 min. it could be useful with a "timer" so that, say the humidity is 70%, trigger a switch and turn it off after 15 min

**Comment by frederikbay** [comment]
Post to keep active
