### ISSUE TITLE
(Not an issue) Adding OSRAM (LEDVANCE) SMART+ Bulbs

### ISSUE THREAD

**Issue by fullphat** [dresden-elektronik/phoscon-app-beta#126]
Just posting this in case it's useful / can be added to an FAQ.

Managed to get an OSRAM (LEDVANCE) SMART+ bulb added to Phoscon/deCONZ after some messing about.  

Firstly, it seems the bulb arrived pre-paired as Phoscon couldn't detect it during a scan, so it needed reseting.  There were no instructions included on how to reset the bulb, but a Google indicated a 5x off/on power cycle would do this.  This is correct, however the instructions say to wait 5 seconds between turning on and off - I found this to be too long a pause and it should be more like 2 seconds between each off and on.

Once the bulb had reset, I ran another scan, but still no luck.  It seems the bulb has to be turned off and back on during the scan for it to be detected.

Hope this helps others who might be struggling!

**Comment by letszb** [comment]
There are instructions to reset Osram (and others) in the Phoscon App:
Menu > Help > Reset lights > Osram

In the Phoscon App: If you go to group > Edit > Manage lights > Add new lights you see:
Note: Turn off and on the IKEA or OSRAM lights once

There are videos for reseting Osram bulbs:
https://www.youtube.com/watch?v=innZSTe6sHg&list=PLCZWu1Vkf3aldqzL3pfpNvo4SGwvqwJwh&index=5
