### ISSUE TITLE
Conbee 2 - updates

### ISSUE THREAD

**Issue by TungstenE2** [dresden-elektronik/phoscon-app-beta#127]
Hi all,

According to gateway menu my version 2.05.71is up to date.
I thought there is OTA update available. 

![grafik](https://user-images.githubusercontent.com/39955685/81852767-d6692900-955b-11ea-926c-531ae20bc2ab.png)

But now I see manual instructions and several versions.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

http://deconz.dresden-elektronik.de/deconz-firmware/?C=M;O=D

![grafik](https://user-images.githubusercontent.com/39955685/81853126-57c0bb80-955c-11ea-906d-640a5cd8e17b.png)

Which version is latest stable to be used with Conbee 2 on Raspberry Pi?

deCONZ_ConBeeII_0x26580700.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF

I am a bit confused about the updates. 

thx

**Comment by YKO-de** [comment]
Updating via the Phoscon App is associated with some difficulties. We are working on it.
