### ISSUE TITLE
Sonoff Basiczbr3 issues

### ISSUE THREAD

**Issue by TungstenE2** [dresden-elektronik/phoscon-app-beta#129]
Hi all,

I am using V2_05_74 and Conbee2 with Sonoff Basiczbr3.

Issue 1: Basiczbr3 is listed as light but I should be switch. I know this was discussed before, but I does not make it better.

Issue 2: In Phoscon App state of Basiczbr3 is not correct. I am using FHEM and Android App HUE Essentials. All state switchening in HUE Essentials is successfull and shown in FHEM correct. In Phoscon App state in light group is not updated, and toggeling state by pressing the bulb symbol is not always changing state. Bulb symbol is only sometimes changing state, but is also changing symbol to off again after a couple of sec, while Basiczbr3 is still turned on. So Phoscon App is not showing correct state of connected device.

![grafik](https://user-images.githubusercontent.com/39955685/81902671-d0f1fa00-95c0-11ea-93ba-743fd115760a.png)

**Comment by morfei1** [comment]
Hello! Use the workaround described in this issue to add it to deconz/phoscon. If you do it correctly, it will most probably appear as a switch.

https://github.com/dresden-elektronik/phoscon-app-beta/issues/110

**Comment by etique57** [comment]
Hello,

I have a Sonoff BASICZBR3 working fine as a switch with Deconz. It works well through Phoscon when **_toggled_** (also with Home Assistant Deconz integration). When toggled, the relay clicks and the circuit closes and the light switches on.

But when it is inside a scene defined in Phoscon, it doesn't work anymore. It's even weirder than that:
- the BASICZBR3 seems to be switched on: it appears so in Home Assistant (and I guess in Deconz, but I didn't check), and the Group/switch in phoscon also detects that it is On (icons are highligthed in yellow) 
- **_BUT_** the relay doesn't click, and the power doesn't go through and the light doesn't actually switch on.

Am I the only one to observe that?
