### ISSUE TITLE
How to configure Hue dimmer?

### ISSUE THREAD

**Issue by ooii** [dresden-elektronik/phoscon-app-beta#13]
Hi,

Is there a way to configure Hue dimmer switch in the Phoscon app? In my case, it seems disabled.
I'm running Version 2.05.12 of 12/03/2018 with Firmware 261E0500.
![](https://snag.gy/t8FW3c.jpg)

**Comment by ebaauw** [comment]
When controlling a group linked from a switch, the commands are limited to what the switch sends.  The Hue dimmer doesn't send any scene commands, see https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1156#issuecomment-455854646.  To recall a scene from a Hue dimmer switch, you would need to create a rule on the gateway.

**Comment by manup** [comment]
You can call scenes with the Philips Hue dimmer switch by using the switch editor:

https://doc.phoscon.de/app/doc.html#group-edit-switches-buttons-en

Note the switch editor is available for normal groups as described in the docs.
In this mode lights **must not** be assigned directly to the switch (as in your screenshot) only the normal group shall be used.

![image](https://user-images.githubusercontent.com/383386/51438191-19d5bf00-1ca9-11e9-8cb6-8d28d4de71f7.png)
