### ISSUE TITLE
Apt does not show version 2.05.75

### ISSUE THREAD

**Issue by bachandi** [dresden-elektronik/phoscon-app-beta#131]
When checking via apt on http://phoscon.de/apt/deconz for buster stable packages I don't see the 2.05.75 version available. 

```
$ apt-cache policy deconz
deconz:
  Installed: 2.05.74-raspbian-buster-stable
  Candidate: 2.05.74-raspbian-buster-stable
  Version table:
 *** 2.05.74-raspbian-buster-stable 500
        500 http://phoscon.de/apt/deconz buster/main armhf Packages
        100 /var/lib/dpkg/status
```

Did the location of the update change?

**Comment by Mimiix** [comment]
Moved this to Phoscon Git :)!

**Comment by YKO-de** [comment]
[https://phoscon.de/en/support#system-update](https://phoscon.de/en/support#system-update)
