### ISSUE TITLE
DEVICE REQUEST: Lutron Connected Bulb Remote Support in Phoscon

### ISSUE THREAD

**Issue by schmosby** [dresden-elektronik/phoscon-app-beta#134]
Hi, I was checking out the beta app today for phoscon and I saw a LUTRON vendor add switch support in the add switch, but it at the moment doesn't seem to support the Lutron Connected Bulb Remote. 

I have them connected though the REST API for now, this is how they show up on the switch page. They dont appear as an option in any of the switch editors currently in phoscon either.
![image](https://user-images.githubusercontent.com/5651207/84570276-7633f580-ad5a-11ea-9c13-cb95814d5ab4.png)

This is how its identified in the rest api/de_web_plugin.cpp, I am having issues getting deconz to read the basic cluster at the moment, let me know if that is needed for the request.

   { VENDOR_LUTRON, "LZL4BWHL01", lutronMacPrefix }, // Lutron LZL-4B-WH-L01 Connected Bulb Remote

Thanks!

**Comment by mysteryan** [comment]
I have a couple of those Lutron remotes working for several months ago when it wasn't in the Phoscon GUI.  When I paired those remotes, a new group was created (much like the Hue Remote Dimmer).  You simply add the bulbs you want to control in that new group that was created and it should work.

**Comment by YKO-de** [comment]
Since there is currently no separate wizard for these switches, they can only be brought into the network via others. And are therefore not usable via the Switch Editor. 

I will include the switches in the planning for the future development of the app.
