### ISSUE TITLE
Phoscon web UI set to old mode

### ISSUE THREAD

**Issue by rwcrosby** [dresden-elektronik/phoscon-app-beta#135]
Somehow I got the Phoscon app set into it's previous web mode and I can't find how to reset it to the current mode.

**Comment by StephanStS** [comment]
@rwcrosby: Could you please add some screenshots that it is more clear what you mean with "previous web mode"?
What do you enter in the browsers address line?

**Comment by rwcrosby** [comment]
That you for the prompt response, about 10 seconds after posting this I figured out all I had to do was log out and back in again.
