### ISSUE TITLE
Can't turn on lights via switch after scheduled turn off in case the lights are already turned off

### ISSUE THREAD

**Issue by nimric** [dresden-elektronik/phoscon-app-beta#136]
I have a schedule to turn off the lights. The problem appears if the lights are already off at the time the schedule gets executed. In this case I can't turn them on anymore via the associated switch. I have to turn them on via the app to get the switch working again.

**Comment by Mimiix** [comment]
@nimric no need, it will auto redirect.

**Comment by YKO-de** [comment]
When did you create the rules for the switch?

**Comment by nimric** [comment]
Hi @YKO-de,

I don't understand your question? Are you interessted in the version number of phoscon?

**Comment by YKO-de** [comment]
The described problem should no longer exist. However, it is possible that the rules were created before the change. Therefore, perhaps simply delete the rules and create new ones.

**Comment by nimric** [comment]
Hi @YKO-de,

I deleted the rule and created a new one as you suggested. Now I can turn the lights on the next day if the lights are already off at the time the schedule gets executed. However, the brightness of the lights is not as expected. It's a really small value now when I turn the lights on.

**Comment by nimric** [comment]
Should I open a new issue for the wrong brightness of the lights?

**Comment by YKO-de** [comment]
Could you describe to me more precisely what kind of time control you have created? A group of people at a certain time of day?

**Comment by nimric** [comment]
Hi @YKO-de,

I created a timer which turns off my lights at 2 o'clock in the morning without a fading time. Therfore I expect it to behave like a press of the Off-button. However, if I turn the lights on the next day the brightness has changed which does not happen when I use the On/Off-button.

**Comment by YKO-de** [comment]
@nimric Use the "group off" function or a previously created scene which dims the group down to 0?

**Comment by nimric** [comment]
@YKO-de I use the "group off" function for the timer

**Comment by YKO-de** [comment]
Okay. I found out what it is after consultation. The group is not only switched off, but also dimmed down. This is to allow for dimming up with a second timer the next morning. If you turn the light on with a switch now, it will be dimmed down to a minimum value.

**Comment by nimric** [comment]
@YKO-de Will you fix it? Dimming should only be applied if a fading time is specified in my opinion.

**Comment by YKO-de** [comment]
Unfortunately this is not easily possible. Because already existing setups could be broken by this. In any case we will discuss it and maybe add an extra option at this point. So that you can decide.
So I would suggest to create a scene with the desired dim value and put it on the switch.

**Comment by nimric** [comment]
@YKO-de Thanks for taking care of this issue. I don't understand your suggestion. The dim value should stay as it is if my timer turns off the lights. I have 2 scenes already with a different dim value and if the timer turns the lights off I want and expect the same state when I turn my lights on again.

**Comment by nimric** [comment]
@YKO-de  Any news on this issue?

**Comment by nimric** [comment]
Pleas open again
