### ISSUE TITLE
pwa - Rename sensor "name already taken" bug

### ISSUE THREAD

**Issue by Webunity** [dresden-elektronik/phoscon-app-beta#137]
Steps to reproduce:
1) Rename a sensor
2) Choose  a name that already exists - Error in red shows
3) Just close the dialog
4) Click on another node to rename
5) Textbox is populated with that node's name but old error remains visible.

**Comment by morfei1** [comment]
I have the same visual problem. It's a little bit  annoying, but it does not break functionality. It would be nice, if it get fixed in the near future.

**Comment by Webunity** [comment]
Thanx @Mimiix ; i couldn't find the Phoscon repo. Will it be tracked there or should this one remain open?

**Comment by Webunity** [comment]
ah wait, now it is in the new repo already :)

**Comment by YKO-de** [comment]
Bug is already fixed in beta. In pwa then with the next release also.
