### ISSUE TITLE
Triggers based on the Phoscon virtual daylight sensor

### ISSUE THREAD

**Issue by morfei1** [dresden-elektronik/phoscon-app-beta#138]
Hello! Is it posible to add the virtual daylight sensor as a trigger in phoscon -  schedule? Right now, we have alarms, and timers. We can on/off lights and use scenes base on the time, but what about using them based on the sun/moon states?

We all have it by default in phoscon, and it's great for automations based on it's states, and it has a lot of states :) .

For exsample:  Turn on/off the lights based on the daylight sensor state - sunrise, sunset and so on. The daylight sensor has 14 states in total, which we can use for various automations directry in phoscon. We don't have to use third party apps (HA for example), that triggers automation based on this sensor state. It will be great, if we are able to do it directry in phoscon, not using third party, IMO. 

Regards!

**Comment by YKO-de** [comment]
Hello. It's possible. Right now, the TODO list is relatively full. But I will include it in future development plans.
