### ISSUE TITLE
2.05.17: Application lost nodes (already paired lights)

### ISSUE THREAD

**Issue by knob-creek** [dresden-elektronik/phoscon-app-beta#14]
Hardware: Raspberry Pi 2, RaspBee
System: Raspbian Stretch 9.4

What i did: connected three Osram lamps (2x Surface Light, 1x A60 RGBW) using the "old" web app.
Since the A60 was a bit unstable, i decided to update its firmware: Reset, connect to Lightify Gateway, update firmware, remove from Lightify Gateway, reset).
I did not remove it from the RaspBee beforehand.  (is there even a way to do this?)
Then, i reconnected it to the RaspBee system: It was found by the scan, however, it did not show up as new device, it "paired" spontaneously.
The 2 Surface Lights were switched off, meanwhile.
Afterwards, the A60 worked well.  However, the two Surface Lights have disappeared.  The Groups they belong to still exist and the scenes belonging to these groups still work, although the groups claim to contain 0 lights.

Is there a way to revive these lights?
Since these lights are somehow still known (entries in zll.db and session.default), they cannot be re-paired.

**Comment by mysteryan** [comment]
It should migrate back automatically.  Lightify gateway should be off so it doesn't rejoin and bulbs should be reset by switching on/off 5 times.

**Comment by knob-creek** [comment]
I'm not exactly sure what you mean.  The A60 lamp (with the new firmware) is back and works well (see above).  The Lightify gateway is unplugged and back in  its drawer.
The other 2 ones, however, were "lost" in the course of rejoining the A60 and are not visible any more.  After i have reset one of them, it cannot be controlled any more, either.  If i reset it, it seems to rejoin immediately, but it cannot be seen anywhere.
As it seems, all i can do now is trying to clean the config files and the zll.db from them and reconnect them afterwards or dump the whole of the configuration and restart from scratch.

**Comment by manup** [comment]
Starting from scratch should not be needed here. How do you know that the surface joins when it's not visible? If it is not at least visible with a blue blinking dot in deCONZ I guess it hasn't joined yet.

For OSRAM lights it's important to pick the right reset sequence matching the light type (they have different sequences).

Here is how it should work:

* Start search for lights in Phoscon App
* Reset the light with matching sequence
* Powercycle the light

![image](https://user-images.githubusercontent.com/383386/38170654-f4dbb34a-358a-11e8-98ce-541b879eb076.png)

**Comment by knob-creek** [comment]
Guten Morgen Manuel und frohe Ostern!
Actually, the lights are joined, i can see them in deCONZ.  (Thanks for that hint, I usually avoid using the qt5 app, as the Pi runs headless and X via ssh is rather laggy.) The node information is incomplete, however: MAC, NWK and Name are there, Model, Vendor and Version are not.
The lamps shortly blink to ack the reset command from the touchlink and they shortly blink again when they are joined.  (I am pretty proficient resetting the lamps, meanwhile. ;-)
I could delete and re-join a node from here.

**Comment by knob-creek** [comment]
Resetting the nodes did the trick.  Thank you.
