### ISSUE TITLE
SAMOTECH/ Tuya motion sensor not showing up

### ISSUE THREAD

**Issue by hastime** [dresden-elektronik/phoscon-app-beta#141]
Hi,

I have recently started using HA and have just added a conbee 2. I have succesfully paired two innr  bulbs and I am now trying to connect a motion sensor from Samotech/Tuya (https://www.samotech.co.uk/products/zigbee-smart-wireless-motion-sensor-compatible-with-echo-plus-and-echo-show-2nd-generation/). When I try and pair it using the 'other' option, it says 'ready' but never appears in the UI.

 I have had a look at the Deconz app and it appears in there, it also shows in HA as an 'RH3040' - but this looks like a different sensor when I Google it (I guess it could use the same chip). Have I missed something? Is there a way to have the sensor show in the Phoscon UI?

Thanks!

**Comment by YKO-de** [comment]
Can you hand me the modelid? This is available in the deCONZ in the basic cluster in the cluster info.

**Comment by gaz8203** [comment]
Hi, I also have the same issue.
![image](https://user-images.githubusercontent.com/38543873/92373078-b4d91200-f0f5-11ea-8612-7cc3566ae572.png)
