### ISSUE TITLE
E1524 ikea round button with latest firmware doesn't work. - Creates a group without ID (or UI has some error)

### ISSUE THREAD

**Issue by dakipro** [dresden-elektronik/phoscon-app-beta#142]
Hi, 
I am on ubuntu with :latest docker and just started adding devices. I can add lights without problems, but when I try to add an older round switch (honesty I didn't know there are two different models, picture attached) the UI does not allow me to click on its group. I tried resetting the gateway, resetting switches and lights and everything, but it just won't work, here are console logs in the browser that appear on click that mention undefined group id

`manual poll
main.js?032385:3 current site: group/lights
main.js?032385:3 goto: control/switch/00:0b:57:ff:fe:c9:ac:7d/group/undefined
main.js?032385:3 current site: group/lights
main.js?032385:3 goto: control/group/1
main.js?032385:3 current site: group/lights
main.js?032385:3 already on: control/group/1
main.js?032385:3 /scene/groupchanged took 0 ms
group.js?600959:3 check FLS-PP lp special groups for 1
group.js?600959:3 fls-pp count 0
`

So the E1810 remote works fine, but E1524 doesn't (I forgot to take a photo without back cover, it has also different battery placement.

![2020-01-29 00 22 42](https://user-images.githubusercontent.com/1586291/73342581-22c77c00-427f-11ea-8176-7abd008e93b9.jpg)

![Screenshot 2020-01-29 00 12 55](https://user-images.githubusercontent.com/1586291/73342607-32df5b80-427f-11ea-83a5-9c07b70470b7.png)

So if I click on the remote group, it selects the first above it so there is nothing I can assign to the old-remote group

**Comment by YKO-de** [comment]
Is the problem still there? Theoretically, switch groups should only be displayed if there is a light inside them.
