### ISSUE TITLE
Can't select Dark Theme.

### ISSUE THREAD

**Issue by Alpakat2** [dresden-elektronik/phoscon-app-beta#145]
Hey,

why can't I select the "Dark" Theme ? Neither in the stable Version nor in the beta. The "Dark" text is kind of gray:

![image](https://user-images.githubusercontent.com/45306709/86130971-4a986580-bae5-11ea-906f-9d6f8f0f2bf5.png)

Is "Dark Mode" still in progress ? 

.tom

**Comment by pattyland** [comment]
If you are adventurous use the HTML Inspector to activate the field... But don't complain if something goes wrong :P

**Comment by Alpakat2** [comment]
Yea, that kind of works...
![image](https://user-images.githubusercontent.com/45306709/86930632-7fd13300-c137-11ea-9249-db8bdf9b2353.png)

I'll assume that this is still in progress...

**Comment by Alpakat2** [comment]
Yea, that kind of works...
![image](https://user-images.githubusercontent.com/45306709/86931261-2cabb000-c138-11ea-9c14-d5f36302404a.png)

I'll assume, that this is still in progress...

**Comment by YKO-de** [comment]
Right now there is no dark theme. It is planned, but not yet foreseeable when it will come.
