### ISSUE TITLE
Issue with left and right buttons on IKEA TRÅDFRI remote control

### ISSUE THREAD

**Issue by maxnumberone** [dresden-elektronik/phoscon-app-beta#148]
Hello,
I have an issue with an IKEA TRÅDFRI remote control.
The left and right buttons are having an assignment issue in the Phoscon App:
![Capture d’écran de 2020-07-02 08-54-00](https://user-images.githubusercontent.com/1675540/86326204-a546d400-bc41-11ea-82d9-9cfe7031f62c.png)
When I select the button to change the color temperature of lights, it is assigning the action to a long press.
Unfortunately there's no possible long press for these 2 buttons on my remote, when you keep one of them pressed it keeps repeating short press/clicks, no long press.
Is it possible this issue comes from the firmware installed on my remote, I have 2.3.014, maybe it was updated by Ikea in a more recent release?
Thank you for your help

**Comment by maxnumberone** [comment]
Thanks, do you need more information?

**Comment by user2202** [comment]
Hi @maxnumberone,

There are two version of this IKEA remote E1525 / E1810 with 2.3.014 the latest firmware for both.

The E1810 has a weird issue where the long press on the left and right arrow buttons was not been sent after a firmware update to 2.3.014 or straight out of the box with that firmware version (as seen in my case) and the soultion was simple, remove the battery, press a few buttons on the remote to completely drain the remote of power and then put the battery back in.

Hopefully that will fix the remote not sending those long hold messages on the left and right buttons for you, then the remote assignment in phoscon should work.

Let me know how you go.

ref https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2618#issuecomment-626327080

**Comment by ebaauw** [comment]
See the other issue: when long pressing the _On/Off_ button, the remote changes the way the _Previous_ and _Next_ buttons work.

**Comment by maxnumberone** [comment]
Oh, great, it worked (not by long pressing the on/off button but by removing the battery).
I'm now able to use < and > buttons.
Thanks

**Comment by MattWestb** [comment]
@maxnumberone The Ikea remotes its steering devices for lights and if you have reading the instruction the function of the on / off button long press is described. Then using scenes with < and > (for colour (temperature) changes) it can happen some bulbs is not getting the command (radio interference power fail and so on) then the lights is out of sync. Then pressing the remotes on / off button long its sending one reset command to the groupe so all light is being synced.
deCON and others have implemented this function little different for using it in HA and the scene reset function is broken and the HA is also not working as intended.

On the firmware side is both version using the same OTA file but can having different factory data setting (I have not dumping the user data of them both then i dont have the old one) and the Zigbee module is updated to the new one (one external pin lesser for using disabling the OTA flash for battery saving).
