### ISSUE TITLE
Sensor control of group randomly fails by night

### ISSUE THREAD

**Issue by jumpiem** [dresden-elektronik/phoscon-app-beta#149]
I created two sensor controls in phoscon app for my corridor light group. One is active during daytime and the other from dusk till dawn. 

Now there is a strange issue with sensor control by night. Sometimes the lights won`t switch on even though there is movement detected in the app (symbol next to motion sensor). On next movement detection the lights switch on again.

![image](https://user-images.githubusercontent.com/67262159/86439222-721b4800-bd08-11ea-827e-3908ad630cf8.png)

For me this is a strange problem, because during daytime the other control set works flawless. I guess there is a different handling for internal state maschine depending on state of virtual daylight sensor. It seems like a race condition problem which occurs only by night.

My setup uses two Philips Hue motion sensors, lights are five innr GU10. Bridge is RaspBee II on RPi1B.
deCONZ 2.05.78, RaspBee II firmware 0x26610700

With previous deCONZ version 2.05.77 and older firmware it's the same behaviour.

**Comment by YKO-de** [comment]
Are there devices in the network that are completely disconnected from the power at night?

**Comment by jumpiem** [comment]
No, all devices stay on during night.

Supplement: I watched the described behaviour also by day, but strangely, much less often.
