### ISSUE TITLE
Problem with light groups in Phoson app

### ISSUE THREAD

**Issue by SimWhite** [dresden-elektronik/phoscon-app-beta#150]
## Describe the bug
There is a problem with light groups in Phoson app. When I try to turn on or turn off the lights clicking on the lights group nothing happens. But when I click on the light inside the group everything is working fine. Because of this problem I can't use sensors to change the lights status.

## Steps to reproduce the behavior

  1. Go to http://phoscon.de/pwa main page.
  2. Click on group lights icon on the left pane — nothing happens.
  3. Click on the light inside the group on the right pane — light turn on and off, everything is fine.

## Environment

 - Host system: Raspberry Pi 4
 - Running method: HomeBridge image with deCONZ installed via menu
 - Firmware version: 264A0700
 - deCONZ version: 2.5.77
 - Device: ConBee II
 - Do you use an USB extension cable: yes

**Comment by SimWhite** [comment]
So the issue will be closed without any replies and fixes?

**Comment by YKO-de** [comment]
From which manufacturer are the lights?

**Comment by SimWhite** [comment]
Light switches identified as:
```
    "manufacturername": "_TYZB01_xfpdrwvc",
    "modelid": "TS0011",
```

Here is the screencast of the problem: https://cln.sh/6W3IgaURsjROiZTm0E3W. Then I click on the light itself everything is working fine. But when I click on the group on the left nothing happened.

**Comment by SimWhite** [comment]
Any updates?

**Comment by YKO-de** [comment]
I think it's because of the light. Not the app. The light does not seem to accept the group command.

@manup Can you help?

**Comment by Jorael57** [comment]
Hello, I have the same issue here.
I have buy this item : https://fr.aliexpress.com/item/4000369677580.html?spm=a2g0s.9042311.0.0.27426c37yjf5WF
With same identification :   
 "manufacturername": "_TYZB01_xfpdrwvc",
  "modelid": "TS0011",

I have try to link 2 differents switch : Ikea Tradfi and Xiaomi wireless switch 2 gangs, but no effect on the light.

I have tried on Jeedom with Deconz Plugin but nothing works from Jeedom.
Regards..

**Comment by sunshineautomate** [comment]
I'm also having the same problem with these lights:
Vendor: _TZ3000_pmvbt5hh
Model: TS0011
