### ISSUE TITLE
DEVICE REQUEST: Namron K4/K8 switches

### ISSUE THREAD

**Issue by habakke** [dresden-elektronik/phoscon-app-beta#152]
The Namron K4/K8 switches (Luzense/Sunricher clone) switches which are sold in the Scandinavian market. The switches have seems to have been partially added to the deconz-rest-plugin. The [Namron K8 switch](https://www.elektroimportoren.no/namron-zigbee-4-kanaler-bryter-k8/4512703/Product.html)

**Namron K8 (4 channel)**
![image](https://user-images.githubusercontent.com/642472/87191873-9cb36500-c2f5-11ea-99c2-d61d573e3500.png)

**Namron K4 (2 channel)**
![image](https://user-images.githubusercontent.com/642472/87191949-c2d90500-c2f5-11ea-8646-eb011d41ae16.png)

**Cluster info (K8):**

![image](https://user-images.githubusercontent.com/642472/87191736-50682500-c2f5-11ea-8861-73d26e6292b3.png)
![image](https://user-images.githubusercontent.com/642472/87191805-78f01f00-c2f5-11ea-9c7e-534c283c4265.png)

**Comment by SwoopX** [comment]
Wtf, the look exactly like the EcoDim switches...

**Comment by YKO-de** [comment]
The 4-channel should be visible in the app. I did not find any entry for the 2-channel in deconz either. So please open an issue in the rest-plugin first.

**Comment by SwoopX** [comment]
@YKO-de it is there, but generically as the differentiation is done on the last digit of the model identifier. Let me know if you need anything else.

While you're on it, can you also include the EcoDim switches? it's exactly the same device.

ED-10010 / ED-10011 -> 1-gang
ED-10012 / ED-10013 -> 2-gang
ED-10014 / ED-10015 -> 4-gang

Thanks!

**Comment by YKO-de** [comment]
Okay. So, theoretically, they should both leave after the next release. EcoDim and Namron.
But you won't have individual pictures yet. Just names.

I'll update the beta tomorrow. You can test it there. If it doesn't work just write it again.
