### ISSUE TITLE
DEVICE REQUEST: Namron Zigbee Dimmer 400W

### ISSUE THREAD

**Issue by habakke** [dresden-elektronik/phoscon-app-beta#153]
The [Namron Zigbee Dimmer 400W](https://www.namron.com/products/namron-zigbee-dimmer-400w/) dimmers are sold in the Scandinavian market by one of the biggest supplier of electrical equipment and cabling.

**Namron Zigbee Dimmer 400W**
![image](https://user-images.githubusercontent.com/642472/87340080-e5625c80-c547-11ea-8453-680e4af16ac3.png)

**Node info**
![image](https://user-images.githubusercontent.com/642472/87341296-b2b96380-c549-11ea-9c22-4e4dd93c7edb.png)

**Cluster info**
![image](https://user-images.githubusercontent.com/642472/87340185-075bdf00-c548-11ea-93bc-3e76153e525d.png)
![image](https://user-images.githubusercontent.com/642472/87340249-1b9fdc00-c548-11ea-8670-939b6d70434e.png)

**Comment by habakke** [comment]
This one works with the latest deconz-rest-plugin

**Comment by YKO-de** [comment]
The device should be visible in the app after the next release.
