### ISSUE TITLE
Cannot login to the gateway

### ISSUE THREAD

**Issue by fi-sch** [dresden-elektronik/phoscon-app-beta#154]
I've got an issue with Phoscon App Beta. I cannot login to the ConBee II gateway and I'm stuck on first screen.

I'm running DeCONZ via Home Assistant add-on. Home Assistant has SSL configured. Both are up to date.
I've tried connecting via urls:
- phoscon.de/pwabeta/login.html#host/192.168.8.102:8123
- phoscon.de/pwabeta/login.html#host/192.168.8.102:443
- phoscon.de/pwabeta/login.html#host/192.168.8.102:8081

I see the gateway but I cannot click on it and input the password.
![Phoscon Beta App screen](https://user-images.githubusercontent.com/59969726/87525758-3b3f1d80-c68a-11ea-955c-6a9772ae406a.png)

Thanks in advance for your assistance!

EDIT:
I looks like I have an issue with https://phoscon.de/app also.

**Comment by Mimiix** [comment]
You should use your HA ip with 40850 as port or trough ingress.

This is a issue with HA, not phoscon/Deconz.

**Comment by fi-sch** [comment]
> You should use your HA ip with 40850 as port or trough ingress.
> 
> This is a issue with HA, not phoscon/Deconz.

Thanks, it worked. Maybe it's worth to mention that in the readme?

Brs,
Filip
