### ISSUE TITLE
Release file not found by Raspbian buster on Pi4B deconz not loaded

### ISSUE THREAD

**Issue by northseer** [dresden-elektronik/phoscon-app-beta#155]
Having followed the setup instructions several times and carefully, I keep getting the message http://phoscon.de/apt/deconz $(lsb_release Release    404 Not found.

As a result the error 'does not have a release file' is flagged.

And sudo apt update fails to load the files.

This is a newly purchased Pi4B with preinstalled raspbian Buster and no other apps installed yet.

The same problem applies to both the main and the beta versions of the software. Logically speaking the problem appears to be with the files at phoscon, but of course that may be an artefact of the error messaging. 

Any help welcome.

**Comment by letszb** [comment]
It looks like there is the distribution not found in the APT-repository. The manual way should work:

wget http://deconz.dresden-elektronik.de/raspbian/beta/deconz-latest-beta.deb
sudo dpkg -i deconz-latest-beta.deb
