### ISSUE TITLE
app/config (Not Found)

### ISSUE THREAD

**Issue by jonastaedcke** [dresden-elektronik/phoscon-app-beta#157]
I use deCONZ with HomeAssistant but run intro trouble when I try to add some Philips Switches. But step by step. My first problem is at http://phoscon.de/pwa/login.html?123 when i open the (Chrome) browser console and see this:
![image](https://user-images.githubusercontent.com/1809673/88074835-3db4e200-cb78-11ea-8543-74fdf7043ee6.png)

I can't login. When I click on 'Phoscon-GW' and wait for 10 sec the login screen opens. I type my password in and submit the form I have to wait for a long time and receive an error ("Login fehlgeschlagen." / "Login fails"). My console:
```verify password input
login.js?a1493a:3 verify password
login.js?a1493a:3 Error: error on login
    at Object.complete (login.js?a1493a:3)
    at i (jquery-min.js?0baf29:2)
    at Object.fireWith (jquery-min.js?0baf29:2)
    at A (jquery-min.js?0baf29:4)
    at XMLHttpRequest.<anonymous> (jquery-min.js?0baf29:4)
(anonymous) @ login.js?a1493a:3
Promise.catch (async)
submitPassword @ login.js?a1493a:3
dispatch @ jquery-min.js?0baf29:3
q.handle @ jquery-min.js?0baf29:3
jquery-min.js?0baf29:4 POST http://172.30.33.0:40850/api/ net::ERR_EMPTY_RESPONSE
```

When I start the deCONZ Addon in HomeAssistant, login, I get this in console: ```
http://homeassistant.local:8123/api/hassio_ingress/j5veJZAmYfW6gNYp6ORzHAn6RdCERA3dABQmWMQzA9g/pwa/developer.js 404 (Not Found)```
When I try to add a new device (Philips Dimmer Switch): ```http://homeassistant.local:8123/api/hassio_ingress/j5veJZAmYfW6gNYp6ORzHAn6RdCERA3dABQmWMQzA9g/pwa/developer.js 404 (Not Found)```

There are errors on different locations and these must have nothing to do with each other. Often there is one Javascript file missing and the addon/app dosen't work as expected (can't login or add devices). 
I'm new here and it would be awesome to get feedback and an idea to solve my not found problems. Thank you :) 

## Environment
Host system: Raspberry Pi 4B 64bit
Running method: HomeAssistant with deCONZ installed as a Addon
HomeAssistant Version: 0.112.4
deConz Version: 2.05.79 / 22.5.2020, Firmware: Not connected
Device: RaspBee II

the configuration: 
`device: /dev/ttyAMA0`

**Comment by jonastaedcke** [comment]
After some hours I solved my problem. First: for my system the url above doesn't work (I use Docker)!
To get everything work well I changed the device path to ``device: /dev/ttyS0``

**Comment by SwoopX** [comment]
@jonastaedcke Glad that you were able to tackle the root cause. So my understanding is that the root cause was the HA configuration. As this is not our turf, there's nothing for us to do here.

As for the `developer.js` not being found, I already reported this to the Phoscon devs. This should already have been resolved, at least with the online beta version of Phoscon.

Mind closing this one?
