### ISSUE TITLE
Use Xiaomi door contact as sensor for lightning control?

### ISSUE THREAD

**Issue by mgrn0** [dresden-elektronik/phoscon-app-beta#158]
There is a relatively detailed (archived) discussion about the idea of using a Xiaomi door contact as sensor for lightning control, either as switch or as sensor / rule (or both) at 

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1717
and
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1755

Could we please re-discuss this use case? It would be really beneficial..

**Comment by Proche72** [comment]
It is in beta as @YKO-de mentioned here: https://github.com/dresden-elektronik/phoscon-app-beta/issues/114

**Comment by mgrn0** [comment]
aaaah thanks I was not aware of that and obviously I searched not thoroughly enough before opening the issue. will give it a try!
