### ISSUE TITLE
2.05.17 do not enable deconz-wifi.service unconditionally

### ISSUE THREAD

**Issue by knob-creek** [dresden-elektronik/phoscon-app-beta#16]
Hardware: Raspberry Pi 2 with RaspBee module
Software: deconz-2.05.17-qt5.deb

The script `deCONZ-init.sh` enables the script `deCONZ-WIFI.sh` unconditionally.  However, if the Pi is hooked to the network via ethernet, this service pollutes the `daemon.log` with error messages:
`Mar 31 16:50:27 raspberrypi deCONZ-WIFI.sh[11884]: Device "wlan0" does not exist.`

**Comment by phsdv** [comment]
Same issue here, every 30 seconds 4 lines are added to /var/log/daemon.log making the file not very readable any more.

**Comment by manup** [comment]
Which version are you using? 2.05.19 silenced these output (might have forgot a line)

**Comment by phsdv** [comment]
I just updated to 2.05.19 and most lines are gone. Only one line

deCONZ[328]: QGraphicsScene::addItem: item has already been added to this scene

is still being added but that could be another issue?

**Comment by manup** [comment]
Yes thats in the deCONZ core, however good point it will be removed too.

**Comment by peer69** [comment]
Running 2.05.23 but still getting output written to daemon.log und syslog: 
`May 12 10:46:32 zigbee-gateway deCONZ-WIFI.sh[239]: Device "wlan0" does not exist.
May 12 10:47:03 zigbee-gateway deCONZ-WIFI.sh[239]: Device "wlan0" does not exist.
May 12 10:47:35 zigbee-gateway deCONZ-WIFI.sh[239]: Device "wlan0" does not exist.
May 12 10:48:06 zigbee-gateway deCONZ-WIFI.sh[239]: Device "wlan0" does not exist.`

Any way to disable the wifi entirely? Will disabling the deconz-wifi service do any harm?

**Comment by manup** [comment]
Disable deconz-wifi systemd service is fine. The error message will be silenced in future.

**Comment by knob-creek** [comment]
@peer69 Note, that if the deconz.service still depends on other services (by `Wants=deconz-xxx.service` in the deconz.service file), systemd will re-enable and start these services upon reboot.
(My system still runs on 2.05.17)

**Comment by thymjan** [comment]
This is still happening in 2.05.64:
 
```
May 25 15:56:23 hobby deCONZ-WIFI2.sh[15439]: nl80211 not found.
May 25 15:56:23 hobby deCONZ-WIFI2.sh[15439]: Device "wlan0" does not exist.
May 25 15:57:37 hobby deCONZ-WIFI2.sh[15439]: nl80211 not found.
```

**Comment by fretmeat** [comment]
Hello there,
stumpled upon this post while searching for the issue below - maybe others have the same problem.

**Phoscon App Wifi Settings not working after update**

Using a Raspi 1B+ + **Phoscon Image** + Raspbee
I updated to 2.05.67 recently and found my wifi connection broken afterwards.
ethernet would still work and wifi dongle seamingly working.

Found the solution:
Somehow there has been a dist-upgrade at some point - can't remember. . 
for some reason debian stretch uses MAC-based interfaces names.. like wlx05da03bc..... etc..
the app expects WLAN0 to setup the wifi.

To get back to old "wlan0"  the following line has to be added to /boot/cmdline.txt
**net.ifnames=0**

Afterwards the Wifi-setup inside of Phoscon started working again.

**Comment by Hypfer** [comment]
Apparently, deconz-init.sh tries to re-enable the service so just disabling isn't enough. You also have to mask the unit file.

```
Dec 10 15:24:04 phoscon deCONZ-init.sh[1109]:  starting deconz-wifi.service
Dec 10 15:24:04 phoscon deCONZ-init.sh[1109]: Failed to start deconz-wifi.service: Unit deconz-wifi.service is masked.
Dec 10 15:24:04 phoscon deCONZ-init.sh[1109]: Failed to enable unit: Unit file /etc/systemd/system/deconz-wifi.service is masked.
```

**Comment by ckessing** [comment]
Almost the same Problem. I installed a new Pi 3B+ with image Raspian Buster Headless 2.05.72. During boot phase wlan gets an IP but deCONZ-WIFI2.sh destroys it. So the interface wlan0 is down.
Short solution:
After renaming deCONZ-WIFI2.sh to a different Name and configuring the interface manually by wpa_supplicant, all is working fine.
