### ISSUE TITLE
Device request: Develco Humidity Sensor

### ISSUE THREAD

**Issue by fincha** [dresden-elektronik/phoscon-app-beta#161]
Hi,

I am not sure if this is right here, but I have few of develco sensors and some of them are working fine, but specially air sensors, air quality and humidity not. I can't connect them. 

Some of sensors does not appear in object list in frontend but are visible via api in iobroker, and this is fine for me, but not this two sensors. 

Maybe if there are some helpful commands to debug it, I can provide some logs. I really don't want to use develco gateway for this :)

**Comment by SwoopX** [comment]
If they do not show up in ioBroker, then those are probably not supported yet by the REST API. Please raise a corresponding device support request there, thanks!
