### ISSUE TITLE
Bitron Home 902010/20 Outside Siren

### ISSUE THREAD

**Issue by Smarti15** [dresden-elektronik/phoscon-app-beta#163]
Hey, I have an outside siren from Bitron Home type 902010/29.

(http://media.bitronvideo.eu/bitronhome/download/LBT90359-A_902010-29_GB-DE.pdf)

I tried to pair the device and in the Phoscon app it does not report it successfully, but om deconz adapter of ioBroker I get states. Only they don't work properly. I would like to script an alarm to a state and trigger the siren. Could you possibly see the device better?

ioBroker:  https://i.imgur.com/ZsjotMg.png

**Comment by SwoopX** [comment]
Please raise an issue to request device support in the deconz REST API plugin repository for it. It is not yet supported, and there's probably some more work to be done. Thanks!

**Comment by Smarti15** [comment]
ok, thanks for the tip. i just created
