### ISSUE TITLE
Support for Xiaomi Mijia Zigbee 3.0 Smart Home Light Sensor

### ISSUE THREAD

**Issue by pattyland** [dresden-elektronik/phoscon-app-beta#166]
Good Morning,

it seems that the Xiaomi Mijia Zigbee 3.0 Smart Home Light Sensor is already supported via deCONZ but not displayed in Phoscon: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2380

Would be nice if this could be fixed!

Greets
Sören

**Comment by Gammenon** [comment]
I can say, since version 2.05.18 / 14.9.2020 the sensors are visible in my setup. So I can confirm this can be closed.
