### ISSUE TITLE
Hi, big problem since reboot 2.05.79 - raspi , conbee 2 usb  100% CPU !!

### ISSUE THREAD

**Issue by sam-75** [dresden-elektronik/phoscon-app-beta#168]
I have the problem that with the 2.05.79 I have 100% CPU after rebooting the system.
I will try to downgrade to stable version now

**Comment by Mimiix** [comment]
Hi! 

This repo isn't the right for issues like this. 

However, do you have LQI enabled? This causes that behaviour when left on for a while. 

If you have LQI disabled, i'd like you to open a [bug report](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new?assignees=&labels=Bug+report&template=bug_report.md&title=) and please provide all details requested.
