### ISSUE TITLE
Apache ReverseProxy: 403 Forbidden for queries to set state

### ISSUE THREAD

**Issue by laurentbeaumer** [dresden-elektronik/phoscon-app-beta#169]
I am trying to use Apache as Reverse Proxy to access Phoscon via HTTPS (I have done it with Home-Assistant):

httpd.conf:
`
<VirtualHost *:443>
    ServerName phoscon.example.com

    <Directory />
        Options FollowSymLinks
        Require all granted
    </Directory>

    <Location />
        Require all granted
        Require ip 192.168.0.1/24
    </Location>

    ProxyPreserveHost On
    ProxyRequests off
    ProxyPass / http://192.168.0.2/
    ProxyPassReverse / http://192.168.0.2/

    SSLEngine on
    SSLProtocol -all +TLSv1.2
    SSLCipherSuite HIGH:!kRSA:!kDHr:!kDHd:!kSRP:!aNULL:!3DES:!MD5
    SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
</VirtualHost>

`

I can load the web app and access every menu, but when I try to switch on or off a light, I get 403 Forbidden:

- https://phoscon.example.com/api/8A39F7D3AA/lights?_=1596537558863 works

- https://phoscon.example.com/api/8A39F7D3AA/lights/3/state returns 403 Forbidden

`Forbidden

You don't have permission to access /api/8A39F7D3AA/lights/3/state on this server.`

I have attached the screenshots of query directly to the back-end server and the query using the reverse proxy.

Both servers are on the same LAN (192.168.0.0/24)

Thanks

![phoscon working](https://user-images.githubusercontent.com/22333939/89286613-0ea37380-d642-11ea-8c15-3bd12775304c.png)

![phoscon not working](https://user-images.githubusercontent.com/22333939/89286646-182cdb80-d642-11ea-86af-c5f7496d135c.png)

PS: I gave up trying to format properly the conf part in a code block

**Comment by SwoopX** [comment]
I don't use apache as reverse proxy, but nginx. However, that shouldn't matter. Probably one major difference is that I solely allow local connections though.

Worth to note that I locally put a symlink to the Phoscon `pwa` directory in my webserver root folder as `/phoscon`. So the first entry enables connections to my local Phoscon, the 2nd enables the API calls.

Hope, it helps.

```
location /phoscon {

        if ($ssl_client_verify != SUCCESS) {
            return 403;
        }

        allow       1.2.3.4;
        deny        all;

        index index.html;

    }

location /api/ {

        if ($ssl_client_verify != SUCCESS) {
            return 403;
        }

        allow       1.2.3.4;
        deny        all;

        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_http_version      1.1;

        proxy_pass              http://127.0.0.1:8080/api/;

    }
```

**Comment by laurentbeaumer** [comment]
I appreciate that you shared your configuration.

The issue is not from the Reverse Proxy, which is working, but the Forbidden returned by Phoscon when trying to change the state.

My guess is that the key created during the authentication is attached to the same host. When they are not matching you get the "403 Forbidden". The Proxy may hide the host calling the service, ergo the issue. 

That's why I would appreciated the point of view of one of the developers to know what headers are required.

**Comment by laurentbeaumer** [comment]
The solution is to enable PUT calls in mod_security:

https://serverfault.com/a/1015920
