### ISSUE TITLE
Missing Groups

### ISSUE THREAD

**Issue by cs42** [dresden-elektronik/phoscon-app-beta#170]
I'm missing at least one group in the Phoscon web. It is working and accessible/configurable via the old web interface.

There's on big difference between groups shown in Phoscon and not shown: all missing groups have an **button icon** in front of the name in the old interface.:
![image](https://user-images.githubusercontent.com/103868/89386428-5937f500-d701-11ea-843c-7f37c455827c.png)

BTW, those groups existed in Phoscon as I configured everything in Phoscon and I'm just using the old interface now because I can't configure those groups in Phoscon now.

PS: forgot to mention - I first noticed some missing groups in 2.05.76. With 2.05.77 some at least returned (maybe all, I'm not sure) and currently I'm running 2.05.79

**Comment by YKO-de** [comment]
These are the switch groups. That these are no longer there is intentional at the moment. Because often the switch group and the switch editor were used at the same time. But this leads to problems. We are working on making both available again.
