### ISSUE TITLE
Switch Configuration On/Off should use short an long press

### ISSUE THREAD

**Issue by timwegenerDE** [dresden-elektronik/phoscon-app-beta#171]
Hi there,

when using a wall switch (e.g. FoH Switch with EnOcean) sometimes the lights are not responding correct. A short press starts dimming the lights; I think it's because the key release was not detected (e.g. when pressing the button just on one edge). When setting the button action to just On/Off, the button does nothing on long press. So if this happens again the light will not turn on/off. It would be nice to use the On/Off function on both: short and long press for better reliability.

Kind regards Tim

**Comment by YKO-de** [comment]
Is the problem still there?
I would close this issue now. If the problem persists, please reopen it.
