### ISSUE TITLE
Sensor device not shown in sensors tab (BlitzWolf Temperature& Humidity sensor BW-IS4 .)

### ISSUE THREAD

**Issue by kispalsz** [dresden-elektronik/phoscon-app-beta#172]
I have a BlitzWolf Temperature& Humidity sensor BW-IS4 . 
[REST api issue1]( https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2970 )
[REST api issue2]( https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2489 )

REST api already supports it, but it **doesn't appear** on the sensors in Phoscon GW, and **I can't apply rules to the measured values ​​in Phoscon GW.**
Please add it to the supported sensors as well.

Thanks.

**Comment by killeriq** [comment]
Seems like they are the same as those: https://www.aliexpress.com/item/4001201737778.html OEM
It behaves the same for me as well.

thanks
![Image2](https://user-images.githubusercontent.com/39062891/90520914-39291c80-e16a-11ea-9e71-ae8b54f59896.png)
![image (1)](https://user-images.githubusercontent.com/39062891/90520917-3a5a4980-e16a-11ea-951b-9a9bb19ecea8.png)
![image](https://user-images.githubusercontent.com/39062891/90520919-3a5a4980-e16a-11ea-9b76-36f2bc0cd010.png)

**Comment by kispalsz** [comment]
Yes. It's just another brand. It has a different brand name on it.
 I can also record it, also indicated by a green stripe on the surface that it picked up, but I no longer see the phoscon gw at the sensors. And I can't create a rule either.

**Do you see it at the sensors after recording?**

This is my Sensors list after add sensor: (only xiaomi motion sensor visible)
![image](https://user-images.githubusercontent.com/33829634/90540803-0428c400-e182-11ea-95cf-8656b1fe5878.png)



add sensor log?:
`5:07:57:901 send permit join, duration: 59
15:07:59:901 send permit join, duration: 0
15:08:00:696 Search sensors done
15:08:01:902 send permit join, duration: 59
15:08:03:801 CTRL skip polling while permit join is set
15:08:03:846 CTRL skip polling while permit join is set
15:08:03:868 CTRL skip polling while permit join is set
15:08:03:870 DeviceAnnce of SensorNode: 0xEC1BBDFFFE326459 [1]
15:08:03:871    nwk address changed 0x0000 -> 0x9ACB [2]
15:08:03:873 DeviceAnnce of SensorNode: 0xEC1BBDFFFE326459 [1]
15:08:03:874    nwk address changed 0x0000 -> 0x9ACB [2]
15:08:03:876 device announce 0xEC1BBDFFFE326459 (0x9ACB) mac capabilities 0x80
15:08:03:877 set fast probe address to 0xEC1BBDFFFE326459 (0x9ACB)
15:08:03:878 FP indication 0x0000 / 0x0013 (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:03:878                       ...     (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:03:879 device announce 0xEC1BBDFFFE326459 (0x9ACB) mac capabilities 0x80
15:08:03:905 discard double entry in binding queue (size: 2) for for 0xEC1BBDFFFE326459, cluster 0x0001
15:08:03:985 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:03:985 [1] get node descriptor for 0xec1bbdfffe326459
15:08:03:985 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:03:985 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 0 ms
15:08:03:985 CTRL skip polling while permit join is set
15:08:04:169 FP indication 0x0104 / 0x0001 (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:04:169                       ...     (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:04:169 no button map for: TS0201 ep: 0x01 cl: 0x0001 cmd: 0x0A pl[0]: 020
15:08:04:169 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0001, ep: 0x01, frame control: 0x18, mfcode: 0x0000
15:08:04:169 discard double entry in binding queue (size: 3) for for 0xEC1BBDFFFE326459, cluster 0x0402
15:08:04:170 discard double entry in binding queue (size: 3) for for 0xEC1BBDFFFE326459, cluster 0x0405
15:08:04:362 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:04:362 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 377 ms
15:08:04:362 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:04:362 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 377 ms
15:08:04:362 CTRL skip polling while permit join is set
15:08:04:771 FP indication 0x0104 / 0x0402 (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:04:771                       ...     (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:04:771 no button map for: TS0201 ep: 0x01 cl: 0x0402 cmd: 0x0A pl[0]: 000
15:08:04:771 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0402, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:04:801 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 815 ms
15:08:04:867 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:04:867 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 881 ms
15:08:04:867 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:04:867 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 882 ms
15:08:04:867 CTRL skip polling while permit join is set
15:08:04:901 send permit join, duration: 0
15:08:04:996 dev /dev/ttyAMA0
15:08:04:997 GW update firmware not found: deCONZ_ConBeeII_0x26490700.bin.GCF
15:08:05:371 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:05:371 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 1386 ms
15:08:05:371 MAC poll fastEnddeviceProbe() 0xEC1BBDFFFE326459
15:08:05:371 wait response fastEnddeviceProbe() 0xEC1BBDFFFE326459, elapsed 1386 ms
15:08:05:387 FP indication 0x0104 / 0x0402 (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:05:387                       ...     (0xEC1BBDFFFE326459 / 0x9ACB)
15:08:05:387 no button map for: TS0201 ep: 0x01 cl: 0x0402 cmd: 0x0A pl[0]: 000
15:08:05:387 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0402, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:05:689 Search sensors done
15:08:05:981 no button map for: TS0201 ep: 0x01 cl: 0x0402 cmd: 0x0A pl[0]: 000
15:08:05:981 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0402, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:06:406 no button map for: TS0201 ep: 0x01 cl: 0x0405 cmd: 0x0A pl[0]: 000
15:08:06:406 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0405, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:06:900 send permit join, duration: 59
15:08:07:007 no button map for: TS0201 ep: 0x01 cl: 0x0405 cmd: 0x0A pl[0]: 000
15:08:07:007 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0405, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:07:393 CTRL skip polling while permit join is set
15:08:07:894 CTRL skip polling while permit join is set
15:08:07:984 ZCL attribute report 0xEC1BBDFFFE32C4B6 for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:08:397 CTRL skip polling while permit join is set
15:08:08:461 no button map for: TS0201 ep: 0x01 cl: 0x0001 cmd: 0x0A pl[0]: 020
15:08:08:461 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0001, ep: 0x01, frame control: 0x18, mfcode: 0x0000
15:08:08:900 CTRL skip polling while permit join is set
15:08:09:403 CTRL skip polling while permit join is set
15:08:09:521 no button map for: TS0201 ep: 0x01 cl: 0x0402 cmd: 0x0A pl[0]: 000
15:08:09:521 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0402, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:09:901 send permit join, duration: 0
15:08:09:937 no button map for: TS0201 ep: 0x01 cl: 0x0405 cmd: 0x0A pl[0]: 000
15:08:09:937 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0405, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:10:445 no button map for: TS0201 ep: 0x01 cl: 0x0001 cmd: 0x0A pl[0]: 021
15:08:10:446 ZCL attribute report 0xEC1BBDFFFE326459 for cluster: 0x0001, ep: 0x01, frame control: 0x08, mfcode: 0x0000
15:08:10:718 Search sensors done
15:08:12:265 don't close database yet, keep open for 900 seconds
15:08:12:901 send permit join, duration: 59
15:08:14:901 send permit join, duration: 0
15:08:14:994 dev /dev/ttyAMA0
15:08:14:995 GW update firmware not found: deCONZ_ConBeeII_0x26490700.bin.GCF
15:08:15:697 Search sensors done
15:08:16:901 send permit join, duration: 59
15:08:18:901 send permit join, duration: 0
15:08:18:919 Current channel 25
15:08:18:923 CTRL got nwk update id 2
15:08:18:928 Device TTL 3800 s flags: 0x7
15:08:19:218 Search sensors done`

**Comment by wilsonlspacheco** [comment]
Any news about this thread / issue? Im interested too.. 🙄

**Comment by wilsonlspacheco** [comment]
Any news? Now the sensor appear in urs phoscon app? @kispalsz? Thks.

**Comment by kispalsz** [comment]
Sorry for the slow response.
There have been many changes in my system since then. I've upgraded the system to beta, and since then several times. I am now using the latest beta.
Now I Use: 
"Version: 2.06.00 / 2020. 11.11.
Firmware: 26660700 "
 The blitzwolf BW-IS4 device now appears in the Phoscon app.
![BW-IS4-1](https://user-images.githubusercontent.com/33829634/100544019-5b473600-3253-11eb-91b1-8d222c7b5dab.jpg)
![BW-IS4-2](https://user-images.githubusercontent.com/33829634/100544024-5edabd00-3253-11eb-8dd9-64278a304c60.jpg)

But since then I have bought a similar sensor, only in Tuya brand, it doesn’t show up, I only get it with the REST API.

**Comment by wilsonlspacheco** [comment]
@kispalsz thank you for your reply! 😉👍

**Comment by srtxema** [comment]
i can´t sync with phoscon. is there any special sync mode?
