### ISSUE TITLE
Request: Change the name for groups in phoscon to avoid confusion with zigbee groups

### ISSUE THREAD

**Issue by Mimiix** [dresden-elektronik/phoscon-app-beta#173]
Hi,

As the remote grouping feature has been disabled, more and more people get confused by the name of "groups" within phoscon. They are groups of lights/devices but they are not the same as a Zigbee group is. 

Proposed change would be to either rename the groups to "sections" or make the remote groups return. 

Thanks!

**Comment by hpio** [comment]
Considering how useful remote grouping is (mainly as a fallback for switches for when deconz is unavailable) why was that feature removed? @Mimiix do you have a link to the docs, PR that removed it please?

**Comment by Mimiix** [comment]
@hpio I do not. It was a change in phoscon, which is closed source unfortunately. 

@YKO-de Can you elaborate?

**Comment by YKO-de** [comment]
The switch groups have been removed because they caused errors in connection with the switch editor. We are working on it.

**Comment by hpio** [comment]
@YKO-de does that mean you plan on adding the feature back hopefully in the near feature? Thanks

**Comment by Mimiix** [comment]
Bump.
