### ISSUE TITLE
LEDVANCE Edge-Lit Undercabinet TW Not Pairing as TW

### ISSUE THREAD

**Issue by ryancasler** [dresden-elektronik/phoscon-app-beta#174]
## Describe the bug
This device is just tuneable white but it is showing up in the Phoscon app as an RGB light. Not even RGBW. It had been working before but now it seems to miss-identify them.

## Steps to reproduce the behavior
Add the device. 
Try to click on Color Temperature 
Nothing happens

## Expected behavior
The light show up at tuneable white (color temp) not at RGB.

## Screenshots
![image](https://user-images.githubusercontent.com/30270489/89590915-ea4cc000-d816-11ea-93e3-9ffaff9786d3.png)

## Environment
Host : Raspbian Buster
Method: Raspbian
Firmware: 26350500
Device: Conbee
deCONZ: 2.05.79
No extention cable

### deCONZ Logs
If you want me to grab the logs when the device is paired, let me know.

**Comment by ryancasler** [comment]
> No, it should not. `ct` is in mired.

I'm sorry....I don't know what that means.  CT is mired?

**Comment by ryancasler** [comment]
> So as far as I'm concerned this is a issue with phoscon. I'll move this over to their repo.
> 
> @ryancasler Despite your disrespect against me, I forwarded it to their dev to give it priority.
> 
> _Be the change you want to see in this world._

You know what....I buy your damn products and recommend them to others.  Your flippant attitude is what got you that response.  Fix it or don't fix it, I won't buy another DE product ever again and won't recommend that anyone else buy them either.  Good day.

**Comment by ebaauw** [comment]
> as I understand it should be a cooler or bluer light.
> I'm sorry....I don't know what that means. CT is mired?

Really?

The value that `ct` reports is the colour temperature in mired.  See https://en.wikipedia.org/wiki/Mired.

**Comment by Mimiix** [comment]
@ryancasler As i told you before: I am a volunteer. Not employed by DE in any way. I am just keeping this stuff sorted and cleaned. The way you talk to me, is not done in **any** way.  

I have nothing personal against you, i treat everyone the same. Issues that do not comply with templates are closed. Don't take it personal.

**Comment by ryancasler** [comment]
> > as I understand it should be a cooler or bluer light.
> > I'm sorry....I don't know what that means. CT is mired?
> 
> Really?
> 
> The value that `ct` reports is the colour temperature in mired. See https://en.wikipedia.org/wiki/Mired.

Yes really.  I have never seen a system that reports CT in this manner.  Hue, SmartThings, Hubitat...all of them use the Kelvin scale, so I have never seen a mired.  And thank you so much for the insulting nature of your post.  It's always nice to insult people who ask questions.  it's so encouraging.
