### ISSUE TITLE
Float panels don't change colour temp via scene, but work manually via sliders

### ISSUE THREAD

**Issue by ianspray** [dresden-elektronik/phoscon-app-beta#177]
Hi,

I'm running Phoscon 2.05.79 on a Pi 4 with Raspbee II on 26610700, with a four bulbs in a group:

 * 2 x Ikea Tradfri E27 opal 980lm (2.3.050)
 * 2 x Ikea Float 30x30 panel (1.2.224)

When I manually drag the brightness and colour temperature in the app the group follows exactly as expected, but when I store a scene for all four bulbs, only the E27 devices change colour temperature and the Floalt panels stay at mid warmth.

Brightness changes in a scene are tracked by all four devices in the group correctly.

I only switched away from the Ikea gateway to the Raspbee this week, so I believe that the panels are at the latest Ikea firmware version for their hardware revision, but am open to advice there if there's a more recent Ikea FW I need to load.

Any suggestions for how to get the scene colours tracking on all four devices would be most welcome.

**Comment by E1onE2** [comment]
I got a similar issue with a Pi 4, RaspBee 2, Phoscon and a smart light strip controller (RGBCW).
Manually I can choose to use color temperature, but it is not saved in the scene. Once switched to a scene with color settings, the scene with temperature gets kinda overwritten.

**Comment by ulph** [comment]
I have the same issue with my IKEA floalt

previewing in the scenes editor is fine, but the color is always switched to a "neutral" temperature when I switch scenes.

quite annoying
