### ISSUE TITLE
Xiaomi Aqara Smart Switch - Long Press Button not available

### ISSUE THREAD

**Issue by Maddinthebrain** [dresden-elektronik/phoscon-app-beta#180]
## Describe the bug
I am using several Xiaomi Apara Smart Switches (Button). It works fine. But deconz only offers two possibilties to use it. 1x short press and 2x press. But the Button offers a 3rd possibilty: 1x long press. Could you please implement this into deconz? By the way the API recongizes the 1x long press yet. I can see and also use in FHEM. 

## Expected behavior
Implement the 1x long press function, too

## Environment
Version: 2.05.78
Firmware: 26350500

**Comment by YKO-de** [comment]
The problem should have been resolved by now. I would therefore close the issue for the time being. If it still exists please create a new one.
