### ISSUE TITLE
[DEVICE REQUEST] SR-ZG2835 Zigbee Rotary Switch

### ISSUE THREAD

**Issue by alexdepalex** [dresden-elektronik/phoscon-app-beta#181]
Device has been added to deconz [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3085). I tested it, and it works, but it's still missing from Phoscon. I did use the old ui to add members to the device and that works, so technically, things look good.

**Comment by YKO-de** [comment]
I will add. I will be there with the next release. :)

**Comment by Mimiix** [comment]
Was this included already @YKO-de ?

**Comment by Qredent** [comment]
Yes: via the old GUI you can assign groups and using deCONZ you can see the status and cluster info.

**Comment by alexdepalex** [comment]
So, to be honest, about 2 months ago, I also created a group on the old UI as stated above. I just don't have a clue though, how I made it work. I still see the group, it has only one member though, but I can still control it through the rotary switch.

@Qredent Care to share?

**Comment by Qredent** [comment]
@alexdepalex when you add this 'switch'  the old UI will show a group. Whatever lights you add to there will see it's brightness increase/decrease and turned off/on by the switch. It will use whatever color or warmth setting it had when it last turned off. You can edit this via the old UI via the group.

**Comment by alexdepalex** [comment]
Thanks. Well, I had multiple groups, so something went wrong. Shame it isn't properly integrated yet. Hope that'll change. Regarding the color temperature. When I pair the rotary switch directly with my led controller, I can change the temperature by pushing the switch and rotating it. This doesn't work with Deconz unfortunately. I'll see if I create a separate issue for that.

**Comment by danli003** [comment]
Hi, waking up an almost year old thread.  Did you have any success with this SR-ZG2835 Zigbee Rotary Switch. I just got one of these. I can include it to deconz and do simple "bind actions" - on/off, dimmer. But that's it. It does not seem to be fully intergrated. Cannot access it from Phoscon (neither "new" nor "old" gui). It doesn't let me change it's name. The Basic cluster info  looks like this.
![image](https://user-images.githubusercontent.com/31520946/120541755-91c06200-c3ea-11eb-94b1-6b0c51c4e635.png)
However, in the "node list" - it is all blanks
![image](https://user-images.githubusercontent.com/31520946/120541826-ac92d680-c3ea-11eb-9ec6-b21ec7721481.png)

Any advise from you that have managed to get it integrated? (I do run latest beta of both deconz and the firmware)
