### ISSUE TITLE
[DEVICE REQUEST] Sengled Window & Door Sensor (E1D-G73)

### ISSUE THREAD

**Issue by keithpitt** [dresden-elektronik/phoscon-app-beta#184]
I have a bunch of these: https://www.amazon.com.au/Sengled-E1D-G73-Smart-Sensor/dp/B07QHDXQXJ

Adding them *kinda* works in the Phoscon UI, but it doesn't show in the Sensors list.

The device itself is fully functioning via the API, and the open/close state works a treat, just nothing via the UI.

```json
{
  "config": {
    "battery": null,
    "on": true,
    "pending": [],
    "reachable": true
  },
  "ep": 1,
  "etag": "66bea73474547605a53574db7a565e55",
  "lastseen": "2020-08-23T03:40:24.509",
  "manufacturername": "sengled",
  "modelid": "E1D-G73",
  "name": "E1D-G73",
  "state": {
    "lastupdated": "2020-08-23T03:40:11.416",
    "lowbattery": false,
    "open": false,
    "tampered": false
  },
  "type": "ZHAOpenClose",
  "uniqueid": "b0:ce:18:14:00:0e:70:98-01-0500"
}
```

Let me know if there's any further information I can provide!

**Comment by YKO-de** [comment]
Sensor should be visible from today through the new release. If not please open new issue.
