### ISSUE TITLE
[Device Support Request] Samsung SmartThings Multipurpose Sensor

### ISSUE THREAD

**Issue by Mdleal** [dresden-elektronik/phoscon-app-beta#185]
Device shows up in deconz but not phoscon. Let me know what info you need from me. 

Github issue in the deconz repository.
[Issue](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1264)

**Comment by armandomuassab** [comment]
I have de same problem. Sensor STS-MLT-250

**Comment by YKO-de** [comment]
Sensor should be visible from today through the new release. If not please open new issue.

**Comment by armandomuassab** [comment]
Now see, but only when read attributes from vnc, and don't show status sensor opened/closed

**Comment by dherran** [comment]
I'm having exactly the same issue as @armandomuassab. The device appears in deCONZ but not in Phoscon. It will only show up once you read the attributes in deCONZ. Also, the sensor doesn't have the binary "open/close" entity, only vibration and temperature.
