### ISSUE TITLE
Switch Editor doesn't show switch

### ISSUE THREAD

**Issue by Surfer2010** [dresden-elektronik/phoscon-app-beta#186]
## Describe the bug

I have a Switch (Osram Lightyfy 4 Button Switch) in the "switches" menu, but no available switch in the switch editor in my Room

## Expected behavior
In my "room" i go to SwitchEditor to add a switch that is known to the system

## Environment
Newest Docker Image (2.05.80 / 14.8.2020)

 - Host system: intel server
 - Running method: Marthoc Docker container on a debian server
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.05.80)
 - Device: ConBee II
 - Do you use an USB extension cable: yes

**Comment by Mimiix** [comment]
@YKO-de Switch doesn't show in Phoscon switch editor. Needs support 

@Surfer2010 I moved the issue, as phoscon need to add support.

**Comment by Surfer2010** [comment]
any help on this?

**Comment by YKO-de** [comment]
Works with the next release.

**Comment by Mimiix** [comment]
Thanks @YKO-de !

**Comment by Surfer2010** [comment]
When will this be? And will this be in the docker-container version directly aswell?
Thanks a lot :-)

**Comment by Mimiix** [comment]
@Surfer2010 As far as i know, this will be done the 15th this month on beta channel. 

docker version will follow after that.
