### ISSUE TITLE
Aqara wireless switch D1

### ISSUE THREAD

**Issue by giuliandenicola1** [dresden-elektronik/phoscon-app-beta#187]
## Device

- Product name: Aqara Wireless switch D1
- Manufacturer: Xiaomi
- Model identifier: WXKG07LM
- Device type: 
  - Switch

Edit: [Banggood](https://banggood.app.link/izlKJPmrk9) 

## Screenshots

![Screenshot_20200828-233045_Banggood](https://user-images.githubusercontent.com/67443916/91616693-82f1de00-e986-11ea-981e-769f4b5537f0.jpg)

**Comment by giuliandenicola1** [comment]
> In the future: Please make sure to fill the complete template.

Sorry, I got mine two days ago and didn't even know that deconz and phoscon aren't one whole.

**Comment by YKO-de** [comment]
Should work with the new release since today. If not, please reopen an issue here in the "phoscon-app-beta".
