### ISSUE TITLE
Add an option to store session (e.g in Home Assistant)

### ISSUE THREAD

**Issue by domoritz** [dresden-elektronik/phoscon-app-beta#189]
It would be awesome if we could store a session so that it's not necessary to input the password every time we open the Phoscon interface for example from Home Assistant. 

See https://github.com/home-assistant/hassio-addons/issues/1556 for details.

**Comment by letszb** [comment]
Are you logging out of the Phoscon App? In our Hassio installation the Phoscon App will be opened without any password request.

**Comment by domoritz** [comment]
No, I am not. But I did customize my password. My session usually stays active for a bit but not beyond days. 

<img width="1517" alt="Screen Shot 2020-09-15 at 07 09 07" src="https://user-images.githubusercontent.com/589034/93221304-76a9a700-f722-11ea-9448-6f6ead8aa05e.png">

**Comment by YKO-de** [comment]
The login page is currently being revised. However, this will take some time.

**Comment by ottelo9** [comment]
I also want to know if this could be possible. I use deconz in my Home Assistant and dont want to use passwords.
