### ISSUE TITLE
password reset won't work

### ISSUE THREAD

**Issue by jorgenslings** [dresden-elektronik/phoscon-app-beta#19]
running Phoscon on a Pi 3+ and can not get my password to reset, even after power cycle the PI, password delight fails to work. I can get to my HUE using the 'button' on HUE

**Comment by manup** [comment]
Hmm strange this was testet recently and should work, I'm gonna looking into it.
Meanwhile you may try to reset the password with the old login page.

`http://<raspberrypi-IP>/login.html`

**Comment by jorgenslings** [comment]
that page works, but asks me username (my default Pi won't work it seems).. When inside the deCONZ app (via VNC into Pi) I presse the Phoson App button I get the "wrong" page and when I select the WerbApp button I get the "old page" ... what's the default username for the "old page" ?

**Comment by manup** [comment]
They both use the same configuration and user credentials.

user: delight
password: delight (unless it is changed)

Note: user is not changeable.

**Comment by jorgenslings** [comment]
I seem to be in now .. but was never asked username/password when using browser on local machine .. remote is still an issue so there must be something on my end ref n/w connect (although SSH is open and I can get to my Node-Red in the same Pi

**Comment by manup** [comment]
Do you use 2.05.49? We fixed this very issue in this version.
Or if you use http://dresden-elektronik.de/pwa?123 it should also work (the ?123 refreshs the cache).

**Comment by dergreg** [comment]
Thanks, the URL did the trick! I’m on 2.4.48.
Is this the correct link for the most stable version?
https://www.dresden-elektronik.de/rpi/deconz/stable/deconz-latest.deb

**Comment by busshi** [comment]
Hello, I cannot access to the DeconzApp ! My password is not recognized, it only worked on the first time. Impossible to change it because it says each time wrong password ! But this is the screen to reset the password !!! What is wrong ?

**Comment by jotheman0303** [comment]
Just updated to the latest version and am having the same issue described here. Password is no longer working. I was able to use the ?123 URL once, but after that it's not working anymore

**Comment by elmocito** [comment]
Have the same issue...

**Comment by magnus919** [comment]
Several years later... password change is not possible here, either. 

`Current deCONZ version: 2.15.00`
