### ISSUE TITLE
[Device Request] Sunricher Remote SR-ZG2868

### ISSUE THREAD

**Issue by pur3asdf** [dresden-elektronik/phoscon-app-beta#190]
Hello

I've been told to open an issue in the phoscon repo.

So I got this [SR-ZG2868](https://www.sunricher.com/dim-cct-rgb-3-in-1-zigbee-remote-sr-zg2868.html) remote controller, which I added to my zigbee network. I can see the device in deConz, but i'm unable to get it shown up as a switch in the phoscon app.

I'd love to be able to add these remote controller in the Phoscon app.

**Comment by YKO-de** [comment]
Can you give me the modelid to the switch?

**Comment by pur3asdf** [comment]
@YKO-de  I'm not sure which one the modelid is.
![image](https://user-images.githubusercontent.com/66328149/94288731-0a1b7d00-ff58-11ea-8c0d-4cbb1a822118.png)
If you need more information, just tell me what you need.

**Comment by pur3asdf** [comment]
I'm having the same issue with the [SR-Z9001K12-DIM-Z5](https://www.sunricher.com/single-color-5-groups-zigbee-key-remote-controller-sr-zg9001k12-dim-z5.html).
![image](https://user-images.githubusercontent.com/66328149/94290016-e822fa00-ff59-11ea-9ce2-27b10bfc75a8.png)

**Comment by pur3asdf** [comment]
puah

**Comment by YKO-de** [comment]
I have added the device to the whitelist. Can you please check under phoscon.de/pwabeta if it worked? I do not own the device and cannot test it.

**Comment by pur3asdf** [comment]
I put my Conbee 2 on my windows machine because I had issues connecting to the beta app, chose "Others" when connecting the remote. Now I can see it in deConz again but not it the beta app.
![image](https://user-images.githubusercontent.com/66328149/97039220-5d3f1a80-156c-11eb-9b64-7f76cde66030.png)

**Comment by SwoopX** [comment]
The device is not supported by deconz.

**Comment by pur3asdf** [comment]
so I have to open an issue in the deConz rest api repo?

**Comment by SwoopX** [comment]
Yes, indeed. Please read the template thoroughly!
