### ISSUE TITLE
[DEVICE REQUEST] Danfoss Ally

### ISSUE THREAD

**Issue by JSteunou** [dresden-elektronik/phoscon-app-beta#191]
Hi,

this eTVR was added not so long ago into deconz, is it possible to add it into Phoscon to have a nice UI to manage those? :) 

Here is the issue from deconz to get more details https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2983

Thank you

**Comment by YKO-de** [comment]
Will be visible in the Ui with the next release ;)

**Comment by JSteunou** [comment]
This is nice, thank you! Is the next release will be available as normal or beta release?

**Comment by simoneras** [comment]
Hi I can't see Ally valves on Phoscon App. Help

**Comment by boelle** [comment]
@YKO-de it's not added yet. You can only add lights, switches and sensors. A thermostat is non of those 

Same with ikea roller blinds, they can be added as lights but you have to know that beforehand

New users would think they are not supported and give up on HA or not getting the products
