### ISSUE TITLE
[DEVICE REQUEST] Konke Motion Sensor

### ISSUE THREAD

**Issue by aap82** [dresden-elektronik/phoscon-app-beta#193]
Hello - I was able to add a Konke Motion Sensor using Add Device in the Phoscon PWA.  I can see it is available the REST API at <code>/api/APIKEY/sensors/2</code>.  

Here is the response:
<code>
{"config":{"battery":null,"duration":60,"on":true,"pending":[],"reachable":true},"ep":1,"etag":"6426ac7d0b0487449b7413eb355948b4","lastseen":"2020-09-11T22:56:12.485", "manufacturername":"Konke","modelid":"3AFE28010402000D","name":"Motion Sensor","state":{"lastupdated":"2020-09-11T22:57:07.469","lowbattery":false,"presence":false,"tampered":false}, "swversion":"190829", "type":"ZHAPresence","uniqueid":"14:b4:57:ff:fe:07:5b:e1-01-0500"}
</code>

however, it is not displaying because it fails a test within the <code>addOne(model)</code> method of <code>SensorListView</code>.   It specifically fails here:

<code>
var modelid = ["de_occ", "PHDL00", "SML001", "SML002", "TRADFRI motion sensor", "VMS_ADUROLIGHT", "CSW_ADUROLIGHT", "LM_00.00.03", "IR_00.00.03", "LMHT_00.00.03", "DC_00.00.03", "OJB-IR715-Z", "Motion Sensor-A", "FLS-NB", "LG IP65 HMS", "lumi.weather", "lumi.sensor_ht", "lumi.sensor_magnet", "lumi.sensor_motion", "lumi.ctrl_ln2.aq1", "lumi.vibration", "lumi.sensorwleak.aq1", "3011", "3043", "902010/21", "motion", "multi", "water", "WL4200S", "TH-", "WATER", "Water", "WarningDevice"].find(x=>model.has("modelid") && -1 !== model.get("modelid").indexOf(x));

 if (!modelid)  return;
</code>

Can this be updated please?

**Comment by YKO-de** [comment]
Bug is already fixed and should not occur with the next release.
