### ISSUE TITLE
Sonoff SNZB-02 - wrong icon

### ISSUE THREAD

**Issue by jan666** [dresden-elektronik/phoscon-app-beta#195]
<img width="636" alt="SONOFF Temp" src="https://user-images.githubusercontent.com/869857/93179214-a6ae7580-f735-11ea-9799-66fb9401b224.png">

The [Sonoff SNZB-02](https://sonoff.tech/product/smart-home-security/snzb-02) (Temperature & Humidity Sensor) is shown as motion sensor in the Phoscon web interface (2.05.81 / 14.9.2020)

**Comment by YKO-de** [comment]
This is the generic symbol. It is always used if we do not have an individual one yet. This is not intended to represent a motion detector. Just a sensor in general. :)
