### ISSUE TITLE
Transition Time with no effect

### ISSUE THREAD

**Issue by boehser-enkel** [dresden-elektronik/phoscon-app-beta#197]
Hi,
I am using Phoscon on an RP4 headless with a Conbee 2.
The setting Transition Time seems to have no effect. Light are on directly without fading time (i.e. 10 Minutes).
How do i use this?

greetz
boehser enkel

**Comment by YKO-de** [comment]
You mean with the scenes?

**Comment by boehser-enkel** [comment]
Yes with Scenes. Got it to work (have to set Brightness also). 

But Tradfri Driver does not seem to support it. It has no effect

**Comment by YKO-de** [comment]
Hmm, okay. I'm gonna go test it out. But if it is because of the device, i.e. if it is not supported by some IKEA lamps, then I probably can't do much. 
Have you checked if there is an update for the lamps?

**Comment by boehser-enkel** [comment]
I have no hub so I can't check for updates. Bulbs are all same charge. Some of them work, some don't.

**Comment by YKO-de** [comment]
Okay. I have now tested it and can confirm the problem. After consultation with a colleague, it can be assumed that the IKEA lights are to blame. But a solution is being worked on.

**Comment by boehser-enkel** [comment]
Okay thank you

**Comment by boehser-enkel** [comment]
New insights (since there was no change since then):

No i have to create 2 scenes:

1. set transition time, turn on light, set brightness to 1%
2. set brightness to 100%

This works also with the tradfri driver.
If i set everything at once (turn on, brightness to 100%, set transition time) it turns on instantly to 100%. Also with Osram bulbs.

It seems that the transition is set after the bulbs (on, brightness) are set: https://pastebin.com/sg3qfHX2
Deconz: 2.09.03, homebridge-hue (neweset)
