### ISSUE TITLE
[Device Support Request] Samsung SmartThings Multipurpose Sensor

### ISSUE THREAD

**Issue by armandomuassab** [dresden-elektronik/phoscon-app-beta#199]
Device shows up in deconz but not phoscon. Sensor STS-MLT-250.
Now see, but only when read attributes from vnc, and don't show status sensor opened/closed

**Comment by RichJeanes** [comment]
Same issue here. deCONZ via VNC sees the device, but Phoscon doesn't. Latest version of deCONZ plugin in Home Assistant (plug-in 6.4.0, deCONZ 2.05.84).
Device: Samsung SmartThings Multipurpose Sensor M/N: STS-MLT-250, aka SmartThings multiv4
I don't know how the contact sensor is supposed to be reported in deCONZ. The buttons I have report button presses via the IAS zone alarms, but the multi sensor doesn't show anything there when opening/closing the sensor.
![image](https://user-images.githubusercontent.com/6753081/96286649-8f151780-0f95-11eb-93db-e7a3dc1ecaaf.png)
![image](https://user-images.githubusercontent.com/6753081/96286970-0cd92300-0f96-11eb-8829-f8c71035adda.png)
![image](https://user-images.githubusercontent.com/6753081/96286661-96d4bc00-0f95-11eb-9752-3482c12e1dd6.png)
![image](https://user-images.githubusercontent.com/6753081/96286998-1b273f00-0f96-11eb-80ee-334a44d7e2e1.png)
![image](https://user-images.githubusercontent.com/6753081/96287110-4b6edd80-0f96-11eb-8a42-fa5f3abf5fe5.png)

**Comment by YKO-de** [comment]
Let me get this right. You can see the sensor, but the status is not displayed correctly? Have you ever tried to relearn it. Maybe something was not detected correctly. It works for me. 
![image](https://user-images.githubusercontent.com/55535297/96556756-ae73b380-12b9-11eb-951a-a4c17f0cf9ec.png)

**Comment by dherran** [comment]
Same issue. This is how it looks in Phoscon. I'm running the deCONZ Home Assistant plugin 6.4.1. Device Model: STS-MLT-250.

![chrome_seAXAIPh7u](https://user-images.githubusercontent.com/134963/97367458-0c4b6100-18a1-11eb-97fd-a4a4df762eae.png)

The State isn't even shown in Phoscon like it does for @YKO-de . I think somehow the binary property for the contact sensor is not registering.

![chrome_EtFcU3FQU0](https://user-images.githubusercontent.com/134963/97367816-af03df80-18a1-11eb-9dcc-847445b63b12.png)
![chrome_SOJLmEDjqv](https://user-images.githubusercontent.com/134963/97367822-b1663980-18a1-11eb-9d0b-2f274720a6f9.png)
![chrome_RbHuBZcAwO](https://user-images.githubusercontent.com/134963/97367826-b2976680-18a1-11eb-97eb-70b7723c70c6.png)

I tried deleting and adding the sensor again, same issue.

**Comment by townsmcp** [comment]
I am getting the same for Smartthings multipurpose sensor STS-MLT-251. I connected the devices to SmartThings today, did firmware update and then tried adding to Phoscon again. I hold the connect button for 10 seconds, watch the LED flash red, click on connect in Phoson, the LED goes blue and flashes but Phoson eventually times out. However the device is showing in VNC but exactly like @dherran pictures show - no actual name on VNC.
My Home Assistant is 0.117.1
Phoson version is 2.05.84 / 14/09/2020
Conbee 2 firmware is 26660700

**Comment by RichJeanes** [comment]
@YKO-de It seems like @dherran's situation might be slightly different since the device does appear in Phoscon. For the rest of us, it does not appear at all in Phoscon, only in DeCONZ via VNC. I have followed the same procedure as @townsmcp to similar results. The device appears again in DeCONZ VNC, but Phoscon just times out. I have also tried deleting and reseting the device from DeCONZ with the same result.

**Comment by RichJeanes** [comment]
Also, as @dherran said, it appears the Binary Input cluster is not reading correctly, even in DeCONZ, as I can't get it to register any change there when opening and closing the contact sensor.
![image](https://user-images.githubusercontent.com/6753081/99100329-edcfb000-2598-11eb-9710-e00d9169522a.png)

**Comment by townsmcp** [comment]
This is definitely not a stale request!

**Comment by YKO-de** [comment]
Try to reprogram the device via other devices. With the current version. Does it work then?

**Comment by RichJeanes** [comment]
Can you clarify what you mean by "reprogram the device via other devices"? I don't understand what "via other devices" means.

**Comment by YKO-de** [comment]
I mean re-learning the device. Sorry.

**Comment by RichJeanes** [comment]
I had to pair the sensor back to my SmartThings Hub, then delete it, but I was then able to re-pair it to my ConBee. Now it is showing in Phoscon for me, not just deCONZ, but it is not showing open/closed status, same @dherran. In deCONZ, I can see properties changing when it is moving ("vibration"/"active") and position changes. However I don't see anything change when the magnet is opened or closed even though the dot in deCONZ blinks green when I open or close it.
Also, there appears to be a missing translation or something?
![image](https://user-images.githubusercontent.com/6753081/102520185-a5505a00-4050-11eb-88ac-29324ff8c28a.png)
![image](https://user-images.githubusercontent.com/6753081/102520846-6242b680-4051-11eb-8bbc-32ea118dbfc7.png)
![image](https://user-images.githubusercontent.com/6753081/102519717-193e3280-4050-11eb-8cdc-b04a46a3648a.png)
![image](https://user-images.githubusercontent.com/6753081/102519787-2b1fd580-4050-11eb-98e4-d256a9acd333.png)
![image](https://user-images.githubusercontent.com/6753081/102519766-25c28b00-4050-11eb-8ed3-fd455d40ac90.png)

**Comment by YKO-de** [comment]
Hmm okay. I'll look at it again.

**Comment by SwoopX** [comment]
Maybe one thing to note here: v2.8.0-beta contains a fix for the IAS enrollment where only Samjin devices are affected (SmartThings). It probably would solve deconz not recognizing the open/close events here.

@RichJeanes Can you read the IAS zone cluster attributes at the bottom of that cluster? It's probably telling you that it's not enrolled yet. Be sure to wake the sensor before reading them.

**Comment by RichJeanes** [comment]
@SwoopX You are correct. It lists Zone State: Not Enrolled
![image](https://user-images.githubusercontent.com/6753081/102648671-21b46d00-4125-11eb-8154-999f54bbdc15.png)

**Comment by SwoopX** [comment]
You might try to enroll it manually and see what happens:

- Select the coordinator, click on the node info panel and click on the coordinator mac address
- Copy it
- Double click on the value for the IAS CIE address
- Paste the mac address there
- Ensure the device is awake and press write

**Comment by RichJeanes** [comment]
So I tried that and it seemed to work with opening and closing the sensor toggling the Alarm 1 in deCONZ, but it still didn't show the state in Phoscon. So I restarted Home Assistant (by installing the latest version) and now I don't see the IAS checkbox list thing at all for any of my nodes in deCONZ...
![image](https://user-images.githubusercontent.com/6753081/102672147-4f151100-414d-11eb-86df-216fe1680b0d.png)

Phoscon still doesn't show the state:
![image](https://user-images.githubusercontent.com/6753081/102672182-5d632d00-414d-11eb-87d5-b8e7aa1ef216.png)
But Home Assistant is showing a binary sensor for it.
Open:
![image](https://user-images.githubusercontent.com/6753081/102672218-74098400-414d-11eb-88c9-53c7ce277ad7.png)
Closed:
![image](https://user-images.githubusercontent.com/6753081/102672230-7b309200-414d-11eb-898b-b6be1d96e3ac.png)

This is the same behavior I have with my SmartThings motion sensor, as well. It doesn't show its state in Phoscon, but Home Assistant sees a working binary sensor for motion.

**Comment by SwoopX** [comment]
Great, so almost there. The checkboxes dissappearing is already fixed in the latest beta and the open/close should also be included.

@YKO-de if you can include the open/close state in Phoscon as well, then the mission is complete.

**Comment by RichJeanes** [comment]
This issue is not stale. The open/closed state of the sensor does not appear in Phoscon. (Also, there is still an untranslated string.)
![image](https://user-images.githubusercontent.com/6753081/105726868-bdd15100-5ee7-11eb-94ac-61aa7671f2b1.png)

**Comment by hcw3** [comment]
Glad the issue is not marked **Stale** as I have the same problem with the STS-MLT-250, ie: missing the open/closed state in deCONZ and in Phoscon.
I will check this morning to be sure I'm on the latest firmware/software, try @SwoopX's "enroll it manually" trick, and update my situation here. 
Thanks all.

**Comment by hcw3** [comment]
After manually enrolling, per @SwoopX's suggestion, it seems I'm now at the same point that @RichJeanes is at with this. The door-open switch now registers in deCONZ as Alarm 1, but I don't know how to get it into Phoscon and JowiHue (HomeSeer)... 

From what I understand (I have very limited experience), Phoscon only reads the attributes of the MultiSensor for three minutes when I click 'Add new sensor', is that correct? 

And initializing the device's 'include' mode (remove battery, press button, insert battery, release button) resets its attributes, so, when Adding, I must insert the battery, quickly get into deCONZ, change the  IAS CIE address and write it, before the 3-minute Phoscon 'read' is finished?

Is there a way to write the  IAS CIE address into deCONZ before adding the device to Phoscon?

Thanks for any help!

**Comment by hcw3** [comment]
Further update...

I restarted JowiHue, and it shows the door-open sensor...! 

But not showing in Phoscon. How to get Phoscon to read it again?

**Comment by SEK-DE** [comment]
@hcw3 no, deCONZ can not "learning" thru pairing or something like that. We work on principle without cloud, so everything you see in deCONZ is made by hand. This goes also for all integrations, pictures, switch options etc.
JowiHue has no influence on our system, there is just the compatibility.
