### ISSUE TITLE
Existing groups not imported/visible

### ISSUE THREAD

**Issue by RudolfRendier** [dresden-elektronik/phoscon-app-beta#2]
The new app doesn't show my existing groups (still visible in old app)

When recreating a group with an existing name; I get an error:
"The group <groupname> already exists."

I expect existing groups to be imported and visible in the new app.

Love the app though! It looks really good.

**Comment by woodkazor** [comment]
I had this issue at first too.Groups had cryptic names with numbers.  I renamed them and it was ok.  App is absolutely beautiful. 
Only scenes with tradfri missing.  That's a bit sad.  
I am using homebridge. But I did not yet succeed in using it with HomeKit.  That's a pitty.

**Comment by manup** [comment]
Currently the Phoscon App hides groups which are controlled by switches and sensors which are not yet supported in this part of the App (for example IKEA motion sensor group).

> Only scenes with tradfri missing. That's a bit sad.

This will be possible in future (early 2018), we're working on a UI editor so that a switch button can trigger any action like calling a scene, on/off and adjust brightness.

**Comment by ftonat** [comment]
I understand hat it may make sense to hide groups associated to switches. I use 5 Dresden Scene Switches, so I see 5 groups in phoscon app.
I can switch on the associated scenes, but there is no off button...
Frank

**Comment by manup** [comment]
>I can switch on the associated scenes, but there is no off button...

On the Phoscon app: *Main page > Scenes*, you can click on the graphical buttons off the switch to also use on/off.

**Comment by ftonat** [comment]
Sorry, cannot find scenes on main page. There is only groups. 
I am using phoscon on iOS
![d58aacad-27db-4674-8725-c4cbb5ccd761](https://user-images.githubusercontent.com/30591339/34448380-fa0276ba-ecec-11e7-842b-f48bb771102c.jpeg)

**Comment by manup** [comment]
It's on the right side when you select a switch and click on scenes.

![image](https://user-images.githubusercontent.com/383386/34448423-75494b28-eced-11e7-8aa4-79266b86a2f2.png)

**Comment by ftonat** [comment]
I see. Thank you.
On my iPad I can use the mentioned switch buttons.
On iPhone the controls are not visible.
So it might be an issue regarding the responsive design of phoscon app
![fdc044ad-5a6c-4426-abee-6c09ca0336f5](https://user-images.githubusercontent.com/30591339/34448548-be13fb40-ecee-11e7-8806-3b100941c41f.jpeg)

**Comment by manup** [comment]
I see, yes that's true the mobile phone version is still work in progress and limited in specific cases. We'll figure something out to support that.

**Comment by StephanStS** [comment]
@RudolfRendier: Is this issue already open? If not, please close it.
