### ISSUE TITLE
no Zigbee showing up in switches

### ISSUE THREAD

**Issue by jorgenslings** [dresden-elektronik/phoscon-app-beta#20]
![screenshot 2018-04-24 12 32 38](https://user-images.githubusercontent.com/35294037/39181985-978d9d6e-47bb-11e8-8fb6-a1fd6ea098e5.png)

trying to add a Bitron Zibee socket in but don't seem to have that option .. it does show up (and works nice'ish) in my deCONZ

**Comment by ebaauw** [comment]
deCONZ treats smart plugs (and in-wall switches) as lights, not as switches.  You should also see a ZHAConsumption sensor resource, see #482.

**Comment by StephanStS** [comment]
@jorgenslings: If ebaauws answer helped for your question, please close this issue.
