### ISSUE TITLE
WLAN Config problem

### ISSUE THREAD

**Issue by creactiv** [dresden-elektronik/phoscon-app-beta#200]
Hi, got zigbee card for Raspberry Pi and i want to reset the wifi password within Phoscon. It always tells me, for a configuration change i would have to plug in an Ethernet cable. Given, that Pi 3 was connected via Ethernet cable, i cannot do anything right now. 
How to fix this? I can see the wifi network name on my mobile devices, but cannot connect due to missing password.... 

Thanks for help!
hs

**Comment by creactiv** [comment]
I am still wondering, whether the Access Point Feature can only be used when NOT using zigbee card on Raspberry Pi Any insights, please? If not, why is phoscon not respecting the network cable being plugged in my Pi?

Thanks and best

**Comment by ChrisHae** [comment]
Do you have an eth0 device? When you type ifconfig into your console?

**Comment by 7wells** [comment]
What kind of "zigbee card"? RaspBee/II? That card - to my knowledge, as I use it myself - has no own Wifi. So what does the Wifi password of the Raspberry Pi have to do with phoscon?

**Comment by ChrisHae** [comment]
You can configure the raspberry pi wifi within the Phoscon app. When it says please connect an ethernet cable then it is a bug within the Phoscon app or the wifi script or a wrong raspbian configuration. Thats why I asked if the eth0 device is present.

**Comment by 7wells** [comment]
Ah, thank you! I have learned something again today. :)

**Comment by creactiv** [comment]
Well, unfortunately my dad died, so i had other things to do in the last couple of days. 

Interestingly enough, eth0 is present, and it got an ip address within my home ip adress range (192.168.77.19), WIFI is also present, with a different ip adress range (192.168.10.1/24). I had to enable ssh, so i can work on it from remote and when i open raspi-config, it says it cannot communicate with wpa-supplicant, although it shows in the startup screen that it had been loaded.  So i am out of my wits...
