### ISSUE TITLE
How can I use motion sensor together with schedules

### ISSUE THREAD

**Issue by bruesche** [dresden-elektronik/phoscon-app-beta#201]
Hi there, I want to do the following:
I want to use a motion sensor to switch on/off light the complete day. I want to use schedules for this light too so that the lights are 4 hours always on and after the they used the motion sensor. How can I configure this? Can anybody can give me advice?

Thx for help

**Comment by bruesche** [comment]
The issues from 2018 is about the same problem:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1075

There was no solution.

**Comment by 7wells** [comment]
Hello!

Phoscon offers for my Osram Lightify Motion Sensor the following options in its settings:
- Always active
- Active from evening to morning
- Active during the day
- Active when at least one light is on
(The terms here are freely translated from German. I don't know how they appear in the English language setting, sorry.)

See screenshot: https://workupload.com/file/ewZx7de5ztq

If(!) we knew what exactly "from evening to morning" and "during the day" mean, we could program the lights(s) for certain hours to be on and then use the sensor to have them switched.

I wonder why Phoscon does not offer to set the exact hours and minutes or at least (as an interim solution) shows in parentheses how "from evening to morning" and "during the day" are timed.

I use a Raspberry Pi 2 w/ RaspBee II module | Phoscon 2.05.81 / 14.9.2020 (FW 26610700).
