### ISSUE TITLE
Hue motion sensor light detection not respected

### ISSUE THREAD

**Issue by max3-2** [dresden-elektronik/phoscon-app-beta#206]
## Describe the question or issue you are having
Paired a Hue motion sensor with Phoscon. This is running in a room with a ceiling light. **I want to only turn on the light when the ceiling light is off**, e.g. the room is dark.
I adjusted `tholddark` and `tholdoffset` so that the sensor shows `dark : false` and `daylight : true` If the ceiling light is on. Even though., the sensor triggers (icon in Phoscon) and the connected group lights up and starts the motion sensor mode.

- Do I need to update / reboot the sensor in any way to apply the new values? 
- What exactly does the sensitive (currently on 2, max. Value) influence if light levels are set elsewhere (see above)

## Environment
Vanilla updated deconz (service), phoscon, RPi, RaspBee II

**Comment by max3-2** [comment]
This was actually a quite easy fix after some time looking into rules. When searching the created rules, identify the pir-......-start for the group in question and add the sensors values using `POST` and `eq` as additional conditions. After deleting and (re-)creating a rule, this has to be done again. Edits from PHOSCON seem to be `PUT` and thus do not interfere with the custom edits performed.

I still think this might a an interesting feature like a checkbox "Consider local sensor light level" - Is this the place to submit sort of a feature request?

**Comment by YKO-de** [comment]
I will include the idea in the future planning of the app. And you are welcome to contribute ideas under phoscon-app-beta.
