### ISSUE TITLE
Philips Hue Motion Sensor: Cannot configure daylight parameter in phoscon App

### ISSUE THREAD

**Issue by jwich71** [dresden-elektronik/phoscon-app-beta#209]
Where can I configure the daylight parameter for Hue Motion Sensor in phoscon App? The sensor is already connected and shows the current light level in lux. Now I want to use this feature to configure a light level and using it in my motion sensor control settings. But there is no option for activating motion sensor on light level (lux) basis.
How can I do this?

**Comment by Mimiix** [comment]
I moved this to the correct repository, as this is deconz and phoscon has their own repository.

@YKO-de Can you help this user?

**Comment by YKO-de** [comment]
Currently the lux value cannot be used for configuration.

**Comment by jwich71** [comment]
Hmm... not good news. I bought this sensor because it is on your compatibility list https://phoscon.de/en/conbee2/compatible. There you should point out that the device is not fully supported. 
Is it generally not supported to configure the lux value with phoscon or does it depend on the device?

**Comment by Mimiix** [comment]
@jwich71 It is. But not in phoscon. You can with the rest api ;)

**Comment by jwich71** [comment]
Can I use the rest api with openhab?

**Comment by jwich71** [comment]
Is it planned to implement the lux value feature in phoscon too?

**Comment by Mimiix** [comment]
@jwich71 Yes. Openhab uses that too.

@YKO-de Needs to answer this :)

**Comment by jwich71** [comment]
Hopefully you'll integrate the lux value for motion detection in phoscon soon. It makes much more sense to combine motion with brightness. The daytime parameter doesn't solve this in the same manner.

**Comment by YKO-de** [comment]
I am not sure if I understand the question correctly. But in the sensor control a brightness value can be set, which is adjusted when motion is detected.

**Comment by jwich71** [comment]
You have misunderstood my question: I have a Philips HUE motion sensor with daylight lux sensor. I want to configure a motion activity where depending on the Lux value I want to set myself the light is activated or not.

**Comment by bee-con** [comment]
> I want to configure a motion activity where depending on the Lux value I want to set myself the light is activated or not.

I would like to have this as well.

**Comment by jwich71** [comment]
@YKO-de Do you have new information regarding daylight lux control with motion sensor?

**Comment by YKO-de** [comment]
We do not currently support the use of the Lux value. We will include it in future plans for the app.
