### ISSUE TITLE
Can access old webapp

### ISSUE THREAD

**Issue by abmantis** [dresden-elektronik/phoscon-app-beta#21]
After accessing http://<ip-address>:<port>/pwa I can no longer access the old webapp trough http://<ip-address>:<port>
It always redirects to the new one.

**Comment by stan23** [comment]
There's a link to the old webapp:
in Phoscon GUI go to the menu, then help, and then there's the link called "Open Wireless Light Control (2016)"

**Comment by abmantis** [comment]
@stan23 That works! Thank you.

**Comment by ronnyandre** [comment]
Doesn't work here. Redirects to the new one
