### ISSUE TITLE
Question/feature request about virtual daylight sensor

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#210]
Hello,

Is it possible to use the virtual daylight sensor directly, i.e. switch a light on with sunset and switch it off with sunrise (maybe with the possibility to add/subtract an offset of x minutes)?

Do you accept feature requests like this here in the GitLab issue tracker, or shall I rather ask somewhere else? If yes, where? Thank you.

**Describe the bug**
NA - no bug

**Expected behavior**
It is possible to use the virtual daylight sensor to witch a light on with sunset and switch it off with sunrise (maybe with the possibility to add/subtract an offset of x minutes).

**Screenshots**
None

**Environment**
    Version: 26.8.2020
    Host system: Raspberry Pi 2
    Running method: Raspbian
    Firmware version: 26650700
    deCONZ version: 2.05.82
    Device: RaspBee II
    Do you use an USB extension cable: No

**deCONZ Logs**
None

**Additional context**
None

**Comment by 7wells** [comment]
Has nobody ever seen the need for this? The only current possibility for (indirect) use of this virtual daylight sensor seems to be to control a light in connection with a real motion sensor and telling it to only be active during nights hours ("From dusk till dawn"):
https://phoscon.de/en/app/img/group-edit-sensor-editor-settings-bb-en.png

Why can't we use the virtual daylight sensor directly, i.e. without another (motion) sensor?
Or am I completely misunderstanding the concept of this virtual daylight sensor?

E.g., how would you control a light to go on at sunset -1 hour and off on sinrise +1 hour?

**Comment by YKO-de** [comment]
Work is currently in progress on daylight control. However, it will still take some time.

**Comment by 7wells** [comment]
Thank you so much - I appreciate it!

If I might ask this f'up question: Is it currently possible to program a motion sensor to only trigger between certain hours? E.g. the motion sensor should switch/dim a light only between 8 pm and 10 pm. I can also open another question about this if that's better. Thanks for your kind advice.

**Comment by Herjar** [comment]
I would also like this feature. Is it still being worked on?

**Comment by Schiki** [comment]
At least there should be a hint in the documentation that this isn't possible at the moment, this would have saved me some time.
With the Philips-Hue Bridge and App you can use dawn and dusk as triggers in your own routines exactly this way.

**Comment by 7wells** [comment]
Hello!
Please open this again and explain what needs to be done too resolve this question and how we users could maybe help. Thank you so much.

**Comment by LifeIsBrilliant** [comment]
Hi, would appreciate this feature to use this virtual sensor actively
