### ISSUE TITLE
Question/feature request about long-press function for Osram Smart+ Switch (4 buttons)

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#211]
Hello,

Is it possible to add a long-press function for the Osram Smart+ Switch? (4 buttons)

Do you accept feature requests like this here in the GitLab issue tracker, or shall I rather ask somewhere else? If yes, where? Thank you.

**Describe the bug**
NA - no bug

**Expected behavior**
It is possible to use long-press function for the Osram Smart+ Switch (4 buttons), i.e. not only 4 but 8 different functions are available for that switch (4x short-press + 4x long-press).

**Screenshots**
None

**Environment**
    Version: 26.8.2020
    Host system: Raspberry Pi 2
    Running method: Raspbian
    Firmware version: 26650700
    deCONZ version: 2.05.82
    Device: RaspBee II
    Do you use an USB extension cable: No

**deCONZ Logs**
None

**Additional context**
None

**Comment by YKO-de** [comment]
I am not sure if I understand the question correctly. 
With the switch editor you can assign the long press function of the switch.

https://phoscon.de/en/app/doc#group-edit-switches-en

**Comment by 7wells** [comment]
Yes, you are right. But you cannot assign a long-press function for a button for which you have configered power-off on short-press, correct? If that is intended, that's ok. I just wanted to be sure if I have overseen something. And sorry that I was unclear in my initial post (indeed I overlooked that possibility).
