### ISSUE TITLE
Phoscon-GW: Vendor "unknown" (should be "dresden elektronik")

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#212]
Hello!

**Describe the bug**
The phoscon-app-beta shows "unknown" for vendor.

**Expected behavior**
The phoscon-app-beta shows "dresden elektronik" for vendor.

**Screenshots**
None

**Environment**
    Version: 26.8.2020
    Host system: Raspberry Pi 2
    Running method: Raspbian
    Firmware version: 26650700
    deCONZ version: 2.05.82
    Device: RaspBee II
    Do you use an USB extension cable: No

**deCONZ Logs**
None

**Additional context**
None

**Comment by YKO-de** [comment]
The bug is fixed in the meantime. And there is probably only a problem with the browser cache. Ctrl+F5 should help here.

**Comment by 7wells** [comment]
Well, it does not. It still reads "unknown" for vendor, also after Ctrl+F5 (Firefox 81.0, 64-Bit). Am I maybe using an outdated beta?
