### ISSUE TITLE
Question/feature request about definition of brightness/colour of Osram Lights after hard power-off and back to power-on

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#213]
Hello,

Is it possible to define brightness & colour of Osram Lights (e.g. Tunable White GU10, Surface Light TW, Gardenpole Mini RGBW OSRAM, Flex RGBW, and Classic B40 TW - LIGHTIFY) after hard power-off and back to power-on? E.g. to have a nightlight after hard power-off and back to power with only 10% of brightness.

The reason I ask: My nightlight (with a Classic B40 TW - LIGHTIFY bulb) always powers on with 100% brightness, and I mean after a hard power-off (i.e. by switching electricity off, not via zigbee) and back on. You might know how it goes: The kids forget that certain switches should be used and the regular switches left untouched. So when the light cannot be switched on via zigbee (as no electricity is on the line after a hard power-off), the regular switch is pushed and the nightlight goes on with 100% brightness - not nice in the evening. ;)

Do you accept feature requests like this here in the GitLab issue tracker, or shall I rather ask somewhere else? If yes, where? Thank you.

**Describe the bug**
NA - no bug

**Expected behavior**
It is possible to define brightness & colour of Osram Lights (Tunable White GU10, Surface Light TW, Gardenpole Mini RGBW OSRAM, Flex RGBW, and Classic B40 TW - LIGHTIFY) after hard power-off and back to power-on. E.g. to have a nightlight after hard power-off and back to power with only 10% of brightness.

**Screenshots**
None

**Environment**
    Version: 26.8.2020
    Host system: Raspberry Pi 2
    Running method: Raspbian
    Firmware version: 26650700
    deCONZ version: 2.05.82
    Device: RaspBee II
    Do you use an USB extension cable: No

**deCONZ Logs**
None

**Additional context**
None

**Comment by YKO-de** [comment]
Unfortunately this is not possible. I just tried it with an OSRAM bulb E27. There are luminaires that remember their last state and take it back even when the lamp is hard on/off. Osram is not one of them. Luminaires from IKEA, for example, can do that.

**Comment by holli73** [comment]
hello,

the answer is not correct - my complete house is only using lightify devices from osram (e27/gu10/surface tw/...)
on the deconz ui on the cluster-info node you have an osram attribute and there you can save the power own state for the bulb - i just tried it on an e27 rgbw bulb from osram - attached a screenshot so you can see what i mean.

adjust the light to the desired settings - than cluster-info on that node - follow screenshot 1-3 - if you get success - try it - but i do have sometimes (verry rare) that some devices lose it but it is a 99% solution and easy to fix it it is lost.
<img width="876" alt="deconz-osram startup" src="https://user-images.githubusercontent.com/1434090/94654076-d4cab280-02fc-11eb-9e0e-ebaa3fa85740.png">

**Comment by 7wells** [comment]
@holli73 
Yes, I could save the states of all my Osram Lightify/Osram Smart+ lights with the decommissioned Lightify app, and I am glad for your confirmation and screenshot. For the time being, this is at least a workaround.

@YKO-de 
Would you mind adding this as a feature request for a future phoscon version? (for lights that support this)

Thank you both!

**Comment by 7wells** [comment]
Hello, why is this topic still closed? Can you please reopen it? Thank you.

**Comment by YKO-de** [comment]
@holli73 Thanks for the tip. I had not thought of that.

**Comment by ebaauw** [comment]
I adde the definition of the command to general.xml, so it shows in the GUI, but it’s not exposed over the API.  That would be the first step in supporting this from Phoscon.

**Comment by wesnm** [comment]
My LEDVANCE, which were sold under the OSRAM branding, return UNSUP_CLUSTER_COMMAND. Any hope of debugging this without another hub?

**Comment by YKO-de** [comment]
@wesnm Which do you have the US or EU version?

**Comment by 7wells** [comment]
Is this still about the topic of this request? Is somebody working on it? How can I help? I have the EU devices (Osram Lightify and Osram Smart+ GU10 Tunable White).

**Comment by wesnm** [comment]
@YKO-de I have the US version.
