### ISSUE TITLE
Phoscon help should be in English when gateway is set to English

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#214]
Hello!

**Describe the bug**
The phoscon online help appears in German when the gateway language is set to English:
https://phoscon.de/de/app/doc

**Expected behavior**
When the phoscon gateway language is set to English, the online help should appear in English:
https://phoscon.de/en/app/doc

**Steps to reproduce**
1. Set gateway language to English (Einstellungen/Settings => Darstellung/View => Sprache/Language = English).
2. Go to help (Help => Instructions => Online help).
3. The link https://phoscon.de/app/doc redirects to https://phoscon.de/de/app/doc despite language is set to English.

**Screenshots**
None

**Environment**
    Version: 26.8.2020
    Host system: Raspberry Pi 2
    Running method: Raspbian
    Firmware version: 26650700
    deCONZ version: 2.05.82
    Device: RaspBee II
    Do you use an USB extension cable: No
    Browser: Firefox 81.0 (64-Bit)

**deCONZ Logs**
None

**Additional context**
None

**Comment by YKO-de** [comment]
Thanks for the hint. I will correct that.
