### ISSUE TITLE
Phoscon not loading with Conbee II

### ISSUE THREAD

**Issue by PhilipKazmeier** [dresden-elektronik/phoscon-app-beta#215]
Hello,

I am trying to set up the Conbee II USB stick with Hass.IO and the deCONZ Add-On and have issues with the Phoscon application.

**Describe the bug**

I have a Conbee II USB Stick that is connected to one of the USB 2.0 ports of my Raspberry Pi 4.
I am running Hass.io and have installted deCONZ as an Add-On.
The device is successfully detected as /dev/ttyACM0 and is also shown in the deCONZ interface via VNC.

However, when I open the Phoscon interface, it only shows the the Phoscon logo and no gateway. 
I am able to click onto the logo to start the scan, but nothing happens. 
![Screen](https://user-images.githubusercontent.com/6966688/94462744-418a6380-01bc-11eb-806a-31c1471f97b0.png)

On the console, there are several errors:
![Errors](https://user-images.githubusercontent.com/6966688/94462721-3b948280-01bc-11eb-8399-f8c2f55c4624.png)

The relevant lines where the errors on the console occur:
- Uncaught TypeError: app.on is not a function
```js
    app.on("active-item-changed", ()=>{
        app.listGroups || (app.listGroups = document.querySelectorAll(".main-list .list-group")),
        app.listGroups.forEach(el=>{
            el.shdRAF || (el.shdRAF = requestAnimationFrame(()=>{
                setShadowClass(el)
            }
            ))
        }
        )
    }
```
- Uncaught Error: avail
```js
function probeSubnet(ip) { throw new Error('avail');
    return request('GET', '//' + ip, timeoutSubnetsMs)
           .catch(err => {
                if (err === 'avail' && false)
                    return Promise.resolve();
                //console.log(ip, err);
                throw err;
            });
}
```

I am not sure if it is an error with Phoscon or if I am doing something wrong.

Help would be appreciated.

**Expected behavior**

I am able to see the gateway in the Phoscon interface.

**Screenshots**

**Environment**
Phoscon version: 2020-09-14
deCONZ: 6.3.0
Host system: Raspberry Pi 4 (4GB)
OS: Hass.IO
Device: Conbee II
Do you use an USB extension cable: No

**deCONZ Logs**

[deconz.log](https://github.com/dresden-elektronik/phoscon-app-beta/files/5293806/deconz.log)

**Additional context**
None

**Comment by FelixGail** [comment]
Did you find a solution for this problem? I am currently facing exactly the same issue.

**Comment by tannyl** [comment]
This problem is not a problem with the Phoscon App it self (even though the javascript behind the Phoscon App is rather wonky and contains errors), but rather a problem in the way  Home Assistant Ingress integration is handled.

If you access the Home Assistant interface directly via its IP address, then Phoscon App will work.
But access it via a FQDN (domain name) and it won't work, due to several different errors.

I have attempted to create a fix for this and submitted a PR to the Home Assistant Addon repo.
