### ISSUE TITLE
Unable to login to PhosCon App, but WebApp works

### ISSUE THREAD

**Issue by PrimaryInc** [dresden-elektronik/phoscon-app-beta#216]
Hi Guys, 

So for a while I've been having issues not being able to logon to PhosCon App while WebApp works well.
PhosCon App button from DeConz UI open web browser on localhost:8090/pwa/login.html

![Screenshot 2020-09-29 at 08 59 39](https://user-images.githubusercontent.com/45151934/94523862-1cd0d300-0232-11eb-87b1-ead6facfa5a6.png)

Pushing the bridge Icon then asks me to sett a new password.

![Screenshot 2020-09-29 at 09 00 59](https://user-images.githubusercontent.com/45151934/94523992-4c7fdb00-0232-11eb-9839-c6785b79cf44.png)

And here Im stuck.

WebApp sends me to localhost:8090/login.html and Im able to login.
![Screenshot 2020-09-29 at 09 03 33](https://user-images.githubusercontent.com/45151934/94524247-a84a6400-0232-11eb-9d8f-c8e834fd1f6b.png)

So what am I missing on PhosCon App?

DeZonz 2.05.81 runing on windows

Thanks :)

**Comment by YKO-de** [comment]
Hey. Do you use the default password in the old web app? To improve Security the Phoscon App requires to set a new stronger password in case the old default password is set.

**Comment by PrimaryInc** [comment]
Hi @YKO-de, no the default password was changed at install a looooong time ago :) Before this issues started to happen.

**Comment by ChrisHae** [comment]
I don't understand quite well where you are stuck.
the Phoscon app asks you to choose a new password. And then? What happen when you choose a new password? Can you not click the "next" button?

**Comment by PrimaryInc** [comment]
Hi @ChrisHae, 

Thing is that password was changed long time ago, I have been able to reset password and then be able to login.
But when ever Deconz/Phoscon has been running for a few days, I get asked to change passoword, and it does not work.
And no I cannot continue, error statues the new passord is not accepted. So Phoscon is at this stage useless 🤷‍♂️

Error show is Login failed.

**Comment by PrimaryInc** [comment]
Oh, upgraded to .86 today did not change anything.

**Comment by PrimaryInc** [comment]
So I had time to look into this and i had a switch I had to configure. Per default pressing the button Phoscon in Deconz openes a web browser with the url http://127.0.0.1:8090/pwa so i swapped 127.0.0.1 with FQDN and login works a expected. Not sure if this is by design, og a bug, or an enhancement to be fixed. But it solves my isues. I'll leve the case open for comment for a day or two.
