### ISSUE TITLE
Cannot link Aquara Switch to any groups

### ISSUE THREAD

**Issue by crabmanX** [dresden-elektronik/phoscon-app-beta#221]
My setup:

- Aqara D1 2 Gang switch (WXKG07LM)
- Phoscon version: 2.05.83 / 14.9.2020
- Conbe II Version: 26580700
- deconz is running in a docker container (marthoc/docker-deconz) on CentOS 7

I have successfully paired the switch, it is displayed in phoscon in the "Connected switches" section and listed when polling the REST API. Listening to events via home assistant works fine, too. However, the switch is not displayed when trying to link it to a group:

![grafik](https://user-images.githubusercontent.com/1190429/95015225-184e5500-064c-11eb-946f-aecedb68890b.png)
![grafik](https://user-images.githubusercontent.com/1190429/95015239-2dc37f00-064c-11eb-9e55-c33617fbb146.png)
![grafik](https://user-images.githubusercontent.com/1190429/95015286-56e40f80-064c-11eb-9e86-0c8df1a7199d.png)

```
{
<snip>
  "2": {
    "config": {
      "battery": 100,
      "group": "2",
      "on": true,
      "reachable": true
    },
    "ep": 2,
    "etag": "dc644cdc3ba8eb7598fa505ba3a53232",
    "lastseen": "2020-10-04T12:19Z",
    "manufacturername": "Philips",
    "mode": 1,
    "modelid": "RWL021",
    "name": "WZ_dimmer",
    "state": {
      "buttonevent": 4002,
      "eventduration": 2,
      "lastupdated": "2020-10-03T21:12:29.821"
    },
    "swversion": "5.45.1.17846",
    "type": "ZHASwitch",
    "uniqueid": "00:17:88:01:10:5e:5e:0c-02-fc00"
  },
  "3": {
    "config": {
      "battery": 61,
      "group": "4",
      "on": true,
      "reachable": true
    },
    "ep": 2,
    "etag": "bcdecf0de01341757bb8a58e8ce264ce",
    "lastseen": "2020-10-04T12:20Z",
    "manufacturername": "Philips",
    "mode": 1,
    "modelid": "RWL021",
    "name": "SZ_dimmer",
    "state": {
      "buttonevent": 1002,
      "eventduration": 1,
      "lastupdated": "2020-09-30T16:49:23.447"
    },
    "swversion": "6.1.1.28573",
    "type": "ZHASwitch",
    "uniqueid": "00:17:88:01:10:5e:5e:28-02-fc00"
  },
<snip>
  "8": {
    "config": {
      "battery": 100,
      "on": true,
      "reachable": true,
      "temperature": 2800
    },
    "ep": 1,
    "etag": "eed8b3dcf4b631add29e46eaedd3dd99",
    "lastseen": "2020-10-04T11:43Z",
    "manufacturername": "LUMI",
    "mode": 1,
    "modelid": "lumi.remote.b286acn02",
    "name": "SZ_schalter_1",
    "state": {
      "buttonevent": 1002,
      "lastupdated": "2020-10-03T05:35:14.857"
    },
    "swversion": "20190329",
    "type": "ZHASwitch",
    "uniqueid": "00:15:8d:00:04:4e:78:98-01-0012"
  }
}

```

**Comment by SwoopX** [comment]
It is not confirmed those devices support zigbee groups at all. To be more precise, the may allow you to assign it to a group, but it's questionable if they can use group casts unless somebody confirms.

**Comment by crabmanX** [comment]
So is there a way to check whether group casts are supported from 
deconz? I couldnt

Am 04.10.20 um 16:47 schrieb SwoopX:

**Comment by YKO-de** [comment]
I will take care of it. For the next release he will be there.

**Comment by crabmanX** [comment]
@YKO-de : Thats great news! Which release is going to fix this issue? I am currently running 2.05.86 / 15.10.2020 FW 26660700 but the switch does not show up in the editor.

**Comment by YKO-de** [comment]
15.11.

I would also close the issue with this. If it does not work, then simply make a new one.

**Comment by crabmanX** [comment]
I just tested with the latest release and it works like a charm. Many thanks!
