### ISSUE TITLE
IKEA rotating dimmer - not able to add it to a group

### ISSUE THREAD

**Issue by magnusvage** [dresden-elektronik/phoscon-app-beta#222]
Just bought an a IKEA rotating dimmer, and was able to pair it with my Conbee2 without issue, but when I add it to a group, it doesn't show up in the list of available switches. What am I doing wrong?

Version: 2.05.83 / 14/09/2020
Firmware: 26580700

<img width="1680" alt="Screenshot 2020-10-07 at 20 11 46" src="https://user-images.githubusercontent.com/36159342/95374579-cd983b80-08de-11eb-8cd7-08905030d18d.png">
<img width="1680" alt="Screenshot 2020-10-07 at 20 12 03" src="https://user-images.githubusercontent.com/36159342/95374582-cec96880-08de-11eb-883e-bfd1ce560563.png">
<img width="1680" alt="Screenshot 2020-10-07 at 20 12 22" src="https://user-images.githubusercontent.com/36159342/95374583-cec96880-08de-11eb-957c-8d502b659218.png">

**Comment by YKO-de** [comment]
You're not doing anything wrong. The switch is currently not supported in the Switch Editor.

**Comment by magnusvage** [comment]
> You're not doing anything wrong. The switch is currently not supported in the Switch Editor.

Copy that. Triggering on the events in Home Assistant works just fine in the meantime. I heard rumors that IKEA is retiring this dimmer, will there be support in future versions?

**Comment by YKO-de** [comment]
As far as I know, IKEA no longer has it. You can only get it from third parties. After tests we have made the experience that it does not work reliably. Since IKEA will probably no longer provide updates, we do not plan to support it any further.
