### ISSUE TITLE
How to backup the devices configuration

### ISSUE THREAD

**Issue by pippo73** [dresden-elektronik/phoscon-app-beta#223]
Hello all.
I hope this is the right place where to post my request.
I would like to know if there is a way to backup the configuration of the network/names/triggers?
If migrate to an similar system or format and reinstall it, may I backup all my network or I have to rescan and reconfigure my network every time?

thank

PS I'm not sure this is the right place where to post my request. If I'm wrong, I'm sorry. Point me where to post my question

**Comment by YKO-de** [comment]
If I understand the question correctly, all you really need to do is Settings -> Gateway -> Backup Options. Make a backup.

**Comment by pippo73** [comment]
I will give a try... I've really did not seen this :-P
thank you really much
