### ISSUE TITLE
Bug: Phoscon App - Sensor sorting by name

### ISSUE THREAD

**Issue by TungstenE2** [dresden-elektronik/phoscon-app-beta#224]
Hi all,

phoscon app is sorting sensors by ID and not by sensor name, while ID is not visible in app.

Please fix.

![grafik](https://user-images.githubusercontent.com/39955685/95686072-05afbf00-0bfc-11eb-9dc5-a53ff2d7f798.png)
![grafik](https://user-images.githubusercontent.com/39955685/95686121-4c9db480-0bfc-11eb-8dea-e10d7bdb31e9.png)

**Comment by thomasvnl** [comment]
It would even be better if this table was sortable by clicking on one of the headers (e.g. name/type/vendor, as values header is not realistic to sort by).

**Comment by YKO-de** [comment]
I once wrote a small function for the sensor page. Can be tested in the beta. I would be glad about a feedback.

**Comment by YKO-de** [comment]
@TungstenE2 Should also work now, in the beta.

**Comment by jensflorian** [comment]
Bump

**Comment by YKO-de** [comment]
So you can sort, but the pictures are missing and you can't see the S1?

**Comment by thomasvnl** [comment]
@YKO-de In what release should sorting be implemented? I am running <code>2.07.01</code> but am not able to sort sensors.

**Comment by jensflorian** [comment]
> So you can sort, but the pictures are missing and you can't see the S1?

Yes, exactly. The pictures are missing in the switches beta folder but are shown in the normal switches folder.

**Comment by YKO-de** [comment]
@thomasvnl Currently, the sorting function is only available in beta.
@jensflorian Thank you for pointing this out. I'll take another look at it.

**Comment by MGrotz** [comment]
@YKO-de: Thank you for implementing the sort function. it is working great in the beta.
May I ask you to also include a sorting into the settings page of adding Sensor control to a group -currently it looks unsorted:
![2021-01-06_11h37_51](https://user-images.githubusercontent.com/49819913/103759484-1661ac80-5014-11eb-945d-b8bd6a773907.png)

**Comment by YKO-de** [comment]
This page is currently being revised. Therefore, no sorting function is provided in the current version for the time being.
