### ISSUE TITLE
Last update info do not respect language settings

### ISSUE THREAD

**Issue by kses** [dresden-elektronik/phoscon-app-beta#227]
I have the set the language to english but the last update extra info is in german. See attached screen shots.

Version: 2.05.85 / 2020-10-15

<img width="573" alt="image" src="https://user-images.githubusercontent.com/17168512/96386678-f355f800-119c-11eb-9f5f-e401495cc61e.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/17168512/96386684-0ff23000-119d-11eb-87ec-7bb77834f94f.png">

**Comment by YKO-de** [comment]
The error is known to us and will be fixed with the next release.

**Comment by kses** [comment]
Great! Thank you!
