### ISSUE TITLE
[Question] Which in-wall (German "Unterputz") zigbee actors for 240V (at least 1000W) sockets are supported?

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#228]
Hello,

Are there any in-wall (German "Unterputz") zigbee actors for 240V (at least 1000W) sockets supported? I mean an actor that can be placed in-wall (=flush-mounted) behind the usual socket (if, of course, there is enough room). I have not found any in the compatibility lists, but maybe that does not mean much?

More generally, which zigbee standard/version (3.0?) is currently supported by the RaspBee II module?

I hope it is ok to ask these questions here as an "issue". If not or if this rather belongs to another forum, I kindly ask the moderators to move my post. And thank you for your hints regarding support/compatibility.

**Comment by YKO-de** [comment]
Here is the list from deconz. Maybe there is something there. If you are looking for a specific device, you can also make an enquiry there. This is more about devices that are supported below, but are not visible in the app.

**Comment by 7wells** [comment]
PS for interested people:
https://zigbee.blakadder.com
