### ISSUE TITLE
Feature request | Xiaomi Aqara Opple Switch | Long press button support in Phoscon

### ISSUE THREAD

**Issue by helipus** [dresden-elektronik/phoscon-app-beta#229]
Hi there,
the Xiaomi Aqara Opple Switch WXCJKG13LM supports five different button events:
1x press
2x press
3x press
button hold long
button released

In the moment only the first three are implemented in the Phoscon App. It would be great to use the long button press as well to combine it with the dimming features. Is it possible for someone to implement that?
![image](https://user-images.githubusercontent.com/19687604/96843563-c16bbc80-144e-11eb-9b79-188496dc539e.png)

**Comment by YKO-de** [comment]
The problem with the switch is that it does not give me a release event. At least mine does not. So I do not know when a hold is finished. Therefore I cannot offer a hold event.

**Comment by helipus** [comment]
Hi @YKO-de,
since the last update 2.05.86 the switch gives me the following button events:
100x	200x
300x	400x
500x 	600x

For example on the first button 100x:
1002	short	 	
1001	pressed but not released yet		 
1003	released	
1004	2x press	
1005	3x press   

Does this help in anyway?

**Comment by YKO-de** [comment]
Okay. I re-trained mine. You're right. There is now also with release. I added it. You can test it at phoscon.de/pwabeta. But there is no additional key below the picture now. Just select 1x and then select dim as function.

**Comment by helipus** [comment]
I would like to test it but how is the password to login there?

**Comment by YKO-de** [comment]
The password of your gateway. Select your Conbee or Raspbee and enter your password. Just like in the Phoscon app. This is just a different version.

**Comment by helipus** [comment]
It works! Thank you so much.

But I would like to suggest another way of implementation.  I would like to switch the lights ON with button 1 using the toggle feature. 
Button 2 will have a complete different duty.
Long press 1 will reduce the lights and long press 2 will make the lights brighter.
This way it is not handy that there is no additional key in the picture now.

With my implementation idea I can have 24 diffent function with this 6 button switch.
Example for my planned implementation in the far future:
````
1002	short	 	toggle scene Relax ON/OFF
1001	pressed		dim all active lights darker
1003	released	stop dimming
1004	2x press	Musik Playlist Easy Listining
1005	3x press    Schaumi reinigt Wohnzimmertisch

2002	short	 	toggle scene Clean ON/OFF
2001	pressed		dim all active lights brighter
2003	released	stop dimming
2004	2x press	Musik Playlist Party
2005	2x press    Schaumi reinigt Wohnzimmer komplett

3002	short	 	toggle scene TV ON/OFF
3001	pressed		
3003	released	
3004	2x press	Musik aus, Fernseher an
3005	3x press    


4002	short	 	toggle scene Dining ON/OFF
4001	pressed		
4003	released	n/n
4004	2x press	Musik Playlist Dining
4005	3x press    Schaumi reinigt unter Esstisch

5002	short	 	toggle scene X-MAS ON/OFF
5001	pressed		all lights OFF
5003	released	scene X-MAS ON
5004	2x press	Musik Playlist Weihnachten
5005	3x press    


6002	short	 	toggle scene Party ON/OFF
6001	pressed		all lights OFF
6003	released	scene Party ON
6004	2x press	Musik Playlist Erwachsenenparty
6005	3x press    Musik Playlist Kinderparty
```

**Comment by YKO-de** [comment]
You can assign a long press to each key. I meant the keys under the picture. There are only 1x, 2x, 3x. And it doesn't matter what you select there. If you decide to dim the picture, then the long press will do the job. The events hold and relese are currently not independently allocatable.

**Comment by helipus** [comment]
Yes I undestood and this is working really good. I think it also handles 99% of all use cases.

For the 1% use cases this would be nice:
Can you may be then add the option to also only dimm the light?
![image](https://user-images.githubusercontent.com/19687604/96860159-b589f580-1462-11eb-9db6-e5d9c8d65db3.png)
This way I can here use button 2 for a other group of lights.

By the way: I don't find how to delete a scene in the Phoscon App. There is no delete button anywhere as for the other items. :-)

**Comment by YKO-de** [comment]
Ahh. Okay. I'll include it in the planning. It's gonna take a little longer than the other one right now. ;)

**Comment by stheinen** [comment]
Hello, 
I do not see the long press code x003 in the deCONZ iobroker adapter as well as in node red. 
Is there a solution for this issues?

**Comment by helipus** [comment]
@YKO-de : When do you have it in the planning?

**Comment by helipus** [comment]
@YKO-de : When do you have it in the planning? I try to keep it open.

**Comment by manup** [comment]
I think this should be fixed in the next release.

**Comment by helipus** [comment]
I try to keep it open.

**Comment by SEK-DE** [comment]
@manup anything new?

**Comment by helipus** [comment]
Is this issue solved now in any version @SEK-DE ?
