### ISSUE TITLE
Direct login url

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/phoscon-app-beta#23]
I would like to have the possibility of using a full url to directly login to a specific device and provide user name and password directly. This so I could easily embed phoscon in an iframe inside of home assistant with pale iframe component

**Comment by manup** [comment]
You can use `http://<ipaddress>/pwa/index.html`, the first time this will open login.html but once logged in the next time index.html should open directly since the credentials are cached in browsers localStorage (until user logged out).

**Comment by marcelmu** [comment]
This seems to work ... at least on my Desktop. 
On my Phone I have phoscon saved as a PWA (Add to Homescreen option in chrome). There I always have to select the Gateway and enter the credentials. Even though savng credentials is generally enabled in Chrome

**Comment by MickL** [comment]
@manup The url is outdated and does not work anymore. What is the latest one?

**Comment by ebaauw** [comment]
https://phoscon.de/app
