### ISSUE TITLE
Cannot add any new switches

### ISSUE THREAD

**Issue by JasperAlgra** [dresden-elektronik/phoscon-app-beta#230]
I'm trying to add new switched to an already existing setup. 

Phoscon version: 2.05.86 / 10/15/2020

I've tried
- Phoscon beta
- normal webinterface
- old interface

Three types of hardware:
- IKEA E1743 (rectangular on / off remote) (brand new, don't know firmware)
- IKEA E1524 (round remote) (latest firmware)
- Xiaomi Oplle 3-gang (WXCJKG12LM)

I've already have a few of the E1743 and xiaomi switches joined and working. But I cannot add any new ones.

Trying to join fails in similar ways, the device can be seen in Deconz GUI but not in phoscon. 
Attached are screenshots + the log.

If you need anything else please let me know.

Result in Phoscon:
![firefox_r3r7lxCrvE](https://user-images.githubusercontent.com/6338832/96937350-7043e300-14b7-11eb-8ff4-c26d1809ba97.png)
![firefox_ykhje917oU](https://user-images.githubusercontent.com/6338832/96937494-cb75d580-14b7-11eb-9458-bc6ddeb86925.png)

In Deconz Gui the devices are seen:
![XWin_MobaX_6cd58utt52](https://user-images.githubusercontent.com/6338832/96937356-75a12d80-14b7-11eb-899c-ffdeb205e0d2.png)
![XWin_MobaX_3EtVlOK7Zk](https://user-images.githubusercontent.com/6338832/96937362-78038780-14b7-11eb-8c26-5264c88b789d.png)

webbrowser console log:
![firefox_5MTl7gPthW](https://user-images.githubusercontent.com/6338832/96937437-a2554500-14b7-11eb-938d-0e8dec958872.png)
![firefox_2bKfbZF0rz](https://user-images.githubusercontent.com/6338832/96937439-a3867200-14b7-11eb-91ae-04cbc87a5bf6.png)

Log file:
[20201023-adding_switch.log](https://github.com/dresden-elektronik/phoscon-app-beta/files/5426300/20201023-adding_switch.log)

**Comment by Mimiix** [comment]
Wrong Github repo. I am not moving it, as it does not follow the templates. 

https://github.com/dresden-elektronik/deconz-rest-plugin

Should open a issue there, while following the template.


@YKO-de You can close this one if you want.

**Comment by YKO-de** [comment]
Good. Then I would close it now.
