### ISSUE TITLE
Feature Request: A warning/block if device is "Not connected"

### ISSUE THREAD

**Issue by Mimiix** [dresden-elektronik/phoscon-app-beta#231]
Hi!

Within the discord, i see a lot of users that say they can't pair devices. Afterwards, 6/10 times it was due to misconfiguration of their conbee to the software. This could be prevented if a user was actively notified with a message that it's not connected.  Best way would be that they can't search for lights/sensors/switches and errors out. 

This should be simple to implement, as it's a simple "if" statement. 

Thanks!

**Comment by YKO-de** [comment]
Yeah, okay. Thanks for the advice.

**Comment by Mimiix** [comment]
Anything on a ETA of this?

**Comment by YKO-de** [comment]
I'm working on it.

**Comment by Mimiix** [comment]
Your my hero!

**Comment by YKO-de** [comment]
Okay. I'm done. I'm about to update the beta. In stable it will be ready for the next release.
