### ISSUE TITLE
Bug: Xiaomi Smart Button - Option Dim / On-Off not working anymore

### ISSUE THREAD

**Issue by cavernerg** [dresden-elektronik/phoscon-app-beta#232]
I'm using this button: https://www.amazon.de/gp/product/B07X71ZS7J/ref=ppx_yo_dt_b_asin_title_o04_s01?ie=UTF8&psc=1

Since Updating to: 
2.05.86 / 15.10.2020
26660700

I can't use the option 'on / off (short press) , dim on long press' ("abwechselnd heller/dunkler, an/aus") on 1x-click. 
It causes the lights to just go on and off again really fast after short press. 

When using just "on/off" it works fine.

**Comment by cavernerg** [comment]
Now it's getting worse, on/off not working either. - also hue switch won't work.

**Comment by YKO-de** [comment]
Do you have the possibility to check if the shuttering delivers the release event. Pretty likely it's 1003, if he delivers it.

**Comment by cavernerg** [comment]
Can I see that in phoscon or deconz-vnc?

**Comment by YKO-de** [comment]
You can also see this in Phoscon. But the best way is directly over the Api. With a programme. For example Postman. Do you know how to do it.

**Comment by cavernerg** [comment]
I know postman, but never used it for ZigBee /deconz. Phoscon would be easier I think

**Comment by YKO-de** [comment]
Okay. Then simply open the developer console (F12). Click on the Network Tap there. 
![image](https://user-images.githubusercontent.com/55535297/97982041-79945000-1dd3-11eb-90b9-4a3728f62a5d.png)

Now there should be a list on the left. Now when you start to press and hold the switch. The event appears here.
![image](https://user-images.githubusercontent.com/55535297/97982190-b102fc80-1dd3-11eb-82d4-f6a9d5ce2dc5.png)

And you can see it on the right. 
![image](https://user-images.githubusercontent.com/55535297/97982311-e14a9b00-1dd3-11eb-8311-f17755436b12.png)

What I would like to know. If you let go now. Will there be another event and if so which one.

**Comment by cavernerg** [comment]
Ok thats pretty easy. 😊 

 

Long Pressed: 



 

Release: 



 

 

 

And just the short press:



 

Von: YKO-de 
Gesendet: Dienstag, 3. November 2020 12:57
An: dresden-elektronik/phoscon-app-beta <phoscon-app-beta@noreply.github.com>
Cc: cavernerg <daniel@ruping.de>; Author <author@noreply.github.com>
Betreff: Re: [dresden-elektronik/phoscon-app-beta] Bug: Xiaomi Smart Button - Option Dim / On-Off not working anymore (#232)

 

Okay. Then simply open the developer console (F12). Click on the Network Tap there.
 <https://user-images.githubusercontent.com/55535297/97982041-79945000-1dd3-11eb-90b9-4a3728f62a5d.png> 

Now there should be a list on the left. Now when you start to press and hold the switch. The event appears here.
 <https://user-images.githubusercontent.com/55535297/97982190-b102fc80-1dd3-11eb-82d4-f6a9d5ce2dc5.png> 

And you can see it on the right.
 <https://user-images.githubusercontent.com/55535297/97982311-e14a9b00-1dd3-11eb-8311-f17755436b12.png> 

What I would like to know. If you let go now. Will there be another event and if so which one.

**Comment by YKO-de** [comment]
I don't know if you have added pictures. But it looks like I'm just about to...
![image](https://user-images.githubusercontent.com/55535297/97988918-0a702900-1dde-11eb-906b-c8bfa4f3e636.png)
^^

**Comment by cavernerg** [comment]
Yeah I did ☹ 

 

Long press begin: 

{"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"75bb059d87af0edf761358f8e119b470","lastseen":"2020-11-03T13:01Z","manufacturername":"LUMI","mode":1,"modelid":"lumi.sensor_switch","name":"Schalter Wohnzimmer hint. Reihe","state":{"buttonevent":1000,"lastupdated":"2020-11-03T13:01:13.984"},"type":"ZHASwitch","uniqueid":"00:15:8d:00:04:a0:31:9e-01-0006"}

Long press Release: 

{"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"cebdbf447096913dcae1de4a1e6608be","lastseen":"2020-11-03T13:01Z","manufacturername":"LUMI","mode":1,"modelid":"lumi.sensor_switch","name":"Schalter Wohnzimmer hint. Reihe","state":{"buttonevent":1002,"lastupdated":"2020-11-03T13:01:18.275"},"type":"ZHASwitch","uniqueid":"00:15:8d:00:04:a0:31:9e-01-0006"}

 

Short press: 

 

{"config":{"battery":100,"on":true,"reachable":true},"ep":1,"etag":"a78f7bb4d77d09e51c889e3326e326ee","lastseen":"2020-11-03T13:02Z","manufacturername":"LUMI","mode":1,"modelid":"lumi.sensor_switch","name":"Schalter Wohnzimmer hint. Reihe","state":{"buttonevent":1000,"lastupdated":"2020-11-03T13:02:40.263"},"type":"ZHASwitch","uniqueid":"00:15:8d:00:04:a0:31:9e-01-0006"}

 

Von: YKO-de 
Gesendet: Dienstag, 3. November 2020 14:10
An: dresden-elektronik/phoscon-app-beta <phoscon-app-beta@noreply.github.com>
Cc: cavernerg <daniel@ruping.de>; Author <author@noreply.github.com>
Betreff: Re: [dresden-elektronik/phoscon-app-beta] Bug: Xiaomi Smart Button - Option Dim / On-Off not working anymore (#232)

 

I don't know if you have added pictures. But it looks like I'm just about to...
 <https://user-images.githubusercontent.com/55535297/97988918-0a702900-1dde-11eb-906b-c8bfa4f3e636.png> 
^^

**Comment by YKO-de** [comment]
Okay. Just learned the problem was already known. It should be fixed with the next release on the 15th. However, you might have to create the rules again. If it still doesn't work, then just write again.

**Comment by cavernerg** [comment]
Okay. 


Do you have any experience how long it will take for new versions to go into docker (Marthoc/deconz)?
