### ISSUE TITLE
Dialog "Zuweisung Farbtemperatur ändern": Textfehler

### ISSUE THREAD

**Issue by StephanStS** [dresden-elektronik/phoscon-app-beta#235]
Der Text in Dialog ist vermutlich falsch.

![grafik](https://user-images.githubusercontent.com/57687516/97988148-cfb9c100-1ddc-11eb-9a7d-3008b12ce3d0.png)

**Comment by YKO-de** [comment]
I will take care of it. Thanks for the advice.
