### ISSUE TITLE
[Device Support Request] innr SP220 smart plug

### ISSUE THREAD

**Issue by wuast94** [dresden-elektronik/phoscon-app-beta#236]
In addition to
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2678
it would be nice to have to had them Implemented to the web ui too .. so i can rename them and use them better in Grafana and co.

Actually they all get named sp_120_2_3 sp_120_2_4 sp_120_2_5 and so on .. this makes it very difficult to work with them with services behind deconz.

When this is the wrong place to ask sry :D

**Comment by YKO-de** [comment]
SP120 and SP220 are already supported in the Ui. And can be renamed with it. Under lights. Can't you see them?

**Comment by wuast94** [comment]
ok now i see ..in home assistant they are named correctly too .. but the measurements ar named as sensor.sp_120_7_2 in Home assistant .. 

so is this a failure of the api or is HA grabbing the wrong names vor sensors? becouse the "lights" or "switch" is named correctly

**Comment by YKO-de** [comment]
Well. With us the whole thing is displayed as one device. So the socket and in it the sensors. HA will display the sensors separately. But the sensors will not be renamed, only the socket. This is probably why these names are in HA.

**Comment by tuxick** [comment]
SP220 can not track consumption data but switches ok. It's not in compatibility list though.
