### ISSUE TITLE
virtual daylight sensor triggers my outdoor lamps one hour early

### ISSUE THREAD

**Issue by bee-con** [dresden-elektronik/phoscon-app-beta#239]
## Describe the bug

Ever since daylight saving time changes (on the 25th of october), the built-in virtual daylight sensor triggers my outdoor lamps one hour early. The timezone setting is correct for my location, and the time on my raspberry Pi4 is also correct.
See also https://discord.com/channels/494922323518947329/714772122236354644/772029441647050793

## Steps to reproduce the behavior

Create a group of lamps that is controlled by motion sensor, and set this control to be active from dusk till dawn (thus using the built-in virtual daylight sensor). Set your timezone and time correctly, and then wait for daylight saving time to change from summertime to wintertime. Observe that the built-in virtual daylight sensor now triggers one hour early.

## Expected behavior

The built-in virtual daylight sensor should be aware of daylight saving time changes.

## Screenshots

See also https://discord.com/channels/494922323518947329/714772122236354644/772029441647050793

## Environment

 - Host system: Raspberry Pi 4
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version: 2.05.88
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs

not applicable.

## Additional context

not applicable.

**Comment by Mimiix** [comment]
@ebaauw Done!

**Comment by bee-con** [comment]
> BTW, where is the Phoscon repo? I could only find one for beta versions...
> https://github.com/dresden-elektronik/phoscon-app-beta

...got my question answered. Thanks, @Mimiix and @ebaauw. @YKO-de : Let me know if you need additional information.

**Comment by bee-con** [comment]
At 08:12 this morning, the virtual daylight sensors value for "daylight" was still false. As was the value for "dark", btw.

![daylight_sensor_at_0812](https://user-images.githubusercontent.com/73778640/99142112-4ca53000-2652-11eb-9c97-ae5f77d383fe.jpg)

At 08.18, the values looked this this:

![daylight_sensor_at_0818](https://user-images.githubusercontent.com/73778640/99142115-5169e400-2652-11eb-9a5a-6657c08ec3bb.jpg)

I've written a small iobroker blockly script to monitor changes in "daylight", the change occurred at 08:16:16.421.

![daylight_sensor_change_at_0816](https://user-images.githubusercontent.com/73778640/99142116-5464d480-2652-11eb-8023-0985baa2e968.jpg)

Is the calculation performed by deCONZ correct? 06:46 + 30 minutes != 08:16, imho.

**Comment by bee-con** [comment]
> Is the calculation performed by deCONZ correct? 06:46 + 30 minutes != 08:16, imho.

My mistake, apparently. The display in iobroker seems to be incorrect, shows UTC as GMT. So 06:46 UTC = 7:46 GMT. 
And 07:46 is also what my iPhone states as sunrise for my location.
Add 30 minutes to this, and you get 08:16 GMT.
Will monitor the change from daylight to dark tonight and report back. If that is also correct, I will close this issue.

**Comment by bee-con** [comment]
> I've written a small iobroker blockly script to monitor changes in "daylight"

And a second blockly script to monitor changes in "dark":
![monitor_dark](https://user-images.githubusercontent.com/73778640/99145443-3194e900-266f-11eb-8ec9-53a40d53a00a.jpg)

**Comment by bee-con** [comment]
> Will monitor the change from daylight to dark tonight and report back. If that is also correct, I will close this issue.

![daylight_dark](https://user-images.githubusercontent.com/73778640/99150699-a0d20380-2696-11eb-805b-1d0a1b763cd2.jpg)

My bad. Apparently, everything is working exactly as it should, and my own human perception (it is still light at the moment) led me to believe things were otherwise. Closing the case, sorry for the fuss.

**Comment by bee-con** [comment]
pebkac (problem exists between keyboard and chair)

**Comment by Mimiix** [comment]
@bee-con No worries!
Glad it works 👍
