### ISSUE TITLE
Switcheditor dont work for Busch Jäger / Jung Light Link Switches...

### ISSUE THREAD

**Issue by v8turbo** [dresden-elektronik/phoscon-app-beta#240]
Hello,

i bought a 4-Channel Busch Jäger Light Link Switch and i miss the function "Switcheditor" in the Phoscon App. When comes it ? Its only a bug ?

Thanks

**Comment by YKO-de** [comment]
Busch Jäger should actually work. Can you tell me the modelid of the device?
