### ISSUE TITLE
Login failure with Phoscon App V2_05_86 and later

### ISSUE THREAD

**Issue by MikeDeltaHH** [dresden-elektronik/phoscon-app-beta#241]
Hi there!

I have a strange problem with my Conbee II Stick (newest firmware version installed) and the phoscon app on Windows 10  - i can login to the phoscon app V2_05_84 but after do an update to version V2_05_86 or later i cannot login - "login Failure" - revert to V2_05_84 the login works again - reset the password has no effect - no idea what happens - can anybody help?

Thanks!
Mike

**Comment by YKO-de** [comment]
How do you get into the app? Via browser, third party provider...?

**Comment by MikeDeltaHH** [comment]
Via Browser - test Firefox, Edge, Internet Explorer on two different PCs with no luck!

Gerne auch die Kommunikation auf deutsch... :)

**Comment by raovdk** [comment]
Same issue. Can't login on any newer versions than 2.05.84. Password reset function is not working.
When opening the phoscon app I normally see device names. They are removed on version 2.05.86 and later.
Installing 2.05.84 names and login are OK again.

**Comment by MikeDeltaHH** [comment]
@YKO-de ... any hints for this problem?

**Comment by YKO-de** [comment]
Does the problem still exist with the current version?

**Comment by MikeDeltaHH** [comment]
Yes, same problem with version V2_07_01!

**Comment by YKO-de** [comment]
Can you try this URL? 
http://phoscon.de/pwa/login.html#host/<local-ip-adress>:<port>

**Comment by MikeDeltaHH** [comment]
No luck, same problem!

**Comment by manup** [comment]
Hi can you please try the recent deCONZ Version 2.8.0, there is a Fix for Windows in it which prevent the start of the REST-API plugin on some Windows machines.

**Comment by MikeDeltaHH** [comment]
> 
> 
> Hi can you please try the recent deCONZ Version 2.8.0, there is a Fix for Windows in it for a bug which prevented the start of the REST-API plugin on some Windows machines.

This version works - thanks a lot!

**Comment by Mayhem-SWE** [comment]
Is this broken again? Just updated from 2.7.1 to the newly released 2.9.3 and Phoscon just says login failed. Password should be correct and resetting it does not seem to work either.

Using a Raspberry Pi 3b+ with RaspBee board. Still on Stretch but all available updates installed.
