### ISSUE TITLE
Devices RH3001 are partly supported

### ISSUE THREAD

**Issue by panenka** [dresden-elektronik/phoscon-app-beta#243]
Devices Tuya, Tuyatec RH3001 cannot be renamed, are not shown in Phoscon.

**Comment by YKO-de** [comment]
I'm looking at it. Should go with the next release.

**Comment by Adjrobinson** [comment]
I have one of these devices, bought from Amazon as it said specifically "supports Deconz", it works, it just doesn't show in Deconz webpage but shows in home assistant. It does show when I vnc into phoscon / Deconz. Not sure if I have done anything wrong or not.
