### ISSUE TITLE
Ubisys S1 support incomplete

### ISSUE THREAD

**Issue by jensflorian** [dresden-elektronik/phoscon-app-beta#247]
I am using 2.06.00 / 15.11.2020 with Firmware 26580700.

Ubisys S1 in wall switches are incorrectly labeled as S2 power switches in phoscon:
<img width="675" alt="Bildschirmfoto 2020-11-17 um 18 02 53" src="https://user-images.githubusercontent.com/58853392/99422058-64eda700-28ff-11eb-8706-ccf9fa23ccb3.png">

The power control option is missing for S1 switches:
<img width="696" alt="Bildschirmfoto 2020-11-17 um 18 07 10" src="https://user-images.githubusercontent.com/58853392/99422358-c150c680-28ff-11eb-924a-46d3b677bacc.png">

In Contrast the power control option is shown for S2 and C4 switches (note: English translation is incomplete for button options):
<img width="793" alt="Bildschirmfoto 2020-11-17 um 18 05 33" src="https://user-images.githubusercontent.com/58853392/99422275-abdb9c80-28ff-11eb-80d9-0b956055f2bc.png">

Can you please add button support for S1 switches as well?
Plus, it would be great if I can change switch configuration between stationary and momentary (currently only possible on the command line: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/360#issuecomment-357500729 ).

**Comment by YKO-de** [comment]
I take care of the incorrect designation. For the purpose of the key assignment I have to see. But it should work as well.

**Comment by jensflorian** [comment]
It is possible to test this in Phoscon beta?

**Comment by jensflorian** [comment]
In Version 2.9.0 the designation is still incorrect.
