### ISSUE TITLE
Sensor couple button and scrollbars not visible on iPhone

### ISSUE THREAD

**Issue by dergreg** [dresden-elektronik/phoscon-app-beta#249]
There are two issues with the "sensors" page on an iPhone 11 Pro and maybe also other devices / smart phones:

1) in portrait mode, the button to add a new sensor is not visible at the bottom

2) in landscape mode, there is no scrollbar indicating that there are other sensors available in the list. This bug might also apply to other pages like "lights" and maybe also in portrait mode (I don't have enough devices to verify).

![IMG_1248](https://user-images.githubusercontent.com/39279568/99566435-2faf8a80-29cd-11eb-8c05-0b69b22a1bc3.PNG)

![IMG_1247](https://user-images.githubusercontent.com/39279568/99566284-fe36bf00-29cc-11eb-9ffd-b9d8e9c85258.PNG)

**Comment by YKO-de** [comment]
The button should not be visible. Also not in the landscape view. I will hide it. And watch the scrolling.

**Comment by dergreg** [comment]
Why shouldn't it be visible? I sometimes use it when I need to re-pair a device.

**Comment by YKO-de** [comment]
Because the whole site is not yet optimised for mobile. Visually.
