### ISSUE TITLE
Wifi password length is limited to 50 characters

### ISSUE THREAD

**Issue by TwoBeers44** [dresden-elektronik/phoscon-app-beta#251]
As the title say...when you try to connect to your router in client mode, the maximum password length is set to 50 characters. 

With WPA2-AES the password can be from 8 to 63 characters.

[https://www.routersecurity.org/wepwpawpa2.php#:~:text=The%20shortest%20password%20allowed%20with,up%20to%2063%20characters%20long.](url)
> The shortest password allowed with WPA2 is 8 characters long. A password of 14 or 15 characters should be long enough to defeat most brute force guessing. [...] WPA2 passwords can be up to 63 characters long.

**Comment by MPA-DE** [comment]
Thank you for the information. We will fix the bug

**Comment by TwoBeers44** [comment]
> Thank you for the information. We will fix the bug

Hi, did you fix the bug? For me, its still not fixed.
