### ISSUE TITLE
Tradfri Wireless Dimmer don't show up in Home Assistant

### ISSUE THREAD

**Issue by pasoad** [dresden-elektronik/phoscon-app-beta#252]
Hello, i know this dimmer switch is end of life but i still have 3 of them and would like to use it ;)

When i do the pairing with deconz i can see it (can't link it with light but i saw it's not supported, so evertihing seems to be good)

But in HA, i just have the battery state...

Can you tell me what i did wrong ?

Thanks :)

**Comment by YKO-de** [comment]
I do not know exactly what you mean. ^^ Do you have a screenshoot or something?

**Comment by pasoad** [comment]
No problem ^^

Here it is : 
![image](https://user-images.githubusercontent.com/46829490/100239543-d0ec9280-2f31-11eb-9d7f-c0eedbeab9ef.png)

in state of something like this : 
![image](https://user-images.githubusercontent.com/46829490/100239718-01343100-2f32-11eb-88fa-178bf6309d9f.png)

And in deconz, it's seems to be ok:
![image](https://user-images.githubusercontent.com/46829490/100239822-245ee080-2f32-11eb-8419-774b18b676b7.png)

Thanks for your reply by the way :)

**Comment by YKO-de** [comment]
Ahh okay. Let me take a look at it.

**Comment by letszb** [comment]
Can you choose left/right additional to battery state via automation? Sorry only german installation available in the screenshot.

![grafik](https://user-images.githubusercontent.com/43775871/100375019-758fd280-300d-11eb-85bb-77319ca6c7ba.png)

**Comment by pasoad** [comment]
Ok, i can see it from here like you:

![image](https://user-images.githubusercontent.com/46829490/100392576-4aba7400-3037-11eb-95f8-ce456fc883ab.png)

But in yaml i have this (because i never use UI to write my automations):

`alias: New Automation
description: ''
trigger:
  - device_id: 1f07202d135041e162019038fe0c0135
    domain: deconz
    platform: device
    type: remote_button_rotated
    subtype: left
condition: []
action:
  - device_id: ''
    domain: ''
    entity_id: ''
mode: single`

Do i need to use this ID or can i change it ?

Is it normal i can't see this device in Integration/Deconz or Developer Tools/States ?

**Comment by pasoad** [comment]
After some tests, i've got a begining of an answer.

the battery sensor's called: `sensor.tradfri_wireless_dimmer_2_battery_level` so i tryed to create an automation with the name `tradfri_wireless_dimmer_2` and it worked...

I have to use it like this:

```
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_wireless_dimmer_2
```

But it's the only Zigbee Deconz integration who work that way. For the others, i can just use the entity_id

**Comment by Kane610** [comment]
Remote controls are not visible in hass as entities, battery levels are since they are not momentary events.
