### ISSUE TITLE
Honeywell/Xiaomi - smoke sensor - temperature value to high

### ISSUE THREAD

**Issue by TungstenE2** [dresden-elektronik/phoscon-app-beta#253]
Hi all,

I just got 4 Honeywell/Xiaomi smoke sensors installed.
All of them show about 7 degree to high temperature.

Is there a way to change offset or to do calibration?

![grafik](https://user-images.githubusercontent.com/39955685/100545590-d6611a00-325c-11eb-8a10-371f1995f48e.png)

thx

**Comment by YKO-de** [comment]
Unfortunately not. We cannot influence the data that the sensor displays.
