### ISSUE TITLE
Sensor object values in iobroker are not updated after some time

### ISSUE THREAD

**Issue by sannc** [dresden-elektronik/phoscon-app-beta#254]
## Describe the bug
After some random period of time the object values in iobroker are no longer updated. This was observed my my with two Philips Hue Motion sensors and by other people with Aqara motion sensors (see https://forum.iobroker.net/topic/26758/deconz-aktualisiert-nicht-stati-von-phoscon-aqara/86).

## Steps to reproduce the behavior
The problem is occurring every time, but it is not predictable when

## Expected behavior
All deconz object states should be updated reliably at any time.

## Screenshots
n/a

## Environment
 - Phoscon 2.05.88 **and** 2.06b
 - deConz ZigBee 1.3.11 
 - ConBee II 26660700 **and** 26670700
 - iobroker 4.1.10 on Raspberry Pi 4 with Node.js v12.20.0 and NPM v6.14.9

## Additional context
A reboot fixes the problem temporarily. A downgrade to **Phoscon 2.05.84** fixes the problem permanently.

**Comment by letszb** [comment]
There are some fixes for device management in the latest versions. Can you please update to deCONZ 2.7.1 stable and firmware 26680700.
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually
