### ISSUE TITLE
wpa_supplicant not working, wpa_supplicant.conf file almost empty...

### ISSUE THREAD

**Issue by creactiv** [dresden-elektronik/phoscon-app-beta#255]
Hi, 
after wondering, why i cannot use the Access Point feature, which would suit me in my living room, because my router is two floors above with poor wifi quality, i worked myself through the house to place a working network socket in my living room and hook up my sky box, my firetv and. of course my Pi 3+ with zigbee module. 

For testing i removed the pi from living room and hooked it up to keyboard, mouse etc. and found out the following: 

wifi: With raspi-config i cannot set the country code, because it cannot communicate with wpa_supplicant. It also uses a different IP adress segment then the rest of the network. (if rest of the network uses 192.168.8.1/24, wifi uses 192.168.49.1/24), After spending quite some time in order to dig through the system, i found this file:  /etc/wpa_supplicant/wpa_supplicant.conf with this content: #generated by deCON2 and that's it. 

I resetted the name of the wifi network and provided a password, and i can connect to the wifi, but i do not have any internet connection if i tell my mobile to use dhcp. if i switch to static IP it shows me this:

IP 192.168.8.121
Gateway 192.168.8.1
DNS1 192.168.8.1
DNS2 8.8.4.4

No internet, no fun. So i changed the dns1 to 8.8.8.8 no fun either. 

So, i am missing the content of the wpa_supplicant.conf, the wpa_supplicant service is running, but raspi-config tells me, that since i did not set a wifi country, wifi is deactivated, but seems to be running, since i can connect to the raspi. Side note: If i am connected to the wifi of my phoscon gateway, i can get into phoscon app, so wifi seems to work. 

Any idea how to fix this?

Thanks and best
c

**Comment by creactiv** [comment]
Anyone please? It would really make sense to get the gateway access point up and running and unfortunately there is no documentation about this feature available. 
Or did i miss something?
Thanks and best

**Comment by manup** [comment]
Which version of deCONZ are you running?
There was a recent fix in v2.8.0, since newer Raspbian versions have changed the way to enable the Wi-Fi interface.

The docs can be found at: https://phoscon.de/en/app/doc#settings-wifi-en

Admittedly, should be more detailed.

**Comment by ChrisHae** [comment]
The wpa_supplicant file is empty when you use the Gateway in Accesspoint mode or when you have disabled WIFI in the phoscon app. So can you connect to a WIFI when you setup client mode in the phoscon app? As mentioned there was a fix in deCONZ v.2.8.0 when WIFI didn't start at all. It was related to a problem that WIFI was disabled on the RPI and you could solve it when you right click at the connection symbol on the RPI Desktop in the top right corner (the two arrows) and then "activate wifi". But it is also fixed with v.2.8.0.

**Comment by creactiv** [comment]
Well,

I have got RaspBee and it says, that there is no new version at all, although it tells me, that i am using 2.0.5 from April 2019. I assume, it won't be able to get into Internet, wgich seems also the problem with access point feature. 

Any idea truly appreciated.

Best

Btw: i downloaded the raspbian image, dumped it with etcher and installed from there. I also have different views of phoscon. When i connect to my LAN via mobile phone, i see everything i installed... When i connect via PC i am mossung quite a lot of devices...

**Comment by ChrisHae** [comment]
2.05.xx is indeed an old version. And when the Gateway is configuread as an AP it has no internet until it is connected with an ethernet cable to the router.
I would recommend following steps to clean up and update your gateway:
- Connect the RPI with an ethernet cable to your router
- (You can connect to your RPI either with a monitor or over network via VNC/ Putty)
- Download and install newest deCONZ version manually https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually
- Go to the phoscon app either by enter the IP address of your RPI into your browser or pressing the Phoscon App button in the deCONZ GUI (on the RPI Desktop)
- enable WIFI client mode in Phoscon App

**Comment by creactiv** [comment]
Well, the Pi is being connected via cable to a network switch, being behind a firewall/router.

Shouldn't this setup work? 

Thanks and best

**Comment by ChrisHae** [comment]
Can't say how much the firewall affects the Phoscon App but when you have internet access then it should work.
So update deCONZ to the newest version to see if it solves your wifi problems.

**Comment by creactiv** [comment]
Ok, i will try. Otterwise i will have to dig into Raspbian networking... :-(

Thanks and best

**Comment by creactiv** [comment]
So, gave it a try by hooking it up to router directly, without firewall, no fun either. It cannot connect to internet and it keeps telling me, that my version is the latest.. 

Very strange, indeed. When i open Phoscon, i have german gui, which is ok for me, but when i click on WLAN gui changes to english and the WIFI entry is missing, so no chance on checking that either. 

the rasbian gui does not accept root user, and pi user's password is not being accepted. So i am stuck with debian deskop, with no chance of logging in and setting back to command line...

i pinged google.com via command line and it could connect and receive the ping back, so networking and internet access is working. 

No raspbian updates available either, it also keeps telling me, that i am using the most current version. 

First of all i need to get the command line back, probably by setting the .conf file accordingly, and then try to do the upgrade manually. Haven't found a button in phoscon to check for updates yet. 

Best

**Comment by ChrisHae** [comment]
Did you installed a phoscon Image from here: https://phoscon.de/en/conbee2/sdcard
You can take one of the beta images it is version 2.07.00. or use stable image it has version 2.05.88. Everything should work there, too. In both cases you should update deconz manually as descripted to version 2.08.00.
When logging into the Raspbian  Desktop and using the phoscon image the username is pi and the pw is raspbeegw.
when using original raspbian image I think pw is raspberry.

**Comment by creactiv** [comment]
So, i got back on command line disabled debian GUI and did, what i read here: 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually by using those wget commands; flashed firmware and updated to deconz beta app. 

Interestingly enough with command line i can connect to the internet from behind the firewall, as well as when i connect directly to the internet router. But still no internetconnection with WLAN Accesspoint feature. 

After updating the phoscon app and flashing firmware i deactivated the Accesspoint featuer and re-activated it again Still no internet.

What do i miss here?

**Comment by creactiv** [comment]
PS: I am running: 

Version: 2.08.00 / 8.12.20202
Firmware: 6390500

**Comment by ChrisHae** [comment]
I'm not sure if internet is forwarded to your mobile device when connected to the RPI Accesspoint.

When you have connected the Raspbee Gateway to your router via cable then you can connect your mobile device via WIFI to your router and use internet and the phoscon app.

If you want to connect the Raspbee Gateway without a cable go to the phoscon app wifi setttings and activate client mode. Connect the gateway via phoscon app to your wifi router and your mobile device also. Then you also have internet and phoscon app.

**Comment by creactiv** [comment]
Well, 

my current local LAN is sort of overcrowded and in some areas of my house i've got not a good wifi connection. Since i am mostly in my living room, and the pi is located there as well, i thought, having a seperate wifi network with different ip adress would do the trick. 

Scenario 1: 

having Pi with Phoscon directly behind the router, running as access point and LAN cable connection to router: 

+ can access Phoscon App via wifi access point
+ can connect to internet from command line and install / upgrade software
- cannot access internet via wifi access point feature. 

having Pi with Phoscon directly behind the firewall, running as access point and LAN cable connection to firewall, and from there via LAN Cable to router

+ can access Phoscon App via wifi access point
+ can connect to internet from command line and install / upgrade software
- cannot access internet via wifi access point feature. 
- 
Neither nor, it is not working at all, and i am confused, Why would i have an access point option, if the only thing i can access is phoscon app? Doesn't make sense to me. 

Or am i barking up the wrong tree?

Best

**Comment by creactiv** [comment]
Btw, tried to create anothe copy of ssh, but this will not survive the reboot. I installed the OS on an external SSD because i had a lot of dead sdhc cards lately. But this is not a problem with my Pi 3 i suppose..

Best

**Comment by creactiv** [comment]
Anybody from dresden-elektronik being able to tell, what the Access Point feature is for and how i can get it working? In my understanding i can hook up a tablet or mobile phone and browse the internet and local network, correct?

As my Pi3 with RaspBee is able to access internet, i assume, the internetconnection is working. Whether behind the router or behind the firewall doesn't make any difference. So why can i only get a connection to phoscon setup page when i connect via access point to my Pi3 and not being able to get into internet?

I find a bunch of complaints about people not wanting the access point feature, but not the other way round. 

So what? 

Thanks in advance and best.

**Comment by ChrisHae** [comment]
The Accesspoint is only intended to access the Phoscon App when no other infrastructure is available e.g. in industry halls. Perhaps some other users or raspberry pi web tutorials can help how to forward internet to devices connected via raspbery pi access point. Perhaps like this one: https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md
Phoscon also uses the files hostapd.conf, dnsmasq.conf and dhcpcd.conf to configure the accesspoint. Just delete the lines #created by deconz in these files, else Phoscon will restore the default configuration. 
I think net.ipv4.ip_forward=1 and sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE like describted in that tutorial would do the trick.
