### ISSUE TITLE
Use deCONZ and Phoscon On Non-Standard Web Ports?

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [dresden-elektronik/phoscon-app-beta#26]
I am running deCONZ and Phoscon on an Ubuntu server with several other web apps.

I am now facing an issue where because other services require port 80/8080/443 (such as my Apache server), I have to choose between either Phoscon/deCONZ or Apache (trying to run them both at the same time causes one to fail.

Please can an method be exposed to be able to map deCONZ/Phoscon to non-standard web ports?

I have tried editing the config.ini file, but as soon as the service (re)starts, it reverts back to original settings..

I have read that there is a command line switch, but it would be nice to have this as a permanent setting, considering that there is a configuration file..

**Comment by holli73** [comment]
hello,

i start this with following parameters and do not use the delivered service files:

`
deCONZ --auto-connect=1 --dbg-error=1 --http-port=8080 --ws-port=20877 --upnp=0
`

best regards
holli

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks Holli,

I did mention the command line switch above. It would be nice to hard-wire it straight into config..

Daniel

**Comment by manup** [comment]
Proper way to change the default port is to use a systemd overwrite in /etc/systemd/system based on copy from /usr/systemd/system/deconz-gui.service.

**Comment by mansdahlstrom1** [comment]
Just tried to switch the service port using `sudo systemctl edit deconz`. After a bit of trouble my service seems to be running fine again. According to `sudo service deconz status`...

Output from `sudo systemctl cat deconz`:
```
# /etc/systemd/system/deconz.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8080 --ws-port=8081 --auto-connect=1 --dbg-error=1
```

Now i can't seem to access the Phoscon app at port 8080. accessing via `http://<ip-address>:8080`. Can someone maybe point me in the right direction?

**Comment by Patricen1** [comment]
@mansdahlstrom1 
you said you had some troubles with deconz service you wanted to change port.
I'm currently having troubles changing the ports.
I edited "sudo systemctl edit deconz" and added
-http-port=8080
-ws-port=8081
reloaded daemons but "sudo systemctl cat deconz" gives me the following output:
```
# /lib/systemd/system/deconz.service
[Unit]
Description=deCONZ: ZigBee gateway -- REST API
Wants=deconz-init.service deconz-update.service

[Service]
User=1000
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=80
Restart=on-failure
StartLimitIntervalSec=0
RestartSec=30
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_KILL CAP_SYS_BOOT CAP_SYS_TIME

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/deconz.service.d/override.conf
-http-port=8080
-ws-port=8081
```
Do you have any clue?

**Comment by mansdahlstrom1** [comment]
In override file you need to specify what to override. Like `ExecStart` in your case. Take a read here to understand more about how systemd services work https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services.

Anyways in your case your override file should look more like this

```
[Service]
ExecStart=
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8080 --ws-port=8081
```

**Comment by Patricen1** [comment]
Thanks a lot

I'm a bit confused as when I try creating override.conf I do have the following message:
`pi@domoticz:/etc/systemd/system/deconz.service.d $ sudo systemctl edit override.conf

No files found for override.conf.service
Run 'systemctl edit --force --full override.conf.service' to create a new unit.`

I then tried `sudo systemctl edit --force --full override.conf.service` but it looks like the file is going to be overwritten in  /etc/systemd/system/ . I didn't dare going further. Should I pursue this way completing the file with  
`[Service]
ExecStart=
ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8080 --ws-port=8081`?

**Comment by mansdahlstrom1** [comment]
use `sudo systemctl edit deconz ` not `sudo systemctl edit override.conf`. You propably don't have a systemd service called `override.conf`. ;)

**Comment by giovanniferretti** [comment]
In my experience, for Raspberry Pi with GUI enabled the override actually needs to be done on the `deconz-gui` service, so the following needs to be invoked:
`sudo systemctl edit deconz-gui`
which needs to be populated as explained above i.e.
```
[Service]
ExecStart=
ExecStart=/usr/bin/deCONZ --http-port=<new port>
```

**Comment by JamesBedwell** [comment]
> In my experience, for Raspberry Pi with GUI enabled the override actually needs to be done on the `deconz-gui` service, so the following needs to be invoked:
> `sudo systemctl edit deconz-gui`
> which needs to be populated as explained above i.e.
> 
> ```
> [Service]
> ExecStart=
> ExecStart=/usr/bin/deCONZ --http-port=<new port>
> ```

@giovanniferretti, thanks, this worked for me. However, now I seem unable to launch the deCONZ gui app. One problem replaced with another. Do you know why this is?
