### ISSUE TITLE
Compatibility list: SilverCrest triple 230V socket outlet is working ("LIDL Smart Home Steckdosenleiste)

### ISSUE THREAD

**Issue by StephanStS** [dresden-elektronik/phoscon-app-beta#261]
The triple socket outlet from SilverCrest, which is actually sold by LIDL Germany (["Smart Home Steckdosenleiste" mit USB-Stecker](https://www.lidl.de/de/silvercrest-steckerleiste-zigbee-smart-home/p355170)) can be integrated as a lamp and can be switched on/off via deconz.

![image](https://user-images.githubusercontent.com/57687516/101267791-25c3b080-375d-11eb-9c14-19f3f237cf22.png)

The outlets can be assigned to groups and controlled via switches.  
Unfortunately, timer controls and alarms are not usable (only for switching off the outlets).

**Comment by Lorccan** [comment]
I'm not having any luck in pairing the UK version of these with Conbee II. I've tried via Phoscon web app and by initiating a search for new lights via the REST API. It seems to me that the pairing light on the outlet stops flashing quite quickly (certainly compared to the single outlet which paired first time). 
Did you have to do anything particular to get it to work for you?

**Comment by StephanStS** [comment]
I used my debian system updated via `apt update` resp. `apt upgrade`.  
I used <http://phoscon.de/pwabeta> for the beta version of the UI.  
I used 26680700 firmware for my Conbee II stick.

When pairing the three outlets appear one after another during one scan in about 30 seconds of scanning. I.e. you should not stop the pairing manually until all three plugs were found.

**Comment by truidix** [comment]
Hey,

how did you pair the socket outlet?
Just start paring in phoscon and press the power button for 5 seconds, until the light is flashing?
I did that, but the outlets where not recognized, even after the led stops flashing. 

thx

**Comment by StephanStS** [comment]
@truidix: The pairing worked good at my setup.  
Do you have the latest phoscon resp. firmware?

![image](https://user-images.githubusercontent.com/57687516/102753071-dee3d680-436a-11eb-8cea-b16619b98306.png)
