### ISSUE TITLE
Phoscon loads if no stick attached

### ISSUE THREAD

**Issue by Mimiix** [dresden-elektronik/phoscon-app-beta#262]
HI,

On my own request, phoscon now shows a page if the conbee/raspbee cant be accessed properly. However, if you have a stick in a setup with a symlink it seems that phoscon still loads. 

The check works for incorrect firmware/not able to access the network(0xE1), but not for _device not there_.

Probably needs a fix here 😅 

Thanks :)

**Comment by CrawlWarner** [comment]
Hi.

Here som screenshots with this issue
![conbee3](https://user-images.githubusercontent.com/62287764/101620694-25edd580-3a15-11eb-8b11-4c03b7eda0d9.PNG)
![conbee5](https://user-images.githubusercontent.com/62287764/101620698-26866c00-3a15-11eb-9cf9-cfa23b1b33eb.PNG)
![conbee4](https://user-images.githubusercontent.com/62287764/101620699-271f0280-3a15-11eb-87f8-63fded054768.PNG)

**Comment by Mimiix** [comment]
REstAPI Results
{
    "UTC": "2020-12-09T11:12:44",
    "apiversion": "1.16.0",
    "backup": {
        "errorcode": 0,
        "status": "idle"
    },
    "bridgeid": "00212EFFREDACTED",
    "datastoreversion": "93",
    "dhcp": true,
    "disablePermitJoinAutoOff": false,
    "factorynew": false,
    "fwversion": "0x00000000",
    "gateway": "192.168.1.1",
    "internetservices": {
        "remoteaccess": "disconnected"
    },
    "ipaddress": "192.168.1.232",
    "linkbutton": false,
    "localtime": "2020-12-09T12:12:44",
    "mac": "dc:a6:32:REDACTED",
    "modelid": "deCONZ",
    "name": "Conbee II",
    "netmask": "255.255.255.0",
    "networkopenduration": 600,
    "panid": 0,
    "portalconnection": "disconnected",
    "portalservices": false,
    "portalstate": {
        "communication": "disconnected",
        "incoming": false,
        "outgoing": false,
        "signedon": false
    },
    "proxyaddress": "none",
    "proxyport": 0,
    "replacesbridgeid": null,
    "rfconnected": false,
    "starterkitid": "",
    "swupdate": {
        "checkforupdate": false,
        "devicetypes": {
            "bridge": false,
            "lights": [],
            "sensors": []
        },
        "notify": false,
        "text": "",
        "updatestate": 0,
        "url": ""
    },
    "swupdate2": {
        "autoinstall": {
            "on": false,
            "updatetime": ""
        },
        "bridge": {
            "lastinstall": "2020-11-13T10:31:42",
            "state": "allreadytoinstall"
        },
        "checkforupdate": false,
        "install": false,
        "lastchange": "",
        "lastinstall": "",
        "state": "allreadytoinstall"
    },
    "swversion": "2.5.88",
    "timeformat": "24h",
    "timezone": "Europe/Berlin",
    "uuid": "500bf6a7-d115-47f1-9b2e-dc00365d4f4f",
    "websocketnotifyall": true,
    "websocketport": 443,

       "zigbeechannel": 0
}
