### ISSUE TITLE
TuYa ZigBee Hygrometer

### ISSUE THREAD

**Issue by kispalsz** [dresden-elektronik/phoscon-app-beta#263]
Previously we had a similar problem with a [Blitzwolf BW-IS4 device,](https://github.com/dresden-elektronik/phoscon-app-beta/issues/172) then that problem was solved quickly. The problem is similar now.
It looks the same from the front as the Blitzwolf, only from another manufacturer.
![Tuya-hygrometer](https://user-images.githubusercontent.com/33829634/101621963-be388a00-3a16-11eb-917f-ad49c6731a7b.jpg)

I have a [hygrometer device,](https://www.aliexpress.com/item/4000830582090.html?spm=a2g0s.9042311.0.0.4b5b4c4dZNCOpi) type:
TuYa ZigBee Infrared Temperature And Humidity Sensor Thermometer Digital Thermometer Hygrometer

I managed to add it with deconz right away, it can be seen in my Domoticz system with the Domoticz-deCONZ plugin
https://github.com/Smanar/Domoticz-deCONZ
![tuya-hygro-domoticz-devices](https://user-images.githubusercontent.com/33829634/101621992-cb557900-3a16-11eb-9cea-24f2ffcfaf38.jpg)

but it doesn't appear in the Phoscon app ( only my 2 Blitzwolf BW-IS4 devicses show, **but I also have 4 Tuya senosors in the system.** (latest version :), I can't add rules to it.
![deconz-phoscon-gw-version](https://user-images.githubusercontent.com/33829634/101622016-d4464a80-3a16-11eb-916a-aa32bce62b4f.jpg)
![Phoscon-sensors](https://user-images.githubusercontent.com/33829634/101622052-df00df80-3a16-11eb-9752-eee544b36626.jpg)

Please include this option in the next beta test version, as you did with the BlitzWolf BW-IS4.

root@domoticz:~# cat /tmp/phoscon.log | grep bc
11:42:50:546 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:43:18:734 neigbor 0x5c0272fffec4bc67 is unknown child
11:43:19:128 new node - ext: 0x5c0272fffec4bc67, nwk: 0xCACC
11:43:21:450 DB sql exec UPDATE devices SET nwk = 51916 WHERE mac = '5c:02:72:ff:fe:c4:bc:67';INSERT INTO devices (mac,nwk,timestamp) SELECT '5c:02:72:ff:fe:c4:bc:67', 51916, strftime('%s','now') WHERE (SELECT changes() = 0);
11:43:31:549 CTRL db store gui node 5c:02:72:ff:fe:c4:bc:67
11:44:09:546 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:45:39:547 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:47:09:547 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:48:39:546 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:50:09:546 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:51:39:547 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:53:09:546 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:54:39:546 sql exec SELECT conf FROM zbconf ORDER BY rowid desc limit 1
11:55:10:482 Node data 0x5c0272fffec4bc67 profileId: 0x0104, clusterId: 0x0402
11:55:10:996 DB UPDATE device_descriptors SET data = x'010401020300040000010002040504011900', timestamp = 1607511310 WHERE device_id = (SELECT id FROM devices WHERE mac = '5c:02:72:ff:fe:c4:bc:67') AND endpoint = 1 AND type = 4
11:55:10:996 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 1, 4, x'010401020300040000010002040504011900', 1607511310 FROM devices WHERE mac = '5c:02:72:ff:fe:c4:bc:67'
11:55:11:011 Node data 0x5c0272fffec4bc67 profileId: 0x0104, clusterId: 0x0405
11:55:11:465 DB UPDATE device_descriptors SET data = x'0240800210520002002c000200', timestamp = 1607511311 WHERE device_id = (SELECT id FROM devices WHERE mac = '5c:02:72:ff:fe:c4:bc:67') AND endpoint = 0 AND type = 2
11:55:11:465 DB INSERT INTO device_descriptors (device_id, endpoint, type, data, timestamp) SELECT id, 0, 2, x'0240800210520002002c000200', 1607511311 FROM devices WHERE mac = '5c:02:72:ff:fe:c4:bc:67'
11:55:11:474 [ND] Ext: 0x5c0272fffec4bc67
11:55:11:494 Node data 0x5c0272fffec4bc67 profileId: 0x0104, clusterId: 0x0001

Thanks.

**Comment by YKO-de** [comment]
Then it probably also has a different modelid. Can you tell me what it is?

**Comment by kispalsz** [comment]
I use this version:
2.07.01 / 2020. 12. 08.
26660700

I see these in the deconz gui:

![4TuyaAND2 Blitzwolf](https://user-images.githubusercontent.com/33829634/102357708-eabc4b00-3fae-11eb-9594-eb30eec337ee.jpg)

![TuyaHG-Nodeinfo](https://user-images.githubusercontent.com/33829634/102357747-f576e000-3fae-11eb-88fb-67017a0cf5bf.jpg)

![Tuya_basic](https://user-images.githubusercontent.com/33829634/102357761-f9a2fd80-3fae-11eb-8629-b0f520de2acf.jpg)
![Tuya_PowerConfiguration](https://user-images.githubusercontent.com/33829634/102357785-ff98de80-3fae-11eb-90c0-efd377b46eee.jpg)

![Tuya_Temperature](https://user-images.githubusercontent.com/33829634/102357871-1b03e980-3faf-11eb-82e7-0f9b1b764ebf.jpg)

![Tuya_RH](https://user-images.githubusercontent.com/33829634/102357885-1f300700-3faf-11eb-932f-c2754b25f622.jpg)

![Tuya_OTAU](https://user-images.githubusercontent.com/33829634/102357909-248d5180-3faf-11eb-99e1-08b5f648d597.jpg)

**Comment by YKO-de** [comment]
You can click on read in the basic cluster. The information I need is not in the screenshot. 
![image](https://user-images.githubusercontent.com/55535297/102359476-20623380-3fb1-11eb-8278-2e6dcfa47700.png)

**Comment by kispalsz** [comment]
Sorry I forgot to wake up the device.

The new pictures:

![Tuya_Basic2](https://user-images.githubusercontent.com/33829634/102360406-43411780-3fb2-11eb-9bb6-d9fac4d32469.jpg)
![Tuya_Power2](https://user-images.githubusercontent.com/33829634/102360437-49cf8f00-3fb2-11eb-89de-d785eca2db7a.jpg)
![Tuya2_Nodeinfo](https://user-images.githubusercontent.com/33829634/102360452-505e0680-3fb2-11eb-8c18-27f5f304aba9.jpg)
![Tuya2_OTAU](https://user-images.githubusercontent.com/33829634/102360469-5522ba80-3fb2-11eb-9a01-8e320d700a09.jpg)
![Tuya2_RH](https://user-images.githubusercontent.com/33829634/102360480-59e76e80-3fb2-11eb-948f-d772141bcf41.jpg)
![Tuya2_temp](https://user-images.githubusercontent.com/33829634/102360498-5f44b900-3fb2-11eb-8d75-f6eb0c285f3e.jpg)

**Comment by YKO-de** [comment]
Ahh okay. That should work with the next update. But you can have a look at phoscon.de/pwabeta to see if you see it there and let me know.

**Comment by kurim** [comment]
I have the same Sensor, it does not show up at phoscon.de/pwabeta

![Screenshot 2021-01-09 092934](https://user-images.githubusercontent.com/1880220/104087398-96c81d80-525f-11eb-9217-fe9a250d6f76.jpg)

![Screenshot 2021-01-09 093930](https://user-images.githubusercontent.com/1880220/104087386-8e6fe280-525f-11eb-89cb-f04c9f9bb214.jpg)

Local Gateway:
Version: 2.09.00 / 23.12.2020
Firmware: 26690700

**Comment by rugarci** [comment]
Same problem here. F12 logs when testing in phoscon.de/pwabeta:

```json

16 | Object { ep: 1, etag: "d2a21869b8c123f20a02f1542af55537", lastseen: "2021-02-13T12:54Z", … }
config | Object { battery: 100, offset: 0, on: true, … }
battery | 100
offset | 0
on | true
reachable | true
ep | 1
etag | "d2a21869b8c123f20a02f1542af55537"
lastseen | "2021-02-13T12:54Z"
manufacturername | "_TZ2000_a476raq2"
modelid | "TS0201"
name | "TS0201 (2)"
state | Object { lastupdated: "2021-02-13T12:54:31.830", temperature: 2160 }
lastupdated | "2021-02-13T12:54:31.830"
temperature | 2160
type | "ZHATemperature"
uniqueid | "5c:02:72:ff:fe:cb:e5:e0-01-0402"

21| Object { ep: 1, etag:"d2a21869b8c123f20a02f1542af55537", lastseen: "2021-02-13T12:54Z", … }
--
config | Object { battery: 100, offset: 0, on: true, … }
battery | 100
offset | 0
on | true
reachable | true
ep | 1
etag | "d2a21869b8c123f20a02f1542af55537"
lastseen | "2021-02-13T12:54Z"
manufacturername | "_TZ2000_a476raq2"
modelid | "TS0201"
name | "TS0201 (2)"
state | Object { humidity: 4810, lastupdated: "2021-02-13T12:54:33.486" }
humidity | 4810
lastupdated | "2021-02-13T12:54:33.486"
type | "ZHAHumidity"
uniqueid | "5c:02:72:ff:fe:cb:e5:e0-01-0405"


```

**Comment by fribse** [comment]
I see the excact same problem here.
I am on 2.09.03 in a HomeAssistant addon.
It did register properly previously, as I now have an old one that shows up properly, and a new one that shows up only in Phoscon and HomeAssistant.

**Comment by cbrightly** [comment]
Is [this open device request issue] for an identical unit (https://github.com/dresden-elektronik/phoscon-app-beta/issues/350) redundant?

**Comment by falkenbt** [comment]
I have the same issue with 2.09.01 running in docker on a raspi. But the sensor doesn't even get a name and I can't change it. Discovery via phoscon was no successful. 
I'm new to this and I'm having issues with reading the Basic Cluster Info on, it's pretty much empty (I clicked read): 
![image](https://user-images.githubusercontent.com/1234748/110705171-4a18a880-81f6-11eb-8b18-d0f8255e534c.png)
But it looks like this for all my devices which otherwise work fine so I'm not sure what the problem is here and it shouldn't be covered in this issue.

**Comment by fribse** [comment]
I have two of these devices bought at the same time.
They were originally added on a previous version of phoscon, and showed up correctly.
I then had to remove one, and readd it after upgrading to 2.09.03 and now it doesn't show up in phoscon, it does show up in deconz and in Home Assistant. But they cannot be renamed:
This one shows up correctly (haven't been removed / readded):
![image](https://user-images.githubusercontent.com/13660621/111899765-c8631f00-8a2e-11eb-9536-e6d5c2109fb8.png)
![image](https://user-images.githubusercontent.com/13660621/111899779-dadd5880-8a2e-11eb-89dd-c3057591b8f9.png)

This one was removed and readded, and shows up like this:
![image](https://user-images.githubusercontent.com/13660621/111899799-f6486380-8a2e-11eb-94ba-499ae1237943.png)
![image](https://user-images.githubusercontent.com/13660621/111899827-24c63e80-8a2f-11eb-8199-4814552d2690.png)

**Comment by falkenbt** [comment]
Any update on this?

**Comment by JamieP83** [comment]
+1 same issue here, just got one off amazon UK and i see the cluster but doesnt show in DeConz

**Comment by fribse** [comment]
After moving to 2.10.04 both the old sensor that still showed up, and the new one that didn't are gone from phoscon.
They still appear in deconz and HA.
This is definetely going the wrong way...

**Comment by SEK-DE** [comment]
Any changes with the newest FW and deCONZ for you?

**Comment by fribse** [comment]
Well, it's still showing in deconz, but not in phoscon.

Phoscon shows version: 2.11.05
Firmware shows: 26670700

**Comment by kurim** [comment]
> Any changes with the newest FW and deCONZ for you?

I can confirm that latest FW and deCONZ does not help.
Even it does show up in deConz but not in pwabeta.

Through API you can change the Name, so it is an Phoscon Issue.

**Comment by fribse** [comment]
@kurim How do you change the name through the API?

**Comment by kurim** [comment]
@fribse,
I used Postman (app) to get an API Key.
Like discriped here: https://dresden-elektronik.github.io/deconz-rest-doc/getting_started/#acquire-an-api-key

then you need to use the API key and use the "PUT /api/[apikey]/sensors/[id]" option with this in raw payload.
```json
{
  "name": "Fancy Name"
}

**Comment by fribse** [comment]
Thanks @kurim I got the API key set up, and I have the RESTClient installed in firefox, it was just how to PUT values I didn't know, it worked like a charm, thankyou!

**Comment by SEK-DE** [comment]
Please try it now in the pwa beta : http://phoscon.de/pwabeta
@YKO-de should have fixed the issue.
Let us know if it works for you!

**Comment by kurim** [comment]
Hi @SEK-DE ,
it shows up but is not clickable.
![image](https://user-images.githubusercontent.com/1880220/121297606-d8cebb80-c8f2-11eb-809a-4e6d053623d1.png)

**Comment by SEK-DE** [comment]
Please try it again now in http://phoscon.de/pwabeta
Feedback is welcome!

**Comment by kurim** [comment]
Looks better but not perfect ![image](https://user-images.githubusercontent.com/1880220/121546851-eaf04d00-ca0b-11eb-8009-a8c89b54b227.jpeg)

Version is missing and icon is wrong

**Comment by fribse** [comment]
List view of sensors looks ok
![image](https://user-images.githubusercontent.com/13660621/122069442-7d6e6300-cdf5-11eb-926e-1ecea993e803.png)
The detail view
![image](https://user-images.githubusercontent.com/13660621/122069533-8eb76f80-cdf5-11eb-8dcb-01849e8bbb2d.png)
Looks ok, though the icon looks odd, and version is not showing.
But it's showing up, which is great.

**Comment by SEK-DE** [comment]
Great! We have to do some fine tuning, it may takes a while. I let this issue open then for further requests about this.

**Comment by AliakseiT** [comment]
Looks like the same device appears with a different manufacturer ID now. Result is the same - it cannot be added in the phoscon app.
![Screenshot 2021-09-23 at 16 29 28](https://user-images.githubusercontent.com/600679/134527344-3914ebdf-b02c-44d8-8260-cd7377712a21.png)

**Comment by AliakseiT** [comment]
The issue is still open, although it is unclear - is it a phoscon app or deconz_rest_api that need extension.
