### ISSUE TITLE
Two Devices in one Device

### ISSUE THREAD

**Issue by gsieben** [dresden-elektronik/phoscon-app-beta#264]
Hello dear Dresden Elektronik Team,

Thank you, for your wonderful software. Today I have successfully integrated a "Iolloi Zigbee Dimmer". (https://www.iolloi.shop/collections/uk/products/iolloi-zigbee-led-dimmer-5-200-w-230v-trailing-edge-rotary-dimmer-for-dimmable-led-and-halogen-lamps-compatible-with-alexa-philips-hue-and-google-home-without-clamping-claws-3-years-guarantee). 

The integration has worked very well. The device is integrated as Vendor: HZC Model: Dimmer-Switch-ZB3.0 under the group of lights.

But since the device is also a switch it should appear under the switches in my opinion. If this would be possible, I would be very happy about a corresponding feature.

**Comment by SEK-DE** [comment]
@gsieben was there any improvement thru the last updates? 
Otherwise it would be nice if you could send us the log from the API-Information in the beta.
