### ISSUE TITLE
Can't pair Xiaomi motion sensor anymore

### ISSUE THREAD

**Issue by MarpleA** [dresden-elektronik/phoscon-app-beta#265]
Hi,

I recently upgraded Conbee 2 stick manually via Windows with the latest firmware
2.05.88 / 10/15/2020
26680700

I don't know if that's the reason or if there is another issue. However I can't add/pair two newly bought Xiaomi motion sensors (RTCGQ11LM). I am already running three of these sensors which work fine.

After starting the discovery within Phoscon app, the process simply times out and no devices are being discovered.
The other ~25 sensors and switches still work fine.

Any idea how I can debug this issue to find the root cause?

**Comment by YKO-de** [comment]
Can you see the sensor in the deCONZ surface?

**Comment by StephanStS** [comment]
Did you pressed the sensors button (pin hole) for an appropriate long time (approx. 5 seconds) until the sensor internal LED flashes?
The Xiaomi devices seems to have two button options: Short press for reconnecting (if already paired) and long press (> 5 seconds) for pairing.

**Comment by MarpleA** [comment]
Hey,

yes, I did pair it the right way but it just didn't work.
I downgraded the firmware of the usb stick via another windows pc. This way deconz software was able to pair again. Then I upgraded to the lastest firmware the same way and pairing was still possible.
So it seems, that something went wrong while upgrading the firmware via deConz.

Best

**Comment by thecem** [comment]
I can confirm the problem with 26680700 conbee II (NUC/Win10/VirtualBox/HA 2020122 and deconz 2.71. (6.6.2) it is not possible to pair the xiaomi devices. 
Tested with:
WSDCGQ11LM Temp/Hum Sensor (Both sw Version 1.03 and 1.05)
MCCGQ11LM  Door Sensor
DJT11LM Vibration Sensor

When I downgrade the FW to 26670700 on ConBee II the pairing is working.

I tried all paring reset on the devices many time.

What is the problem?

**Comment by MarpleA** [comment]
Things got even worse.
2 of my 4 Aquara Wireless Remote Switches (WXKKG03LM & WXKG02LM) stopped working suddenly (same day). So I deleted them in Phoscon and tried to pair again. Phoscon didn't find any devices. In order to check if the problem is phoscon or the switches I ordered a new switch and unfortunately I also couldn't pair it.
That's pretty annoying.

**Comment by thecem** [comment]
Which FW? 26680700?

**Comment by MarpleA** [comment]
yes

**Comment by thecem** [comment]
Downgrade to 26670700 and you will be able to pair again.

**Comment by MarpleA** [comment]
I downgraded and this seems to work. thx

**Comment by thecem** [comment]
So you have made the same experience.
So I think there must be a problem with 26680700 ConBee I and Xiaomi. I hade also the problem that devices loses the connection and are not able to coming back. Same with one router (smart plug osram) and one setup without router.
@manup: only as Information, but did you know about this?

**Comment by romcosha** [comment]
> 
> 
> Downgrade to 26670700 and you will be able to pair again.

Thank you, helped me. I had 26680700 and my devices cannot pair again, after downgrade, no problem.

**Comment by mhin76** [comment]
you guys have been luckier than me :( I had a great Zigbee network with 10 xiaomi temperatur, motion and door sensors, several plugs, lights and switches. suddenly one door sensor disapeared and I did not manage to pair it again (without any upgrade of any software). phoscon just did not show any new devices. but in deconz I saw new one with just short 0x ID. so I resetted my gateway (loosing all devices) and tried to pair again. plugs, lights and motion sensor worked. but I cannot get any door nor temperatur sensor to pair. I downgraded to the above and even earlier firmwares. still nothing. I only see the devices connected in deCONZ (2.10.4 stable version) with the short 0x ID. any idea what else I can try?

**Comment by romcosha** [comment]
Hi, and which firmware of Conbee II do you have ?

**Comment by mhin76** [comment]
I used 26670700 but I also tried 26680700 and 264a0700, no luck. I remember that the issue started when I upgraded to the latest deconz beta version 2.11.1 (I think it is) for buster version on my raspberry. I saw under https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4573 a similar issue but I guess it has nothing to do with the rest plugin but rather with the phoscon app. I can open a new issue here, if that makes sense?

**Comment by SEK-DE** [comment]
Did you ever try to just re-integrate the device? Without deleting it before. 
Otherwise you can visit our beta http://phoscon.de/pwabeta , go there to "Help" -> "API-Information" and read out the sensor. Please copy the log and post it here.
