### ISSUE TITLE
[DEVICE REQUEST] Sonoff motion sensor snzb-03

### ISSUE THREAD

**Issue by SuperSpe** [dresden-elektronik/phoscon-app-beta#266]
I am requesting to add compatibility for this device. I have another sonor umidity/sensors (snzb-03) and works ok, so I think is not a big deal.

These are the info:

![image](https://user-images.githubusercontent.com/2812598/101782602-82c2bc00-3af9-11eb-8cf5-e9d9b78c28d2.png)
![image](https://user-images.githubusercontent.com/2812598/101782659-95d58c00-3af9-11eb-8881-bc0b9ea7c9c1.png)
![image](https://user-images.githubusercontent.com/2812598/101782791-bc93c280-3af9-11eb-8421-143d3fc8c38d.png)

Thanks

**Comment by YKO-de** [comment]
Can you tell me the modelid of the sensor? There is nothing in your screenshot. ^^

**Comment by SwoopX** [comment]
@YKO-de 
![grafik](https://user-images.githubusercontent.com/4005212/102359100-a631af00-3fb0-11eb-9858-51848b02cbf2.png)

**Comment by YKO-de** [comment]
Thank you. I added that today. It should work after the next update. If not, please just write again.

**Comment by riccardospeggiorin-centropaghe** [comment]
sorry I never done that before. where should I have seen this information?

**Comment by YKO-de** [comment]
You can see that in the deCONZ, in the basic cluster. Here is an example of a lamp.
![image](https://user-images.githubusercontent.com/55535297/102362068-3cb39f80-3fb4-11eb-9706-1967a10494d3.png)

**Comment by SuperSpe** [comment]
like the screenshot I posted, I have an empty string on "model identifier"
