### ISSUE TITLE
One IKEA Range Extender shown as an extender, the other one shown as a light?

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/phoscon-app-beta#268]
## Describe the bug

I have two range extenders, one for each of my blinds currently on deconz.
One shows up in phoscon as a range extender, the other one shows up as a light.
![image](https://user-images.githubusercontent.com/13660621/101888792-e81cb880-3b9e-11eb-8bea-3d3c992bf55b.png)
![image](https://user-images.githubusercontent.com/13660621/101888954-1e5a3800-3b9f-11eb-9a64-dd7f5f67dc93.png)

## Steps to reproduce the behavior

  1. Remove the extender from deconz
  2. Readd it to deconz

But the weird part is, that one of the extenders will always show as an extender, and the other one always as a light.
I've gone to the deconz graphical view, and did a lot of 'read' on the different clusters, but that didn't change anything.

## Expected behavior

Extenders should be registered as extenders.
## Environment

 - Host system: Intel NUC with PVE
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.7.1
 - Device: ConBee II
 - Do you use an USB extension cable: yes USB3
 - Is there any other USB or serial devices connected to the host system? Aeotec Z-stick Gen 5 I

## Additional context

Extender registered as a light:
![image](https://user-images.githubusercontent.com/13660621/101889577-dab3fe00-3b9f-11eb-887e-72415bfd298d.png)
Excender registered as an extender:
![image](https://user-images.githubusercontent.com/13660621/101889682-fa4b2680-3b9f-11eb-9942-9507a4cc3695.png)

**Comment by YKO-de** [comment]
I have corrected it. It should work with the next app update. Or test it at phoscon.de/pwabeta.

**Comment by fribse** [comment]
That is great news @YKO-de I have it installed as a addon in Home Assistant, so it's not that easy to apply a beta release, I'll look forward to the next release.

**Comment by Mimiix** [comment]
@fribse I have a suprise for ya:

http://phoscon.de/pwabeta/login.html#host/<ip-adress>:<port>


For you that would be 40850 as port (on the addon).

**Comment by fribse** [comment]
Hi @Mimiix 
Eh? Please explain 😁 
Am I to put in my local ip and port, or the public ip and port? Or just add 40850 after the colon, or something completely different?
I can see it shows me a login for phoscon, and it's called fribertzigbee (which is what I named it here locally) 😄 
But it shows the IP as 172.x.x.x which is not what I have on the lan, but I think it's the internal docker network, so I'm a bit confused to say the least 😉
I tried entering my pw for the gateway, but that failed 😢

**Comment by fribse** [comment]
Ahaaaaaaaa 😁 
I entered my ip and port after the host/ and then it logs in, wow, that is cool, so the phoscon is running all in the browser?
But with the beta, it shows the signal repeater correctly (and even changes signal repeater to Signal Repeater, which it much prettier)! Wowsers.

Thankyou @Mimiix and @YKO-de , I think it's safe to close the issue.
