### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by Seaha4487** [dresden-elektronik/phoscon-app-beta#27]
How could i connect my Rpi3+ over Wifi instead of the ethernet cable.
I am using a Raspbee module

**Comment by maddin152** [comment]
Same problem here. Can't connect to my Wifi. "No wireless interfaces found" :-(
Any solution?

**Comment by maddin152** [comment]
Found it! In Phoscon App I changed Wifi setting from "Access Point" to "Client mode".

**Comment by dredzed** [comment]
I'm trying to change my Phoscon app to client mode on my raspberry pi with Raspbee, but the option is greyed out. Any ideas?

**Comment by czebulski** [comment]
Wifi Client still not working?!?!

**Comment by caplam** [comment]
I spent a moment looking to enable wifi connection on my raspbee gw. I hadn't seen there was an option in phoscon app. Unfortunately it seems it's still unavailable. It would be a good option especially for a wireless gateway.
