### ISSUE TITLE
AQARA WXKG06LM cant select in groups

### ISSUE THREAD

**Issue by truidix** [dresden-elektronik/phoscon-app-beta#272]
Hey,

I have a AQARA WXKG06LM wall switch. 
I can add it to phoscon, but unfortunately, I cannot select that switch in a group. It is just not showing up. Could you please add support for that switch at groups?
thx

**Comment by YKO-de** [comment]
Okay. I have added it. You can test it at phoscon.de/pwabeta. Otherwise it should work for the next release.

**Comment by truidix** [comment]
Hey,

thanks, for the quick response

I just tried the beta but I still cannot select the wall switch in groups.

**Comment by YKO-de** [comment]
Okay. Again, please. Sorry. ^^

**Comment by truidix** [comment]
Still not there.. :-(

**Comment by YKO-de** [comment]
Okay. Then I need the modelid. Please.

**Comment by YKO-de** [comment]
Of course, it could also be that your browser still has a cache. And it does not get the change. Maybe you could empty it and try again.

**Comment by truidix** [comment]
Okay, I tried a new private browser window.. -> Not it is in. 

thx!
