### ISSUE TITLE
How to use virtual daylight sensor for automation ?

### ISSUE THREAD

**Issue by mspbonn** [dresden-elektronik/phoscon-app-beta#273]
`Der virtuelle Tageslichtsensor wird vom Gateway bereitgestellt. Mit Hilfe der Position und aktueller Zeit am Standort berechnet dieser Sonnenaufgang, Sonnenuntergang sowie Dämmerungsphasen.`

https://phoscon.de/de/app/doc#settings-sensors-overview-de

How to use this sensor to switch lights on depending on the time of sunset ?

**Comment by YKO-de** [comment]
You can do this under sensor control
https://phoscon.de/de/app/doc#group-edit-sensors-de

**Comment by mspbonn** [comment]
This is not, what I want to do. The virtual daylight sensor should switch the lights directly dependent on sunset/sunrise without additional motion sensors.

**Comment by mspbonn** [comment]
May it's possible to insert another "dummy motion sensor" into the database

```
root@phoscon:~# sqlite3 /home/pi/.local/share/dresden-elektronik/deCONZ/zll.db "select * from sensors where manufacturername = 'Phoscon' order by sid"
6|CLIP-Sensor PUSHDIM-TOOGLE|CLIPGenericFlag|PHOSCON_FSM_FLAG|Phoscon|00:00:00:00:01:72:76:fb-f2-pushdim-toogle-2-Wed Dec 16 2020 15:13:46 GMT+0100 (Mitteleuropäische Normalzeit)|1.0|{"flag":true,"lastupdated":"2020-12-17T19:30:16.086"}|{"on":true,"reachable":true}||normal|2
7|VPIR Daylight|CLIPPresence|PHOSCON_VPIR|Phoscon|vpir-1608219385824|1.0|{"lastupdated":"2020-12-17T15:37:38.461","presence":false}|{"duration":60,"on":true,"reachable":true}||deleted|2
8|FSM_STATE Daylight|CLIPGenericStatus|PHOSCON_FSM_STATE|Phoscon|fsm-state-1608219385824|1.0|{"lastupdated":"2020-12-17T15:37:38.449","status":0}|{"on":true,"reachable":true}||deleted|2
9|CLIP-Sensor PUSHDIM-TOOGLE|CLIPGenericFlag|PHOSCON_FSM_FLAG|Phoscon|00:00:00:00:01:72:76:fb-f2-pushdim-toogle-2-Sun Dec 13 2020 20:08:09 GMT+0100 (Mitteleuropäische Normalzeit)|1.0|{"flag":true,"lastupdated":null}|{"on":true,"reachable":true}||normal|2
```

with the state = triggered ?

**Comment by mspbonn** [comment]
I've solved the problem using a bash script:

```
#!/bin/bash
.
.
# Getting sunset from virtual daylight sensor
SUNSET=$(sqlite3 /home/pi/.local/share/dresden-elektronik/deCONZ/zll.db "select * from sensors where name ='Daylight'" | sed 's/.*sunset.:["0-9\-]*T\([^"]*\).*/\1/g')
.
.
  # REST Command
  LIGHTON=(/usr/bin/curl -S -s -X PUT --header \"Content-Type: application/json\" --data \'{\"on\":true, \"bri\":175, \"transitiontime\":100}\' http://localhost/api/$APIKEY/lights/$LIGHTNO/state)
  LIGHTOFF=(/usr/bin/curl -S -s -X PUT --header \"Content-Type: application/json\" --data \'{\"on\":false}\' http://localhost/api/$APIKEY/lights/$LIGHTNO/state)
.
.
  # Using 'at' command to queue on/off times
.
.
```

You just need to generate an api-key and inspect the database for the particular light number.

**Comment by 7wells** [comment]
@YKO-de
Can you please check if we can use the **virtual** daylight sensor to e.g. automatically switch on a light from dusk till dawn?

@mspbonn
Can you please provide some additional information for the normal user how your workaround functions?

Thank you both!

**Comment by mspbonn** [comment]
```
#!/bin/bash

# Phoscon API-Key
APIKEY=YOURAPIKEY
# Lights 
LIGHTS=( 2 6 )
TZ=$(date +%Z)
LOG=/var/log/$(basename $0).log 

# Getting sunset from virtual daylight sensor
SUNSET=$(sqlite3 /home/pi/.local/share/dresden-elektronik/deCONZ/zll.db "select state from sensors where name ='Daylight'" | sed 's/.*sunset.:["0-9\-]*T\([^"]*\).*/\1/g')
UTCDIFF=$(echo "($(date +%H) - $(date --utc +%H))" | bc)
SUNSET=$(date +"%H:%M" --date="$SUNSET +$UTCDIFF hour")
.
.
# DO SOME CALCULATIONS
.
.
for L in "${LIGHTS[@]}"; do 
 .
 .
 # DO SOME CALCULATIONS
 ON=...
 OFF=...
 .
 .
   # REST Command
  LIGHTON=(/usr/bin/curl -S -s -X PUT --header \"Content-Type: application/json\" --data \'{\"on\":true, \"bri\":175, \"transitiontime\":100}\' http://localhost/api/$APIKEY/lights/$L/state)
  LIGHTOFF=(/usr/bin/curl -S -s -X PUT --header \"Content-Type: application/json\" --data \'{\"on\":false}\' http://localhost/api/$APIKEY/lights/$L/state)

  # Switch lights on and off
  echo -e "echo -n \$(/usr/bin/date): >> $LOG; ${LIGHTON[@]} >> $LOG 2>&1;  echo >> $LOG" | at -M -t $ON
  echo -e "echo -n \$(/usr/bin/date): >> $LOG; ${LIGHTOFF[@]} >> $LOG 2>&1; echo >> $LOG" | at -M -t $OFF
 .
 .
done

```

**Comment by 7wells** [comment]
@mspbonn
Thank you, but I still do not get the full picture where to put that code and how to invoke it etc.

@YKO-de
Do you understand it and see a way to implement it in phoscon, so the virtual daylight sensor can be used to e.g. automatically switch on a light from dusk till dawn?

**Comment by mspbonn** [comment]
You need to generate an APIKEY.

The scripts is running once a day using cron and switches on and off several lights using the atq.

**Comment by 7wells** [comment]
You place the script on your Raspberry Pi or other device that runs deconz/phoscon?
What does "atq" stand for?
Doesn't the API key change frequently? (I remember vaguely about such a problem)
Do you know if this aorkaround could somehow be integrated in deconz/phoscon?

Sorry for my noob questions. 😊

**Comment by mspbonn** [comment]
Everything runs on the Raspberry Pi with the deconz/phoscon device.

Getting APIKEY

```
$ curl --header "Content-Type: application/json" --data '{"devicetype":"cli"}' http://localhost/api
[{"success":{"username":"<YOURAPIKEY>"}}]
```
atq: https://linux.die.net/man/1/atq

**Comment by 7wells** [comment]
Ah, thank you. I had not understood that atq was a Linux command. 😊

**Comment by 7wells** [comment]
@YKO-de
Still it would be great of you could consider making the virtual daylight sensor usable for scenes, e.g. switching lights on in the evening (sunset) and off in the morning (senrise), maybe with allowing the user to add or subtract a to be specified amount of minutes. Thank you so much! 👍

**Comment by SEK-DE** [comment]
It´s planed, but it will take a while. Please be patient.

**Comment by 7wells** [comment]
This has been closed now. Has three topic been dropped or is somebody still investigating this?

**Comment by SEK-DE** [comment]
@7wells like i said: "It´s planed, but it will take a while. Please be patient."
As we are a small team, we can´t do magic here.

**Comment by 7wells** [comment]
Sorry, I didn't mean bothering you. It's because I'm not too familiar with how things work at GitHub and when something is closed. Anyway, U thank all you guys very much for the great developments and support. It really makes a difference. 😊👍

**Comment by SEK-DE** [comment]
All good! Some people think that we are a big company like Philips with thousends of employees, but actualy we are a small team. Have a nice weekend :)

**Comment by 7wells** [comment]
Thanks a lot, you too! :)

**Comment by mat-l** [comment]
I am interested for a trigger based on the virtual sun light sensor as well 🙋🏻‍♂️
