### ISSUE TITLE
Xiaomi Mijia Smart Door&Window Sensor not detected in Phoscon

### ISSUE THREAD

**Issue by DoubyCz** [dresden-elektronik/phoscon-app-beta#274]
**Describe the bug**
Xiaomi Mijia Smart Door&Window Sensor not detected in Phoscon app

**Steps to reproduce the behavior**
Open deCONZ WEB UI in Home Assistant, 
Click Phoscan button
Then select sensors from hamburger menu
Clicked Add new sensor button -> other -> ...
Reset door sensor (3 seconds pin hole)
Wait 3min.
Reset sensor (several times) to start over with pairing
--> For me this 100% reproducable (tried pairing approx. 20 times)

Expected behavior
Device should be discovered in Phoscon app

Screenshots
Device listed in deCONZ:
![image](https://user-images.githubusercontent.com/41196960/102552186-0a439880-40c1-11eb-9791-a093eca9dece.png)

Environment
Home Assistant Add-on: deCONZ, version: 6.6.1

Phoscon app:
Phoscon Gateway version: 2.07.01 / 12/8/2020
Phoscon Gateway firmware: 26660700
deCONZ:
![image](https://user-images.githubusercontent.com/41196960/102552371-660e2180-40c1-11eb-8d90-0e4e6b826891.png)

..

Host system: Raspi 4
Running method: Hass OS
Device: ConBee II
Do you use an USB extension cable: no
Is there any other USB or serial devices connected to the host system? ...NO

LOGS:
```
"https://douby.duckdns.org:8123/api/hassio_ingress/EbbjiN_hx2oyoxgzs4eMhM34Alsgjghziuq9rlukwX8/pwa/devices-sensors.html?_v=ef2490db4af3aa72f263cc508edfedc869c4df5b,11,4,23&gwid=00212EFFFF05FCA5" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
firm request id: 42 -> confirmed, timeout 23589376
23:44:08:824 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 117, rssi: 32
23:44:08:825 APS-DATA.indication request id: 42 -> finished
23:44:08:826 APS-DATA.request id: 42 erase from queue
23:44:10:037 New websocket 127.0.0.1:44580 (state: 3) 
23:44:12:166 APS-DATA.request id: 57, addrmode: 0x03, addr: 0x00212effff05fca5, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
23:44:12:181 APS-DATA.confirm id: 57, status: 0x00 SUCCESS
23:44:12:181 APS-DATA.confirm request id: 57 -> confirmed, timeout 23619672
23:44:12:185 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 117, rssi: 32
23:44:12:186 APS-DATA.indication request id: 57 -> finished
23:44:12:186 APS-DATA.request id: 57 erase from queue
23:44:15:526 APS-DATA.request id: 73, addrmode: 0x03, addr: 0x00212effff05fca5, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
23:44:15:542 APS-DATA.confirm id: 73, status: 0x00 SUCCESS
23:44:15:543 APS-DATA.confirm request id: 73 -> confirmed, timeout 24446880
23:44:15:546 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 117, rssi: 32
23:44:15:547 APS-DATA.indication request id: 73 -> finished
23:44:15:547 APS-DATA.request id: 73 erase from queue
23:44:16:002 APS-DATA.request id: 76, addrmode: 0x02, addr: 0xfffc, profile: 0x0000, cluster: 0x0036, ep: 0x00 -> 0x00 queue: 0 len: 3 tx.options 0x00
23:44:16:003 send permit join, duration: 59
23:44:16:004 APS-DATA.request id: 77, addrmode: 0x02, addr: 0xfffc, profile: 0xA1E0, cluster: 0x0021, ep: 0xF2 -> 0xF2 queue: 1 len: 6 tx.options 0x00
23:44:16:004 send GP proxy commissioning mode
23:44:16:676 APS-DATA.confirm id: 76, status: 0x00 SUCCESS
23:44:16:680 APS-DATA.confirm id: 77, status: 0x00 SUCCESS
23:44:16:726 aps request id: 76 finished, erase from queue
23:44:16:806 aps request id: 77 finished, erase from queue
23:44:18:886 APS-DATA.request id: 90, addrmode: 0x03, addr: 0x00212effff05fca5, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
23:44:18:901 APS-DATA.confirm id: 90, status: 0x00 SUCCESS
23:44:18:902 APS-DATA.confirm request id: 90 -> confirmed, timeout 24431584
23:44:18:905 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 117, rssi: 32
23:44:18:906 APS-DATA.indication request id: 90 -> finished
23:44:18:907 APS-DATA.request id: 90 erase from queue
23:44:22:246 APS-DATA.request id: 105, addrmode: 0x03, addr: 0x00212effff05fca5, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
23:44:22:261 APS-DATA.confirm id: 105, status: 0x00 SUCCESS
23:44:22:262 APS-DATA.confirm request id: 105 -> confirmed, timeout 23596248
23:44:22:265 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 117, rssi: 32
23:44:22:266 APS-DATA.indication request id: 105 -> finished
23:44:22:266 APS-DATA.request id: 105 erase from queue
23:44:25:408 APS-DATA.indication srcAddr: 0x62c3, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x0013, lqi: 183, rssi: -71
23:44:25:409 unknown node 0x00158D0003F80E92 (0x62C3), lqi: 183
23:44:25:410 0x0484 nwk changed to 0x62C3
23:44:25:411 device announce 0x00158D0003F80E92 (0x62C3) mac capabilities 0x80
23:44:25:411 set fast probe address to 0x00158D0003F80E92 (0x62C3)
23:44:25:412 FP indication 0x0000 / 0x0013 (0x00158D0003F80E92 / 0x62C3)
23:44:25:412                       ...     (0x00158D0003F80E92 / 0x62C3)
23:44:25:413 device announce 0x00158D0003F80E92 (0x62C3) mac capabilities 0x80
23:44:25:456 APS-DATA.indication srcAddr: 0x62c3, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0000, lqi: 183, rssi: -71
23:44:25:458 FP indication 0x0104 / 0x0000 (0x00158D0003F80E92 / 0x62C3)
23:44:25:458                       ...     (0x00158D0003F80E92 / 0x62C3)
23:44:25:459 ZCL attribute report 0x00158D0003F80E92 172.30.32.2 - - [17/Dec/2020:23:44:25 +0100] "GET /api/543A74931B/config?_=1608245048969 HTTP/1.1" 200 2098 "https://douby.duckdns.org:8123/api/hassio_ingress/EbbjiN_hx2oyoxgzs4eMhM34Alsgjghziuq9rlukwX8/pwa/devices-sensors.html?_v=ef2490db4af3aa72f263cc508edfedc869c4df5b,11,4,23&gwid=00212EFFFF05FCA5" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```

![image](https://user-images.githubusercontent.com/41196960/102552981-678c1980-40c2-11eb-8284-cd18dfbe1f3c.png)

**Comment by YKO-de** [comment]
You have stated that you do not use an extension cable. The connection problems could be related to this. Do you have the possibility to attach an extension cable?

**Comment by DoubyCz** [comment]
I have now used a 2m USB extension cable, but unfortunately it behaves exactly the same. I tried to pair 3 different Xiaomi door sensors without success.

BTW, these three sensors used to work without problems with ConBee II few weeks ago, this problem occurred when I completely reinstalled HassOS on my RPI4 and tried to reconnect them (probably this changed the software versions from the previous functional state)

**Comment by DoubyCz** [comment]
BTW there are **many 404 errors** in Phoscon :-/
![image](https://user-images.githubusercontent.com/41196960/102689832-9e1c7e00-4201-11eb-9f94-bafbd20c0671.png)

**Comment by StephanStS** [comment]
At my setup the door/window sensor works very well:
![grafik](https://user-images.githubusercontent.com/57687516/103452433-d4f99600-4ccf-11eb-8f80-ef0282c90a13.png)

The pairing with other devices from xiaomi often works like this:
- If the sensor was already coupled with phoscon, pressing the sensor button (e.g. pin hole) for only less than one second reconnects it. Then you don't have to start a sensor search in the phoscon web app. This is similar to a battery exchange.
- If the sensor was already coupled with phoscon or any other gateway, pressing the sensor button for more than approx. 5 seconds clears the coupling. Then you have to start a sensor search in the phoscon web app to re-couple the sensor.

Possibly you pressed the pin hole button too short? I press the button as long as an LED inside the sensor begins to blink. Most Xiaomi sensors have them.
I did not test the whole behaviour with my door/window sensor in detail for you. Try to figure it out how it works for you.

Generally, the coupling of Xiaomi devices to Phoscon is a quite stable procedure (compared to other devices I have).

**Comment by dzukero** [comment]
I have the same issue - a Xiaomi Door/Window sensor is being added to deCONZ but not to Phoscon (and not to Home Assistant).

This is the exact type of sensor: [https://www.gearbest.com/smart-light-bulb/pp_257677.html](https://www.gearbest.com/smart-light-bulb/pp_257677.html)

This is the sensor in deCONZ:
![image](https://user-images.githubusercontent.com/47693760/106385460-19fd0f00-63d9-11eb-8e5a-c813ce0be6e1.png)


This is the output in deCONZ debug view when I press the sensor button for <1 sec.:
![image](https://user-images.githubusercontent.com/47693760/106385565-9ee82880-63d9-11eb-979d-20080e59e0d1.png)

This is the output in deCONZ debug view when I start sensor search in Phoscon and press the sensor button for about 2-3 sec. (until the led flashes 3 times, which puts it into pairing mode):
![image](https://user-images.githubusercontent.com/47693760/106385811-c390d000-63da-11eb-8801-62a2492e9016.png)

I suspect the issue might have something to do with the last line above.

ConBee details:
![image](https://user-images.githubusercontent.com/47693760/106386073-e4a5f080-63db-11eb-8e88-1f3f8a9b51c1.png)

DeCONZ Add-on version:
![image](https://user-images.githubusercontent.com/47693760/106386104-0ef7ae00-63dc-11eb-81a1-b8946b7f8572.png)

Home Assistant version:
![image](https://user-images.githubusercontent.com/47693760/106386125-2df64000-63dc-11eb-865a-ec43e6fc978c.png)

I have tried adding this sensor in many different ways and dozens of times to no avail.  In the meantime I have successfully added without any issues 5 Xiaomi temp/humidity sensors, 3 Xiaomi motion sensors, 2 Xiaomi Aqara motion sensors II (with light sensor), 6 Xiaomi smart wireless switches, 3 Xiaomi power plugs, and 1 Xiaomi powered wall switch.  So I really don't think there is something wrong with the setup or how I am doing the pairing.

Any help is appreciated.  Happy to provide any additional info required.

**Comment by StephanStS** [comment]
The sensor I referenced above is the aqara sensor: https://www.gearbest.com/access-control/pp_626703.html?wid=1433363. 
This sensor worked together with my (Node-RED based) home automation routed via phoscon. 

I do not have the mijia sensor, so unfortunately I cannot test it.

**Comment by dzukero** [comment]
I finally made it work by "opening"/"closing" the sensor a few times right after releasing the inclusion button...
