### ISSUE TITLE
[DEVICE REQUEST] Trust ZYCT-202 Support

### ISSUE THREAD

**Issue by akinomeroglu** [dresden-elektronik/phoscon-app-beta#276]
Hi, 

This remote control supported in deconz application and it shows as a sensor in rest API. Unfortunately this device does not represented in phoscon application and hence it is very hard to set it up from a standard user perspective. 

This device have simple on and off button and brightness settings and on top of that it support five channel / group for controlling different devices.

I can't find any template for new device request but I will be very happy to supply any information if needed.

Thanks,

**Comment by YKO-de** [comment]
I'll take a look at it. Thanks for the tip.

**Comment by SEK-DE** [comment]
@akinomeroglu how is it going with the asked device?
If you still have issues with that, please visit our beta: http://phoscon.de/pwabeta
Go to "Help" and "API Information", select the device over the filters and send us the log here.

**Comment by akinomeroglu** [comment]
@SEK-DE unfortunately I am not using phoscon anymore but I will try to build a phoscon env with same device and send you log in a couple of days.
