### ISSUE TITLE
Blitzwolf BW-SHP13 is registered and works like a plug, but is shown as a bulb and no measurement sensors

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/phoscon-app-beta#278]
I have one BW-SHP13 bought as an experiment (https://www.banggood.com/BlitzWolf-BW-SHP13-Zigbee-3_0-Smart-WIFI-Socket-16A-EU-Plug-Electricity-Metering-APP-Remote-Controller-Timer-Work-with-Amazon-Alexa-Google-Home-p-1679992.html?cur_warehouse=CN&rmmds=search)
It works perfectly with power on/off, but it shows up like this:
![image](https://user-images.githubusercontent.com/13660621/102685726-f5f7bc80-41e2-11eb-8151-4e5bf8e18072.png)
So the name is not BlitzWolf, and the power consumption sensors are not showing up.
Looking in deconz, 
![image](https://user-images.githubusercontent.com/13660621/102685846-a82f8400-41e3-11eb-831c-da9a0f8d8dcf.png)
The 0000 basic cluster:
![image](https://user-images.githubusercontent.com/13660621/102685761-2c353c00-41e3-11eb-9a6e-a73d59e8152a.png)
The 0006 on/off cluster
![image](https://user-images.githubusercontent.com/13660621/102685790-5ab31700-41e3-11eb-9d16-8b271b991372.png)
The 0702 Simple Metering cluster:
![image](https://user-images.githubusercontent.com/13660621/102685805-75858b80-41e3-11eb-98e4-fd50a9c61809.png)
The 0B04 Electrical Measurement cluster:
![image](https://user-images.githubusercontent.com/13660621/102685829-8df5a600-41e3-11eb-9596-8f572851c95f.png)

**Comment by YKO-de** [comment]
Currently we have the problem that modelids are duplicated. This could also be the reason for your issue. I will have another look at it.

**Comment by MNieddu91** [comment]
+1 I have the exact same probleme here.

**Comment by SEK-DE** [comment]
@fribse @MNieddu91 solved for you with the latest updates or still some issues there?

**Comment by kurim** [comment]
Phosccon still show it as a bulb.

FW: 266E0700
phosconbeta =>
In overview it shows a plug:
![image](https://user-images.githubusercontent.com/1880220/120538223-8b2feb80-c3e6-11eb-9135-e312aff25143.png)

If you click on it, it is a bulb
![image](https://user-images.githubusercontent.com/1880220/120538239-908d3600-c3e6-11eb-9ca4-54f1b7c83aa4.png)

**Comment by SEK-DE** [comment]
We will try to get such a device to solve the issue. Please be patient.

**Comment by kurim** [comment]
In this type i would suggest to split the Adapter plug from the lights.
Other thing is, but this might be a deConz Issue they are reported as Light not as Plug, this will end in wrong reporting to homebridge...

Left: original Philips Adapter plug
Right: TZ3000 through deConz + homebridge
![IMG_2781](https://user-images.githubusercontent.com/1880220/120846291-30c39600-c572-11eb-9b79-917a406d2682.jpg)

**Comment by SEK-DE** [comment]
We have fixed and tested it. Now the blitzwolf should shown up correctly in every menue.

**Comment by kurim** [comment]
@SEK-DE
looks good
![image](https://user-images.githubusercontent.com/1880220/121584230-8c3dca00-ca31-11eb-9ec6-306b00dff341.png)

**Comment by SEK-DE** [comment]
@kurim so for now its only in the beta like i said. I guess it will be in one of the next two releases. have a great weekend!

**Comment by fribse** [comment]
Looks good here as well:
![image](https://user-images.githubusercontent.com/13660621/122298626-497e6500-cefd-11eb-8d0e-47510c857e7e.png)

**Comment by fribse** [comment]
Oh, it doesn't show the powermeasurement either?
![image](https://user-images.githubusercontent.com/13660621/122299117-dcb79a80-cefd-11eb-8e8f-48d90428194f.png)
![image](https://user-images.githubusercontent.com/13660621/122299144-e50fd580-cefd-11eb-86df-26881b332c6e.png)

**Comment by fribse** [comment]
Still the same

**Comment by SEK-DE** [comment]
investigating
