### ISSUE TITLE
After adding some xiaomi sensor there are undeletable sensors

### ISSUE THREAD

**Issue by bytegetter** [dresden-elektronik/phoscon-app-beta#28]
Hi,

I´m trying to add some Xiami-Sensors (20 Temperature Sensors, 10 magnet sensors.

After adding some sensors with phoscon the app will not add any sensors any more. Mostly it helps if I stop deconz and restart it.

Sometimes it does not help and there will be undeletable sensors in deconz. Phoscon did not see the sensor, but in deconz I see these sensors. It´s impossible to remove these sensors. After restarting deconz the sensor will appear again.

The first to entrys are some of these sensors:
<img width="554" alt="grafik" src="https://user-images.githubusercontent.com/5726208/45255892-aaf96880-b38e-11e8-8629-31b665e72412.png">

After this issue appears it´s impossible to add any new magnet sensors in phoscon (phoscon did not recognize the added sensor and some fields in deconz will be empty). Adding of temperature-sensor will work after restarting deconz.

I´m using the last deconz beta.

Any idea to delete the undeletable sensors? It seems to bee happen on adding motion and magnet-sensor, but not on the round temperature sensors.

Best regards,
Bytegetter

**Comment by erikced** [comment]
Interesting I was just about to open what appears to be a similar issue. I have three Xiaomi Aqara Door/Window sensors of which two are not visible in pwa but I can see what appears to open/close events in the logs:
```
ZCL attribute report 0x00158D00xxxxxxxx for cluster 0x0006, ep 0x01
        payload: 00001001
...
ZCL attribute report 0x00158D00xxxxxxxx for cluster 0x0006, ep 0x01
        payload: 00001000
```
`
