### ISSUE TITLE
Changing a name in Phoscon doesn't propagate into Home Assistant

### ISSUE THREAD

**Issue by oywino** [dresden-elektronik/phoscon-app-beta#280]
Changing the name of a device/entity or a group in Phoscon is easy and convenient.
But the new/changed name doesn't seem to propagate into Home Assistant. 

Also, Phoscon groups are listed as devices in Home Assistant. Why is that ?

**Comment by thecem** [comment]
Try to refresh the device:

![C7F3163B-18E2-4CDD-9BA5-E858E09D9A2A](https://user-images.githubusercontent.com/46648579/103166856-7ee7a700-4826-11eb-8c0d-2fca27955553.jpeg)

**Comment by oywino** [comment]
That's interesting. Thank you very much. 
It seems however, that there is a bit of confusion between deCONZ and Home Assistant as far as naming conventions are concerned. This service is named `deconz.device_refresh` but the name should perhaps have been `deconz.entity_refresh` ?
Phoscon Groups are listed under `Devices` in Home Assistant, but are also listed as `Entities`, while all other Home Assistant groups are listed only under `Entities` with an ID beginning with the word `group`  This is very confusing.
Perhaps it's possible to define groups in deCONZ also and not just in Phoscon ? (And if so - are they listed differently?)

**Comment by YKO-de** [comment]
@oywino I think this request is more for the rest-plugin. Not for the app. Therefore, please open another issue at https://github.com/dresden-elektronik/deconz-rest-plugin.
