### ISSUE TITLE
differents sensor in localhost and phoscon.de

### ISSUE THREAD

**Issue by srtxema** [dresden-elektronik/phoscon-app-beta#282]
Hi, I have a problem with Conbee2 with deconz in RPI4 for jeedom.
deconz is installed ok, but when I click on the phoscon web button, sometimes it will open the ip localhost: 8080 and other times phoscon.de/app, with different devices on each one. Why is this happening? which one is correct to work with? with phoscon.de or with localhost? thanks!
both images are of the same installation

![image](https://user-images.githubusercontent.com/18092080/103144494-79a53200-472a-11eb-8358-d91c256830f8.png)
![image](https://user-images.githubusercontent.com/18092080/103144496-7dd14f80-472a-11eb-9e6d-4259fab40260.png)

**Comment by YKO-de** [comment]
In principle, it doesn't matter. However, your local variant does not seem to be as up-to-date as the pwa. Which is why the devices are not visible there. You can check under sidemenu Gateway whether it is the same version.

**Comment by srtxema** [comment]
finally i installed zigbee2mqtt and it work perfectly with this

**Comment by YKO-de** [comment]
All right. :)
