### ISSUE TITLE
Scene setting to set light on or off

### ISSUE THREAD

**Issue by espen4001** [dresden-elektronik/phoscon-app-beta#283]
As of now the way to create a scene with one or more lights to be in state=off when scene recalled, is to set the brightness slider to lowest possible value, and store this.
Wanted solution: A separate button to select light to be "on" or "off" in current scene. This button should override any value set by the brightness-slider.
Tetsing performed:
- Created scene from pwa, with multiple lights set to minimum in slider and store the scene
- Recall scene, and observe that some lights are still on, but wanted state is "off"
- API Get: "<api_url>/groups/1/scene/1/" shows the scene setting of lights in scene. Those lights which was set to lowest brightness i PWA, randomly reports the state stored as "on": false or "on": true, and "brightness": 1.
- Recall scene: The lights with "on": true are turned on with brightness 1, those with "on": false are turned off.
- Did an API POST to modify scene to set all lights to "on": false, and when scene is recalled, all lights are in the correct/wanted state.

**Comment by YKO-de** [comment]
Do I understand correctly that you would like to have the light off state in the form of a scene?

**Comment by espen4001** [comment]
I have a group of lights that I control via scenes. In some of the scenes I would like to have one or more light to be off. But as of now there is no way to specify a light to be off in a scene, other than setting the brightness to lowest possible value.
So I think your understanding is correct :) I want to turn off a light with a scene recall (light state=off)
See attached result of an API GET of a specific scene I have. I would like to make sure the light has attribute "on=False" when creating scene in phoscon web app.

![4C10932E-0F76-4715-B718-080E201E7629](https://user-images.githubusercontent.com/38804642/104192642-63cc8800-541f-11eb-9d6c-7d0edcc03c71.jpeg)

**Comment by YKO-de** [comment]
Ahh okay. I see. I'll take a look at it. It probably won't be that easy, though. Turning it on again in a different scene at a certain brightness level may lead to errors. I'll have a look.

**Comment by espen4001** [comment]
I have created several scenes by doing API posts to save a scene with light attribute on=false, and others with same light and on=true, and I have no issues at all. But please, have a look and see if you  find a possible solution! :)

**Comment by YKO-de** [comment]
Okay. I'll look at it again.
