### ISSUE TITLE
[Device Request] Lidl/Silvercrest Remote control

### ISSUE THREAD

**Issue by eric-zimmer** [dresden-elektronik/phoscon-app-beta#284]
As in this topic
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3829

I would like to use the remote within the phoscon app.

**Comment by davidkrass** [comment]
Yes, that would be great. I have 4 of these flying around.

**Comment by snapcatcher** [comment]
Yes i woud also love it, if support for that remote would be added :)

**Comment by YKO-de** [comment]
Noted. ;)

**Comment by lucky2k12** [comment]
Amy News? @YKO-de

**Comment by SEK-DE** [comment]
Duplicate of #315 
Closed
