### ISSUE TITLE
Plug as a Switch an not as a light.

### ISSUE THREAD

**Issue by tonibert** [dresden-elektronik/phoscon-app-beta#285]
Is it possible to add a plug (Osram) as a switch and not as a light?
When I want to turn off all the lights, I often turn off my plugs.
That is not my intention.
A switch would possibly be more suitable.

**Comment by Kane610** [comment]
A switch is not a power plug. You can create a new group with only the lights you want to control.

**Comment by SwoopX** [comment]
So the answer remains
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4051
