### ISSUE TITLE
Inactive Scheduler activates after reboot

### ISSUE THREAD

**Issue by olla69** [dresden-elektronik/phoscon-app-beta#286]
Hello,
after rebooting a Pi3b with Image "Phoscon_Gateway_Headless_2020-06-19.xz" where a deactivated schedule exist, the schedule is activated again. I think that this isn't desired.

**Comment by YKO-de** [comment]
Can you please attach this issue to https://github.com/dresden-elektronik/deconz-rest-plugin. This is not a direct app problem. ;)
