### ISSUE TITLE
"The group already exists"

### ISSUE THREAD

**Issue by erd82** [dresden-elektronik/phoscon-app-beta#287]
Hello, Phoscon App tells me that the group already exists, although there is no group with this name yet (see video attached). The installation already runs for a while. It might be that I have created a group with this name in the past which I have later deleted (but not sure). Can you please check? Cheers

https://user-images.githubusercontent.com/63564291/103432628-71456f00-4be2-11eb-81ea-4c97d97e40c0.mp4

**Comment by erd82** [comment]
I made it to open the old web app (not that easy with ingress).
There I could see that the "Sleeping Room" already existed. It is just not showing up in the Phoscon App. This should be fixed to be consistent. Cheers

![image](https://user-images.githubusercontent.com/63564291/103444470-bf9d5100-4c68-11eb-9cfd-0778607310c7.png)

**Comment by YKO-de** [comment]
Okay. I'll take a look at it. Thanks for the tip.
