### ISSUE TITLE
FLS-PP lp colorloop effect interferes with scene programming

### ISSUE THREAD

**Issue by Sonderstorch** [dresden-elektronik/phoscon-app-beta#288]
Once the colorloop effect is still active when storing a scene will persist the colorloop setting somehow. At least sometimes when restoring the scene the colorloop effect will activate again in an undeterministic manner.

There is no option within the scene / lights configuration to clear or otherwise influence the colorloop setting of the FLS-PP Ip devices within a scene.

**Comment by YKO-de** [comment]
Ohh. This problem doesn't necessarily have anything to do with the app. I'll pass it on. Thanks for the tip.
