### ISSUE TITLE
New Device - Trust ZYCT Remote

### ISSUE THREAD

**Issue by Puntoboy** [dresden-elektronik/phoscon-app-beta#289]
As per this topic. Apparently it has been supported but It does not appear in Phoscon or Home Assistant.

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3682

**Comment by YKO-de** [comment]
I'm looking at it. It's probably just not listed yet.

**Comment by YKO-de** [comment]
I have added the device. It should work with the next release. So I would close the issue for now.
