### ISSUE TITLE
Need ability for simple on/off light option

### ISSUE THREAD

**Issue by Pigweed** [dresden-elektronik/phoscon-app-beta#29]
I just got the Centralite Smart Outlet Mini from Amazon working with Raspbee Phoscon. This is a pretty powerful 15A switch which is VERY useful. It was identified by the system as a  light bulb, which is OK by me. But I could not turn the device on and off. It is identified by deCONZ as "On/Off light" and dimmer bar is not provided for it. Basically there is no on/off capability.

I did find a workaround by going to help, using Old WebApp version, setting up simple On and Off scenes in the old version and then going back and using the scenes from my mobile in the new app.

Just simply allowing on/off will greatly enhance what can be done with the app.
Also documenting in the app simple switches being identified as lights will help people make use of them.
Thanks.

**Comment by manup** [comment]
>Just simply allowing on/off will greatly enhance what can be done with the app.

When you click on the bulb icon it should do just that — toggle on/off. It works the same as in the old WebApp.

![image](https://user-images.githubusercontent.com/383386/46570150-10c21b80-c960-11e8-958e-9a9d6fe16472.png)

**Comment by Pigweed** [comment]
I got it now. Sorry for the confusion.
Works well.
