### ISSUE TITLE
[DEVICE REQUEST] RGBGenie ZB-5121

### ISSUE THREAD

**Issue by shadowdognh** [dresden-elektronik/phoscon-app-beta#290]
Hello,
I have a RGBGenie ZB-5121 Zigbee 3.0 remote (https://rgbgenie.com/?product=rgbgenie-mini-remote-with-single-scene-recall-zigbee). It is supported in deCONZ (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1256) but it does not seem to be supported in Phoscon. I can add the remote to deCONZ, and I can use it with 3rd party apps via the REST API but I would like to be able to use it within Phoscon. Is it possible to add support for this remote? 

Thanks!

**Comment by YKO-de** [comment]
Yes. I'll take care of it. :)

**Comment by YKO-de** [comment]
@shadowdognh Can you please tell me which manufacturer's name and which modelid the switch provides in the API. It is actually already listed and should work.

**Comment by shadowdognh** [comment]
Hi,
Is this the information you are looking for? 

![image](https://user-images.githubusercontent.com/56440161/104601682-842b5b00-5648-11eb-80d6-a350ae8a08d6.png)

Thanks!

**Comment by YKO-de** [comment]
Perfect. Should go after the next release of the app.
