### ISSUE TITLE
anybody tested tint LED-Ambienteleuchte Talpa with Deconz/Phoscon?

### ISSUE THREAD

**Issue by Gammenon** [dresden-elektronik/phoscon-app-beta#291]
Hi,
does anybody know if this device works with deconz/phoscon? 
tint LED-Ambienteleuchte Talpa white+color
Artikel-Nr.:404027
https://www.mueller-licht.de/produktinformationen/artikel/404027/

**Comment by svkn71** [comment]
I bought a Talpa and tried to connect via Phoscon. Unfortunately Phoscon didn't find the device.

**Comment by YKO-de** [comment]
@svkn71 Were you able to see the lamp in the deCONZ?

**Comment by svkn71** [comment]
I'm not sure. Because i installed deconz without gui. Is there an logfile?

**Comment by SEK-DE** [comment]
@svkn71 is this issue still relevant for you?
