### ISSUE TITLE
Xiaomi aqara temp sensor not on alexa

### ISSUE THREAD

**Issue by Gruenyst** [dresden-elektronik/phoscon-app-beta#292]
Hello, i have two xiaomi aqara temp sensor in the phoscon app. Why i can‘t see the sensor in the alexa app ? Is it possible to fix it ?
Best regrads

**Comment by SEK-DE** [comment]
@Gruenyst please let me know the following things if this is still relevant for you:

1. host system (Raspberry Pi / PC / NAS):
2. execution method (Raspbian / Ubuntu / Home Assistant deCONZ add-on / Marthoc Docker container / Windows / Virtual Machine):
3. Firmware version (format 26xxyy00):
4. deCONZ version (format 2.xx.yy):
5. device (ConBee I / ConBee II / RaspBee I / RaspBee II):
6. is a USB extension used?   (yes / no) - only relevant for ConBee I/II:
7. are other USB or serial devices connected to the host system? (yes / no) - If yes: Which ones?):
8. if Raspberry Pi: Which power supply is used? (original / manufacturer+model) Indication of volts and amps: (e.g. 5.0V, 1.0A):
9. if Raspberry Pi: On which image base is the system set up?: (Phoscon / Raspbian / Raspberry Pi OS / Home Assistant ...):

**Comment by Gruenyst** [comment]
Hello,
1. Host Sytem is Raspberry Pi
2. Execution method iss Raspbian
3. Firmware version
4. deconz v.: 2.12.0
5. Raspbee II
6. No
7. No
8. The Original one
9. On the phoscon image

**Comment by SEK-DE** [comment]
And you have integrated all devices successfull to Alexa at first?

**Comment by Gruenyst** [comment]
Yes without problems

**Comment by SEK-DE** [comment]
Thats seems more like a problem of the alexa app. Please be patient, i will try to reproduce the issue in our test setup.

**Comment by SEK-DE** [comment]
@Gruenyst 
so, as long as you use only our web-intern integration of alexa, you wan´t be able to see other devices then bulbs in alexa.
You have to go over a home automation software (https://phoscon.de/de/conbee2#hasystems). And in there are also specific integrations for alexa and other devices. It is then the question of how good are those integrations are developed. It´s possible that you can see sensor devices in the alexa app, but we we cant promise this.
