### ISSUE TITLE
Adjusting night/day time

### ISSUE THREAD

**Issue by Ma-Str** [dresden-elektronik/phoscon-app-beta#293]
## Describe the question or issue you are having

Hello,
I am not sure, if this was posted earlier, but I haven't found anything for my specific Issue.
I have an Ikea motion Sensor set up and wanted to have two different sensor controls. One for daytime and one for night time.
Is there any way to adjust the preset time, when "night time" begins? I think it corresponds with sunset & sunrise, which is way to early for my use case.
Is there any way to set it to specific times like 23:00 - 05:59 for night and 06:00 - 22:59 for daytime?
Thanks 👍

## Screenshots

![Bildschirmfoto 2021-01-06 um 08 14 55](https://user-images.githubusercontent.com/76751947/103740506-a2191000-4ff7-11eb-8e75-346b1769462f.png)

## Environment

 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26680700
 - deCONZ version: 2.09.00 / 14.9.2020
 - Device: ConBee II
 - Do you use an USB extension cable: no
 - Is there any other USB or serial devices connected to the host system? No

## deCONZ Logs

No Logs

## Additional context

No additional context

**Comment by YKO-de** [comment]
Currently there is no possibility. But this is currently being worked on. So it will be possible in the future. I ask for a little patience for this. ;)
