### ISSUE TITLE
iluminize 511.514 (ZGRC-TEUR-005 8)

### ISSUE THREAD

**Issue by vogtgbr** [dresden-elektronik/phoscon-app-beta#294]
## Device

- Product name: iluminize 511.514 Wand-Dimmer
- Manufacturer: iluminize
- Model identifier: ZGRC-TEUR-005 8
- Device type : 
  - Remote
  - Switch

## Screenshots
![grafik](https://user-images.githubusercontent.com/10582813/103771516-2edbc200-5028-11eb-97ec-9c308c84e1fd.png)

![grafik](https://user-images.githubusercontent.com/10582813/103771545-39965700-5028-11eb-9328-2993f273dd07.png)

![grafik](https://user-images.githubusercontent.com/10582813/103771570-41ee9200-5028-11eb-9e37-42d6d3d67198.png)

**Comment by YKO-de** [comment]
I have added the device. It should work with the next release. So I would close the issue for now.
