### ISSUE TITLE
Full support of Osram Smart+ Mini switch

### ISSUE THREAD

**Issue by danzbox** [dresden-elektronik/phoscon-app-beta#295]
@YKO-de Great to see some progress in the Phoscon app. Finally undusting the unused Smart+ Switch Mini and after pairing it just works fine as you described it [here](https://github.com/dresden-elektronik/phoscon-app-beta/issues/64). (Phoscon 2.07.01). 

For full support I have three open topics and you asked to open another issue in #64 (which is closed) so here it is:
1. As known and mentioned it is a three button device not a four button. This should be changed in phoscon/deconz. Do I need to open a separate ticket for Deconz?

2. Image in Phoscon: There is a great 2D black and white image available from LEDAVANCE as inspiration for the Phoscon icons so that we don't need 4 button generic
![image](https://user-images.githubusercontent.com/46283463/103892299-a7578700-50eb-11eb-93ff-e875c572480a.png)
 https://dammedia.ledvance.info/media/resource/450x450/asset-1895087/SMART+-Switch-Mini.jpg
    ...even as high quality [EPS ](https://dammedia.ledvance.info/media/resource/hires/asset-1895087/SMART+-Switch-Mini.eps) available.

3. For the name I would suggest Osram SMART+ Switch Mini (as Lightify is the name for the cloud solution and the SMART+ hardware still continues under Ledvance)

Feedback: Using all three buttons and works as expected (Still new to the Phoscon/Deconz world though)
![image](https://user-images.githubusercontent.com/46283463/103891797-b984f580-50ea-11eb-8005-0dec0318f2c2.png)
The biggest limitation for me is that I cannot define short and long press actions separately from each other, but I guess that is not specific to this device but all switches.

**Comment by YKO-de** [comment]
Okay. I'll look at it again.

**Comment by 7wells** [comment]
Sorry that I have not sent feedback for a while. I also looked into the now closed thread and this one, but am unsure how to proceed about further testing in the beta. I see my 2 mini switches also in beta but greyed out and not configurable. However, clicking the buttons works, i.e.:
- Button 1 (top): short = brighter // long = RGB colour cycle up
- Button 2 (middle): short = colour temperature cycle (seems to be the same for long-press)
- Button 3 (bottom): short = darker // long = RGB colour cycle down

Should the buttons now appear in the **beta** GUI with the new 3-buttons style? Here, they still have the old 4-buttons design:
![Mini](https://user-images.githubusercontent.com/65889763/104345420-9d27f500-54fe-11eb-82de-9a10628682e7.png)

One of the mini switches shows like this:

![Mini1](https://user-images.githubusercontent.com/65889763/104345537-c183d180-54fe-11eb-970d-47e5a369c5d1.png)

The **non-beta** GUI shows them like this:
![Non-beta_mini](https://user-images.githubusercontent.com/65889763/104345895-1d4e5a80-54ff-11eb-9df3-06f60c3cfe15.png)

And one of the mini switches shows like this in the **non-beta** GUI:
![Non-beta_mini1](https://user-images.githubusercontent.com/65889763/104346071-4b339f00-54ff-11eb-8b0d-e7c1c7117133.png)

Is this as currently to be expected?

Version: 2.09.00 / 15.12.2020
Firmware: 26650700
GUI link used: http://phoscon.de/pwabeta

**Comment by YKO-de** [comment]
I got myself one of those switches and am looking at it again.

**Comment by ralf-neugebauer** [comment]
Hello KO-de, 
Do you have any progress with that issue?

**Comment by 7wells** [comment]
I am still interested in this, too.

**Comment by ilceko** [comment]
hi, i'm new to this world, still trying to figure it out how all this works.
I have a doubt.
I got my switch linked in Phoscon App but when i go in Home Assistant to use the switch as a trigger... no triggers available. 
Is it normal?

Sorry for being OT

**Comment by ralf-neugebauer** [comment]
Hello YKO-de,

Do you have any progress with that issue?
The server from OSRAM will shut down on August and I bought the stick from Dresden Elektronik to be prepared,
but there is no progress with this problem.

Kind regards
 Ralf

**Comment by 7wells** [comment]
@ralf-neugebauer @YKO-de 
My Osram Galaxy stopped working already last year. Since then I can use the original switches also with the RaspBee II. However, I still have the same questions as other users mentioned here.

**Comment by 7wells** [comment]
If someone looks for HowTo pair these mini switches, check this out:

> **Pairing**
> For the OSRAM Smart+ Switch Mini (AC0251100NJ/AC0251700NJ) hold the Middle and Arrow Down Buttons for 10 Seconds to Reset the Device. Hold the Middle and Arrow Up Buttons for 3 Seconds to connect. If the Switch is connected hold Middle and Arrow Up Buttons for 3 Seconds to disconnect.

https://zigbee.blakadder.com/OSRAM_AC0251x00NJ.html

**Comment by SEK-DE** [comment]
@YKO-de anything new here?

**Comment by 7wells** [comment]
Same here - closed but no news. Is somebody still investigating about this?

**Comment by SEK-DE** [comment]
@7wells we work on a automisation for nearly all switches, it will come in one of our further updates.
