### ISSUE TITLE
[DEVICE REQUEST] Talpa Tint Müller Licht 

### ISSUE THREAD

**Issue by svkn71** [dresden-elektronik/phoscon-app-beta#296]
Please add support for Talpa Tint Müller Licht (https://www.mueller-licht.de/produktinformationen/artikel/404027/)

**Comment by duffbeer2000** [comment]
Maybe you should provide more informations about what's not working. Is it missing only in Phoscon or in Deconz too?
With this description no one can help you.

**Comment by svkn71** [comment]
I think it also missing in Deconz.

**Comment by duffbeer2000** [comment]
Then you have to make a correct device request for deconz with all the informations you have to provide. In this repository it's wrong.

**Comment by h4rm** [comment]
@duffbeer2000 I would love to open a request for a new device, but I am struggling with getting the info described on the Request Device Support page. Deconz is all setup and works with other devices, but the GUI is not showing the new, unknown, device anywhere so I cannot give you the information required.
Do I need to start a "scan" mode or something like it?

**Comment by svkn71** [comment]
I tried yesterday again and phoscon detected it now. I don't know what was wrong. I do the same. Switched the lamp 5 time on/off until the lamp blink.
