### ISSUE TITLE
Feature Request: Support IKEA Tradfri Shortcut button in Phoscon

### ISSUE THREAD

**Issue by snookyly** [dresden-elektronik/phoscon-app-beta#297]
Regarding https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3975 please support IKEA Tradfri Shortcut button in Phoscon app as it is supported by deconz already. Realisation is highly appreciated.

**Comment by YKO-de** [comment]
I'll take care of it. Thanks for the tip.

**Comment by snookyly** [comment]
Never mind. Thanks for doing it. Happy coding :)

**Comment by YKO-de** [comment]
I have added the switch. It should work with the next release. So I would close the issue for now.

**Comment by snookyly** [comment]
Thank you very much.

**Comment by tanders82** [comment]
> I have added the switch. It should work with the next release. So I would close the issue for now.

Do you know the release number for when the Tradfri shorcut button will be included in Phoscon App? I did not find support for it in the 2.10.01 / 2/19/2021 under switches beta -> Ikea

**Comment by gidadavid** [comment]
Same. Cant connect via Phoscon. In the deconz tap there is a note that is named "TRADFRI SHORTCUT Button" But it is not showing up under switches

**Comment by phbasler** [comment]
@gidadavid it shows under Switches (beta) if you use the phoscon beta app http://phoscon.de/pwabeta

**Comment by gidadavid** [comment]
# #
![deconz](https://user-images.githubusercontent.com/40966169/110843189-4e9d9980-82a8-11eb-8dbc-0e08501114a5.JPG)
![HA](https://user-images.githubusercontent.com/40966169/110843192-4f363000-82a8-11eb-89df-0d6af34ef71a.JPG)

This it how it looks like.
Im currently on version 2.09.03 / 23.12.2020
Firmware 26660700

Home Assistant just doesn't show any events.

**Comment by andreaCremisini** [comment]
> ![deconz](https://user-images.githubusercontent.com/40966169/110843189-4e9d9980-82a8-11eb-8dbc-0e08501114a5.JPG)
> ![HA](https://user-images.githubusercontent.com/40966169/110843192-4f363000-82a8-11eb-89df-0d6af34ef71a.JPG)
> 
> This it how it looks like.
> Im currently on version 2.09.03 / 23.12.2020
> Firmware 26660700
> 
> Home Assistant just doesn't show any events.

Can i update my conbee II? I have 264A0700 version and i don't see another version from terminal or  UI

**Comment by wuschel1337** [comment]
have exactly the same problems. do not think that it is due to HA, since so far all devices have been found if they were recognized by phoscon. in deconz all fine but und phoscon they are not visible

**Comment by LukasOchmann** [comment]
Same here 
conBee 2 with 2.10.04 / 14.3.2021 
and deconz HA-plugin at 6.8.0

**Comment by reynos** [comment]
Also on 2.10.04 and no luck with the shortcut switch appearing, keen to see it working, thanks.

**Comment by RingoRohe** [comment]
Conbee2 with 2.11.05 / 9.5.2021
Still no Ikea Shortcut Button. :(

**Comment by mrclschstr** [comment]
Since phoscon beta 2.12.01 it finally works. Just give it a shot!

**Comment by FickleLife** [comment]
I've upgraded to 2.12.03 and the options for switches under the beta app (http://phoscon.de/pwabeta) show tradfri remote control, tradfri on/off switch and tradfri open/close switch. Do any of these work work with the tradfri shortcut switch or am I missing an option here?
