### ISSUE TITLE
Aqara Smart WXKG12LM - long press not available in group switch editor

### ISSUE THREAD

**Issue by senilio** [dresden-elektronik/phoscon-app-beta#298]
Single click, double click and shake is available in the Switch editor, but his switch also supports long press... is it possible to allow mapping long press action in the switch editor as well?

Thanks!

![Screenshot 2021-01-10 at 16 39 35](https://user-images.githubusercontent.com/7874309/104127460-759c2580-5362-11eb-9d66-56a682dbee61.png)

**Comment by StephanStS** [comment]
@senilio: Does the information in issue #233 help?

**Comment by senilio** [comment]
I wanted to map switch actions to a power plug/outlet (short press for on, hold for off). 

Since this is a switch with 4 action types, I was just expecting to find all of of them available on the Key Assignment page, freely available to map as I wish. I do understand that light dimming might be the most common use case, and my request is somewhat of a corner case :)

**Comment by YKO-de** [comment]
Currently, it is not intended to use the long press for anything other than dimming. But I will consider this for the further planning of the app.
