### ISSUE TITLE
Switch editor - some observations

### ISSUE THREAD

**Issue by ronaldvans** [dresden-elektronik/phoscon-app-beta#30]
With the switch editor I regularly run into the problem that upon opening it i get a new window saying: "Bezeignung" Zu stuerende Gruppe wählen. (my language is set to English). The buttons on that page (Züruck and Weiter) do not work and I have to use back to go to the previous page. I can reset the switch editor by adding '?1234' to reset the cache.

When I am in the switch editor there is a small typo in the "call scene" window. It says "call preview scene" instead of "call previous scene".

**Comment by roaringbits** [comment]
The editor stills says 'Preview scene' - Had me confused for sure.

**Comment by manup** [comment]
Woops :) fixed in next version.
