### ISSUE TITLE
IKEA TRÅDFRI E1743 ON/OFF Switch, not able to pair.

### ISSUE THREAD

**Issue by Hjortsberg** [dresden-elektronik/phoscon-app-beta#300]
Hi, I had my E1743 switch paired before with Phoscon. The battery ran out, I replaced it, removed the switch from Phoscon web GUI and now I can't re-pair it.
The switch shows up in the deCONZ gui but not in Phoscon. 
How can I debug this? 
I'm fairly new to all of this but will try to provide all information I can to resovle this. :)

* I've tried to remove the node from deCONZ gui also, but it keeps popping up.
* I've reset the switch by pressing 4x under 5 secodns, very many times.
* I've tried to hold the pair button for more than 10 seconds (according to the IKEA manual for pairing).
* I've tried to pair it as "Other" type of switch  as this suggests,](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/853#issuecomment-458695666) also tried IKEA switch types but according to issue I mostly tried the "other" siwtch type.

**Comment by YKO-de** [comment]
Hi. You don't have to press the switch for 10 seconds. This step applies only to direct connection between IKEA devices. You just start the switch search and then press the button 4x within 5 seconds. After that just wait for a short time. That should be enough.

**Comment by Hjortsberg** [comment]
Hi, that's exactly what I tried. Approx. 40 times.
The switch paired perfectly the first time, but as I said I can't manage to re-pair it after my battery change and removal in the phoscon app. 

It shows upp in the deconz UI but not in phoscon.

**Comment by Hjortsberg** [comment]
Ok, seems like the 41th time is the charm! :+1: 
I just re did these steps and it worked, no idea why since I did exactly as the other 40 attempts.
Anyhow, thanks for a quick response!

**Comment by adampetrovic** [comment]
I'm going through the same issues and honestly it's so frustrating. I'm only 20 pairing attempts in for now, so i'll keep trying.

It really shouldn't have to come to this.

**Comment by mitchins** [comment]
I had issues too... but you need to really get it close to the conbee as per the ikea instructions.
I find if it doesn't start flashing right away when you hold it near, then you have to reset the device and wave it again while holding the pair button.
I've paired two so far with a 50/50 success rate after trying the above.
