### ISSUE TITLE
Update firmware, but then it goes back to previous version

### ISSUE THREAD

**Issue by SHxKM** [dresden-elektronik/phoscon-app-beta#303]
In the Phoscon app, I see my Conbee II is on firmware version 26580700. I see a button that says "Update to 266607000". I go through the procedure and Phoscon reports that the update was successful, but shortly after the version is back to 26580700 and Phoscon once again offers me to update the firmware.

Version: 2.09.00

What gives?

**Comment by YKO-de** [comment]
You can try to update manually. You can find help on this at https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually. Updating via the app sometimes leads to errors. We are working on this.
