### ISSUE TITLE
Feature Request: set a scene when motion is detected

### ISSUE THREAD

**Issue by JayJay68** [dresden-elektronik/phoscon-app-beta#304]
If motion is detected or after x minutes no motion is detected you can set several actions (e.g. switch group on, set brightness for all lamps (of the group)). It would be nice, if I could define a scene, too. Then you have more posibilities to control the lamps
Example:
1. Motion detected:  Action "set scene" scene_01 (e.g. brightness 100%, color temperatur: 4000K)
2. No Motion after 2 Minutues: Action "set scene"  scene_02 ((e.g. brightness 70%, color temperatur: 3000K)
3. No Mtion after ....
Thank you.

**Comment by SEK-DE** [comment]
Sry for the late response. Thx for the idea, we are on it to inovate our app continiously. This type of manual config is kind of complicated to integrate.
