### ISSUE TITLE
Xiaomi Aqara Smart Switch - Long Press Button not available

### ISSUE THREAD

**Issue by Maddinthebrain** [dresden-elektronik/phoscon-app-beta#305]
@YKO-de @ebaauw

This is still not working... is it built in now?

Cu Martin

The problem should have been resolved by now. I would therefore close the issue for the time being. If it still exists please create a new one.

_Originally posted by @YKO-de in https://github.com/dresden-elektronik/phoscon-app-beta/issues/180#issuecomment-713443743_

**Comment by YKO-de** [comment]
Can you please tell me the modelid of the switch that is not working?

**Comment by Maddinthebrain** [comment]
Does this help? Or do you more details? 

![image](https://user-images.githubusercontent.com/43421040/104920097-946c6e80-5997-11eb-83c0-260b5cdbbac2.png)

**Comment by YKO-de** [comment]
I think I understand now. There is no extra button for long. The long event only allows you to use the dim function in the switch editor. So you select it once and go to dim on the next page. If the switch supports dimen the long event is automatically used for this. It will not be displayed directly in this case.

**Comment by Maddinthebrain** [comment]
@YKO-de Thanks, well after some time I was now looking for it and found well hidden ;-). 
![image](https://user-images.githubusercontent.com/43421040/118175882-f7937c80-b430-11eb-82f5-629e09d9aaec.png)
But it doesn't work as expected. When it is configure like in the screenshot, the short press switches on/off as expected. But the longpress does nothing at light. But while your looking at the light control in phoscon 
![image](https://user-images.githubusercontent.com/43421040/118176119-48a37080-b431-11eb-8c36-132211f2c084.png)
the brightness controller goes from maximum straight to minimum and stays there until you move it with your mouse. While moving with the mouse the light is dimming as expected.

Maybe it is bug in the control of the light controller, as with another type of light controller it works as expected.
