### ISSUE TITLE
Phoscon doesn't show Tradfri Shortcut in Switches

### ISSUE THREAD

**Issue by palletodap** [dresden-elektronik/phoscon-app-beta#307]
Hi,

Just got an Tradfri shortcut button today, and ran into my computer to connect it to my deconz.

And then i found out it wasn't compatible yet....

Literally 30 minutes after i noticed a brand new update for deconz was released! And it freaking included an update that made it able to handle the button!! I must be blessed by the zigbee gods! ;)

I got the button connected to deconz, but my phoscon cant see it anywhere... (The beta doesn't show it either)

Are you working on an update for phoscon? 

Thanks for the amazing work,
Palle

**Comment by YKO-de** [comment]
Hey. Yes in the Phoscon app the same thing will happen. The switch will work with the next release ;)

**Comment by Szwuntex** [comment]
Hi.
What is "next release"?
I'm running  "2.09.02-raspbian-buster-beta" and I can't add Trådfri Shortcut button in Phoscon  :-(   I'm I missing something?
Do I need to add it in Deconcz gui? (I don't run any GUI/Desktop on my Pi).

**Comment by YKO-de** [comment]
The app will next be updated with deCONZ version 2.10.0.

**Comment by palletodap** [comment]
> Hi.
> 
> What is "next release"?
> 
> I'm running  "2.09.02-raspbian-buster-beta" and I can't add Trådfri Shortcut button in Phoscon  :-(   Am I missing something?
> 
> Do I need to add it in deCONZ gui? (I don't run any GUI/Desktop on my Pi).

It's not showing in phoscon, but deconz was updated some versions ago to be able to handle it😄

**Comment by YKO-de** [comment]
Please first via phoscon.de/pwabeta. We are currently restructuring the stable. Therefore, there will be delays during the update.

**Comment by dseehof** [comment]
I still don't see the shortcut button in the beta, I can see and add the new on/off button with no problem, but shortcut is nowhere to be seen.

**Comment by szoller** [comment]
I can add the shortcut button in beta but I cannot add it to any groups.

**Comment by dseehof** [comment]
How do you add it?

**Comment by szoller** [comment]
The normal phoscon app (2.10.04/14.3.2021) does not even find it when trying to pair. Inside the beta app I can pair it (it still does not show up inside normal app), but It's not visible when trying to add a switch to a group (beta app)

**Comment by dseehof** [comment]
I can't even add it in the beta app - other doesn't work and the on/off doesn't work either.

**Comment by szoller** [comment]
News about the issue? Updated phoscon app to 2.11 - no change.

**Comment by szoller** [comment]
News?

**Comment by dseehof** [comment]
Same here -  no way to add in beta.

**Comment by Owlbertz** [comment]
I am able to add it using http://phoscon.de/pwabeta by clicking Buttons (beta) -> Add -> Ikea -> Dimmer.
It also shows in the REST api using `/api/<token>/sensors/<ID>` but the `buttonevent` and `lastUpdated` properties are always `null`.

Adding it to openHAB also works (thing is being shown as online and visible via inbox) but cannot be used as no button press is being reported.

**Comment by Owlbertz** [comment]
Not sure why, but after some fiddling around it works now for me, both in the API and via openHAB.

**Comment by dseehof** [comment]
In Switches Beta I have no Dimmer and if I use the dimmer in the normal switches nothing appears.

**Comment by Owlbertz** [comment]
@dseehof sorry I recalled it wrong when posting on Wednesday.
It is actually labelled "open/close" (the one on the right "auf/zu").
![image](https://user-images.githubusercontent.com/4280373/119184923-4b781400-ba76-11eb-9bde-8269394c1844.png)

Hope this helps and you can get it to work!

**Comment by dseehof** [comment]
Yup. Got it added. But how do you use the press in automations?

**Comment by SEK-DE** [comment]
@YKO-de can you tell us something new here?

**Comment by Sommerzeit** [comment]
For everyone else who happens to come across this post via Google and who is not able to connect a shortcut button to his phoscon application:

I did struggle to add a the button myself and I would not even work with the beta phoscon app. **But once I updated my local deconz package on my Raspberry Pi** (e.g. via `sudo apt-get upgrade deconz`) the beta version could find the button as described by @Owlbertz latest post.

Not working:
![not_working](https://user-images.githubusercontent.com/45332743/128641425-686b3924-5615-47de-a2d2-9b2ed140bdcb.png)

Working:
![working](https://user-images.githubusercontent.com/45332743/128641435-f3cc7bb2-b469-497d-af76-70483fe21638.png)

Don't ask my why two very different deconz versions are both displayed with a somewhat new date such as `7/20/2021`. That was the main reason why it did'nt occur to me that package versions/firmware could be an issue.

**Comment by mlazzarotto** [comment]
I've just received by mail my Conbee II usb stick and I've connected to my HomeAssistant.
I installed the deCONZ add-on and it's integration.
I have a IKEA shortcut button and an ON/OFF switch, neither of those are being detected by the Phoscon web app.
![image](https://user-images.githubusercontent.com/8932945/134966178-5fa534c5-3934-4676-a19a-bd0620d63cf1.png)
Please help!!!!
