### ISSUE TITLE
Tuya Heatcontrol show up as "Fairy Light" in deconz and does not appear in Phoscon app

### ISSUE THREAD

**Issue by pankewen** [dresden-elektronik/phoscon-app-beta#308]
Version 2.09.00 / 23.12.2020
Firmware 26680700

I updated today to the latest deconz Versions and had to add a Tuya heat controller
Device reference: https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html

Adding the heater control created a new device "Fairly light" showing up in the deconz GUI network map. But the device was not added to the device list in Phoscon.

I added these devices already succussfully in an earlier version (sorry, not sure, which one) and it worked as expected - so it seems to be a regresson with one of the newer updates.

Let me know, if you need more information.

Chris
P.S. great work on creating these regular updates! I am really happy with your SW support.

**Comment by YKO-de** [comment]
Can you tell me the modelid of the unit and the manufacturer? The information can be found in the deCONZ Gui in the Basic Cluster.

**Comment by pankewen** [comment]
Sure:
Manufacturer: 0x1002
Manufacturer Name: _TZE200_ckud7u2l
ModelID: TS0601

**Comment by YKO-de** [comment]
Thank you. I'll take a look at it.

**Comment by iisworks** [comment]
Exactly the same here on 2.9.1.

![image](https://user-images.githubusercontent.com/33196233/106753628-33e26000-662c-11eb-9d5d-823cc8eef993.png)

It's this radiator actuator:
https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html

**Comment by pankewen** [comment]
Hello, after more than on e year I updated deconz to 2.12.6, but the issue still exists...
