### ISSUE TITLE
No gateways found on iPhone

### ISSUE THREAD

**Issue by flobernd** [dresden-elektronik/phoscon-app-beta#31]
Hi there,

the Phoscon App is unable to find any gateways on my iPhone (iOS 12.1). It works great on my local Windows machine.

Anything I can do about that?

Best regards

**Comment by 00lex** [comment]
> Fixed login and discovery issues
> Safari issues are still under investigation

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_50

Same bug on Mac. Try another browser

**Comment by Lucleonhart** [comment]
... which is impossible on iOS cause all browser need to use the WebKit engine.

**Comment by manup** [comment]
This is fixed now on the online version http://dresden-elektronik.de/pwa

Will also be part of deCONZ 2.05.53.

**Comment by 00lex** [comment]
Not 80. i need 80 for pihole. Anyway phoscon works with Firefox on 8009 in my case.

**Comment by manup** [comment]
Ah ok, guess that's the reason. With Safari only ports 80 and 8080 are scanned. With version 2.05.53 it should work again in Safari, since the ip:port will be extracted from the URL.

    http://<ip-address>:<port>/pwa

**Comment by Lucleonhart** [comment]
> Might be cache issue, please try with appended bogus query string
> 
> http://dresden-elektronik.de/pwa?12345
> 
> Also ,is deCONZ using the default port 80 or 8080?

No difference using a randum number query string. Also my deCONZ is running on port 80...

**Comment by manup** [comment]
Hmm, can you please test with version 2.05.54.
In the browser bar open the login page directly:

    http://<gateway-ip>/pwa?555

**Comment by Lucleonhart** [comment]
Yes i can confirm its working perfectly fine now using the latest version. 
Thank you!

**Comment by manup** [comment]
Cool thanks, glad it works. Closing the issue for now.
