### ISSUE TITLE
Senic Smart Switch (Friends Of Hue) isn't listed in the settings of sensor controll of groups

### ISSUE THREAD

**Issue by JayJay68** [dresden-elektronik/phoscon-app-beta#310]
I have a Philips motion sensor and a Scenic Smart Switch (with energy harvesting). Both are configured and working fine.

If I go to Group > Edit > Sensor control and then on Settings, I see the motion sensor and some switches, but not the Scenic Smart Switch.

**Comment by YKO-de** [comment]
Do you mean the Senic Friends of Hue Smart Switch?

**Comment by JayJay68** [comment]
Yes, I mean the Senic Friends of Hue Smart Switch.

**Comment by YKO-de** [comment]
Okay. One more question. Can you tell me if the modelid of your switch is "FOHSWITCH"?

**Comment by JayJay68** [comment]
No problem and yes, the modelid is "FOHSWITCH". If you need further information, please ask.

**Comment by YKO-de** [comment]
Okay. Thanks. I'll take a look at it. Because actually it should work.

**Comment by JayJay68** [comment]
For your interest (maybe it helps): I just updated the firmware of my rasbee to 26390500 and the phoscon app to the last stable 2.07.01 / 8.12.2020. Unfortunately does this not solve the problem.

**Comment by YKO-de** [comment]
I have ordered the switch. I hope it comes soon. Then I will test it.

**Comment by Ilkase7en** [comment]
I have the exact same problem using a Friends of Hue Voltus eVoToggle https://www.voltus.de/evotoggle/

Works fine (controlling lamps) within Phoscon (last stable) on a ConBee II but is not available at sensor control settings list. While all other switches I have connected in teh same way are available.

**Comment by YKO-de** [comment]
I have found the error. Should work with the next release.

**Comment by JayJay68** [comment]
@YKO-de Thank you! I have updated to 2.12.06 and it works now
