### ISSUE TITLE
"Smart LED Mood Light" shows wrong vendor

### ISSUE THREAD

**Issue by Floyer007** [dresden-elektronik/phoscon-app-beta#312]
My new "Smart LED Mood Light" from _LIDL (Livarno Lux)_ doesn't show the expected vendor.
Instead it's: _TZ3000_9cpuaca6

Here's the full API response
{
  "colorcapabilities": 0,
  "ctmax": 65279,
  "ctmin": 0,
  "etag": "7bcf6ff3d191529e8eca29bd43a248a1",
  "hascolor": true,
  "lastannounced": null,
  "lastseen": "2021-01-20T18:57Z",
  "manufacturername": "_TZ3000_9cpuaca6",
  "modelid": "TS0505A",
  "name": "Extended color light 15",
  "state": {
    "alert": "none",
    "bri": 48,
    "colormode": "xy",
    "ct": 153,
    "effect": null,
    "hue": 0,
    "on": true,
    "reachable": true,
    "sat": 254,
    "xy": [
      0.1572,
      0.0193
    ]
  },
  "swversion": null,
  "type": "Extended color light",
  "uniqueid": "84:2e:14:ff:fe:05:d0:a0-01"
}

**Comment by YKO-de** [comment]
This is not wrong. It is because the manufacturer of the chip of the device is Tuya and they specify as such strange strings. But we are working on it. So that the seller is displayed as the manufacturer.
