### ISSUE TITLE
"Sensor control of group" : Turn light off immediately

### ISSUE THREAD

**Issue by Staubgeborener** [dresden-elektronik/phoscon-app-beta#314]
So i've got a aqara door & window sensor to detect if my door is open or closed. If door is open -> turn light on, if door is closed -> turn light off. This works. But the lowest value for the detection is "4 minutes". Why not "1 minute" or even better "immediately"? In my case, i don't need some kind of timeout.

![Unbenannt](https://user-images.githubusercontent.com/28908603/105636370-650ea380-5e68-11eb-90b6-60cb0d4bf23a.png)

Automation with phoscon are much more reliable then automation with HomeKit, so this would be a blessing for me.

**Comment by YKO-de** [comment]
Try it like this...
![image](https://user-images.githubusercontent.com/55535297/105696064-1bbf6200-5f03-11eb-8853-5e45746c9e67.png)

**Comment by Staubgeborener** [comment]
Turning the light on if the door is closed works perfectly like this:
![on](https://user-images.githubusercontent.com/28908603/105704167-a9ed1580-5f0e-11eb-85e9-29af1d0c722c.png)

But turning the light off like this 
![off](https://user-images.githubusercontent.com/28908603/105704182-b1142380-5f0e-11eb-8c56-55dfd13541bf.png)
don't work. Like i said, its an aqara door and windor sensor, not a motion detector

So i think, i would need something like this:
![no](https://user-images.githubusercontent.com/28908603/105704283-ddc83b00-5f0e-11eb-82b7-a6a3cb084a7d.png)
(also, the last screenshot don't turn the light off)

**Comment by YKO-de** [comment]
Okay. I'll take a look.

**Comment by YKO-de** [comment]
Okay. So it works for me. You don't need 2 rules either. Only one. It should dim up when detected. And when no longer detected down. Then the light goes on when the door is open. And with door closed after 10 seconds off again.

**Comment by YKO-de** [comment]
I think we have misunderstood each other now. I can do that with the "immediately". I had only assumed that it does not work in principle because it seemed so in the top image.

**Comment by Staubgeborener** [comment]
Oh yeah. So to be clear: Your example is working great! Door open -> light on, door closed -> wait 10 seconds -> light off. With one rule instead of two. And even better as a homekit automation. But a "immediately" option would be superb.

**Comment by YKO-de** [comment]
Yes. It's coming. ;)

**Comment by YKO-de** [comment]
So ready. Comes with the next release. However, an "IMMEDIATE" is not that either. Because the communication between the devices takes 1-2 seconds.

**Comment by Staubgeborener** [comment]
> 
> 
> So ready. Comes with the next release. However, an "IMMEDIATE" is not that either. Because the communication between the devices takes 1-2 seconds.

Thats totaly okay for me! Love to see the next release.

**Comment by Staubgeborener** [comment]
Just a quick question: the last release v2.10.3 has this fix?
