### ISSUE TITLE
Switch editor 'remembers' deleted switch configurations

### ISSUE THREAD

**Issue by gvdhoven** [dresden-elektronik/phoscon-app-beta#316]
**Scenario: Hue Tap**

- Go to group > switches
- I've assigned certain button presses/actions on to play around with.
- Then when i got the hang of it; I deleted those button presses and tried to assign a different action to that button.
- When i remove all button presses; the switch disappears from the left column, but the switch is not actually deleted from the group. Because pressing one of the buttons still performs the previously assigned action. Removing the switch from the system and re-adding it doesn't clear anything as well.

The only solution is to complete delete the group and re-create it as seen in this issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1779

So, somehow i think there are 2 problems:
1) Deleted button presses are not 'cleared'
2) When there are no button presses assigned, the switch remains active in that group somehow.

**Comment by Ilkase7en** [comment]
This also happens using the original Hue Dimmer Switch.
