### ISSUE TITLE
Sunricher's Single Color 4 Groups ZigBee Key Remote Controller SR-ZG9001K12-DIM-Z4 can be paired, but cannot be assigned to any group

### ISSUE THREAD

**Issue by hsteinme** [dresden-elektronik/phoscon-app-beta#317]
## Describe the question or issue you are having

My question refers to Sunricher's Single Color 4 Groups ZigBee Key Remote Controller SR-ZG9001K12-DIM-Z4

https://www.sunricher.com/single-color-4-groups-zigbee-key-remote-controller-sr-zg9001k12-dim-z4.html
https://zigbeealliance.org/zigbee_products/dimmer-switch/

This remote unit is not listed in the ConBee II Compatibility List. 

It could easily be paired with the ConBee II gateway. It is displayed in Phoscon's switches list (unfortunately with an inappropriate icon). But it cannot be assigned to any group. After selecting th Switch Editor and after clicking on "+ Link Switch" the list of available switches is shown - but the remote unit is not displayed in this list. 

What did I wrong? Is there any idea for bypassing this problem?

## Screenshots

![image](https://user-images.githubusercontent.com/33778564/106164134-f55f2800-6189-11eb-9319-b93663cd0804.png)
![image](https://user-images.githubusercontent.com/33778564/106164186-027c1700-618a-11eb-9dd6-06474a74b76f.png)
![image](https://user-images.githubusercontent.com/33778564/106164232-0ad45200-618a-11eb-8428-946ac8270d05.png)
![image](https://user-images.githubusercontent.com/33778564/106164263-1162c980-618a-11eb-8768-b64789cf2567.png)

## Environment

 - Host system: Raspberry Pi 3 Model B Rev 1.2
 - Running method: Raspbian GNU/Linux 10 (buster)
 - Firmware version: 26680700
 - deCONZ version: 2.09.00 / 12/23/2020
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

## deCONZ Logs

[INFO.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5888474/INFO.txt)
[ZCL.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5888475/ZCL.txt)
[ZDP.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5888476/ZDP.txt)
[APS.txt](https://github.com/dresden-elektronik/deconz-rest-plugin/files/5888477/APS.txt)

## Additional context

./.

**Comment by hsteinme** [comment]
![sr-2833n-z4_6](https://user-images.githubusercontent.com/33778564/106246887-1c137200-620f-11eb-8dc8-ec7dfeeb7b2c.jpg)

The Remote Controller SR-ZG9001K12-DIM-Z4 contains 3 button groups:
* On/Off buttons 1/2/3/4
* Scene buttons S1/S2
* All-on/all-off buttons I/O

My proposal for mapping the buttons to deConz:
* the 4 on/off buttons and the 2 scene buttons should be used as switch buttons usually are used: Mapping the buttons to lights/plugs/groups with the functions On/Off, Call scene, Effect, Change brightness, Change color temperature
* if possible the 2 I/O buttons should be treated in the same way
* otherwise the I button should execute all functions assigned to the left side of the rockers 1/2/3/4/S1 and the O button should execute all functions assigned to the right side of the rockers 1/2/3/4/S2

If I can assist you with additional information please let me know.

[SR-ZG9001K12-DIM-Z4 V2 instruction.pdf](https://github.com/dresden-elektronik/phoscon-app-beta/files/5892354/SR-ZG9001K12-DIM-Z4.V2.instruction.pdf)

**Comment by YKO-de** [comment]
This switch is currently not yet supported in the Switch Editor. The missing display is therefore not an error here.

**Comment by hsteinme** [comment]
(1) My issue text does in no way contain the word "error".

(2) After @Mimiix moved my former question issue to dresden-elektronik/phoscon-app-beta please consider it as an friendly request to support this valuable device by ConBee/deConz/Phoscon. I'm not the specialist myself to estimate which of the concerned components have to be adapted for this.

**Comment by YKO-de** [comment]
I'm sorry for the misunderstanding. We have him on the list. But it will probably take a while. Since I can't just bring him in with a generic picture.

**Comment by hsteinme** [comment]
Thank you very much for this good news. I will wait patiently for your final ready-message. (I have already relegated the remote control to a drawer so as not to be constantly reminded that it is still useless to me 😁).

If I can assist you with further information about the unit, please let me know.

**Comment by SEK-DE** [comment]
@hsteinme how is it going for you? Are you able to integrate the switch in one of the last versions?

**Comment by hsteinme** [comment]
As this issue doesn't contain any feedback that the controller is now supported I didn't see any reason for a new test.

**Comment by hsteinme** [comment]
Please tell me which version I should use for testing. Wordings like "one of the last versions" is unfortunately a good base for misunderstandings.

**Comment by hsteinme** [comment]
See https://github.com/dresden-elektronik/phoscon-app-beta/issues/421#issuecomment-1050121104
