### ISSUE TITLE
Group/Light assignment: Scrolling not possible

### ISSUE THREAD

**Issue by Tscherno** [dresden-elektronik/phoscon-app-beta#318]
Firefox

On the group/light assignment page, it is not possible to scroll through the list of lights. Makes assignment of invisible ones impossible.

![grafik](https://user-images.githubusercontent.com/5594674/106362302-56216880-6322-11eb-9e56-3a31ec4d84ac.png)

**Comment by YKO-de** [comment]
Ohh. Okay. I'll take care of it. Thank you very much for the advice.

**Comment by Tscherno** [comment]
Thx. In the meantime i found a workaround: add lights which are not needed until the needed ones are shown on bottom. Then remove the unwanted again from the group...
