### ISSUE TITLE
Best way to move conbee to new host

### ISSUE THREAD

**Issue by My-userid** [dresden-elektronik/phoscon-app-beta#319]
Hi

I have a conbee running on a Raspberry Pi. It works good, however I want to move the stick to a Windows pc.
I have installed deCONZ and it finds the Conbee and connects and devices are found.

However, what ever I do, Phoscon still shows the old Raspberry Pi gateway/IP.
I have tried searching for the new host but nothing happens.

If I go to http://phoscon.de/discover, it also shows the old IP.
I also tried the beta URL and entering the IP of the new host, but it still shows the old gateway.
http://phoscon.de/pwabeta/login.html#host/192.168.1.7:80

How do I update to the correct IP?
The old IP is 192.168.1.118 and the new one is 192.168.1.7
Running Windows 10 Pro 20H2, tried disabling the Windows firewall, but still no luck.

**Comment by My-userid** [comment]
Why close this without a response ?
Question still stands.

**Comment by SEK-DE** [comment]
Over 4 months of no response, the stale Bot should have close this months ago.
In most cases, there is no issue anymore then.
Thanks for your feedback, we will take a look on it.

**Comment by letszb** [comment]
Possibly not current data is displayed in the WebApp. Here it helps to open the Phoscon App again in a private tab. Alternatively, cache and app data can be cleared in the browser.

Searching for new gateways is possible by clicking at the big Phoscon logo "P".

You can also open the Phoscon App by typing in the IP in the browsers address line.

**Comment by My-userid** [comment]
So.. today I tried again from scratch. Took a backup from my old 2.0.7 installation,. Upgraded the 2.0.7 install on windows to 2.11.05, shutdown the raspberry and moved the USB stick to the Windows machine.

This time it worked :) After restoring the backup its all up and running again.
Now I just have to find out how to run the deconz app as a service.
