### ISSUE TITLE
Problem with Ikea tradfri controller and gledopto ww-cw led strip controller 

### ISSUE THREAD

**Issue by xircom** [dresden-elektronik/phoscon-app-beta#320]
Hello, I have a tradfri controller from Ikea (attached photo), and a cw/ww led strip controller from gledopto (attached photo), the controller is configured in a group , the up and down button are configured for dimming lights ( this function is not working , when I press dimming up or dimming down the light turns on or off, not dimming even if I do a long press), the left and right button are configured for change the color temperature and this function is not working , but with the web contro I am able to dim the lights and also change the color temperature .
![Screenshot_20210201-105738](https://user-images.githubusercontent.com/18197508/106527056-edcfb400-64e6-11eb-9bd8-6a188bab0a9c.jpg)

![Screenshot_20210201-105849](https://user-images.githubusercontent.com/18197508/106527079-f9bb7600-64e6-11eb-8548-72af6a485eb6.jpg)

**Comment by xircom** [comment]
Hello, any news about this?

**Comment by xircom** [comment]
??

**Comment by SEK-DE** [comment]
@xircom Its kind of hard to test because we just have this one user request about those devices. We´re on it.
