### ISSUE TITLE
"Add New Sensor" button only visable in landscape mode on moble phone browser

### ISSUE THREAD

**Issue by morfei1** [dresden-elektronik/phoscon-app-beta#323]
If you try to add or re-pair a sensor via mobile phone browser the button is not visable on the bottom of the page, unless you rotate the phone in landscape mode. Then, the button is visable but the added sensors become unvisable.

Button not visable:
![1](https://user-images.githubusercontent.com/62436468/106944649-86587500-672f-11eb-834f-93ad392ad60c.jpg)

Button visable:
![2](https://user-images.githubusercontent.com/62436468/106944650-86f10b80-672f-11eb-8ca9-5c1b40b34832.jpg)

Regards!

**Comment by YKO-de** [comment]
The site is not yet optimised for mobile phones. Actually, the button should not be visible at all on mobile phones. However, we are currently revising the page.

**Comment by morfei1** [comment]
Then... please, if possible don't remove this "bug", it's actually a very convenient feature, if a device suddenly drops from the mesh.

regards!

**Comment by YKO-de** [comment]
Do not remove an error. I can manage that. ;)

**Comment by 7wells** [comment]
@YKO-de 
On my Samsung S7, neither in portrait nor in landscape mode, is it possible to create scenes. There is a picture shown with two hands and a circle, telling me to hold the mobile in landscape mode, but that does ot change anything. Is this related to the above topic?

**Comment by morfei1** [comment]
It's not possible to do that in a mobile device browser.

**Comment by 7wells** [comment]
@morfei1 @YKO-de
Why not? When I tell my mobile browser (Firefox) to use the desktop mode, other webpages switch to the desktop content (ok, sometimes difficult to read, as the text gets smaller, but it works). Any where exactly is the threshold for phoscon? The display size? Or is it complicated (if not impossible) on all mobile phones - but possible on tablets? Phoscon's settings should be available on all mobile devices. At least I find it more convenient than going to a PC or laptop just for the purpose of changing/adding something in phosco, but that's of course only my personal flavour. 😀
