### ISSUE TITLE
Heiman HS1CA-E Carbon Monoxide Detector not recognized

### ISSUE THREAD

**Issue by Fabfab60** [dresden-elektronik/phoscon-app-beta#324]
Hi,

it is my first post on Github so I hope I am at the right place.

I am facing difficulties to connect a Co monoxyde detector with a conbee 2 key.

It is not recognize by phoscon APP. 

Dear Phoscon team could you add support for HS1CA-E ?

Information on Conbee 2 key:

![Capture d’écran 2021-02-06 à 17 35 38](https://user-images.githubusercontent.com/78656561/107124869-7ca54d80-68a6-11eb-90ec-679ff557ce28.png)

There was an issue previously closed and it looks like it is still not implemented in current version

[https://github.com/dresden-elektronik/phoscon-app-beta/issues/117](url)

Thanks for your help

**Comment by Fabfab60** [comment]
After working around my problem it looks like detection is now OK:

![Capture d’écran 2021-02-07 à 16 41 01](https://user-images.githubusercontent.com/78656561/107151644-edf70600-6963-11eb-96c1-8754d850780a.png)

**Comment by YKO-de** [comment]
Can you tell me the modelid?

**Comment by Fabfab60** [comment]
modelid: COSensor-EM

**Comment by StephanStS** [comment]
@Fabfab60: Which product on the Heiman homepage (http://www.heimantech.com/product)?
Is is this: http://www.heimantech.com/product/?type=detail&id=4?

**Comment by Fabfab60** [comment]
@StephanStS : yes thats it .

I think I didn't wait enough during the adding process. It works fine

**Comment by StephanStS** [comment]
@Fabfab60: Also, I now see above that you already mentionen the HS1CA-E.

**Comment by Fabfab60** [comment]
close as problem resolved itself after waiting for full communication
