### ISSUE TITLE
Login Issue after Firmware-Update

### ISSUE THREAD

**Issue by Tobius69** [dresden-elektronik/phoscon-app-beta#326]
first - I am still a beginner.  I have installed on a PI3 the current Raspi, then Iobroker and the drivers for my CONBEE II. Have already learned in Phoscon an IKEA lamp and a switch. In the gateway I was offered a firmware update (I still had a firmware from 2019 on the stick). 

After updating the firmware and a restart now the error: 
I can only log in for a half second and then I am immediately logged out. Sometimes I come back to the setup menu and in the next moment I'm logged out again.

Several restarts or the use of another browser did not help. Clearing the browser cache does not work.
Then I installed the firmware deCONZ_ConBeeII_0x26650700.bin.GCF of 13-Sep-2020 in Windows - same error.
After that I tested again the older deCONZ_ConBeeII_0x264a0700.bin.GCF of 27-May-2019 - this one runs without errors.

**Comment by YKO-de** [comment]
After consultation, I would first recommend installing the latest version. This may already solve the problem.

**Comment by YKO-de** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian

**Comment by Tobius69** [comment]
As I wrote, I did just that. I was offered this update (V. 26660700) in Phoscon, from there I did the update. 
After the restart the error came and I could not log in permanently.

The update was the problem!

![image](https://user-images.githubusercontent.com/78813674/107676589-99bc9080-6c99-11eb-8f78-8d9de0be05b3.png)
