### ISSUE TITLE
Add AMIKO HOME (Feibit) Sensors/Switches/Plugins

### ISSUE THREAD

**Issue by Satmedia** [dresden-elektronik/phoscon-app-beta#327]
Hi, I'm using deconz with conbee II stick on raspbee with feibit plugins/switches/sensors and aqara sensor. 
From feibit I only can connect the plugins/switches in phoscon app. the sensors not. Sensors are shown in deconz gui, but not connected.
Plugins and Switches are connected as lights in phoscon app. It are working in phoscon app and in iobroker with deconz adapter. BUT it are not working as a router. In deconz it are shown with yellow color (for router) but it do not connect to near sensors/other routers. 
All plugins/switches are connected in the right place for first time.

Shown in phoscon app as lights:
Plugins:  Feibit Inc co. | FB56+SKT13KJ1.6
Switches: Feibit Inc co. | FB56+ZSW1GKJ2.3

Importeur/Products:
https://www.amikohome.com/smart-home 

![Bild_2021-02-10_151217](https://user-images.githubusercontent.com/78860688/107521051-5f2bf880-6bb2-11eb-8bc7-e0895276d08a.png)

Schalter_aussen_lift has good connection.
Schalter_bad_1Stock is only 5m away from schalter_aussen_lift but it is connected to conbee stick.
Schalter_Poolpumpe is 10m away from schalter_aussen_lift and sometimes connected sometimes not. if connected then direct to the stick.

**Comment by Satmedia** [comment]
AMIKO SMART TEMPERATURE & HUMIDITY SENSOR shown in Deconz GUI but not in Phoscon APP

https://www.amikohome.com/product/85-smart-home-temperature-humidity-sensor

![Bild_2021-02-11_090954](https://user-images.githubusercontent.com/78860688/107613583-ea57cd80-6c48-11eb-90ed-fda9dd19635f.png)

![Bild_2021-02-11_091408](https://user-images.githubusercontent.com/78860688/107613881-81248a00-6c49-11eb-97b6-02843471ea13.png)

![Bild_2021-02-11_091449](https://user-images.githubusercontent.com/78860688/107613926-9a2d3b00-6c49-11eb-87ff-31fceb00fc22.png)

![Bild_2021-02-11_091528](https://user-images.githubusercontent.com/78860688/107613969-b16c2880-6c49-11eb-9346-79311297d935.png)

![Bild_2021-02-11_091612](https://user-images.githubusercontent.com/78860688/107614034-cba60680-6c49-11eb-9db8-39d8ca6378f3.png)

**Comment by Satmedia** [comment]
AMIKO SMART WATER LEAKAGE SENSOR shown in Deconz GUI and in Phoscon APP as a Light but do not trasmit sensor values.

https://www.amikohome.com/product/85-smart-home-temperature-humidity-sensor

![Bild_2021-02-11_091844](https://user-images.githubusercontent.com/78860688/107614209-263f6280-6c4a-11eb-85a0-2537885d232a.png)

![Bild_2021-02-11_092538](https://user-images.githubusercontent.com/78860688/107614699-1d02c580-6c4b-11eb-9b77-2e87c3b9fc2d.png)

![Bild_2021-02-11_092635](https://user-images.githubusercontent.com/78860688/107614771-3efc4800-6c4b-11eb-9022-48112ee9627e.png)

**Comment by Satmedia** [comment]
AMIKO SMART DOOR SENSOR shown in Deconz GUI but not in Phoscon APP

https://www.amikohome.com/product/83-smart-home-door-sensor

![Bild_2021-02-11_093142](https://user-images.githubusercontent.com/78860688/107615158-f5f8c380-6c4b-11eb-98d8-1de873118b03.png)

![Bild_2021-02-11_093237](https://user-images.githubusercontent.com/78860688/107615235-16c11900-6c4c-11eb-864c-a5b898bf5e71.png)

![Bild_2021-02-11_093514](https://user-images.githubusercontent.com/78860688/107615420-74556580-6c4c-11eb-98a5-3ddae4830ef9.png)
Zone Status Value change from Open/Close

**Comment by YKO-de** [comment]
Presumably the devices are not yet whitelisted in the Phoscon app. I'll take a look at it.

**Comment by YKO-de** [comment]
It looks like your devices are not yet correctly supported in deCONZ either. At least they are not listed. Therefore, please open the issue once at https://github.com/dresden-elektronik/deconz-rest-plugin.

**Comment by Satmedia** [comment]
ok, thanks.
I do now.
