### ISSUE TITLE
Support of Tuya Zigbee signal repeater 3.0

### ISSUE THREAD

**Issue by Fabfab60** [dresden-elektronik/phoscon-app-beta#330]
Hi all,

I need to extend my zigbee network and I found this device:
![image](https://user-images.githubusercontent.com/78656561/107767830-e6ee4000-6d35-11eb-8fed-9b322f7cb2fe.png)

Zigbee ID: "TS0207"; "_TZ3000_m0vaazab"

[https://zigbee.blakadder.com/Tuya_TS0207.html](url)

 I tried to add it but I can't see anything in Phoscon app

Does Conbee 2 support it ?

**Comment by YKO-de** [comment]
I recommend the amplifier from Ikea https://www.ikea.com/de/de/p/tradfri-signalverstaerker-10400408/
