### ISSUE TITLE
Tradfri dimmer wireless can be used

### ISSUE THREAD

**Issue by j3r3m067** [dresden-elektronik/phoscon-app-beta#331]
## Describe the question or issue you are having
Hello,
I would like to know why I can't link my TRÅDFRI wireless dimmer to a group on light.
How I was progressed : 
on phoscon web app: on my group "bedroom" > "edit" > "switch editor" > "link switch"" and my dimmer is missing
AND 
on homebridge this dimmer appears as like a button with 4 "buttons": On / Off / Dim Up / Dim Down

My conbee II version:
Version 2.09.03 / 23/12/2020
Firmware 26660700

## Screenshot
The dimmer type
![image](https://user-images.githubusercontent.com/2004347/107822101-d6fa4e80-6d7d-11eb-89a6-c274e7243586.png)

The config in phoscon app

![](https://user-images.githubusercontent.com/2004347/107818461-ef676a80-6d77-11eb-9258-1265f43df1a2.png)

## Environment
 - Host system: Raspberry Pi
 - Running method: Raspbian
 - Firmware version: 26660700
 - deCONZ version:  2.09.03
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? no

**Comment by j3r3m067** [comment]
Any idea??

**Comment by YKO-de** [comment]
As the switch leads to some issues, we do not support this function on the unit.
