### ISSUE TITLE
Add support for JUNG Friends of Hue wall switch (4 channel)

### ISSUE THREAD

**Issue by glenn--** [dresden-elektronik/phoscon-app-beta#332]
Device is described here: https://www.jung.de/10245/produkte/technik/friends-of-hue-funk-wandsender/

Thanks alot.

**Comment by YKO-de** [comment]
This switch should work. Can you see it in the deconz?

**Comment by mannes** [comment]
I use Home Assistant with the deCONZ plugin.

I have this device paired within the phoscon app and it works for controlling lights when configured through the phoscon app.
However there doesn't seem te be any deconz_event going to home assistant for this switch. (other switches do get events in HA). Is there anything i can do to get events for this button in HA?
