### ISSUE TITLE
Suggestion: Temperature / Humidity history in phoscon app

### ISSUE THREAD

**Issue by jeatrexs** [dresden-elektronik/phoscon-app-beta#333]
Hi,

i'm using a raspbee2 to connect some xiaomi aqara temperature and humidity sensors with my raspberry pi.
In the phoscon app i can see the sensors and their current values, but why can't I access / view the history of the temperature and humidity in there? Maybe with the possibility to export it as Excel- or Csv-File? 

This would be very nice, since i know that the history of the temperature and humidity are stored somewhere, because it is possible to view it via the "Eve"-App.

Or am I just blind and did not find the place to view this in the phoscon app?

Regards
Patrick

**Comment by letszb** [comment]
Unfortunately, the Phoscon app cannot currently work with history data. This is not planned directly either. Maybe it will come in the distant future.

You seem to be using iOS. You can use the Phoscon image incl. homebridge-hue and thus have besides deCONZ and the Phosocn app also HomeKit available. This also makes the Eve app and the history data of all common sensors available.

https://www.phoscon.de/en/raspbee2/sdcard

**Comment by jeatrexs** [comment]
Thanks for your response.
I see. Yes I am using iOS. I have already installed phoscon/deconz on my pi together with homebridge and homebridge-hue. I know that it is possible with Eve app. But my thought that it would be great, not to be dependent of the app, or to export the data from the computer instead. But now i know. Thanks!

So the history data is stored on the sensor device itself?

**Comment by YKO-de** [comment]
No. The sensor only has an ACTUAL state. For a history, the values would have to be saved in the database.
