### ISSUE TITLE
Incorrect device type

### ISSUE THREAD

**Issue by Mr-REM-Esq** [dresden-elektronik/phoscon-app-beta#334]
This is how the device is displayed in Phoscon
<img width="827" alt="LUMI" src="https://user-images.githubusercontent.com/42520242/107969414-cbe33080-6fc0-11eb-990d-64acb9b7bef4.png">

This is how the device looks in reality
<img width="596" alt="Socket" src="https://user-images.githubusercontent.com/42520242/107969607-0a78eb00-6fc1-11eb-9e01-0f02af268662.png">

Is it light?

**Comment by YKO-de** [comment]
Sockets are always displayed under lights.
