### ISSUE TITLE
add support for Heiman Carbon Monoxide Sensor

### ISSUE THREAD

**Issue by GitHubxtsnl** [dresden-elektronik/phoscon-app-beta#336]
please add support for this device:
I'm running Home Assistant 2021.2.3
deCONZ 6.7.0
ConBee II 26660700 / 2.09.03 / 12/23/2020

I've got this CO device from Ali:
https://www.aliexpress.com/item/4001031100655.html?spm=a2g0s.9042311.0.0.6da04c4dTuT4Ht

![](https://user-images.githubusercontent.com/43134674/107992415-f2ad6100-6fd8-11eb-9f32-ef28ba599b42.png)

![](https://user-images.githubusercontent.com/43134674/107992443-035dd700-6fd9-11eb-8fbc-8749f7349f4d.png)

![](https://user-images.githubusercontent.com/43134674/107992474-14a6e380-6fd9-11eb-9e21-3ab2bb942186.png)

**Comment by YKO-de** [comment]
This sensor should at least be visible via the beta url. Can you check it out under "phoscon.de/pwabeta"?
