### ISSUE TITLE
Status: not reachable vs. "reachable": true

### ISSUE THREAD

**Issue by jan666** [dresden-elektronik/phoscon-app-beta#337]
Version: 2.09.03 / 23.12.2020
Firmware: 26680700

I have a SONOFF door sensor. Phoscon says its not reachable, API reports rechable: true.

<img width="592" alt="SONOFF" src="https://user-images.githubusercontent.com/869857/108468485-1b5a8280-7287-11eb-9df1-2924f3247ccd.png">

```
{
  "config": {
    "battery": 77,
    "enrolled": 1,
    "on": true,
    "pending": [],
    "reachable": true
  },
  "ep": 1,
  "etag": "473418d70186d7ecef47022076c047e1",
  "lastseen": "2021-02-19T06:18Z",
  "manufacturername": "eWeLink",
  "modelid": "DS01",
  "name": "Garagentorsensor",
  "state": {
    "lastupdated": "2021-02-14T13:06:35.554",
    "lowbattery": false,
    "open": false,
    "tampered": false
  },
  "swversion": "20191107",
  "type": "ZHAOpenClose",
  "uniqueid": "00:12:4b:00:1f:90:15:c4-01-0500"
}
```

**Comment by jan666** [comment]
Still the same.

`Version: 2.11.05 / 9.5.2021`

**Comment by YKO-de** [comment]
Can you tell me if the API shows correctly when the sensor is open?

**Comment by jan666** [comment]
When opened everything is back to normal. After some time it's again reachable: true but "nicht erreichbar" in Phoscon
