### ISSUE TITLE
Philips hue tap switch

### ISSUE THREAD

**Issue by 4d1in3** [dresden-elektronik/phoscon-app-beta#338]
Im unable to pair a new hue tap switch. Ui asks me to press button two for 10 secs, but nothing happens after that. Can anyone guide me on how to progress? Also few youtube video shows hue app requires u to press button 3 instead of 2.

**Comment by YKO-de** [comment]
Yes. He has a new modelid. And it's not listed yet. But it should work with the next update of the app.

Otherwise, try phoscon.de/pwabeta. You should already be able to see the device there.
