### ISSUE TITLE
Increase maximum timer duration

### ISSUE THREAD

**Issue by paradoxon82** [dresden-elektronik/phoscon-app-beta#34]
Hi,

could the maximum duration of timers and alarms be increased to 24 hours?
I wanted to control a chrismas tree illumination to be active for the whole evening. Currently the maximum seems to be 60 mins.

![timer](https://user-images.githubusercontent.com/6465164/49147545-47d00000-f305-11e8-9730-f6be36bcafac.png)

**Comment by manup** [comment]
Hi I've put it on the list of discussion, we're gonna refactor the schedules section for the next stable release might be a good time to enhance the settings.

**Comment by paradoxon82** [comment]
Thank you for this feedback.
Which brings me to this question:
I tried setting the timer yesterday and waited for the switch on.
But it never happened.
What ways do I have to debug this?
