### ISSUE TITLE
Button "delete scene" is hidden with css

### ISSUE THREAD

**Issue by IT-Economy** [dresden-elektronik/phoscon-app-beta#342]
Currently it is not possible to delete a scene. The link "delete scene" on the top right of the scene edit page is hidden with css.

Was this done intentionally? If I remove the "display:none" attribute with chrome developer tools, I can delete the scene just fine.

![image](https://user-images.githubusercontent.com/77216388/109348595-07a9b000-7875-11eb-8185-3d191cc09c63.png)

**Comment by YKO-de** [comment]
The button is only visible when you are in the lower area on the tap Settings.
![image](https://user-images.githubusercontent.com/55535297/110311041-889a4180-8003-11eb-8133-eddcf8eca600.png)
