### ISSUE TITLE
Disable lights flashing after adding new devices

### ISSUE THREAD

**Issue by IT-Economy** [dresden-elektronik/phoscon-app-beta#343]
Is it possible to disable all the lights in all the rooms flashing after (re-)pairing of a sensor or switch?

We have several AirBnB guest rooms with hue lights and the flashing is extremely distracting for the guests and I often wake up my girlfriend when I try to add new devices at night.

Ideally there would be a setting in Phoscon to disable the flashing lights. The feedback on the screen is enough to see when the sensor was added successfully.

Thanks!

**Comment by YKO-de** [comment]
This is to be switched off in perspective anyway. I will take care of it. Thank you for the advice.

**Comment by YKO-de** [comment]
This is to be switched off in perspective anyway. I will take care of it. Thank you for the advice.

**Comment by martin82private** [comment]
> This is to be switched off in perspective anyway. I will take care of it. Thank you for the advice.

Hi thanks for the info, but in the meantime would it be possible to deactivate in eg a config file?

**Comment by YKO-de** [comment]
Unfortunately not.

**Comment by IT-Economy** [comment]
The issue is still present, right?

How is phoscon developed right now?

**Comment by YKO-de** [comment]
We intend to deactivate the flashing in general. But it will take some time. We have to adjust a few things for this.

**Comment by IT-Economy** [comment]
My girlfriend just woke up again because I re-paired a sensor...

Why is this issue closed? It is not yet fixed.

Is Phoscon still under development? Uncommenting a line should not take more than four month, right?

Can you open source the project, so that I can fix these issues (and mobile layout issues) myself? Thanks!

**Comment by nikbyte** [comment]
The same issue. Please add switch or disable this nice "feature".
