### ISSUE TITLE
[DEVICE REQUEST] RGBGenie ZB-5028 RGBW ZB 3.0 Remote

### ISSUE THREAD

**Issue by cbrightly** [dresden-elektronik/phoscon-app-beta#344]
Is it possible to add support for the RGBGenie ZB-5028 to Phoscon? It seems to work in deConz already but I do not see it exposed via Phoscon.

![image](https://user-images.githubusercontent.com/2245021/109399754-be0fa280-7912-11eb-907b-7bfa41c14450.jpeg)
![image](https://user-images.githubusercontent.com/2245021/109399756-c36ced00-7912-11eb-931b-14e7355ab718.jpeg)
![image](https://user-images.githubusercontent.com/2245021/109399869-63c31180-7913-11eb-9509-e5ba5fbe043c.jpeg)
![image](https://user-images.githubusercontent.com/2245021/109399772-ccf65500-7912-11eb-844a-da3360bbd669.jpeg)

Thanks in advance for your assistance!

**Comment by YKO-de** [comment]
It should already work in the beta (phoscon.de/pwabeta). Please feel free to test it. In the stable it will come with the next update.

**Comment by cbrightly** [comment]
It does now appear both under ‘switches’ and ‘switches (beta)’, with the only difference being that the latter exposes the battery percentage to the webpage as well. Will this work with the switch editor?

**Comment by cbrightly** [comment]
Is this device ready for integration into the stable build?

**Comment by YKO-de** [comment]
It should be included in the next stable version.
