### ISSUE TITLE
Set power-on values when electricity comes on?

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#345]
*** Sorry, I see no template in GitHub app for this "issue".

Hello!

How is it possible to set power-on values for e.g. an OSRAM Smart+ E27 Tunable White light bulb (or any other light)? I would like to have the bulb start with 2700K temperature and 10% brightness when powering it (I mean electricity on).

Thanks for sharing your thoughts.

PS:
Since I use the GitHub app, I do not see any template for a new issue. I very politely ask the maintainers and developers to not close my question just because no template is used. If you can provide another forum to ask this, please let me know the link. Thanks a lot for your patience and support.

**Comment by YKO-de** [comment]
Currently, this is not possible via the Phoscon app. But I will take it up. Thank you for the tip.

**Comment by 7wells** [comment]
@YKO-de
Is it possible in deconz? If yes, where would users have to look? I remember that this topic was addressed but cannot find it anymore.

**Comment by 7wells** [comment]
@YKO-de 
See also there (maybe that already helps?):
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/102

**Comment by SEK-DE** [comment]
@7wells still a problem for you? It wont get solved in a minute, i am just asking.

**Comment by 7wells** [comment]
No problem for me anymore - please see linked issue thread.

So I assume that this here can be closed, right?
