### ISSUE TITLE
iPhone app does not connect permanently to phoscon / conbee II

### ISSUE THREAD

**Issue by manoloxxl** [dresden-elektronik/phoscon-app-beta#347]
Hi,

I'm using the app "Sleep Cycle". The app can connect to philips hue and is able to power on lamps during wake up. When i used the Hue Gateway everything was working fine. But i switched to phoscon / conbee II.

Now, with phoscon, the app is not able to contact the selected bulb / the phoscon. 

The app can only connect to the devices when i activate "connect apps" in phoscon. Only during this 60 seconds the app is able to show and use the hue devices. 

As i'm not pretty sure if its a sleep cycle or a phoscon issue, i started here first as the was working fine with the hue gateway.

Has anybody an idea? Is there a way to "open" the phoscon permanently for that app?

Best Regards
Manuel

**Comment by manoloxxl** [comment]
Nobody?

**Comment by SEK-DE** [comment]
@manoloxxl Phoscon works on principle without cloud, which means that that cloud based services, as your app, could not get connected. Its not our point to work with cloud based devices and applications. It´s not excluded that support for the app will come in future updates, but not that quick, as there are very few requests for it at the moment.
