### ISSUE TITLE
Xiaomi Multisensor not registered properly in Phoscon since 2.09.03

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/phoscon-app-beta#348]
The one that I didn't remove and readd, looks like this in phoscon:

![image](https://user-images.githubusercontent.com/13660621/110128453-189f7780-7dc7-11eb-9b46-5c184e678188.png)

- Host system: PC (NUC with PVE)
- Running method: Home Assistent deCONZ Add-on
- Firmware version: (26670700)
- deCONZ version: (2.09.03)
- Device: ConBee II
- Do you use an USB extension cable: yes
- Is there any other USB or serial devices connected to the host system? AEOTEC Gen5 z-wave

I have added them before upgrading to 2.09.03. They showed up as Multipurpose Sensor, and I just added 'Livingroom' in front of it.
I have two of these. As I had a minor zigbee breakdown, I had to remove one of them from the net, and readd it.
It shows up in deconz.
After readding it, it shows up in deconz as TS0201, and also in HomeAssistant (as TS0201)

From deconz:
![image](https://user-images.githubusercontent.com/13660621/110128162-c5c5c000-7dc6-11eb-9102-9e9b6b1917a0.png)

![image](https://user-images.githubusercontent.com/13660621/110128197-cf4f2800-7dc6-11eb-9f0b-c5f9e7cc2954.png)

![image](https://user-images.githubusercontent.com/13660621/110128314-f0177d80-7dc6-11eb-9cce-2cae96ad076f.png)

![image](https://user-images.githubusercontent.com/13660621/110128343-f7d72200-7dc6-11eb-938d-dc850a6b21ef.png)

![image](https://user-images.githubusercontent.com/13660621/110128429-0f160f80-7dc7-11eb-9d34-23f3d9af27ba.png)

**Comment by rugarci** [comment]
This sensor seems to be the same as the one from Tuya. Other issue is open for it: #263

**Comment by fribse** [comment]
@rugarci You are absolutely right! I'll close this one and update the other.
