### ISSUE TITLE
Switch - "Change to basic functions"

### ISSUE THREAD

**Issue by drosenberg-gh** [dresden-elektronik/phoscon-app-beta#349]
![image](https://user-images.githubusercontent.com/69093391/110211142-34f0f200-7e63-11eb-857c-ca89724a96bb.png)

The Phoscon app documentation indicates that there should be an option to create zigbee groups for switches. How can I enable the "Change to basic functions" option for my swithces?

**Comment by YKO-de** [comment]
Currently, this does not work. However, we are working on a concept to be able to support this function again.

**Comment by drosenberg-gh** [comment]
> Currently, this does not work. However, we are working on a concept to be able to support this function again.

Do you have a timeline of when this function will return? Being able to use switch groups was one of the main reasons I purchased a Conbee II.

**Comment by YKO-de** [comment]
That will take time. The problem is that this switch function is not compatible with the switch editor.
