### ISSUE TITLE
[DEVICE REQUEST] eWeLink ZB 3.0 Hygrometer with LCD Screen

### ISSUE THREAD

**Issue by cbrightly** [dresden-elektronik/phoscon-app-beta#350]
I’d like to request support be added for the following device:

[Ewelink ZigBee LCD Digital Hygrometer](https://www.aliexpress.com/store/product/Ewelink-ZigBee-LCD-Digital-Thermometer-Hygrometer-Temperature-Sensor-Humidity-Meter-Detector-Indoor-Gauge-Instruments-Smart-Home/910342166_1005001884101869.html) 

![781DE203-D7A4-4B9B-8625-B02EC106BD24](https://user-images.githubusercontent.com/2245021/110320663-a73a1180-7fde-11eb-97ad-db9ebc8ec7b4.png)

![66ED1648-1DBF-4D71-A1A4-25C52CA4B88E](https://user-images.githubusercontent.com/2245021/110320662-a6a17b00-7fde-11eb-9279-5375d4a0cbe9.png)

![ECCE0A08-89DC-4DD5-8EDC-3D7435744230](https://user-images.githubusercontent.com/2245021/110320664-a73a1180-7fde-11eb-9621-0e838b49bc35.png)

![CEB14863-040D-4BDB-B80D-4E1EDD179727](https://user-images.githubusercontent.com/2245021/110320666-a7d2a800-7fde-11eb-91cc-bf93234935f9.png)

![03EE7C29-1C27-4C78-AE04-739B84B4F951](https://user-images.githubusercontent.com/2245021/110320669-a7d2a800-7fde-11eb-9c5a-f8094231bcd1.png)

Thanks you in advance for your assistance!

**Comment by YKO-de** [comment]
As it seems to me, the device is not yet officially supported in the deCONZ either and thus not delivered to me upstairs. Please open an issue at https://github.com/dresden-elektronik/deconz-rest-plugin.
