### ISSUE TITLE
Ikea trådfri does not respond to Phoscon app controls

### ISSUE THREAD

**Issue by palbyh** [dresden-elektronik/phoscon-app-beta#351]
Ikea light does not respond to "ON" command in Phoscon App. The only action that is working is "All lights off".
Control of light is ok in deConz GUI cluster info tab. 

In the browser console (F12) I get this message;
DevTools failed to load SourceMap: Could not load content for http://192.168.0.206:8080/pwa/library/js/interact.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Is this caused by java/browser/deConz instalation, or is it a common problem?

I have tried different deCons version (up to 2.09.03) , installed with or witout admin priviledges, and same problem is present.

Win 10 pro, Conbee ll (FW 26680700)

**Comment by YKO-de** [comment]
It is probably actually the lamp itself and has nothing to do with the error message. We sometimes have problems with IKEA lamps. But we are working on it.
