### ISSUE TITLE
Prioritization of motion sensor routines

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#353]
The way the Phoscon app handles manual inputs that clash with automatic sensor routines needs to be addressed. Example:

> You setup a motion sensor routine to automatically turn on a given light with 50% brightness when motion is detected. 
> 
> The user subsequently uses a voice command to bring the brightness up to 100%.
> 
> However, after the motion sensor's cool down period another motion-instance is triggered, which in turn automatically sets  the brightness back down to 50%.

Shouldn't the Phoscon app in such cases be able to detect the user's manual change and overwrite/stop the motion sensor routine until the light is manually turned off again?

Besides manual changes made through a voice command this also applies to Zigbee devices like these in-wall and cord dimmers:

[cable dimmer example](https://www.shada.nl/de/node/5290)
[in-wall dimmer](https://www.ecodim.nl/eco-dim07-zigbee-basic.html)

Those devices currently only show up as dimmable lights in Phoscon. The physical switch itself isn't listed in Phoscon and thus can't be defined as a manual overwrite when setting up motion sensor routines. If you change the brightness with the physical dial, the motion sensor routine just automatically overwrites this change again. That's not how it should work, right?!

**Comment by tomillr** [comment]
Maybe a practical suggestion on how this could be handled better is in order:

1. If a manual change in the brightness of a light is detected (by a voice command or a physical dimmer switch), the motion sensor routine should be disabled until the light is manually turned off again.

2. If a light is manually turned on, this should overwrite the motion sensor routine until the light is manually turned off.

3. Once the light is manually turned off, the motion sensor routine should be on a cool down timer of x-seconds. That way, you would be able to manually turn off a light and leave the room without having the motion sensor routine automatically turn on the light again.

**Comment by YKO-de** [comment]
I understand what your problem is, but it's not that easy to fix. As it can cause problems for other users who would not expect this behavior. We can't save the manual change either. It could also have someone a second motion detector with 100%, which then does not want so. You could at most integrate a switch that interrupts the sensor routine when pressed.

To the flush-mounted. The app maps a device as it comes in. And the flush-mounted device comes in as a lamp. What do you mean by a flush-mounted physical switch?

**Comment by tomillr** [comment]
> What do you mean by a flush-mounted physical switch?

I'm referring to devices like an in-wall or in-cable dimmer :

![image](https://user-images.githubusercontent.com/1507977/112323509-23587880-8cb2-11eb-8946-a1ee501dd469.jpg)
![h972bbfc5dee84b63818dba40b429f1efq](https://user-images.githubusercontent.com/1507977/112323696-513dbd00-8cb2-11eb-90e0-7f27c6b8f08b.jpg)

The are Zigbee-based and show up, like you've mentioned, as a regular lamp with adjustable brightness. But those device also feature a physical switch or dial to manually controll the light without going through a Zigbee connection.

A device like this is basically useless when combined with a motion sensor. 

I'd like to use a motion sensor to setup a night light. During the night, whenever the motion sensor detects someone in the hallway, it should turn on the lights with a low brightness setting of 25%. But during this time, any input made via the physical switch would automatically get overwritten by the motion sensor routine.
