### ISSUE TITLE
Hue motion sensor: no temperature and lux readings

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#354]
I've just installed a new Philips Hue motion sensor on my system. While the sensor showed up right away, the reading for the temperature und lux values don't seem to come though:

![Bildschirmfoto 2021-03-10 um 17 39 35](https://user-images.githubusercontent.com/1507977/110664375-a1ebeb00-81c7-11eb-9df2-d681858e3457.png)

**Comment by YKO-de** [comment]
Do you have the possibility to look into the API to see if anything arrives at all? Maybe teach it again?
