### ISSUE TITLE
Cannot add TRADFRI remote control to group, wrong language for OK button and, and does not work at all

### ISSUE THREAD

**Issue by IgnacioHR** [dresden-elektronik/phoscon-app-beta#355]
## Describe the bug
I'm trying to use two switches to turn on/off (toggle) a group of lights but cannot finish the process to add the second switch.

## Steps to reproduce the behavior
Click on + link switch on left dash UP
Select the second switch form the available ones
Clink on the center button, click on Next
Select on/off in actions, then toggle.
See the final screen capture

![Phoscon_App](https://user-images.githubusercontent.com/16385090/110239336-b1a8cc80-7f46-11eb-94cb-89d636326b27.jpg)

## Expected behavior
The switch shall be assigned to the group

## Screenshots

Inline when relevant

## Environment

![Gateway version](https://user-images.githubusercontent.com/16385090/110239418-0f3d1900-7f47-11eb-908b-2418c01df27a.jpg)

![deCONZ version](https://user-images.githubusercontent.com/16385090/110239429-1d8b3500-7f47-11eb-9166-d5087b67f91e.jpg)

- Host system: Raspberry Pi
- Running method: Raspbian - Debian (I installed the image from SD card and updated the OS)
- Firmware version: (26690700)
- deCONZ version: (2.10.2-beta)
- Device: RaspBee II

## deCONZ Logs

![Exclorer console](https://user-images.githubusercontent.com/16385090/110239555-dd788200-7f47-11eb-9d6b-199f69224355.jpg)

## Additional context

Testes with chrome Versión 88.0.4324.192 (Build oficial) (x86_64)

**Comment by Mimiix** [comment]
Yes sir!

**Comment by YKO-de** [comment]
Languages are being revised. It could be that an error has crept in. Thank you for pointing this out.

**Comment by YKO-de** [comment]
On the second problem. Does the error also occur with other combinations? For example, the right button - toggle. Or can it then be added.

**Comment by IgnacioHR** [comment]
Thank you for testing!

@YKO-de I've successfully linked other buttons

![Phoscon_App](https://user-images.githubusercontent.com/16385090/111981160-97a2e880-8b07-11eb-83c4-f493de32d421.jpg)

but the On/Off button

**Comment by YKO-de** [comment]
Unfortunately, I don't really know what the problem could be. Since it also works for me. Does the button in the middle deliver an event?
