### ISSUE TITLE
[DEVICE REQUEST] ZBT-Remote-ALL-RGBW

### ISSUE THREAD

**Issue by ApolloSK** [dresden-elektronik/phoscon-app-beta#356]
I’d like to request support be added for the following device:

ZBT-Remote-ALL-RGBW

![image](https://user-images.githubusercontent.com/43525358/111701805-9fc70380-883b-11eb-89f1-9a62a37eadb1.png)

![image](https://user-images.githubusercontent.com/43525358/111701908-cb49ee00-883b-11eb-9422-05637a98a7d6.png)

![image](https://user-images.githubusercontent.com/43525358/111701959-dd2b9100-883b-11eb-82e2-4e309bec9b7e.png)

Thanks!

**Comment by YKO-de** [comment]
Could you try phoscon.com/pwabeta? It should already be there.

**Comment by ApolloSK** [comment]
I can only connet the switch to/with phoscon
![image](https://user-images.githubusercontent.com/43525358/112006298-e3638b00-8b23-11eb-9694-9ee2b31d601b.png)

But there ist no option do connect the switch with bulbs or to configure the switch
![image](https://user-images.githubusercontent.com/43525358/112006570-1efe5500-8b24-11eb-8ec5-ce53cf6643be.png)

**Comment by killwack** [comment]
Hi. I would like to have this implemented too. This to simplify the usage in using phoscon, and not iobroker or other tools.
This remote is one of the most flexible remotes currently available ...

Would be happy if it would be fully supported and migrated to phoscon. BR

**Comment by YKO-de** [comment]
Can anyone tell me the events of the individual buttons on the switch?

**Comment by ApolloSK** [comment]
yes, i can - i hope this is what you need

1002	power         Short release	Button 1
2002	dimup         Short release	Button 2
2001	dimup         Hold             	Button 2
2003	dimup         Long release	Button 2
3002	dimdown    Short release	Button 3
3001	dimdown    Hold	                Button 3
3003	dimdown    Long release	Button 3
4002	warm          Short release	Button 4
5002	cool            Short release	Button 5
6002	colorloop   Short release	        Button 6
scenes
7002	worklight    Short release	Button 7
8002	sunset        Short release	        Button 8
9002	party          Short release	        Button 9
10002	nightlight   Short release	Button 10
11002	campfire     Short release	Button 11
12002	romance     Short release	Button 12

**Comment by YKO-de** [comment]
I took another closer look at the remote control. Unfortunately, we do not yet have a solution for these special models with colour wheels to support them in the switch editor. Maybe this will be possible in the future, but currently we only support standard remote controls without a colour wheel.
