### ISSUE TITLE
Daylight Sensor

### ISSUE THREAD

**Issue by franck57fr** [dresden-elektronik/phoscon-app-beta#357]
Hello,
first of all apologize for this automatic translation from french to english :-(
I have a problem with the daylight sensor.
In fact, I have a delay of 1 hour in total compared to the real time of sunset.
In Phoscon my location is Europe / Paris.
And when I look at this place:
http: // LOCAL_IP: 8484 / api / API_KEY / sensors / 1 /
I have the following output:
`
{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"H:I:D:D:E:N-","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":false,"daylight":true,"lastupdated":"2021-03-18T17:05:25.164","status":180,"sunrise":"2021-03-18T05:45:29","sunset":"2021-03-18T17:47:20"},"swversion":"1.0","type":"Daylight","uniqueid":"H:I:D:D:E:N-01"}
`
Is there a solution to fix this.
I use the key (conbee2) on RPI3B + with jeedom.

Thank you for you precious help.

Edit.
I specify that I use this sensor to activate motion detection at nightfall.
And the fact that the lights come on when it's still daylight is (in my case) disturbing

Franck

**Comment by ChrisHae** [comment]
Currently there is a workaround for this:
Use the app "Hue Essentials" for Android and connect to the ConBee2 with it.
There you have the option to set the sunrise and sunset offset

> In Hue Essentials go to the devices tab, select your bridge, tap Location. Here you can configure a time offset

**Comment by franck57fr** [comment]
> Currently there is a workaround for this:
> Use the app "Hue Essentials" for Android and connect to the ConBee2 with it.
> There you have the option to set the sunrise and sunset offset
> 
> > In Hue Essentials go to the devices tab, select your bridge, tap Location. Here you can configure a time offset

That's rock :-)
Thanks' a lot

**Comment by 7wells** [comment]
@YKO-de and other developers:
Do you see a way to include the possibility in phoscon to set offsets for sunrise and sunset? I mean in general, for all kinds of daylight sensors, including the virtual phoscon daylight sensor. Thanks for your kind consideration.

**Comment by YKO-de** [comment]
A sensor control system is currently being developed.

**Comment by 7wells** [comment]
@franck57fr 
Hello! Is this topic still relevant for you?

**Comment by SEK-DE** [comment]
@7wells @franck57fr we are still on it atm. There will be some huge updates this year for the web-app, and one will hopefully contain a better usage for the daylight sensor. We have a eye on this. I will close this down until the update will release or someone else has some issues with that.
