### ISSUE TITLE
Motion sensor and switch

### ISSUE THREAD

**Issue by franck57fr** [dresden-elektronik/phoscon-app-beta#358]
Hello,
first of all apologize for this automatic translation from french to english :-(

I use this function:
Motion detector and switch.
https://phoscon.de/en/app/doc#group-edit-sensors-example-motion-switch-en

It works well. indeed if I am detected and I press the switch, the detector (automatic Off function) is deactivated.
My concern is that I have a switch which is remote.
This switch is located before the motion detector.
It would be interesting if the detector (function off) is also deactivated if I press the switch before being detected. And that it returns to its automatic detection function when I press the switch OFF again.

I hope to have been clear ?

Regards,
Franck

**Comment by SEK-DE** [comment]
Sorry for the delayed feedback, we have a increased volume of support requests since weeks.
I don´t get the following part from your massage:
