### ISSUE TITLE
Aqara motion sensor: no motion

### ISSUE THREAD

**Issue by boehser-enkel** [dresden-elektronik/phoscon-app-beta#359]
Hi there,

i have some aqara motion sensor which all work fine.
Now i have a new one which doesn't show any motion function in Phoscon:
![grafik](https://user-images.githubusercontent.com/59539881/111946851-9d370900-8adc-11eb-9ee9-b9548b576789.png)
(connected via "other")

When i connect it via type: dresden electronic i shows motion:
![grafik](https://user-images.githubusercontent.com/59539881/111946994-d7a0a600-8adc-11eb-98a3-4c57e61eb866.png)

Software:
![grafik](https://user-images.githubusercontent.com/59539881/111947012-ebe4a300-8adc-11eb-8303-8d16ca771186.png)

**Comment by YKO-de** [comment]
Can you tell me the modelid?

**Comment by boehser-enkel** [comment]
Where do i find it?

**Comment by YKO-de** [comment]
In the deCONZ. 
1 - Sensor selection
2 - Click on Basic Cluster
3 - Click on Cluster Info at the bottom (it should be in the line).

![image](https://user-images.githubusercontent.com/55535297/111976475-f49ba000-8b01-11eb-8ac2-4194cfda4648.png)

**Comment by boehser-enkel** [comment]
I have only Phoscon available at the moment. I can't see it there?

**Comment by YKO-de** [comment]
Now yes. phoscon.de/pwabeta -> side menu Help -> API Information -> Switches -> Search switches in list

![image](https://user-images.githubusercontent.com/55535297/116867339-3cd3d500-ac0d-11eb-82ac-aa32cc2532d2.png)
