### ISSUE TITLE
Xiaomi Mijia Zigbee 3.0 Smart Home Light Sensor parring fails in phoscon 

### ISSUE THREAD

**Issue by goegsig** [dresden-elektronik/phoscon-app-beta#361]
When i try to add a new sensor it just times out. 
![billede](https://user-images.githubusercontent.com/7282538/112271707-8bd83300-8c7b-11eb-880b-859daebc968d.png)

it appears in deCONZ, but it is not working 
![billede](https://user-images.githubusercontent.com/7282538/112271583-6814ed00-8c7b-11eb-8f8f-28aa35c148f8.png)

Iam using the deCONZ add-on in Home Assistent and it is this version 
![billede](https://user-images.githubusercontent.com/7282538/112271911-ce017480-8c7b-11eb-86ee-f0258769d032.png)

It looks like these issue 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2380
https://github.com/dresden-elektronik/phoscon-app-beta/issues/166

**Comment by goegsig** [comment]
![billede](https://user-images.githubusercontent.com/7282538/112297767-8e945180-8c96-11eb-89fa-c637f821f9ef.png)


![billede](https://user-images.githubusercontent.com/7282538/112297754-89cf9d80-8c96-11eb-8f9e-b367892a861b.png)
![billede](https://user-images.githubusercontent.com/7282538/112297800-97852300-8c96-11eb-97ea-760429c4af55.png)
![billede](https://user-images.githubusercontent.com/7282538/112297822-9d7b0400-8c96-11eb-8be4-84f90916707b.png)

**Comment by tellerbop** [comment]
I have the exact same issue with controller firmware 260B0500

**Comment by YKO-de** [comment]
Can you try phoscon.de/pwabeta?

**Comment by stefanmechelen** [comment]
I tried that, doesn't solve it. Any solution for this coming up?

**Comment by MasterMik** [comment]
Same problem here with the Mi light detection sensor.

**Comment by YKO-de** [comment]
It works for me under the beta. Possibly update the deCONZ version again. 
![image](https://user-images.githubusercontent.com/55535297/118463341-f186ef80-b6ff-11eb-8969-56d53efbbda1.png)

**Comment by MasterMik** [comment]
@YKO-de 
Danke, hat geklappt.

**Comment by stefanmechelen** [comment]
I'm having problems updating. Script runs. It's flashing.

Yet I still get in the app: 2.06.00 / 15-11-2020 - 266B0700

But I choose deCONZ_ConBeeII_0x266b0700.bin.GCF, which is from april 29, 2021 (can't do that with a beta by the way, that sees downloading error)

Log: https://controlc.com/31f1bc71

What am I doing wrong?
