### ISSUE TITLE
Issue with LIDL Livarno Lux light strip

### ISSUE THREAD

**Issue by jokerigno** [dresden-elektronik/phoscon-app-beta#362]
Hi,

based on this pull request #4541 attributes hue, sat, and effect have been removed for LIDL Livarno Lux lights.

Now in Phoscon I only see color temperature (while back there was also slide for RGB colors).

**Comment by youdots** [comment]
Same issue for me, and this also broke the functionality of the light in Homebridge-Hue.

**Comment by youdots** [comment]
I‘ve successfully reverted to deCONZ v2.9.3 via dpkg, which successfully restored all functionality of the lightstrip, incl. my Home Automations.

**Comment by jokerigno** [comment]
I opened #4539 in API repository  but then moved here because I thought it was a phoscon issue. @Mimiix what's the best way to proceed? Can we move this issue or reopen the old one?

**Comment by Mimiix** [comment]
But i am not sure if it's the API or PHoscon. As the API seemed to work fine.

**Comment by youdots** [comment]
I think it is the API, because I'm controlling my lightstrip via Homebridge-Hue and Apple Home.

After updating to deCONZ v2.10.4 the light was reported as incompatible in Apple Home and Homebridge reported errors reading the effects, hue and sat parameters.

**Comment by Mimiix** [comment]
Ah i wasnt aware of the PR that changed the working of the light strip.

I'll re-open the old issue.

**Comment by LeoeLeoeL** [comment]
Same issue with Livarno E27, E14 and GU10.

**Comment by youdots** [comment]
If I followed the conversations in the deCONZ repo correctly, a future beta will include https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4780 that should fix it. (Just referencing this.)

**Comment by LeoeLeoeL** [comment]
I installed 2.11.1.
It seems to work again in HA. Now entity icons are in RGB according the lamp colour.
But phoscon doesn't show the colour bars.

**Comment by YKO-de** [comment]
What does the API say about the attributes of the light?
