### ISSUE TITLE
Add more possibilities (e.g. calling scenes) when long-pressing a switch button

### ISSUE THREAD

**Issue by 7wells** [dresden-elektronik/phoscon-app-beta#363]
Hello!

Would you please consider adding more possibilities (e.g. calling scenes) when long-pressing a switch button? I have here an Osram Smart+ 4-buttons switch. I can set for each button to call a scene (e.g. a different light temperature or a brighter/darker scene), and I can also set for each button another activity when long-pressing the button, but currently, there are only these two possibilities (besides 'no action'):
> Scene dimming up
> Scene dimming down

Why not offer the same possibilities as for short-pressing the buttons? See my screenshot for illustration. Short-press offers more options tan long-press. Is this related to this specific Osram switch or like this for any switch? Could it be changed? Thanks for your kind consideration.

![set_scenes_to_switches](https://i.imgur.com/tPmh1m2.png)

**Comment by YKO-de** [comment]
We think about it. Thank you for the advice.
