### ISSUE TITLE
OSRAM Smart+ Flex 3P Multicolor LED RGBW - how to set white?

### ISSUE THREAD

**Issue by Biggiz** [dresden-elektronik/phoscon-app-beta#364]
This LED stripe is an RGBW stripe. It is shown in the phoscon app but I can only change the RGB color. 
How to change it to white? How to use the white LED?

**Comment by 7wells** [comment]
When you click on "Color temperature", you can pull the right slider down to white:
![1](https://user-images.githubusercontent.com/65889763/116226844-c5f19480-a753-11eb-953b-9824fa816f27.png)
![2](https://user-images.githubusercontent.com/65889763/116226859-c8ec8500-a753-11eb-8ff1-4aa921dbc8cd.png)
Does this work for you?

**Comment by YKO-de** [comment]
Answer from 7wells is correct.
