### ISSUE TITLE
[DEVICE REQUEST] Integration request for RGBGenie  ZB-5004

### ISSUE THREAD

**Issue by tarasfilonenko** [dresden-elektronik/phoscon-app-beta#365]
Could this RGBGenie remote be added in, please?

https://rgbgenie.com/?product=rgbgenie-4-zone-2-scene-remote-zigbee it looks very similar to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2648 but after I paired it with DECONZ I can see " No button map for: RGBgenie ZB-5004, broadcast to: 0x5803, endpoint: 0x04, cluster: ONOFF (0x0006), command: ON (0x01), payload: None, zclSeq: 120" in the log
<img width="1285" alt="Screen Shot 2021-03-25 at 8 14 47 pm" src="https://user-images.githubusercontent.com/1563235/112448794-e02c0180-8da6-11eb-94e1-7374ac2c2dab.png">

Thanks!

<img width="317" alt="Screen Shot 2021-03-25 at 8 05 23 pm" src="https://user-images.githubusercontent.com/1563235/112447508-8119bd00-8da5-11eb-8863-0170e228fbf0.png">
<img width="528" alt="Screen Shot 2021-03-25 at 8 05 02 pm" src="https://user-images.githubusercontent.com/1563235/112447518-837c1700-8da5-11eb-98b1-3bfad0ab2d49.png">
<img width="511" alt="Screen Shot 2021-03-25 at 8 12 24 pm" src="https://user-images.githubusercontent.com/1563235/112448409-790e4d00-8da6-11eb-9bad-c4d0c9f4224c.png">

**Comment by YKO-de** [comment]
Please ask this question in https://github.com/dresden-elektronik/deconz-rest-plugin.
