### ISSUE TITLE
A timer with "group off" function and no fading time still dims down instead of just turning the lights off

### ISSUE THREAD

**Issue by nimric** [dresden-elektronik/phoscon-app-beta#366]
I created a timer which turns off my lights at 2 o'clock in the morning without a fading time using the "group off" function. Therfore I expect it to behave like a press of the Off-button. However, if I turn the lights on the next day the brightness has changed to a very small value which does not happen when I use the On/Off-button.

**Comment by YKO-de** [comment]
The transitiontime must be set to 0. This prevents the lamps from being dimmed, which is to blame for the low brightness the next morning.

**Comment by nimric** [comment]
The fading time is set to "None". The schedule is simply created wrong in deCONZ by Phoscon, since the body of the command is
```
"body": {
    "bri": 0,
    "on": false,
    "transitiontime": 0
}
```
instead of just
```
"body": {
    "on": false
}
```
