### ISSUE TITLE
[Feature Request] Google Assistant support

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#368]
Similar to the existing integration with Amazon Alexa, I'd love to see support for the Google Assistant implemented as well. 

Don't really want to install yet another tool or software (like HA for example) just to be able to control my Zigbee devices through the Google Assistant on my phone or the Google/Hest Home smart speaker.

**Comment by YKO-de** [comment]
Currently it is not planned. But we will include it in the future planning of the app.
