### ISSUE TITLE
[Device request] Paulmann urail zigbee controller

### ISSUE THREAD

**Issue by 0rsa** [dresden-elektronik/phoscon-app-beta#369]
https://en.paulmann.com/indoor-lighting/smart-home/zigbee/controlling/smart-home-zigbee-urail-dim-switch-white-max.-400w-on-off-dimming/50051

Device recognized with Conbee II but I need to force reading attributes to get right/disabled values
Also, I cannot control it using Conbee WebUI, it works with GUI using "Move to level with on/off), it doesn't work using "Move to level"

![paulmann5](https://user-images.githubusercontent.com/769750/112993212-3f07c700-9169-11eb-9c1d-bd5249084de3.png)

![paulmann1](https://user-images.githubusercontent.com/769750/112992911-ec2e0f80-9168-11eb-92e0-fb998187c650.png)
![paulmann4](https://user-images.githubusercontent.com/769750/112992934-f18b5a00-9168-11eb-84f8-91413ac6b02f.png)
![paulmann2](https://user-images.githubusercontent.com/769750/112992920-edf7d300-9168-11eb-95dc-dfae6c80cf34.png)
![paulmann3](https://user-images.githubusercontent.com/769750/112992968-fbad5880-9168-11eb-8561-867b5d73c373.png)

**Comment by YKO-de** [comment]
Please open this issue under deconz-rest-plugin. Thank you
