### ISSUE TITLE
Centralite 3328-C Motion Sensor

### ISSUE THREAD

**Issue by that1guy** [dresden-elektronik/phoscon-app-beta#37]
Looking for any tips to get these motion sensors to work..

Just bought a few of [these motion sensors](https://www.amazon.com/Centralite-Motion-Sensor-SmartThings-platforms/dp/B0713STYJQ) thinking they would work with my ConBee USB stick + RasPi + Hass.io + [DeCONZ Hassio Add-on](https://github.com/marthoc/hassio-addons).  

When pairing the `Centralite 3328-c` with Phoscon I do get a green light on the device indicating things are paired, but then it just times out here after 3 min. 

![image](https://user-images.githubusercontent.com/1218940/50537283-77477780-0b12-11e9-928d-476a28225f18.png)

**Comment by manup** [comment]
Currently the Centralite 3328-c sensor isn't supported.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#supported-sensors

There is ongoing work on the Centralite Motion-Sensor-A, I'm not sure if this is another one?

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/881

If this is another model, if possible please provide some details as described in the Wiki:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support

**Comment by that1guy** [comment]
I'm not sure if my `Centralite 3328-c` completely different sensor `Centralite Motion-Sensor-A`.  In your [screenshots](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Request-Device-Support#screenshots) you're using another piece of software to look at all the device data.  What piece of software is that?  I only have Phoscon UI.

**Comment by manup** [comment]
This is the software deCONZ which is running in the background. Phoscon App is the web-based frontend for it.

How are you running the system, is this on a Raspberry Pi with the official sd-card image?

**Comment by that1guy** [comment]
I'm running ConBee USB stick + RasPi + Hass.io + [DeCONZ Hassio Add-on](https://github.com/marthoc/hassio-addons).  The DeCONZ Hassio Add-on runs the software in a docker container.

**Comment by manup** [comment]
In the docker version there is currently no gui available, since deCONZ is running in headless mode. 

The only way to get more data here is to enable logging as described on the readme: https://github.com/marthoc/docker-deconz#running-the-deconz-container

**Comment by DrJeff** [comment]
Did you ever get the Centralite motions working?
