### ISSUE TITLE
Transition time is set after light setting (on, brightness)

### ISSUE THREAD

**Issue by boehser-enkel** [dresden-elektronik/phoscon-app-beta#370]
Hi,

i want to use transition time, but i have to create 2 scenes:

    1. set transition time, turn on light, set brightness to 1%
    2. set brightness to 100%

If i set everything at once (turn on, brightness to 100%, set transition time) it turns on instantly to 100%. 
Last thought was a problem with the ikea tradfri #197 , but this happens also with normal tradfri and osram bulbs.

It seems that the transition is set after the bulbs (on, brightness) are set: https://pastebin.com/sg3qfHX2
Deconz: 2.09.03, homebridge-hue (newest)

greetz
boehser enkel

**Comment by YKO-de** [comment]
I'm looking at it. Thanks for the tip
