### ISSUE TITLE
Sorting functions and info in device overviews

### ISSUE THREAD

**Issue by Pedder007** [dresden-elektronik/phoscon-app-beta#371]
Hi, would be great if the sorting functionalitiy (up/down arrows in the column headers) for the devices-views, would also be made available in the lights view. Phoscon should also keep the last choosen sorting of the columns in all views.
I guess the device and the sensor IDs are also in the background. Thus why not showing them in addition?
Could support in case of error-detection.

Thanks a lot :-)

**Comment by YKO-de** [comment]
I will take the hint with me. Thank you
