### ISSUE TITLE
Firmeware Verison 00000000

### ISSUE THREAD

**Issue by rtaucher** [dresden-elektronik/phoscon-app-beta#372]
hello!

latest version of phoscon not working anymore....

system: nuc, proxmox vm with debian
working for 1-2 days without problems, after that: no light,... reachable and firmeware version at 00000000
restart of vm -> everything ok

![conbee2](https://user-images.githubusercontent.com/82334386/114316219-e76f4100-9b02-11eb-9119-8df51f8542cc.png)

**Comment by YKO-de** [comment]
Can you please have a look under phoscon.de/pwabeta -> side menu help -> API information. You should be able to read "fwversion" directly in the first view. Are there only zeros there?
