### ISSUE TITLE
Tuya Multisensor still not visible in Phoscon (shows up in deconz and HA) 

### ISSUE THREAD

**Issue by fribse** [dresden-elektronik/phoscon-app-beta#373]
## Describe the bug

I have two Tuya Multipurpose sensor's added to the environment.
Back when I got them they were added without problems, and showed up nicely in Phoscon.
Then I had to remove one and add it back to the zigbee, and at that point it didn't show up in Phoscon, though it does show in deconz.
The second on that was originally added still showed the old one with the right name and all.
With the later version, none of them shows up, not the 'old' multisensor either.

## Steps to reproduce the behavior

1. Get a [Tuya Multisensor](https://www.aliexpress.com/item/4000830582090.html?spm=a2g0s.9042311.0.0.27424c4d6mJ2X1)
2. Add it as zigbee device
3. It shows up in Deconz and Home Assistant
4. It does NOT show in Phoscon.

## Expected behavior

It should show up in Phoscon so it can be renamed and managed there.

## Screenshots

![image](https://user-images.githubusercontent.com/13660621/114453467-d7766080-9bd9-11eb-918f-882a06693918.png)
![image](https://user-images.githubusercontent.com/13660621/114454380-d98cef00-9bda-11eb-9b42-2fdbe276ddb4.png)
![image](https://user-images.githubusercontent.com/13660621/114454431-e578b100-9bda-11eb-8bff-9aae61e4d8a3.png)
![image](https://user-images.githubusercontent.com/13660621/114454456-ef021900-9bda-11eb-8a12-d59ccec4b313.png)
![image](https://user-images.githubusercontent.com/13660621/114454491-f75a5400-9bda-11eb-9a0b-61a9bbf83b86.png)

## Environment

 - Host system: NUC with PVE
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: (26670700)
 - deCONZ version: (2.10.04)
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? Yes, AEOTEC Z-wave stick

## Additional context

I also tried the phoscon beta, no change.

**Comment by rugarci** [comment]
Again?
Other issue is already open: #263

**Comment by fribse** [comment]
Sorry, I thought it was closed without being resolved
