### ISSUE TITLE
Yale Assure Lock in Phoscon

### ISSUE THREAD

**Issue by AntiqS** [dresden-elektronik/phoscon-app-beta#374]
Hi guys,

There was [a feature request](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3750) to add initial support for Yale Assure door lock into Deconz, it is in the Deconz current release now, is it possible to make it available in Phoscon?

**Comment by YKO-de** [comment]
Can you please try it once at phoscon.de/pwabeta. It should work there. The next stable will take a while, as we are currently restructuring.

**Comment by AntiqS** [comment]
Hi, I tried pwabeta multiple times but it fails on login.
I tried to plugin my Conbee2 stick into a different device (Win 10 or Ubuntu) but it's giving the same "Login failed" error when I type my password there.
