### ISSUE TITLE
Integrate double click (without double click event)

### ISSUE THREAD

**Issue by boehser-enkel** [dresden-elektronik/phoscon-app-beta#375]
Hey there,

is it possible to integrate a double click event for buttons which do not send a double click event (i.e. Ikea Tradfri Dimmer, Tradfri Remote, wireless Aqara wall switches).
For example when there are 2 single click events in 1 second it generates a double click.
I think zigbee2mqtt uses something like this

greetz
boehser enkel

**Comment by YKO-de** [comment]
No. That is not planned. We only use switches with the events that they themselves actually deliver.
