### ISSUE TITLE
Legrand wireless double switch

### ISSUE THREAD

**Issue by kurcsics** [dresden-elektronik/phoscon-app-beta#377]
**Legrand Double Switch** is recognized as a **Single Switch** and is **not listed in Switch-Editor**
![image](https://user-images.githubusercontent.com/46639875/115843206-dede0b00-a41e-11eb-84dc-e59d4165b7e8.png)
![image](https://user-images.githubusercontent.com/46639875/115843235-e69daf80-a41e-11eb-9577-a91787bafd35.png)

**Comment by YKO-de** [comment]
This is a generic switch icon for all switches that are not yet individually supported.

The switch is not yet supported by the switch editor, because I don't know the button events. Can you tell me the events of the individual buttons.

**Comment by kurcsics** [comment]
Hi,

Left down:
    short press:    1002
    long press:      1001
    after long press 1003
Left up:
    short press:    2002
    long press:      2001
    after long press 2003
right down:
    short press:    3002
    long press:      3001
    after long press 3003
right up:
    short press:    4002
    long press:      4001
    after long press 4003

**Comment by YKO-de** [comment]
Thank you very much. I will add it as soon as possible and then let you know again. If you could still test it then. That would be great. I'll let you know.

**Comment by YKO-de** [comment]
Under phoscon.de/pwabeta it should theoretically work now.

**Comment by kurcsics** [comment]
Hi!
Thanks!
almost perfect, key assign should be modified according to the attached image.
![Uploading F8EE2B1C-494B-41F2-AE8E-8B15DCA52AFF.jpeg…]()

**Comment by SEK-DE** [comment]
We are working on a generic switch integration. That will fix the position of the keys. Please be patient, it will take some time.

**Comment by kurcsics** [comment]
Thanks!
