### ISSUE TITLE
Aquara temp and door sensor pairing works on windows but not on Raspberry anymore

### ISSUE THREAD

**Issue by mhin76** [dresden-elektronik/phoscon-app-beta#378]
I had a large zigbee network with deCONZ v2.11.0 beta on Raspberry buster version, with ConBee II Firmware 0x26670700. My network included IKEA lamp, switches, plugs, Xiaomi light sensor, windows sensor, motion sensors, plugs, lights and Blitzwolf plugs. All worked nicely until I upgraded deCONZ to version v2.11.1 beta. After restarting deCONZ I noticed that my last added door sensor disappeared from phoscon. I tried to add it again but it did not find it, but on deCONZ UI I saw new device added with the short 0x ID. After googling someone suggested to reset my gateway. After that all devices of course disappeared. I tried to pair them again. Worked fine with IKEA lamp, Xiaomi motion sensor but no success on the temperature nor door sensors. Phoscon does not show any new sensors, but in deCONZ I see again new devices with short 0x ID. But also no cluster info.
Now I just downloaded fresh image with latest deCONZ beta version and buster Raspberry. No success on any pairing (also not in deCONZ with ConBee firmware 0x26670700. I downgraded to 0x264a0700. Tried to pair again the motion, door and temp sensors. This time none of them appeared in phoscon but two appeared in deCONZ. I have attached the printscreen and the log.
I have no idea what is going on. My ConBee II is pluged in directly on my Raspberry III. Before I used an USB extensions cable, but also there no luck.
Any suggestion I can try out?
[deCONZ debug Info and Info L2.txt](https://github.com/dresden-elektronik/phoscon-app-beta/files/6390069/deCONZ.debug.Info.and.Info.L2.txt)
![Screenshot deCONZ](https://user-images.githubusercontent.com/49210075/116368105-4a9dea80-a808-11eb-9a35-112a4c871730.jpg)

**Comment by mhin76** [comment]
Some more investigation. I reset my ConBee II again and plugged it in to my laptop running windows 10 and deCONZ v2.11.1. I flashed ConBee firmware to 0x26660700. Then (with log turned on) I have first tried to pair the Xiaomi door sensor, then the Xiaomi temperature sensor and last the motion sensor. Nothing in Phoscon and in deCONZ only the door and the motion sensor were added as new device but with short 0x ID. After that I have added a Xiaomi light without problem, came up in Phoscon and deCONZ right away. Interesting enough is that the motion sensor in deCONZ suddenly got a real name "Presence 2" and no more 0x9a1b anymore. Also in Phoscon it now shows up correctly and it works.
My takeaway: sensors are first added as unknown device and only after some time it reads additional info. Still issue:
1. my temperature sensors are not showing up anymore (they all worked before)
2. my door sensor shows up as unknown device in deCONZ and nothing in Phoscon.
[deCONZ debug Info L2 and Errors.txt](https://github.com/dresden-elektronik/phoscon-app-beta/files/6391609/deCONZ.debug.Info.L2.and.Errors.txt)
![2021-04-28 13_56_27-deCONZ - ConBee II (__ _COM8)](https://user-images.githubusercontent.com/49210075/116399785-9614c080-a829-11eb-84f2-f106b58460ec.png)

**Comment by mhin76** [comment]
Some more interesting findings (will document all, in case someone has similar issues). I have downgraded firmware to 0x26420700 and paired successfully an Aquara Multisensor (incl. pressure). I noticed that the LED blinked a lot brighter than on my other Aquara temperature sensor (which never showed low bat). So I switched battery and it successfully joined the network!! 
So I flashed my ConBee II again with 0x26670700 and trying pairing, and it worked too!
Seems that for joining the battery needs to be quite full!
And for what reason, now also the door sensor joined. I will now test it again on my Raspberry, but seemed mostly to have been a battery issue. I will keep this issue open to write down my results. Might be that it helps someone :)

**Comment by mhin76** [comment]
ok, ConBee II reset and plugged into my Raspberry III again. Searches for sensors but having same issues as before. Those that worked under windows still don't work under Raspberry. My deCONZ version is the same 2.11.1 (but beta). Some sensors get connected but stay with the short 0x ID and as unknown devices. And nothing in Phoscon.
Anyone has any idea? It all worked before and I did not change anything on hardware.

**Comment by mhin76** [comment]
found a nasty workaround. under windows I can add the devices perfectly, but under Raspberry it only loads to deCONZ with the short 0x ID but not to phoscon. Workaround: I add each device under windows, backup via Phoscon the setting, connect ConBee II to my Raspberry (now it shows up in Phoscon but not in deCONZ and does not work yet) and final step, I pair it again, which adds the device to the deCONZ.
Seems to work now bc all additional info about the device was saved in the backup.
Would still be great to find out why the Phoscon adding is not working under Raspberry.

**Comment by Smanar** [comment]
Your device is not correclty included, the FFFF, and as you said the Name.

But if it work on windows and not on the raspberry, for me the problem is hardware (power supply, USB3.0 or other perturbations)

You can too prevent the device going to sleep during the inclusion procedure with pressing shortly the button every 2s AFTER the inclusion procedure.

**Comment by mhin76** [comment]
Hi Smanar. some very positive updates. I have flashed the conbee with a quite early version from 2020 (0x26420700) and have reinstalled deCONZ on my raspberry incl. deleting the zll.db. I noticed that resetting the gateway does not delete the entries in the zll.db. Maybe that cause some issues as well. Now I was able to add already 10 devices!!! but only when the battery is new. It seems that the battery for pairing need more power than when it is running, so it was always short on power when it came on sending all the metadata. So far all fine. I will close this issue.

**Comment by mhin76** [comment]
well, I am getting from one issue to the next one. After successful pairing again few devices with a full battery I noticed no updates of the temperature. After reboot of my Raspberry and deCONZ I saw that all temperature sensors lost connection. Even when I click on such a sensor to send data, nothing arrives at deCONZ (monitoring the logging). Also I noticed that one device "T Büro" shows on the graph but is not in the Node List. Some very strange things are happening here, after one year all running very smoothly. I will further investigate. 
Printscreen of deCONZ with missing Node in the list.
![image](https://user-images.githubusercontent.com/49210075/116655015-9c6e7e00-a98a-11eb-9753-9ec7e009df21.png)
Printscreen of zll.db with the Node "T Büro" listed:
![image](https://user-images.githubusercontent.com/49210075/116655158-dfc8ec80-a98a-11eb-8255-dee22fa950c9.png)

**Comment by mhin76** [comment]
Update: I found a new firmware version 0x266B0700 (created yesterday) and flashed it successfully under windows. I reset it on Raspberry, deleted the zll.db and started adding some sensors. So far all good incl. recent data updates after restarting deCONZ. Crossing fingers!!

**Comment by mhin76** [comment]
Happy End After All!!! I have most of my devices connected again. 
![image](https://user-images.githubusercontent.com/49210075/116848969-0dfa3680-abee-11eb-97bb-6050cc7de936.png)

The one that caused the whole adventure (Aquara door sensor) still does not get properly connected, but very likely that it is somehow broken. Also with new battery I only get to the 0xXXXX ID in deCONZ but nothing else. Well, good to have a spare one.
Takeaway from this adventure (which might help others):
1. When pairing gets you only to the short 0xXXXX ID in deCONZ but nothing more, try with fresh battery
2. Try to pair several times. One of my sensor only paired after the 10th try
2. Reset your gateway only as LAST option! Once reset, also delete the zll.db, that is not resetted (at least not on my set-up)
3. Try different ConBee firmwares in case you have trouble reconnecting. I changed after all to 0x266B0700 (you can download the firmware from dresden elektronik page and flash e.g. via windows GCFFlasher)
4. Try maybe a different channel, I switched to 25, works fine with my WLAN on 11.
