### ISSUE TITLE
ROB_200-007-0 - 8 button switch not reflecting in Phoscon App

### ISSUE THREAD

**Issue by webnar** [dresden-elektronik/phoscon-app-beta#379]
Hi,
I have the 8 buttons (4 zones switch) from ROB. It is recognized correctly and I can see the 4 zones in Openhab.
But in the Phoscon App, it is showing as one button that is not assignable to any group.
In Phoscon App its:
Vendor Sunricher
Product Remote Controller
Version 2.2.3_r11

![image](https://user-images.githubusercontent.com/7816672/116538503-ebafa280-a8e7-11eb-8625-2dbfeceffc27.png)
![image](https://user-images.githubusercontent.com/7816672/116538589-03872680-a8e8-11eb-8f82-6b75cd108535.png)
![image](https://user-images.githubusercontent.com/7816672/116538642-1568c980-a8e8-11eb-9164-696ee4d979c5.png)
![image](https://user-images.githubusercontent.com/7816672/116538743-39c4a600-a8e8-11eb-99cf-c995e79f2f43.png)

**Comment by YKO-de** [comment]
This switch is only displayed generically by the Phoscon app and is not supported individually.

**Comment by webnar** [comment]
Can it be supported just as the other 8 button scene switches? It would be
very nice to be able to assign lights in Phoscon to the switch.

Op ma 3 mei 2021 11:53 schreef YKO-de ***@***.***>:

**Comment by YKO-de** [comment]
Do you mean in the switch editor? Can you tell me his button events? Of the individual buttons?

**Comment by webnar** [comment]
Hi sorry, never noticed the reply.

First button event:
short press: 1001
hold button: 1002
Long press: 1003

second button:
short press: 2001
hold button: 2002
Long press: 2003

third till the eight buttons:
short press: x001
hold button: x002
Long press: x003

hope this helps
