### ISSUE TITLE
Which Xiaomi Aqara motion sensor Supported?

### ISSUE THREAD

**Issue by that1guy** [dresden-elektronik/phoscon-app-beta#38]
In your [supported software documentation ](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#supported-sensors) it says you support `Xiaomi | Aqara motion sensor`.

When I google `Xiaomi Aqara motion sensor` I find the devices listed below.  Which one is the supported one?

- https://www.gearbest.com/alarm-systems/pp_659226.html
- https://www.gearbest.com/smart-home-controls/pp_009661787808.html

**Comment by StephanStS** [comment]
I have successfully added a Xiaomi cube sensor. Funny. Works fine.
@that1guy: If your issue is answered, pleas close it.
