### ISSUE TITLE
[Device Request] IKEA STYRBAR Remote Type E2001

### ISSUE THREAD

**Issue by zustellr** [dresden-elektronik/phoscon-app-beta#380]
Hi. I would like to request support for the new-ish Ikea Styrbar remote.

https://www.ikea.com/de/de/p/styrbar-fernbedienung-edelstahl-10435224/

![Styrbar-3](https://user-images.githubusercontent.com/7841068/116731889-97d9b200-a9ea-11eb-8d90-436da3b6a363.JPG)
![Styrbar-2](https://user-images.githubusercontent.com/7841068/116731893-990adf00-a9ea-11eb-91b8-d08bbb7e1fbc.JPG)
![Styrbar-1](https://user-images.githubusercontent.com/7841068/116731894-990adf00-a9ea-11eb-8256-bc4c1b71285d.JPG)

Apologies if this is the wrong forum or the wrong format. Please let me know if I can provide more info or help. I am generally only using the Phoscon-App, where I was unable to connect the device.

Thanks!

andreas.

**Comment by YKO-de** [comment]
Can you please try phoscon.de/pwabeta. It should work there. The next stable will take a while, as we are currently restructuring.

**Comment by zustellr** [comment]
Hi @YKO-de . That was one of the first things I tried. Didn't show up, unfortunately. No problem if it takes a while. Let me know if I can help.

**Comment by YKO-de** [comment]
Okay. Then I ask for a little patience. I ordered the device today. When it arrives, I can see what the problem might be.

**Comment by dutch-erik** [comment]
I bought the IKEA STYRBAR Remote N2 control couple of days ago, however Type is E2002 instead of E2001.
Does anyone know the differance and is it supported as well?

**Comment by creactiv** [comment]
Well, got that one too, and found out, that, after i upgraded to Firmware 26400500 for my Raspbee and Phoscon is now at version 2.13.01 / 6.10.2021, but if i get into switches and IKEA, i only see Tradfri; not Styrbar. If i use other, i will get a standard switch, where i am lost a bit, how to get this working. So, anyone can me point in the right direction, please?

When i enter it as other, i can tell it to use the light up for light up and power on, and the light down for lowering the light and power off, but it won't power off, if i use that one. Also, i am wondering how to use the switch light keys for selecting another light / light group in the same room

What did i miss?
Thanks in advance and best
