### ISSUE TITLE
Include additional conditions for routines

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#381]
I know that the REST API offers a load of additional conditions you can incorporate into a routine. It might be a useful addition to make some of those available through the Phoscon GUI.

In particular, I'd be in need of an "**only when light is off**" or "**only when light is set to brightness XY**" option.

Also, some sort of cool-down-timer (don't trigger routine for XY seconds again) would also be helpful.

**Comment by YKO-de** [comment]
Thank you for pointing this out. We'll talk about it in the developers' group.
