### ISSUE TITLE
GLEDOTPO Bug in light control of phoscon?

### ISSUE THREAD

**Issue by Maddinthebrain** [dresden-elektronik/phoscon-app-beta#384]
Hi, 
I'm using several types of GLEDOPTO LED-strip controllers. 
![image](https://user-images.githubusercontent.com/43421040/118179214-45aa7f00-b435-11eb-87a2-8be7f5025251.png)
![image](https://user-images.githubusercontent.com/43421040/118177580-2a3e7480-b433-11eb-9ef5-8f6f57da96fb.png)

Most works as expected. But when it comes to scenes or dimming with switches some weired things happen:

- when a scene is selected with a switch, the WW/CC light controller switches of the warm white channel completely and the cold white channel is put to very low dimming value. It does not care anything about what is programmed in the scene. In Phoscon the light seems to be off as the dimming slider is in the off position. 
- As in https://github.com/dresden-elektronik/phoscon-app-beta/issues/305#issuecomment-840782422 already discribed the dimming per switch does't poperly either. While pressing dim up or dim down nothing happens at the light, but in phoscon the dim slider goes into off possition and stays there until you move it to another position by mouse or finger tip. While moving it with mouse or finger the light dims up an down as expected. 

Both issues do not appear at other types of light controllers like ikea tradfri or innr.

If more infomartion is needes, please comment!

Thx

Martin

**Comment by YKO-de** [comment]
We have a light like that there now and will have a look at it. But it may take a while.

**Comment by SEK-DE** [comment]
@Maddinthebrain it seems  to be a firmware problem. We investigate. It is possible that there will come a firmware update, but we don´t know if this count for the older devices too.

**Comment by Maddinthebrain** [comment]
Well, I was exactly afraid of that. I hope there will be new firmware version. But I'm not very optimistic for old devices.
