### ISSUE TITLE
Missing Devices after upgrade

### ISSUE THREAD

**Issue by BrianOOh** [dresden-elektronik/phoscon-app-beta#385]
Hi, I'm having some problems after I ran updates which upgraded Phoscon (now 2.10.04) and the firmware of my Conbee2 (to 26660700) all running on a RPI3. I have HomeAssistant too (2021.1.5) that is running on a separate Debian machine.   I've "lost" an Xiaomi DoorSensor - which does not appear in Sensors as my other Xiaomi DoorSensor does, although it does show if I create a "Sensor Control Group" (both of the DoorSensors are visable and working in HASS).

I am also having problems with a 2 button light switch, that was working before the upgrade, but now doesn't seem to sync at all - and I've noticed that I have an "unknown device" that appears in HASS (within the Phoscon configuration), so I'm wondering if this is in fact my missing switch and how I may confirm that is the case (or what it is!)? 

Both issues occurred after the upgrade, so I'm assuming they are related.

Any help would be appreciated but I'm running headless, so I don't have deCONZ GUI.

**Comment by BrianOOh** [comment]
Hi... 
Over the past few days, I've tried repeatedly to reset the two devices but with no change.   
I read in the reply to  other issues (regarding upgrade/flash updates) that I shouldn't reset or rollback the changes - is that applicable here? I'm starting to consider resetting the gateway, or reinstalling - or is there a way to clear everything without doing that?

**Comment by letszb** [comment]
Can you try update the firmware manually to 26680700:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

These things are also important with regard to your problem, even if it has worked so far. 

Use the ConBee II on a USB extension. Especially when other USB 3.0 devices are connected. Their distance to the ConBee II is then crucial.

By using the Raspberry Pi, the original power supply is required to guarantee a stable gateway. Only this power supply delivers 5.1V and 2.5A (Raspberry Pi 3B+) respectively 3A (Raspberry Pi 4B). And it definitely has good quality.
https://www.raspberrypi.org/documentation/hardware/raspberrypi/power/README.md

**Comment by BrianOOh** [comment]
Thank you for the reply.

I usually have the Conbee2 on a 0.5m cable (located above the RPI - putting it at ~6ft) - which has worked for many months... but due this new problem, I'm currently using a 2m cable which allows me to locate it closer to the switch device causing me pain.

I'll check my logs for power issues and flash again later.... 

Many thanks.

**Comment by BrianOOh** [comment]
Thank you & OK.... I've flashed to 26680700 as suggested - but no changes on the issue (and everything else continues to work as expected).

Is it possible to remove devices and re-add them?

**Comment by BrianOOh** [comment]
I guess I'm left considering either a gatway restart and/or rebuild, unless there an option to list and remove device from deCONZ/Phoscon without a GUI?

**Comment by BrianOOh** [comment]
OK - rebuilt my PI and all is back and devices are being found/identified as expeccted.....
