### ISSUE TITLE
Ikea STYRBAR do not paired

### ISSUE THREAD

**Issue by nicolalandro** [dresden-elektronik/phoscon-app-beta#386]
As we can see at this [link](https://www.gitmemory.com/issue/dresden-elektronik/deconz-rest-plugin/4572/804398474) the deCONZ GUI show the device, but from Phoscon I cannot pair it.

When this new Ikea device will be implemented in phoscon?

**Comment by lawrencebensaid** [comment]
Any update on this?

**Comment by nicolalandro** [comment]
Up to now no one ask me anything, I try also with the deCONZ UI, I  see it but this view is a bit difficult, and I do not understand how to set up my device, is there some guide to use this instead of phoscon while the problem will be resolved?

**Comment by YKO-de** [comment]
Have you tried phoscon.de/pwabeta? The device should be visible there.

**Comment by nicolalandro** [comment]
If I access with this link direct the site seams does not work, there is any solution to access the pwabeta from HomeAssistant?

**Comment by YKO-de** [comment]
Maybe try this? phoscon.com/pwabeta/login.html#host/<local-ip-address>:<port>

**Comment by YKO-de** [comment]
Maybe try this? phoscon.de/pwabeta/login.html#host/&lt;local-ip-adress&gt;:&lt;port&gt;

**Comment by nicolalandro** [comment]
In that way I have (like the first) an error in the console that say "unautorized" and I see the phosco GW but the click does not have effect so I cannot login

**Comment by letszb** [comment]
Did you activate the port in the settings as describe here? Typical this is port 40850
https://github.com/home-assistant/addons/blob/master/deconz/DOCS.md#using-the-deconzphoscon-api-with-another-add-on

**Comment by nicolalandro** [comment]
I do it now, but the problem does not change, I also try to use http://<MI IP>:40850/pwa but it seams does not work. There is a way to use phoscon app starting from my IP? I think that the problem can be the CORS origin call.

**Comment by letszb** [comment]
You need to use it like this:
phoscon.de/pwabeta/login.html#host/IP:40850

**Comment by nicolalandro** [comment]
Yes that is the link that does not work.

**Comment by nicolalandro** [comment]
By enabling with a plugin CORS origin call It ask me the password but after I cannot login, also the IP showed under the phoscon gateway is not a local net ip

**Comment by letszb** [comment]
Can you try it in a new private browser tab. You need the IP from the host (Raspberry Pi), not the internal.

**Comment by nicolalandro** [comment]
![Schermata del 2021-05-17 13-25-45](https://user-images.githubusercontent.com/18419702/118481166-77f8fc80-b713-11eb-9ff6-e1217e1c9808.png)
This is what happen, I cannot click on the gateway

**Comment by MajestyZ** [comment]
Similar issue here. After a while (10 seconds or so), the above screen changes to a login screen and it asks me for a password, but when I use the Phoscon app password that is known to me (I use it all the time from deConz in Home Assistant), it gives me a 'Login failed'. Any clue? :)

**Comment by nicolalandro** [comment]
Ok I try to reinstall a clean version of Home Assistant and I arrive to PhosconBeta correctly, but I cannot see STYRBAR, so It is not visible yet, and also by searching it is not found. How can I procede @YKO-de ?

**Comment by SEK-DE** [comment]
@nicolalandro it works now in the pwa beta. Will be integratet in the next update.

**Comment by nicolalandro** [comment]
@SEK-DE  Today I re-tried to pair STYRBAR from PhosconBeta again
![image](https://user-images.githubusercontent.com/18419702/122984287-20e2e900-d39d-11eb-97a8-8500ecb735a0.png)
but unfortunatly whithout success
![image](https://user-images.githubusercontent.com/18419702/122985037-fe050480-d39d-11eb-9bad-365f03400534.png)

**Comment by SEK-DE** [comment]
@nicolalandro which deCONZ and Firmware is running?
And did you try it in the beta? http://phoscon.de/pwabeta

**Comment by nicolalandro** [comment]
@SEK-DE  Below is report the version of deCONZ and Firmware
![image](https://user-images.githubusercontent.com/18419702/123082974-e3736f80-d41f-11eb-9969-30173bf258b8.png)
Yes i used Phoscon beta
![image](https://user-images.githubusercontent.com/18419702/123082649-8c6d9a80-d41f-11eb-98a3-7441e43caa94.png)

**Comment by nicolalandro** [comment]
@SEK-DE I just updated the firmware
![image](https://user-images.githubusercontent.com/18419702/123098380-605b1500-d431-11eb-9141-b62e22a65c6f.png)
but STYRBAR continue to don't pair

**Comment by SEK-DE** [comment]
@nicolalandro i will discus this with YKO and give you feedback asap

**Comment by SEK-DE** [comment]
> @SEK-DE I just updated the firmware
> ![image](https://user-images.githubusercontent.com/18419702/123098380-605b1500-d431-11eb-9141-b62e22a65c6f.png)
> but STYRBAR continue to don't pair

Your firmware means "Not connected!" which means you can´t pair anything.
2 reasons for this at the moment: interferences with other devices like Router, Repeater, Dongles etc. or USB devices.
Second one is a error during the update procedure. Please check those and give me feedback.

**Comment by nicolalandro** [comment]
@SEK-DE 
Sorry I upload the wrong screen (before refresh after update procedure)
![image](https://user-images.githubusercontent.com/18419702/123293389-3c243480-d514-11eb-8931-658d9c8f2870.png)

**Comment by SEK-DE** [comment]
@nicolalandro thx for your cooperation. Now your ConBee II is running at a version from oktober 2k20. 
Here is an overview of all versions: http://deconz.dresden-elektronik.de/deconz-firmware/
Please make sure, that you run the latest Firmware Version 266b0700. 
In our Test-Setup we use the deCONZ 2.12.00 and the latest Fw. 
Sometimes it may take a while till our latest versions where integratet in HA. Acctually i don´t know the latest HA deCONZ version, is it 6.9.0? Sometimes you have to be patient in terms of a HA system or use a native system.

**Comment by MajestyZ** [comment]
I'm having the same problem where I still can't connect the Styrbar, even in Phoscon Beta. I don't have deconz 2.12.00 yet though. The latest version is 6.9.0 indeed. Firmware version 26660700. Hope a new version will soon be released, I want to connect my Styrbar :D.

**Comment by SEK-DE** [comment]
We still investigating here, so don´t worry. If you have the time and a SD card, use an image from our homepage (https://phoscon.de/en/conbee2/sdcard) and try if the Styrbar works for you without HA. That would be great for us, because actually we dont see any issues here in our setup 😅

**Comment by nicolalandro** [comment]
@SEK-DE,I installed the "Homebridge-hue + Raspbian Buster" (deCONZ: 2.12.00 Version: 5-2021 released: 25/5/2021) on new SD card. I tryed to pair Styrbar but it continue to doesn't work.
![image](https://user-images.githubusercontent.com/18419702/123488407-301d9d00-d610-11eb-9637-f478c2603d84.png)

**Comment by nicolalandro** [comment]
@SEK-DE After differents try, STYRBAR is now paired. It paired only after pairing another button.
![image](https://user-images.githubusercontent.com/18419702/123490237-f77fc280-d613-11eb-8a6d-1b00228b4f5e.png)
Unfortunately trying to re-pairing STYRBAR another time and it doesn't work. 
In the next days I will try to understand which is the condition when it pair.

PS. when STYRBAR was paired it, only one button worked.

**Comment by letszb** [comment]
> 
> 
> @SEK-DE,I installed the "Homebridge-hue + Raspbian Buster" (deCONZ: 2.12.00 Version: 5-2021 released: 25/5/2021) on new SD card. I tryed to pair Styrbar but it continue to doesn't work.
> ![image](https://user-images.githubusercontent.com/18419702/123488407-301d9d00-d610-11eb-9637-f478c2603d84.png)

It seems you are still at firmware 26660700. You should update [manually ](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually)with your SD card that includes the Phoscon image to 266b0700.

**Comment by nicolalandro** [comment]
@letszb I updated the firmware to the latest beta version available
![image](https://user-images.githubusercontent.com/18419702/123792238-b1ab4e80-d8e0-11eb-9fdc-ef54c55746ce.png)
Now STYRBAR is pair but I cannot assign the lateral buttons (circled in red in picture)
![image](https://user-images.githubusercontent.com/18419702/123792521-fe8f2500-d8e0-11eb-8253-ccf83e7e0c0d.png)

**Comment by nicolalandro** [comment]
@SEK-DE @letszb do you have any news? Do you need some more information?

**Comment by SEK-DE** [comment]
Please try it with 2.12.3 @nicolalandro 
we did it today and have no problems with Styrbar.

**Comment by nicolalandro** [comment]
I update to last version and it work! 
Thank you!
