### ISSUE TITLE
Password prompt after gateway reset

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#388]
I've noticed a couple of times, that the reset function in the Phoscon web app doesn't seem to work properly.

When you hit the "Reset gateway"-button and open up the web app again, you get prompted to enter the password and are not shown the usual setup wizard. 

However, the password prompt doesn't accept the previous password and I couldn't figure out what password you should enter at that point. The only way out of this it to hit the "reset password" link.

Maybe a caching problem with the browser?

![Bildschirmfoto 2021-05-21 um 10 17 54](https://user-images.githubusercontent.com/1507977/119105669-d842b380-ba1d-11eb-9e2b-b0575512c43c.png)

**Comment by SEK-DE** [comment]
It´s possible, that you have to clear the Cache and App-Data in your browser. Otherwise you try to log on to a data corpse which isnt aktiv anymore. We can´t do a automation for that.
