### ISSUE TITLE
[Device Request] Hue wall switch module.

### ISSUE THREAD

**Issue by apfelflo89** [dresden-elektronik/phoscon-app-beta#389]
Please implement the Hue wall switch module within the WebGUI, deconz support is already given. 

See: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4566#

Thank you

**Comment by SEK-DE** [comment]
We are on it. The switch is not so easy to get on the german market, but it´s on the way to us. Please be patient.

**Comment by apfelflo89** [comment]
There seems to be some improvements within the beta page. Now I can see at least the switches!

![image](https://user-images.githubusercontent.com/48082211/121898546-c8b84100-cd23-11eb-8f48-1412e2cf07fb.png)

**Comment by sladexos** [comment]
> There seems to be some improvements within the beta page. Now I can see at least the switches!
> 
> ![image](https://user-images.githubusercontent.com/48082211/121898546-c8b84100-cd23-11eb-8f48-1412e2cf07fb.png)

YES! But the link between Switches and Lights are not implemented in the beta. When I want add a switch to a Group, I see only the "notBetaSwitches". I hope we get a solution a.s.a.p.... I love my Conbee and the last problem in my smart home are the switches. I installed 6 Wall Switch Modules ("PushButton"), so the only thing that I missing is a way to use them. Hue Essentials has actually only implemented the wall switch module as a "SingleRocketPushButton". But they also work on more functionality.

So the only thing we can do Is waiting... :)

**Comment by SEK-DE** [comment]
A little update for you!
It works now in the pwa beta over the normal switch integration (no switch beta).
It comes in like this:
![Schalter 2](https://user-images.githubusercontent.com/80257288/122894679-b2c00700-d347-11eb-8efa-f0937af0e78d.PNG)
(Note: Signify is the new name of Philips Lightning) 


After that, you have to choose which installation is obstructed in your home (it´s absolutly important that you choose the CORRECT build! If you take another, it can cause various issues.)
![Auswahl](https://user-images.githubusercontent.com/80257288/122895202-2e21b880-d348-11eb-94ff-bdbfc1ed1121.PNG)


And finally you can edit the switches as you want:
![Editor](https://user-images.githubusercontent.com/80257288/122895242-3843b700-d348-11eb-938b-b509d93f2c9b.PNG)

Feel free for feedback 😃

**Comment by dieneuser** [comment]
I am desperately trying to pair the module. It worked for a short time. After deletion from GUI, pairing no longer works. 
How do I reset the module/switch correctly (factory reset)? Hold down the reset button for 10 seconds?
