### ISSUE TITLE
Bitron Switch AV2010/34 did not connect

### ISSUE THREAD

**Issue by pillemats** [dresden-elektronik/phoscon-app-beta#390]
Hi

I tried to connect the switch but it dont work.
Not in normal mode and not in beta mode

i am using conbee II stick with the following FW:

<img width="834" alt="Bildschirmfoto 2021-05-27 um 13 43 40" src="https://user-images.githubusercontent.com/26164977/119820262-91f3c580-bef1-11eb-8595-2db8655c69a8.png">

Is it possible to connect the switch?

**Comment by SEK-DE** [comment]
Do you see the device over deconz? If so, please send us a screenshot.

**Comment by pillemats** [comment]
No i Cant see it

**Comment by SEK-DE** [comment]
@pillemats So when you try to pair it, it must shown in deCONZ. Please take a look there.
Also try the beta please.
