### ISSUE TITLE
Backup restore not possible (deconz 2.12.0)

### ISSUE THREAD

**Issue by cracyfloyd** [dresden-elektronik/phoscon-app-beta#391]
In this version i cant restore a backup. Its failed.
With version 2.11.5 all works well.
Any solution for this?

**Comment by SEK-DE** [comment]
Please give me some further informations:

1. host system (Raspberry Pi / PC / NAS):
2. execution method (Raspbian / Ubuntu / Home Assistant deCONZ add-on / Marthoc Docker container / Windows / Virtual Machine):
3. Firmware version (format 26xxyy00):
4. device (ConBee I / ConBee II / RaspBee I / RaspBee II):
5. is a USB extension used?   (yes / no) - only relevant for ConBee I/II:
6. are other USB or serial devices connected to the host system? (yes / no) - If yes: Which ones?):
7. if Raspberry Pi: Which power supply is used? (original / manufacturer+model) Indication of volts and amps: (e.g. 5.0V, 1.0A):
8. if Raspberry Pi: On which image base is the system set up?: (Phoscon / Raspbian / Raspberry Pi OS / Home Assistant ...):

**Comment by cracyfloyd** [comment]
i ve tried on 2 systems.
1st Raspberry pi 4
and 2nd on docker container Marthoc (latest). (Unraid System) 
i use USB Conbee II
No other serial devices. the stick is the only one.
power supply is the original paspberry.
latest paspbian os i use.

**Comment by ChrisHae** [comment]
Can you please check something for me?
1. The output of `ls -l .local/share/dresden-elektronik/deCONZ/`
2. Start deCONZ in GUI mode and open Help/Debug View. Enable INFO and ERROR debug output. Then start a Backup operation in the phoscon app and post the output of the debug view.

**Comment by cracyfloyd** [comment]
Here the debug view:
17:10:55:764 UPNP socket not bound, state: 0
17:11:21:728 command queue EVENT_TIMEOUT, cmd: CMD_APS_DATA_REQ_2, seq: 172
17:11:49:692 New websocket 192.168.2.2:33588 (state: 3) 
17:11:55:624 Skip idle timer callback, too early: elapsed 1 msec
17:11:55:683 Device TTL 1478 s flags: 0x7
17:11:56:657 Bind response success for 0x588e81fffe3fe525 ep: 0x01 cluster: 0x0008
17:11:56:658 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0x588E81FFFE3FE525 (wait reading or unsupported)
17:11:56:739 Bind response success for 0x7cb03eaa0a02307a ep: 0x03 cluster: 0x0006
17:11:56:739 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x7CB03EAA0A02307A (seems to be active)
17:11:57:588 CTRL db store gui node 00:21:2e:ff:ff:04:f5:71
17:11:57:589 CTRL db store gui node 00:15:8d:00:02:57:b7:59
17:11:57:590 CTRL db store gui node 00:15:8d:00:03:19:a6:20
17:11:57:590 CTRL db store gui node 7c:b0:3e:aa:00:ae:0a:51
17:11:57:590 CTRL db store gui node 00:17:88:01:06:73:2e:1e
17:11:57:591 CTRL db store gui node 00:0b:57:ff:fe:96:52:92
17:11:57:591 CTRL db store gui node 7c:b0:3e:aa:0a:01:c7:83
17:11:57:591 CTRL db store gui node 7c:b0:3e:aa:0a:02:30:7a
17:11:57:592 CTRL db store gui node 7c:b0:3e:aa:00:ad:24:86
17:11:57:592 CTRL db store gui node d0:cf:5e:ff:fe:16:ed:4a
17:11:57:592 CTRL db store gui node cc:cc:cc:ff:fe:25:96:b5
17:11:57:593 CTRL db store gui node 00:15:8d:00:02:f8:d0:9e
17:11:57:593 CTRL db store gui node 00:15:8d:00:03:12:ed:07
17:11:57:593 CTRL db store gui node 58:8e:81:ff:fe:3f:e5:25
17:11:57:594 CTRL db store gui node 7c:b0:3e:aa:0a:02:15:08
17:11:57:594 CTRL db store gui node 00:15:8d:00:02:75:51:c9
17:11:57:595 CTRL db store gui node 7c:b0:3e:aa:0a:02:ea:2a
17:11:57:595 CTRL db store gui node 00:15:8d:00:05:79:de:8d
17:11:57:595 CTRL db store gui node 00:17:88:01:08:ba:01:05
17:11:57:596 CTRL db store gui node 00:17:88:01:04:a6:9c:c6
17:11:57:596 CTRL db store gui node 00:15:8d:00:04:45:1e:40
17:11:57:596 CTRL db store gui node 00:15:8d:00:03:57:ce:a1
17:11:57:597 CTRL db store gui node d0:cf:5e:ff:fe:13:c9:c4
17:11:57:597 CTRL db store gui node 00:15:8d:00:04:a9:71:27
17:11:57:597 CTRL db store gui node 00:15:8d:00:03:a4:6a:5c
17:11:57:598 CTRL db store gui node 00:15:8d:00:05:79:e2:d6
17:11:57:598 CTRL db store gui node 00:15:8d:00:04:45:1e:b7
17:11:57:598 CTRL db store gui node 00:15:8d:00:03:13:09:cc
17:11:57:599 CTRL db store gui node 00:15:8d:00:02:1a:3a:28
17:11:57:599 CTRL db store gui node 00:15:8d:00:03:9f:d0:80
17:11:57:599 CTRL db store gui node 00:15:8d:00:03:98:e1:2b
17:11:57:600 CTRL db store gui node 00:0d:6f:ff:fe:26:2c:ce
17:11:57:600 CTRL db store gui node 00:15:8d:00:04:13:dc:1d
17:11:57:601 CTRL db store gui node 00:15:8d:00:03:f1:b4:ad
17:11:57:601 CTRL db store gui node 00:15:8d:00:03:cb:2e:dd
17:11:57:601 CTRL db store gui node 00:15:8d:00:03:9f:d0:85
17:11:57:602 CTRL db store gui node 00:15:8d:00:03:12:ed:b8
17:11:57:602 CTRL db store gui node 00:15:8d:00:03:13:0b:01
17:11:57:603 CTRL db store gui node 00:17:88:01:06:34:8a:9c
17:11:57:603 CTRL db store gui node 00:17:88:01:04:cb:f7:31
17:11:57:604 CTRL db store gui node 00:15:8d:00:02:57:a7:3e
17:11:57:604 CTRL db store gui node 90:fd:9f:ff:fe:de:34:1f
17:11:57:604 CTRL db store gui node 00:15:8d:00:03:94:29:4b
17:11:57:673 saved node state in 0 ms
17:11:57:673 sync() in 0 ms
17:11:57:674 schedule 3 diff 22683, Di. Juni 1 23:30:00 2021
17:11:57:675 enqueue event config/localtime for /config/
17:11:57:675 Wait 10s till query finished
17:11:57:774 rule event /config/localtime: 17:11:56.588 -> 17:11:57.675 (1087ms)
17:11:57:817 poll node 90:fd:9f:ff:fe:de:34:1f-01
17:11:57:818 Poll light node Terrasse-Licht-2
17:11:57:870 read attributes of 0x90FD9FFFFEDE341F cluster: 0x0006: [ 
17:11:57:871 0x0000 
17:11:57:872 ]
17:11:57:872 add task 278 type 19 to 0x90FD9FFFFEDE341F cluster 0x0006 req.id 136
17:11:57:873 Poll APS request 136 to 0x90FD9FFFFEDE341F cluster: 0x0006
17:11:57:918 Poll APS confirm 136 status: 0x00
17:11:57:919 Erase task req-id: 136, type: 19 zcl seqno: 45 send time 0, profileId: 0x0104, clusterId: 0x0006
17:11:57:955 Node data 0x90fd9ffffede341f profileId: 0x0104, clusterId: 0x0006
17:11:57:956 0x90FD9FFFFEDE341F: update ZCL value 0x01/0x0006/0x0000 after 0 s
17:11:57:956 enqueue event event/checkgroupanyon for /groups/65520
17:11:58:587 schedule 3 diff 22682, Di. Juni 1 23:30:00 2021
17:11:58:588 Skip idle timer callback, too early: elapsed 912 msec
17:11:58:788 Bind response success for 0x588e81fffe3fe525 ep: 0x01 cluster: 0x0300
17:11:58:790 configure reporting rq seq 46 for 0x588E81FFFE3FE525, attribute 0x0300/0x0007
17:11:58:791 configure reporting rq seq 46 for 0x588E81FFFE3FE525, attribute 0x0300/0x0003
17:11:58:791 configure reporting rq seq 46 for 0x588E81FFFE3FE525, attribute 0x0300/0x0004
17:11:58:792 configure reporting rq seq 46 for 0x588E81FFFE3FE525, attribute 0x0300/0x0008
17:11:58:868 ZCL configure reporting rsp seq: 46 0x588E81FFFE3FE525 for ep: 0x01 cluster: 0x0300 attr: 0x0003 status: 0x00
17:11:58:869 ZCL configure reporting rsp seq: 46 0x588E81FFFE3FE525 for ep: 0x01 cluster: 0x0300 attr: 0x0004 status: 0x00
17:11:58:869 ZCL configure reporting rsp seq: 46 0x588E81FFFE3FE525 for ep: 0x01 cluster: 0x0300 attr: 0x0007 status: 0x00
17:11:58:870 ZCL configure reporting rsp seq: 46 0x588E81FFFE3FE525 for ep: 0x01 cluster: 0x0300 attr: 0x0008 status: 0x00
17:11:58:993 poll node 00:0b:57:ff:fe:96:52:92-01
17:11:58:994 Poll light node WZ_Li_Fensterbank_Ikea
17:11:59:042 Poll APS request to 0x000B57FFFE965292 cluster: 0x0006 dropped, values are fresh enough
17:11:59:587 schedule 3 diff 22681, Di. Juni 1 23:30:00 2021
17:11:59:587 enqueue event config/localtime for /config/
17:11:59:588 Wait 10s till query finished
17:11:59:598 rule event /config/localtime: 17:11:57.675 -> 17:11:59.587 (1912ms)
17:12:00:087 poll node 7c:b0:3e:aa:0a:01:c7:83-03
17:12:00:087 Poll light node Flur-Spiegel-oben
17:12:00:137 read attributes of 0x7CB03EAA0A01C783 cluster: 0x0006: [ 
17:12:00:137 0x0000 
17:12:00:138 ]
17:12:00:138 add task 288 type 19 to 0x7CB03EAA0A01C783 cluster 0x0006 req.id 152
17:12:00:138 Poll APS request 152 to 0x7CB03EAA0A01C783 cluster: 0x0006
17:12:00:213 Poll APS confirm 152 status: 0x00
17:12:00:213 Erase task req-id: 152, type: 19 zcl seqno: 47 send time 0, profileId: 0x0104, clusterId: 0x0006
17:12:00:231 Node data 0x7cb03eaa0a01c783 profileId: 0x0104, clusterId: 0x0006
17:12:00:231 0x7CB03EAA0A01C783: update ZCL value 0x03/0x0006/0x0000 after 0 s
17:12:00:232 enqueue event event/checkgroupanyon for /groups/65520
17:12:00:587 schedule 3 diff 22680, Di. Juni 1 23:30:00 2021
17:12:00:588 enqueue event config/localtime for /config/
17:12:00:588 Wait 9s till query finished
17:12:00:604 rule event /config/localtime: 17:11:59.587 -> 17:12:00.588 (1001ms)
17:12:01:036 poll node 7c:b0:3e:aa:0a:02:30:7a-03
17:12:01:036 Poll light node Osram-HEIZUNG
17:12:01:087 Poll APS request to 0x7CB03EAA0A02307A cluster: 0x0006 dropped, values are fresh enough
17:12:01:587 schedule 3 diff 22679, Di. Juni 1 23:30:00 2021
17:12:01:588 enqueue event config/localtime for /config/
17:12:01:589 Wait 8s till query finished
17:12:01:602 rule event /config/localtime: 17:12:00.588 -> 17:12:01.588 (1000ms)
17:12:02:012 poll node 7c:b0:3e:aa:00:ad:24:86-03
17:12:02:012 Poll light node Osram-Flur-unten
17:12:02:064 read attributes of 0x7CB03EAA00AD2486 cluster: 0x0006: [ 
17:12:02:065 0x0000 
17:12:02:065 ]
17:12:02:065 add task 296 type 19 to 0x7CB03EAA00AD2486 cluster 0x0006 req.id 163
17:12:02:066 Poll APS request 163 to 0x7CB03EAA00AD2486 cluster: 0x0006
17:12:02:125 Poll APS confirm 163 status: 0x00
17:12:02:125 Erase task req-id: 163, type: 19 zcl seqno: 48 send time 0, profileId: 0x0104, clusterId: 0x0006
17:12:02:138 Node data 0x7cb03eaa00ad2486 profileId: 0x0104, clusterId: 0x0006
17:12:02:141 0x7CB03EAA00AD2486: update ZCL value 0x03/0x0006/0x0000 after 0 s
17:12:02:141 enqueue event event/checkgroupanyon for /groups/65520
17:12:02:587 schedule 3 diff 22678, Di. Juni 1 23:30:00 2021
17:12:02:588 enqueue event config/localtime for /config/
17:12:02:588 Wait 7s till query finished
17:12:02:605 rule event /config/localtime: 17:12:01.588 -> 17:12:02.587 (999ms)
17:12:02:943 poll node 58:8e:81:ff:fe:3f:e5:25-01
17:12:02:943 Poll light node Terrasse-Licht-1
17:12:02:991 Poll APS request to 0x588E81FFFE3FE525 cluster: 0x0006 dropped, values are fresh enough
17:12:08:148 Bind response success for 0x588e81fffe3fe525 ep: 0x01 cluster: 0x0000
17:12:10:148 Bind response success for 0x588e81fffe3fe525 ep: 0x01 cluster: 0x0006
17:12:10:148 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x588E81FFFE3FE525 (seems to be active)
17:12:11:182 Bind response success for 0x7cb03eaa0a02ea2a ep: 0x03 cluster: 0x0006
17:12:11:332 ZCL configure reporting rsp seq: 55 0x7CB03EAA0A02EA2A for ep: 0x03 cluster: 0x0006 attr: 0x0000 status: 0x00
17:12:15:259 ZCL attribute report 0x7CB03EAA0A02EA2A for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
17:12:21:652 Bind response success for 0x588e81fffe3fe525 ep: 0x01 cluster: 0x0300
17:12:21:653 skip configure report for cluster: 0x0300 attr: 0x0007 of node 0x588E81FFFE3FE525 (seems to be active)
17:12:21:653 skip configure report for cluster: 0x0300 attr: 0x0003 of node 0x588E81FFFE3FE525 (seems to be active)
17:12:21:653 skip configure report for cluster: 0x0300 attr: 0x0004 of node 0x588E81FFFE3FE525 (seems to be active)
17:12:21:654 skip configure report for cluster: 0x0300 attr: 0x0008 of node 0x588E81FFFE3FE525 (seems to be active)
17:12:22:713 Bind response success for 0x90fd9ffffede341f ep: 0x01 cluster: 0x0000
17:12:22:804 ZCL configure reporting rsp seq: 64 0x90FD9FFFFEDE341F for ep: 0x01 cluster: 0x0000 attr: 0x4000 status: 0x00
17:12:22:902 Bind response success for 0x90fd9ffffede341f ep: 0x01 cluster: 0x0006
17:12:22:988 ZCL configure reporting rsp seq: 65 0x90FD9FFFFEDE341F for ep: 0x01 cluster: 0x0006 attr: 0x0000 status: 0x00
17:12:31:157 Bind response success for 0x90fd9ffffede341f ep: 0x01 cluster: 0x0008
17:12:31:158 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0x90FD9FFFFEDE341F (wait reading or unsupported)
17:12:31:269 Bind response success for 0x7cb03eaa0a02ea2a ep: 0x03 cluster: 0x0006
17:12:31:270 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x7CB03EAA0A02EA2A (seems to be active)
17:12:33:267 Bind response success for 0x90fd9ffffede341f ep: 0x01 cluster: 0x0300
17:12:33:268 skip configure report for cluster: 0x0300 attr: 0x0003 of node 0x90FD9FFFFEDE341F (wait reading or unsupported)
17:12:33:269 skip configure report for cluster: 0x0300 attr: 0x0004 of node 0x90FD9FFFFEDE341F (wait reading or unsupported)
17:12:33:430 ZCL configure reporting rsp seq: 73 0x90FD9FFFFEDE341F for ep: 0x01 cluster: 0x0300 attr: 0x0007 status: 0x00
17:12:33:430 ZCL configure reporting rsp seq: 73 0x90FD9FFFFEDE341F for ep: 0x01 cluster: 0x0300 attr: 0x0008 status: 0x00
17:12:39:382 sync() in 139 ms
17:12:39:384 EP edit could not read in clusterId: 
17:12:39:425 
17:12:39:474 
17:12:39:587 binding for cluster 0x0006 of 0x7CB03EAA0A021508 exists (verified by reporting)
17:12:39:588 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x7CB03EAA0A021508 (seems to be active)
17:12:41:653 Bind response success for 0x7cb03eaa0a01c783 ep: 0x03 cluster: 0x0006
17:12:41:790 ZCL configure reporting rsp seq: 78 0x7CB03EAA0A01C783 for ep: 0x03 cluster: 0x0006 attr: 0x0000 status: 0x00
17:12:41:920 Bind response success for 0x90fd9ffffede341f ep: 0x01 cluster: 0x0000
17:12:43:069 Bind response success for 0x7cb03eaa00ad2486 ep: 0x03 cluster: 0x0006
17:12:43:196 ZCL configure reporting rsp seq: 80 0x7CB03EAA00AD2486 for ep: 0x03 cluster: 0x0006 attr: 0x0000 status: 0x00
17:12:43:294 Bind response success for 0x90fd9ffffede341f ep: 0x01 cluster: 0x0006
17:12:43:294 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x90FD9FFFFEDE341F (seems to be active)
17:12:44:795 ZCL attribute report 0x7CB03EAA00AD2486 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
17:12:45:011 ZCL attribute report 0x7CB03EAA0A01C783 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
17:12:54:181 Bind response success for 0x000d6ffffe262cce ep: 0x01 cluster: 0x0000
17:12:54:287 ZCL configure reporting rsp seq: 85 0x000D6FFFFE262CCE for ep: 0x01 cluster: 0x0000 attr: 0x4000 status: 0x00
17:12:54:366 Bind response success for 0x90fd9ffffede341f ep: 0x01 cluster: 0x0300
17:12:54:367 skip configure report for cluster: 0x0300 attr: 0x0007 of node 0x90FD9FFFFEDE341F (seems to be active)
17:12:54:367 skip configure report for cluster: 0x0300 attr: 0x0003 of node 0x90FD9FFFFEDE341F (wait reading or unsupported)
17:12:54:368 skip configure report for cluster: 0x0300 attr: 0x0004 of node 0x90FD9FFFFEDE341F (wait reading or unsupported)
17:12:54:368 skip configure report for cluster: 0x0300 attr: 0x0008 of node 0x90FD9FFFFEDE341F (seems to be active)
17:12:54:626 Device TTL 1419 s flags: 0x7
17:12:56:996 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x7CB03EAA0A01C783 (seems to be active)
17:12:58:044 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x7CB03EAA00AD2486 (seems to be active)
17:12:59:683 Bind response success for 0x000d6ffffe262cce ep: 0x01 cluster: 0x0006
17:12:59:789 ZCL configure reporting rsp seq: 91 0x000D6FFFFE262CCE for ep: 0x01 cluster: 0x0006 attr: 0x0000 status: 0x00
17:12:59:904 Bind response success for 0x000d6ffffe262cce ep: 0x01 cluster: 0x0008
17:12:59:904 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0x000D6FFFFE262CCE (wait reading or unsupported)
17:13:03:116 Failed to detect file upload end boundary
17:13:03:174 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x000D6FFFFE262CCE (seems to be active)
17:13:03:959 verified group capacity: 255 and group count: 2 of LightNode 0x000b57fffe965292
17:13:03:960 0x000b57fffe965292 found group 0xFFF0
17:13:03:960 0x000b57fffe965292 found group 0x0015
17:13:04:643 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa0a01c783
17:13:04:644 0x7cb03eaa0a01c783 found group 0xFFF0
17:13:05:404 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa0a02307a
17:13:05:405 0x7cb03eaa0a02307a found group 0xFFF0
17:13:06:140 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa00ad2486
17:13:06:140 0x7cb03eaa00ad2486 found group 0xFFF0
17:13:06:888 verified group capacity: 255 and group count: 1 of LightNode 0x588e81fffe3fe525
17:13:06:889 0x588e81fffe3fe525 found group 0xFFF0
17:13:07:672 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa0a021508
17:13:07:672 0x7cb03eaa0a021508 found group 0xFFF0
17:13:08:153 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0x0001, command: 0x0A, payload: 210020C8, zclSeq: 88
17:13:08:154 ZCL attribute report 0x0017880106348A9C for cluster: 0x0001, ep: 0x02, frame control: 0x18, mfcode: 0x0000 
17:13:08:430 verified group capacity: 7 and group count: 1 of LightNode 0x7cb03eaa0a02ea2a
17:13:08:430 0x7cb03eaa0a02ea2a found group 0xFFF0
17:13:09:144 verified group capacity: 23 and group count: 2 of LightNode 0x0017880108ba0105
17:13:09:145 0x0017880108ba0105 found group 0xFFF0
17:13:09:146 0x0017880108ba0105 found group 0x001A
17:13:09:893 verified group capacity: 6 and group count: 2 of LightNode 0x00158d00021a3a28
17:13:09:894 0x00158d00021a3a28 found group 0xFFF0
17:13:09:894 0x00158d00021a3a28 found group 0x0014
17:13:10:679 verified group capacity: 255 and group count: 2 of LightNode 0x000d6ffffe262cce
17:13:10:679 0x000d6ffffe262cce found group 0xFFF0
17:13:10:680 0x000d6ffffe262cce found group 0x0015
17:13:11:418 verified group capacity: 255 and group count: 1 of LightNode 0x90fd9ffffede341f
17:13:11:418 0x90fd9ffffede341f found group 0xFFF0
17:13:24:588 Skip idle timer callback, too early: elapsed 879 msec
17:13:54:627 Device TTL 1359 s flags: 0x7
17:14:07:270 ZCL attribute report 0x7CB03EAA0A021508 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000 
17:14:15:937 0x00158D0003130B01: 0x0101/0x0505: vibration strength: 8
17:14:15:938 Door lock debug 0x00158D0003130B01, data 0x0000000A 
17:14:15:939 [INFO] - No button map for: lumi.vibration.aq1, unicast to: 0x0000, endpoint: 0x01, cluster: DOOR_LOCK (0x0101), command: ATTRIBUTE_REPORT (0x0A), payload: 05052300000800, zclSeq: 103
17:14:15:939 ZCL attribute report 0x00158D0003130B01 for cluster: 0x0101, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
17:14:21:346 [INFO] - No button map for: RWL021, unicast to: 0x0000, endpoint: 0x02, cluster: 0x0001, command: 0x0A, payload: 210020C8, zclSeq: 135
17:14:21:348 ZCL attribute report 0x0017880106732E1E for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
17:14:54:626 Device TTL 1299 s flags: 0x7
17:14:59:587 GW firmware version: 0x266e0700
17:14:59:588 GW firmware version is up to date: 0x266e0700
------------------------------------------------------------------------------------------------------------------------
here the output of ls -l .local/share/dresden-elektronik/deCONZ

pi@rasp-iobroker:~ $ ls -l .local/share/dresden-elektronik/deCONZ/
insgesamt 264
-rw-r--r-- 1 pi pi   2296 Jun  1 17:10 config.ini
-rwxr-xr-x 1 pi pi      0 Apr 25 20:20 session.default
-rw-r--r-- 1 pi pi     35 Apr 26 09:55 zcldb.txt
-rwxr-xr-x 1 pi pi 262144 Jun  1 17:13 zll.db
pi@rasp-iobroker:~ $
---------------------------------------------------------------------------------------------------------------------------------

**Comment by ChrisHae** [comment]
I can confirm there is a bug introduced with deconz 2.12.0
It will be fixed in one of the next beta releases.

**Comment by manup** [comment]
As reference the related PR was https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4916
The PR was testet under Linux with Chromium, Firefox and curl. It appears there are more differences in HTTP headers on other browsers (platforms?).

**Comment by ChrisHae** [comment]
Thats right. For me it works in firefox but not in chrome.
