### ISSUE TITLE
Xiaomi Aqara wireless switch can't assign "double tap" action

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#392]
ConBee II on Intel x64
Firmware: 266E0700
Version: 2.11.05 / 9.5.2021
Firmware
OS: Debian 10
Switches: 
Xiaomi Aqara WXKG02LM Rev.2 - (2 button) - 2018 Revision
Xiaomi Aqara WXKG03LM Rev.2 - (1 button) - 2018 Revision

According to two previous tickets, it should be possible to sign "double tap" actions to wireless switches made by Aqara/Xiaomi:

https://github.com/dresden-elektronik/phoscon-app-beta/issues/73
https://github.com/dresden-elektronik/phoscon-app-beta/issues/72

However, I can't find a way in the GUI to actually select this option to assign an action to a double tap. I can only select the button and assign a single press action:

![Bildschirmfoto 2021-06-01 um 11 09 00](https://user-images.githubusercontent.com/1507977/120297830-c983b880-c2c9-11eb-975a-347dcf05fb22.png)
![Bildschirmfoto 2021-06-01 um 11 09 44](https://user-images.githubusercontent.com/1507977/120297958-e7511d80-c2c9-11eb-87cc-977b11649c36.png)

The double tap option doesn't seem to be surfaced in the GUI yet.

**Comment by tomillr** [comment]
Anyone? Or am I just missing an option that is buried somewhere to get the double tap action going?

**Comment by tomillr** [comment]
I've just added one of the newer Aqara H1 wireless switches to my system running on build 2.13.01-debian-buster-beta with firmware 26720700. 

Just like with the older Aqara single and double-rocker switches, I could not find a way so assign actions like "double press" or "long press" in Phoscon.

So where should that option reside anyway?

**Comment by Nava75** [comment]
> ConBee II on Intel x64
> 
> Firmware: 266E0700
> 
> Version: 2.11.05 / 9.5.2021
> 
> Firmware
> 
> OS: Debian 10
> 
> Switches: 
> 
> Xiaomi Aqara WXKG02LM Rev.2 - (2 button) - 2018 Revision
> 
> Xiaomi Aqara WXKG03LM Rev.2 - (1 button) - 2018 Revision
> 
> 
> 
> According to two previous tickets, it should be possible to sign "double tap" actions to wireless switches made by Aqara/Xiaomi:
> 
> 
> 
> https://github.com/dresden-elektronik/phoscon-app-beta/issues/73
> 
> https://github.com/dresden-elektronik/phoscon-app-beta/issues/72
> 
> 
> 
> However, I can't find a way in the GUI to actually select this option to assign an action to a double tap. I can only select the button and assign a single press action:
> 
> 
> 
> ![Bildschirmfoto 2021-06-01 um 11 09 00](https://user-images.githubusercontent.com/1507977/120297830-c983b880-c2c9-11eb-975a-347dcf05fb22.png)
> 
> ![Bildschirmfoto 2021-06-01 um 11 09 44](https://user-images.githubusercontent.com/1507977/120297958-e7511d80-c2c9-11eb-87cc-977b11649c36.png)
> 
> 
> 
> The double tap option doesn't seem to be surfaced in the GUI yet.
