### ISSUE TITLE
Tuya _TZ3000_vp6clf9d TS0044 4 buttons scene switch

### ISSUE THREAD

**Issue by kurcsics** [dresden-elektronik/phoscon-app-beta#395]
try with 12.0
Switch not present in switch editor.

## Device

- Product name: Tuya 4 buttons scene switch
- Manufacturer: _TZ3000_vp6clf9d
- Model identifier: TS0044
- Device type :   - Switch

## Screenshots
![Képernyőkép 2021-06-06 090240](https://user-images.githubusercontent.com/46639875/121561766-1594d280-ca19-11eb-8d69-7aa94635013b.png)
![Képernyőkép 2021-06-06 090352](https://user-images.githubusercontent.com/46639875/121561777-175e9600-ca19-11eb-9aa9-75fe2b5217e1.png)
![5](https://user-images.githubusercontent.com/46639875/121571419-47ab3200-ca23-11eb-9cb8-d6ac2b8dd6d9.png)
![4](https://user-images.githubusercontent.com/46639875/121571446-509c0380-ca23-11eb-8f1f-26b47c8a7067.png)

### Basic
try with 12.0
Switch not present in switch editor.

**Comment by SEK-DE** [comment]
@kurcsics we don´t have the device here. But we plan to integrate an auto-generate tool for those devices. It will maybe take a while, please be patient.

**Comment by kurcsics** [comment]
Thanks!
