### ISSUE TITLE
TS0205 tuya smoke sensor is added, but not visible

### ISSUE THREAD

**Issue by olskar** [dresden-elektronik/phoscon-app-beta#396]
Hello!

I can in phoscon add TS0205 tuya smoke sensor perfectly fine, however it is not visible as a sensor after adding

**Comment by SEK-DE** [comment]
@olskar please use our latest deCONZ version or go over the beta (http://phoscon.de/pwabeta) 
then go to "help" -> "API information" -> use the filter to find your specific sensor and send me the log here.

**Comment by olskar** [comment]
having some troubles getting into http://phoscon.de/pwabeta
is "help" -> "API information" supposed to be in 2.11.5 or is it added in later versions? Cant find it in 2.11.5  @SEK-DE  :/

**Comment by SEK-DE** [comment]
@olskar you need the deCONZ version 2.12.1 Rantanplan or you can use the beta web app: http://phoscon.de/pwabeta

**Comment by olskar** [comment]
Here @SEK-DE  :)

```
{
    "config": {
        "battery": 100,
        "enrolled": 0,
        "on": true,
        "pending": [],
        "reachable": true
    },
    "ep": 1,
    "etag": "83950684befb802f929ecff9d599c170",
    "lastseen": "2021-06-23T17:31Z",
    "manufacturername": "_TYZB01_dsjszp0x",
    "modelid": "TS0205",
    "name": "Fire 17",
    "state": {
        "fire": false,
        "lastupdated": "2021-06-23T15:37:31.079",
        "lowbattery": false,
        "tampered": false
    },
    "type": "ZHAFire",
    "uniqueid": "84:71:27:ff:fe:04:40:c0-01-0500"
}
```

**Comment by SEK-DE** [comment]
YKO fixed the entry. Classic Tuya fail, it comes in as a Heimann device 😒 
Should work now correct in the beta, respectively you can see it under sensors.

**Comment by olskar** [comment]
Thanks @YKO-de and @SEK-DE :) Showing up now! Vendor shows up as "_TYZB01_dsjszp0x" but that is nitpicking, closing this :)
