### ISSUE TITLE
Sunrichter CCT Zigbee Touch Remote Controller 

### ISSUE THREAD

**Issue by kurcsics** [dresden-elektronik/phoscon-app-beta#397]
try with 12.0
Switch not present in switch editor.

## Device

- Product name: CCT Zigbee Touch Remote Controller
- Manufacturer: Sunrichter
- Model identifier: ZGRC-TEUR-004
- Device type :   - Switch

## Screenshots
![9](https://user-images.githubusercontent.com/46639875/121766808-d23f7e80-cb54-11eb-921c-4a89d4ef20a1.png)
![10](https://user-images.githubusercontent.com/46639875/121766815-d5d30580-cb54-11eb-81aa-6c07825cdb62.png)
![3](https://user-images.githubusercontent.com/46639875/121563556-cea7dc80-ca1a-11eb-8afe-184578276624.png)
![1](https://user-images.githubusercontent.com/46639875/121562813-1c701500-ca1a-11eb-9280-d7cdd789610d.png)
![2](https://user-images.githubusercontent.com/46639875/121562821-1e39d880-ca1a-11eb-8078-98c4b4b85170.png)

### Basic
try with 12.0
Switch not present in switch editor.

**Comment by SEK-DE** [comment]
Please run the latest deCONZ version or go in the web-app beta. Go there to "Help" - > "API Information" and use the filter to set only this device. Send me the API log here please.

**Comment by kurcsics** [comment]
Hi,

I have it with beta tried.
not all Button works.

{
    "19:18:27:620": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 2002,
            "lastupdated": "2021-06-30T17:18:28.009"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:18:30:846": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 4002,
            "lastupdated": "2021-06-30T17:18:31.232"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:19:06:779": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 2002,
            "lastupdated": "2021-06-30T17:19:07.168"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:19:57:358": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3002,
            "lastupdated": "2021-06-30T17:19:57.668"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:00:120": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 4002,
            "lastupdated": "2021-06-30T17:20:00.514"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:02:384": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3002,
            "lastupdated": "2021-06-30T17:20:02.777"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:03:604": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3002,
            "lastupdated": "2021-06-30T17:20:03.911"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:05:548": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3002,
            "lastupdated": "2021-06-30T17:20:05.880"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:07:187": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3001,
            "lastupdated": "2021-06-30T17:20:07.547"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:10:362": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3002,
            "lastupdated": "2021-06-30T17:20:10.659"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:17:17": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 4002,
            "lastupdated": "2021-06-30T17:20:17.346"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:19:220": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 4001,
            "lastupdated": "2021-06-30T17:20:19.616"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:20:268": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3003,
            "lastupdated": "2021-06-30T17:20:20.664"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:25:823": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 4001,
            "lastupdated": "2021-06-30T17:20:26.157"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:26:288": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3003,
            "lastupdated": "2021-06-30T17:20:26.684"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:29:17": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 4001,
            "lastupdated": "2021-06-30T17:20:29.413"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:29:611": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 3003,
            "lastupdated": "2021-06-30T17:20:29.998"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:32:888": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 2002,
            "lastupdated": "2021-06-30T17:20:33.211"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:37:598": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 1002,
            "lastupdated": "2021-06-30T17:20:37.906"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:37:691": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 2002,
            "lastupdated": "2021-06-30T17:20:38.088"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:53:755": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:20:54.151"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:55:165": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:20:55.563"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:20:56:30": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:20:56.401"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:00:769": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:01.167"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:01:726": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:02.123"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:02:319": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:02.717"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:03:402": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 4002,
            "lastupdated": "2021-06-30T17:21:03.753"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:06:780": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:07.093"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:07:804": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:08.124"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:08:691": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:09.089"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:09:444": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:09.842"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:10:860": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:11.258"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    },
    "19:21:11:502": {
        "e": "changed",
        "id": "107",
        "r": "sensors",
        "state": {
            "buttonevent": 5002,
            "lastupdated": "2021-06-30T17:21:11.900"
        },
        "t": "event",
        "uniqueid": "00:0d:6f:00:0f:c7:75:d1-01-1000"
    }
}

**Comment by kurcsics** [comment]
Hi,

with 2.13.02 Switch not present in switch editor.
