### ISSUE TITLE
Support further Develco devices

### ISSUE THREAD

**Issue by SwoopX** [dresden-elektronik/phoscon-app-beta#398]
Hi there,

Previously, Develco devices were primarily available as white label products. Pretty much all of them are supported, except for the fairly new air quality sensor.

Recently, they have launched a new brand and so the manufacturer name is different ("frient A/S" instead of "Develco products A/S"), while the model ID remains the same.

Could you please also consider the new manufacturer name in future and also support the air quality sensor while exposing the 2 available state values?

**Comment by SEK-DE** [comment]
Ok, so they do the same stuff like Tuya. We work on a solution for this very hard. In first case for Tuya devices, but it will hopefully work vor all manufacturers.

**Comment by SwoopX** [comment]
No no, thank god not like Tuya 😃 Develco is the white label manufacturer, the new brand they (Develco) has launched is called frient (same address). For the new one, it obviously has been decided "just" to change the zigbee manufacturer name but to keep the model identifier. Btw, we see that rather often with white label Sunricher switches as well (rebrands are e.g. Illuminize, EcoDim, etc.).

I'd expect not too much to happen with Develco/frient any time soon in contrast to Tuya. So here, the effort might just be copying a couple of lines. Regardless, I agree a more general approach to this is favorable. Not too sure if applying the Tuya product identification function from the plugin might be a good option to be extended to other devices as well so Phoscon can benefit.

**Comment by SEK-DE** [comment]
@SwoopX thanks for the clarification!
It would be good to have some of there devices here otherwise we just can work with the API logs from customers. Feels like we have hundrets of inquiries about integrate new devices every month, but our developement works on a generic implementation tool which brings definately all functions of a device. But it will take some time.
