### ISSUE TITLE
What trigger the success message on phoscon during inclusion ?

### ISSUE THREAD

**Issue by Smanar** [dresden-elektronik/phoscon-app-beta#400]
Hello, I have 2 devices, but a different result when I try to include them

![2](https://user-images.githubusercontent.com/20152487/123288251-ab4b5a00-d50f-11eb-9527-0948225def69.png)
![1](https://user-images.githubusercontent.com/20152487/123288259-adadb400-d50f-11eb-916d-0a4c85a0fc3f.png)

The second one is not supported by phoscon, not a problem, but  why I dont have success message ?

Both are correclty included and working.

Do it use the websocket return ? On the not working one we have 

`06:07:10:520 Websocket 192.168.8.1:39520 send message: {"e":"added","id":"3","r":"sensors","sensor":{"config":{"battery":null,"group":"10","on":true,"reachable":true},"ep":1,"etag":"586df0f106ab3be3c6c1c736c269ce29","id":"3","lastseen":"2021-06-23T06:07Z","manufacturername":"Legrand","mode":1,"modelid":"Pocket remote","name":"Pocket remote 3","state":{"buttonevent":null,"lastupdated":"none"},"type":"ZHASwitch","uniqueid":"00:04:74:00:00:83:40:f2-01-0005"},"t":"event","uniqueid":"00:04:74:00:00:83:40:f2-01-0005"} (ret = -1095166864)`

So all seem fine, no ?

**Comment by SEK-DE** [comment]
It´s called initial support. There are scenarios where devices get in the mesh without any message. Also in return.
Make sure you use the latest deCONZ and firmware. For newer devices you can check them in the app beta: http://phoscon.de/pwabeta

**Comment by Smanar** [comment]
So it mean a new device (not supported yet by phoscon, but suppported by deconz) will not trigger the "success" message ?
If it s that, not sure it s a good idea, as all users use phoscon to include their devices.

**Comment by SEK-DE** [comment]
Please read exactly what i´ve said: "there can be scenarios.." so, no, it´s not the same with every device that has initial support only. But it can happend. In our test environment this happend less then 5 times during the test of nearly 100 new devices. So don´t worry. This is btw something we got on our to do list, but we are in fact a very small team, so it will take a while to fix it.

That happend with the newest Philips wall switch at the beginning for example. After 2 weeks a fix came out and everyone saws it immediatly.

**Comment by Smanar** [comment]
Ok, thx, it's just I don't see what can be "scenario" during the inclusion procedure. In my mind you was just looking for the Websocket return {"e":"added"}
Don't need support for a special device, was just a general question.
