### ISSUE TITLE
Ecodim ED-10015 8 button switch not linking

### ISSUE THREAD

**Issue by tompijls** [dresden-elektronik/phoscon-app-beta#401]
Hi,

I have an 8 button switch from Ecodim. Phoscon detects it properly as an 8 button switch, but when I want to link it to a group it does not show up as an option.

**Comment by SEK-DE** [comment]
@tompijls please give me some informations about your settings:

1. host system (Raspberry Pi 3B+ / 4B / PC / NAS):
   Answer: 
2. execution method (Raspbian / Ubuntu / Home Assistant deCONZ add-on / Marthoc Docker container / Windows / Virtual Machine):
   Answer:
3. firmware version (format 26xxyy00):
   Answer:
4. deCONZ Version (Format 2.xx.yy):
   Answer: 
5. device (ConBee I / ConBee II / RaspBee I / RaspBee II):
   Answer:
6. Is the ConBee I / II connected to a USB 2.0 or USB 3.0 (blue) socket? - only relevant for ConBee I/II:
   Answer:
7. Is a USB extension used?   (yes / no) - only relevant for ConBee I/II:
   Answer:
8. Are other USB or serial devices connected to the host system? (yes / no) - If yes: which ones?):
   Answer:
9. If Raspberry Pi: which power supply is used? (original / manufacturer+model) Specify volts and amps: (e.g. 5.0V, 1.0A):
   Answer:
10. if Raspberry Pi: On which image base is the system set up?: (Phoscon / Raspbian / Raspberry Pi OS / Home Assistant ...):
    Answer:
11. If Raspberry Pi: Which way was deCONZ installed? (APT repository / dpkg / via a plug-in).
    Answer: 

You can also go to our web-app beta (http://phoscon.de/pwabeta), there to "Help" -> "API Information", use the filter to get the log ONLY from the needed device. Send us the API Log here.

**Comment by tompijls** [comment]
Hi,

sorry for late response.

host system (Raspberry Pi 3B+ / 4B / PC / NAS):
Answer: Rapberry PI 4B
execution method (Raspbian / Ubuntu / Home Assistant deCONZ add-on / Marthoc Docker container / Windows / Virtual Machine): 
Answer: Marthoc Docker
firmware version (format 26xxyy00):
Answer: 26660700
deCONZ Version (Format 2.xx.yy):
Answer: 2.12.01
device (ConBee I / ConBee II / RaspBee I / RaspBee II):
Answer: Conbee 2
Is the ConBee I / II connected to a USB 2.0 or USB 3.0 (blue) socket? - only relevant for ConBee I/II:
Answer: blue socket
Is a USB extension used? (yes / no) - only relevant for ConBee I/II:
Answer: no
Are other USB or serial devices connected to the host system? (yes / no) - If yes: which ones?):
Answer: no
If Raspberry Pi: which power supply is used? (original / manufacturer+model) Specify volts and amps: (e.g. 5.0V, 1.0A):
Answer: original
if Raspberry Pi: On which image base is the system set up?: (Phoscon / Raspbian / Raspberry Pi OS / Home Assistant ...):
Answer: raspbian 5.10.17-v8+
If Raspberry Pi: Which way was deCONZ installed? (APT repository / dpkg / via a plug-in).
Answer: docker

**Comment by tompijls** [comment]
I need to update the request however,

using beta I see the switch, and can configure the buttons.

However only the top buttons function properly . as of second row, pressing the "on" button switches on all lights connected to my deconz install, irrespective of their group or if the buttons have  have been configured

Log as requested for the switch:

> {
    "config": {
        "battery": 100,
        "group": "30209,30210,65520,65520",
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "bc91b0f51373b558c9b4eac75db91bc9",
    "lastseen": "2021-07-07T19:57Z",
    "manufacturername": "EcoDim",
    "mode": 1,
    "modelid": "ED-10014",
    "name": "Ecodim gang",
    "state": {
        "buttonevent": 4002,
        "lastupdated": "2021-07-07T19:57:07.596"
    },
    "swversion": "2.5.3_r20",
    "type": "ZHASwitch",
    "uniqueid": "bc:33:ac:ff:fe:6f:9a:8e-01-0006"
}
