### ISSUE TITLE
Again no FW update to 26660700 possible

### ISSUE THREAD

**Issue by Friedi1970** [dresden-elektronik/phoscon-app-beta#402]
Afaik this issue had been posted for a previous version.
Anyway, in Phoscon (HASS.IO) it is not possible to update from 26580700 to 26660700. When I start the update process it seems it works and I get the message that the update has been finished but as soon as I hit the OK the system shows the same screen as before and no update has been done.

**Comment by schweighart** [comment]
Same issue for me. I just took the stick to my Windows machine and did the update there without an issue.

**Comment by SEK-DE** [comment]
It is strongly advised to use a native installation of one of the update methods. Virtual Machines may work but are not supported, using a VM while trying to update firmware is on your own risk. Same goes with HA Systems.
