### ISSUE TITLE
Loosing Phoscon App after installation Hoobs 4

### ISSUE THREAD

**Issue by Raczka1989** [dresden-elektronik/phoscon-app-beta#404]
how i can installation the Phoscon App in HOOBS 4

Thanks

**Comment by letszb** [comment]
The Phoscon App comes with the deCONZ installation - no extra installation needed. You only need to open it in a browser at a device in the same network. For instance hoobs+ConBee II at your Raspberry Pi > Phoscon App in your Firefox/Chrome at your Mac/PC.

There are 3 ways:
http://phoscon.de/pwa
http://phoscon.de/pwabeta
<IP>:<port>
IP is from your Raspberry Pi, port is where deCONZ is running. It is a different port from the hoobs UI.

You can also add the specific IP at the discovery server URL's like this:
phoscon.de/pwabeta/login.html#host/<local-ip-adress>:<port>
