### ISSUE TITLE
1 of 2 "Mijia Light Sensor" missing in Phoscon

### ISSUE THREAD

**Issue by jan666** [dresden-elektronik/phoscon-app-beta#406]
Hi,

I have 2 "Mijia Light Sensor" (both bought on amazon). 

The first I paired via Phoscon is shown in Phoscon (ID 49). The second is missing in Phoscon (ID 52). Both work fine via API:

`GET .../sensors/49`

```
{
  "config": {
    "battery": 100,
    "on": true,
    "reachable": true,
    "temperature": 0,
    "tholddark": 12000,
    "tholdoffset": 7000
  },
  "ep": 1,
  "etag": "9f912e5297c59ae573af019161f918bf",
  "lastseen": "2021-07-15T10:43Z",
  "manufacturername": "LUMI",
  "modelid": "lumi.sen_ill.mgl01",
  "name": "Lichtsensor DG links",
  "state": {
    "dark": false,
    "daylight": true,
    "lastupdated": "2021-07-15T10:43:04.687",
    "lightlevel": 41190,
    "lux": 13149
  },
  "type": "ZHALightLevel",
  "uniqueid": "04:cf:8c:df:3c:7f:78:50-01-0400"
}
```

`GET .../sensors/52`

```
{
  "config": {
    "battery": 100,
    "on": true,
    "reachable": true,
    "temperature": 0,
    "tholddark": 12000,
    "tholdoffset": 7000
  },
  "ep": 1,
  "etag": "cd8ecdd471c3f3225ed4ef4c87d31e03",
  "lastseen": "2021-07-15T10:44Z",
  "manufacturername": "XIAOMI",
  "modelid": "lumi.sen_ill.mgl01",
  "name": "Lichtsensor Balkon",
  "state": {
    "dark": false,
    "daylight": true,
    "lastupdated": "2021-07-15T10:44:43.315",
    "lightlevel": 36739,
    "lux": 4718
  },
  "swversion": "20200305",
  "type": "ZHALightLevel",
  "uniqueid": "04:cf:8c:df:3c:7f:18:bb-01-0400"
}
```

**Comment by SEK-DE** [comment]
You mean our web-app with "phoscon" right?
Please tell me which gateway device you are using( Con- RaspBee (II)), which version (firmware) and deCONZ.

**Comment by jan666** [comment]
Yes, the web app. 

Produkt: ConBee II
Version: 2.11.05 / 9.5.2021
Firmware: 26680700

**Comment by SEK-DE** [comment]
@jan666 please update your system to the latest versions (deCONZ 2.12.3 and Firmware 266fo700).
Reintegrate the devices again then and take a look if they show up correctly in the API log.
It doesn´t make sence that one shows off and one not.

**Comment by jan666** [comment]
Just updated to 2.12.06 / 19.8.2021. Still the same

**Comment by jan666** [comment]
Updated to 2.13.04 / 18.12.2021. Now they’re both there
