### ISSUE TITLE
SilverCrest (Lidl) motion sensor not visible in Phoscon app

### ISSUE THREAD

**Issue by Nakazen** [dresden-elektronik/phoscon-app-beta#409]
Hi,

The SilverCrest Motion sensor is not becoming visible in the Phoscon app after being added succesfully.
The sensor does appear in Home Assistant but it doesn't appear to be working correctly.
Cleared the gateway, reset the motion sensor and the outcome is the same.

**Comment by SEK-DE** [comment]
For further conversation, it is useful to have the answers to these questions available. Even though this list of questions may seem extensive and overwhelming at first glance, we ask you to answer all questions. This way we can localize causes of the problem and answer questions faster.

The deCONZ and firmware versions can be found in the Phoscon App: Menu > Settings > Gateway, and also in the deCONZ GUI: Menu > Help > About deCONZ.

1. host system (Raspberry Pi 3B+ / 4B / PC / NAS):
   Answer: 
2. execution method (Raspbian / Ubuntu / Home Assistant deCONZ add-on / Marthoc Docker container / Windows / Virtual Machine):
   Answer:
3. firmware version (format 26xxyy00):
   Answer:
4. deCONZ Version (Format 2.xx.yy):
   Answer: 
5. device (ConBee I / ConBee II / RaspBee I / RaspBee II):
   Answer:
6. Is the ConBee I / II connected to a USB 2.0 or USB 3.0 (blue) socket? - only relevant for ConBee I/II:
   Answer:
7. Is a USB extension used?   (yes / no) - only relevant for ConBee I/II:
   Answer:
8. Are other USB or serial devices connected to the host system? (yes / no) - If yes: which ones?):
   Answer:
9. If Raspberry Pi: which power supply is used? (original / manufacturer+model) Specify volts and amps: (e.g. 5.0V, 1.0A):
   Answer:
10. if Raspberry Pi: On which image base is the system set up?: (Phoscon / Raspbian / Raspberry Pi OS / Home Assistant ...):
    Answer:
11. If Raspberry Pi: Which way was deCONZ installed? (APT repository / dpkg / via a plug-in).
    Answer: 


PS: please use our new Forum for device requests, issues etc. in the Future: https://forum.phoscon.de/
