### ISSUE TITLE
[Bug] Light Control / Color Settings page doesnt save or show current settings

### ISSUE THREAD

**Issue by Ltek** [dresden-elektronik/phoscon-app-beta#41]
after I set the light, it never saves / shows Color or Saturation settings on the screen - except for the brightness.
![phoscon_bug_controls](https://user-images.githubusercontent.com/1626802/50728387-232a2d80-10e6-11e9-919d-34673c701e42.JPG)

**Comment by StephanStS** [comment]
@Ltek: This works good at my installation:
<img src="https://user-images.githubusercontent.com/57687516/83324538-2b988080-a266-11ea-8a3b-3acec0f8af73.png" title="Group" width="400" />

I am using phoscon firmware version 2.05.75
<img src="https://user-images.githubusercontent.com/57687516/83324588-8e8a1780-a266-11ea-90f7-b5cbdd806b01.png" title="phoscon firmware version" width="350"/>

Is the problem present at your installation or is it already fixed?
If fixed, please close this issue.

**Comment by StephanStS** [comment]
@YKO-de: I propose to close this issue. It was filed in 01/2019. The actual phoscon app seems not to have this issue.  
There is no statement which app version was used, it must be a much elder one (01/2019). I assume your support will not investigate problems any more at these old releases.
