### ISSUE TITLE
Switch Editor does not save edits for Bush Jäger Light link switches

### ISSUE THREAD

**Issue by joecomo67** [dresden-elektronik/phoscon-app-beta#410]
My DeConz Version is 2.12.03 / 12.7.2021 - Firmware is 26390500.
I can connect my Busch Jäger "Bedienelemente" (the 2 and 4 switch version Model ID 6737-84 - FW is 1.2) to Phoscon (and they appear as routers in DeConz). 
I can also edit them in the Switch editor - however when I have finalized an action and press the "Save"/"Übernehmen" Button, it does not save the action but jumps back to the initial screen of the switch editor.

I tried with a completely new switch as well and I always get this behavior - it worked with an older DeConz version,
but I do not remember which one. 
For other switches (e.g. Philips) all works fine.
There was an older issue #240  which was potentially on the same topic - but closed as stale.
Any hint to a fix - or when this was broken would be great.

Thanks a lot yours

Joachim

PS: I can provide you with more Information, screen-shots etc. if required

**Comment by haraldknoll** [comment]
Have exactly the same problem. Cannot configure the Busch Jäger elements anymore in the Phoscon GUI. Modifying an existing one is also not possible. BR, Harald

**Comment by haraldknoll** [comment]
Switch editor still broken in 2.12.06 / 19.8.2021 for Busch and Jäger switches. GUI switch back to main selection of switches. Broken link?

**Comment by joecomo67** [comment]
not sure it is a broken link - it worked, when I did a clean setup (which it wouldn't if the link was broken).
I suspect some issue between Busch-Jaeger and Tradfri.
Unfortunately this is in my vacation home - so I can only test once I am back there.

**Comment by haraldknoll** [comment]
no, i am talking about the switch editor in the GUI. I have only B&J switches. After 2.12.01 the GUI ignores the switch assignment. I guess it is just a broken link to the next page. After the final switch assignment you end up here without the chance to assign the keys with the selected function.

![2021-08-20 10_49_28-Window](https://user-images.githubusercontent.com/68897141/130207386-75e8591b-bf64-4d82-8712-2fbf8f94203f.png)

**Comment by letszb** [comment]
There is currently a bug in the Phoscon App for the Busch-Jaeger switches. But it's fixed and will come with the next release.
