### ISSUE TITLE
Issue with Ikea Fyrtur tradfri blinds

### ISSUE THREAD

**Issue by andre1210** [dresden-elektronik/phoscon-app-beta#411]
I connected an Ikea Fyrtur blinds to my ConBee II on a raspberrypi. Additionally I use homebridge with hue plugin and control all components with homekit app.
Firmware of my ConBee II: 266F0700
Version 2.12.03 / 7/12/2021
raspbian - up to date
deconz is running headless on the raspi
and the Ikea range extender is also connected to deconz

I have several Ikea lights, switches and remotes. Everything works without issue.
I have only issues with the blinds. Once paired, everything works as expected.
After each reboot or even the restart of the deconz service, the blinds is still visible in deconz (web and gui app), but cannot controlled any more. The value of the opening can be changed, but the blinds don't move.
But: The original remote for the blinds: This is mapped via old Light Control App. This is still working.

My Procedure is then: Don't delete the existing blinds, bring the blinds to pair mode again and search for new lights. The blinds are found immediately and then everything works as expected again.
This is very annoying.

**Comment by SEK-DE** [comment]
Hey @andre1210 ,

can you send us the API Log of the regarding device please?
You can find this in our web-app under "Help" -> "API Information" -> use the filter to find it on the needed device.

**Comment by andre1210** [comment]
This is the rest api tab, the event tab is empty:
{
    "etag": "953e26822e74554c0f2f29c06d93b78f",
    "hascolor": false,
    "lastannounced": "2021-07-29T06:49:01Z",
    "lastseen": "2021-07-29T06:49Z",
    "manufacturername": "IKEA of Sweden",
    "modelid": "FYRTUR block-out roller blind",
    "name": "Rollo 1",
    "state": {
        "bri": 88,
        "lift": 35,
        "on": true,
        "open": true,
        "reachable": true
    },
    "swversion": "2.2.009",
    "type": "Window covering device",
    "uniqueid": "84:2e:14:ff:fe:69:0a:99-01"
}

**Comment by andre1210** [comment]
Maybe one thing to mention lastseen is hous old, even I moved the blinder minutes ago. For other lights, this column is updated more often.

**Comment by SEK-DE** [comment]
I´ll give this to our programmers. Thx for the informations. Please be patient, becouse of vacation time it could take a while.

**Comment by andre1210** [comment]
I see that I had a typo in the phoscon version in my first post:
My current version is 
2.12.03 / 7/12/2021

**Comment by andre1210** [comment]
any update on this?
BR
André

**Comment by andre1210** [comment]
I have one additional information. Maybe you can help me now.
Normally deconz is running headless on my raspberry.
When I start the deconz gui, I cannot control the blinds (my default bahaviour headless or gui - and normally I would re-pair here).
When I have a look on the Cluster Info - "Window Covering", all attributes are black (enabled). When I press once "read" at the attributes, only the supported attributes stay enabled and the others are greyed out.
And after this first click on read, I can control the blinds again.
But back in headless mode I cannot control the blinds. And Headless I cannot press "read attributes".
Do you have a workaround, how to read the device initially?
