### ISSUE TITLE
backup from 2.05.22 not restoring in  2.05.54 

### ISSUE THREAD

**Issue by maxandersen** [dresden-elektronik/phoscon-app-beta#42]
I made a backup in 2.05.54 (running deconz on hassio from https://github.com/neffs/hassio-addons/tree/master/deconz) and now trying to restore that on version 2.05.54 also on hassio from https://github.com/marthoc/hassio-addons/tree/master/deconz) and that is not working.

On startup I ignore the commisioning page - go to index and gateway to then use restore.

It loads the backup file just fine and after a bit says everything went well and reloads the page.

Login again, commision page is there again - no light or sensors around.

I have above 50 lights and sensors - is there *antyhing* I can do to avoid having to re-sync all these again ?

**Comment by maxandersen** [comment]
correction, groups , sensors and switches seems restored - but no lights.

**Comment by maxandersen** [comment]
hmm - i think this might because the tty devices were not working; if I load the old hassio plugin then the lights are there so they are still on the stick. 

Might be good if the UI will actually show an error if the stick is not reachable ?

**Comment by manup** [comment]
Agree this should be more visible, currently only the gateway settings show this information.
