### ISSUE TITLE
Feature Request: Call URL with Remote-Buttons/Sensors

### ISSUE THREAD

**Issue by michaelkandziora** [dresden-elektronik/phoscon-app-beta#424]
Hello Dresden Elektronik,

is there any posibility to assign "Action-URLs" to specific buttons of a zigbee remote?
Im using an IKEA TRADFRI Remote and I would really appreciate to assign URLs to be called for every button and different button states (short buttonpress, long buttonpress).

I would use this to call scenes, which I have defined at the smarthome server system (FHEM) I am using.
(I had to define my scenes there, because not all of my lights are Zigbee)

Best regards,
Michael

**Comment by manup** [comment]
I think this is possible via the REST-API.

Here you can use a http:// URL as action in a rule, this is a currently undocumented Webhook feature. 
I haven't tested it with buttons but it should work there too.

https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/rest_rules.cpp#L863

**Comment by michaelkandziora** [comment]
Thank you very much for the quick response! I will try this out and give a response here of my experience. :)
