### ISSUE TITLE
phoscon app not work

### ISSUE THREAD

**Issue by sansonifabio** [dresden-elektronik/phoscon-app-beta#425]
Recently, when you call up the URL phoscon.de/app or beta, you can no longer log into the Gateway. When I call up the IP from the Gateway it works without a Problem. I have tested several Browsers on IOs Tablet and mobile Phone or Windows 10 from the PC - it does not work. It looks like the Browser hangs up.

Seit kurzem wenn man die URL phoscon.de/app oder beta aufruft kann man sich nicht mehr ins Gateway einloggen. Wenn ich die IP vom Gateway aufrufe  funktioniert das ohne Problem. Ich habe mehrere Browser getestet unter IOs, Tablet und Handy oder Windows 10vom PC aus es klappt nicht. Es sieht so aus das der  Browser sich aufhängt. Unter Firefox geht das noch.
Grüße Fabio

**Comment by sansonifabio** [comment]
With this error, the URL has two logins that are not available when calling via the IP. See link.

Die URL hat bei diesem Fehler zwei Logins die beim Aufruf über die IP sind sie nicht vorhanden. Siehe Link.
**/pwa_/login.html?_0000000000_#login/_111111111111** Organal Zahlen entfernt.

**Comment by chris400** [comment]
IMHO It's due to new security settings in Chrome 94: https://developer.chrome.com/blog/private-network-access-update/

**Comment by sansonifabio** [comment]
Thank you for the info

**Comment by chris400** [comment]
For me the issue persists, but changed:
Mozilla Firefox fully works
Google Chrome find's the gateway, but login fails

Error in DevTools:
> Access to XMLHttpRequest at 'http://192.168.0.220/api/config?_=1641683195070' from origin 'http://phoscon.de' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

**Comment by zijam** [comment]
Maybe for Chrome and iOS, the Phoscon app should redirect user to the device IP address.
