### ISSUE TITLE
[DEVICE REQUEST] Support Woox R7049?

### ISSUE THREAD

**Issue by teras** [dresden-elektronik/phoscon-app-beta#426]
Hello people
I am new to this application and excuse if I am asking something wrong.

I have recently bought a Woox R7049 Fire alarm.
According to the [deCONZ issue tracker](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4693), even if this device is supported in deCONZ, to use it under Phoscon app we need to ask your guys here, since this is a different app.

My final goal is to be able to use this device under HomeAssistant. Since I don't see any other topic, I decided to open one.
Is it possible to inform of the requirements about it?

Thank you

**Comment by timvdsm** [comment]
Same here ... would be great to see it in the Phoscon app.

**Comment by timvdsm** [comment]
> Hello people I am new to this application and excuse if I am asking something wrong.
> 
> I have recently bought a Woox R7049 Fire alarm. According to the [deCONZ issue tracker](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4693), even if this device is supported in deCONZ, to use it under Phoscon app we need to ask your guys here, since this is a different app.
> 
> My final goal is to be able to use this device under HomeAssistant. Since I don't see any other topic, I decided to open one. Is it possible to inform of the requirements about it?
> 
> Thank you

Are you able to see the battery level in deconz? I only get the state of the smoke sensor itself, no indication of battery level unfortunately.
