### ISSUE TITLE
Not able to log into beta: http://phoscon.de/pwabeta/

### ISSUE THREAD

**Issue by x-MaxG-x** [dresden-elektronik/phoscon-app-beta#428]
I recently installed the latest betas (2.13.00 & 2.13.01).
Afterwards I tried to log into the beta UI via http://phoscon.de/pwabeta/.
The GW was found and I was asked for the PW. I tried the same, as for normal login (which is working) but it failed: (with both betas):

![image](https://user-images.githubusercontent.com/49819913/136930830-9d5ee33c-52b0-46d2-8710-36689846dca1.png)

I also tried to use the PW reset with the 10 min after restart - but it also failed with following note:
"Zurücksetzen fehlgeschlagen
Wurde das Gateway bereits neugestartet?"

Did I missed something?

**Comment by Heiner1967** [comment]
Hi, 
I have a similar problem. I did new instalation of Raspberian on my PI 3. I installed the stable Version of phoscom/deconz and it run with password if i put in the browser:
<ip of PI>/pwa
but the same password does not work if i use:
phoscon.de/pwa
phoscon.de/pwabeta/login.html
phoscon.de/pwabeta/login.html#host/:<IP of PI>

I recognised that only in the working way the screen is showing by Conbee II Stick, the other methods show a symbol of a Gateway beside the correct IP Address.

I deleted already in my Crome browser all History and Cookies with no success.
Even on a differnt Laptop i have the same problem.

I then installed the beta Version of the SW (over the stable one) But the behaviour described above is still the same.
I as well did a powerup and password reset with no success.

I hope you have some more idea.

**Comment by x-MaxG-x** [comment]
Hi Heiner,
have you tried the comment hint, mentioned in the link of my last post?

> Mimiix
> Community Manager
> Oct 12
> Not sure for how long it will persist as it has to do with some changes in the browsers.
> 
> Either way, here’s a work around :slight_smile:
> 
> With chrome, you can go to chrome://flags/#block-insecure-private-network-requests then disable “Block insecure private network requests” to use pwabeta. Don’t forget to enable it again when finished.

After switching to disabled it worked for me. Last time firefox worked out of the box for me - this time firefox is also not working for me.

**Comment by Heiner1967** [comment]
Hi,
thanks for the quick reply.

I did under chrome://settings/content ensured that the site phoscon.de is allowed to open unsecure content.

Hower entering in the crome browser: //flags/#block-insecure-private-network-requests does not work * page not available as the IP of Flags is not recognised.

**Comment by x-MaxG-x** [comment]
![image](https://user-images.githubusercontent.com/49819913/144111471-87f0bf79-ba4c-477a-b01d-8257229788af.png)

Just directly enter the following line into the address field:
chrome://flags/#block-insecure-private-network-requests

afterwards the right page is open (see screenshot)

**Comment by Heiner1967** [comment]
Hi, 
many Thanks that was it. 
Sorry that is missed to start the command with "chrome:"
