### ISSUE TITLE
Adding Philips Dim Switch won't proceed

### ISSUE THREAD

**Issue by DrAColian** [dresden-elektronik/phoscon-app-beta#429]
Hey guys,

as a first time user, it is really nice to see, that the installation/pairing of new devices is guided. But, as it is guided, I would expect, that there are information during the process.

So, here are two noticable issues (as I only have two devices yet, I can only refer to them!):
1. When adding a Philips ambient light, it doesn't do anything during the "Search for new devices". In you online help, there is a FAQ on that! Why not just display it in this screen? (As a pro tip or something?!) That devices probably have to be reset in order to be teached with deconz/phoscon!?

2. During the process of adding a switch, I can select "Philips" and then "Dim switch". Phoscon then tells me, that I have to press the "Reset" button for about 10sec until the green light shows up. On this window, there is a disabled "Next" button, but the "Next" button does not get activated - so I wasn't sure what to do - until I found on some other website, that the dim switches will pair when hit the "I" button for some time. I did this: et voila! The switch is paired! And the message on the screen confirms! But the information window won't state any of this. So either you just skip the "Next" and tell everything one should know in one screen, or you should have the "Next" activated by default!

Best regards

**Comment by hoblins** [comment]
In general I can confirm the issue 2 with the Philips Hue Dimmer Switch RWL022 (which is unfortunately not working with Phoscon app). In the windows showing the hint to reset the switch the "Next" button which is greyed out is renamed to "Ready". After resetting the switch is detected. So after closing the window with the "x" the switch is shown in the list. So at least in my case no pressing of the "I" button is required. But the registration procedure should be improved e.g. with a notification, that the switch is detected or the window should be closed automatically.

**Comment by Tscheurgen** [comment]
Hello!
It seems I have the same issue.
I can't add the Philips Hue Dimmer Switch to conbee 2, but I was able to add it to a cc2531 before.  So the Switch itself should be fine.
Is there any log or anything I can check to debug this?  Any other hint to get the connection done?
Thank you!

**Comment by DrAColian** [comment]
> Hello! It seems I have the same issue. I can't add the Philips Hue Dimmer Switch to conbee 2, but I was able to add it to a cc2531 before. So the Switch itself should be fine. Is there any log or anything I can check to debug this? Any other hint to get the connection done? Thank you!

Have you just tried adding it by its normal procedure? After you resetted the switch (10sec reset button), just follow through the steps of pairing (Press "I" for 10 secs or so!). Don't wait for phoscon to tell you the next step! This is what my issue describes: the pairing process doesn't tell you what to do, but if you do it anyway, it works. (At least it did for me!)

**Comment by Tscheurgen** [comment]
No luck at all.
On the CC2531 the connection is established in seconds.
Is there any log I can consult?

**Comment by Tscheurgen** [comment]
Okay, I've fixed the issue for me.
I had the ConBee connected to a USB3.0 Hub, which seems to break some traffic/protocol. While direct connected, the switch get's discoverd immediately.
Thank you for your help!
