### ISSUE TITLE
Unable to integrate a Philips Motion Sensor SML001

### ISSUE THREAD

**Issue by ConnOnGit** [dresden-elektronik/phoscon-app-beta#432]
When I try to add a Philips Motion Sensor SML001 using the interface, the sensor is supposed to be as not reachable. 
There could no data been read from the sensor (temperature & light level) instead of the adress and the firmware.
I'm using the Raspee gateway version 2.13.01 / 6.10.2021 and the firmware 26400500.

I already tried another SML001 sensor- same behavior. The motion sensor is fully recognized with the Philips bridge and app.

The phoscon API information says:
                    {
    "71": {
        "config": {
            "alert": "none",
            "battery": null,
            "delay": 0,
            "ledindication": false,
            "on": true,
            "pending": [],
            "reachable": true,
            "sensitivity": 2,
            "sensitivitymax": 2,
            "usertest": false
        },
        "ep": 2,
        "etag": "aeb434c862ca9d9737e0a3cdfb5fd3d5",
        "lastannounced": null,
        "lastseen": "2021-11-02T08:45Z",
        "manufacturername": "Philips",
        "modelid": "SML001",
        "name": "Bewegungsmelder",
        "state": {
            "lastupdated": "none",
            "presence": false
        },
        "swversion": "6.1.1.27575",
        "type": "ZHAPresence",
        "uniqueid": "00:17:88:01:02:03:9d:4f-02-0406"
    },
    "72": {
        "config": {
            "alert": "none",
            "battery": null,
            "ledindication": false,
            "offset": 0,
            "on": true,
            "pending": [],
            "reachable": true,
            "usertest": false
        },
        "ep": 2,
        "etag": "339f8d8f7bd61dd47991e77763f7f6db",
        "lastannounced": null,
        "lastseen": "2021-11-02T08:15Z",
        "manufacturername": "Philips",
        "modelid": "SML001",
        "name": "Temperature 72",
        "state": {
            "lastupdated": "none",
            "temperature": null
        },
        "swversion": "6.1.1.27575",
        "type": "ZHATemperature",
        "uniqueid": "00:17:88:01:02:03:9d:4f-02-0402"
    },
    "73": {
        "config": {
            "alert": "none",
            "battery": null,
            "ledindication": false,
            "on": true,
            "pending": [],
            "reachable": true,
            "tholddark": 12000,
            "tholdoffset": 7000,
            "usertest": false
        },
        "ep": 2,
        "etag": "339f8d8f7bd61dd47991e77763f7f6db",
        "lastannounced": null,
        "lastseen": "2021-11-02T08:15Z",
        "manufacturername": "Philips",
        "modelid": "SML001",
        "name": "LightLevel 73",
        "state": {
            "dark": null,
            "daylight": null,
            "lastupdated": "none",
            "lightlevel": null,
            "lux": null
        },
        "swversion": "6.1.1.27575",
        "type": "ZHALightLevel",
        "uniqueid": "00:17:88:01:02:03:9d:4f-02-0400"
    }
}
                    
 Any help is highly appreciated!

**Comment by hAMMERlized** [comment]
Had the same issue. So I've deleted the Sensor and reconnected it at the sensor menu but chosen "Others" not "Philips". Sensor got detected instantly and after a few seconds the Lux and Temperatur values plopped in. Hope this will help.
