### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by hoblins** [dresden-elektronik/phoscon-app-beta#433]
Due to excessive contacting diagnostics.meethue.com of the Philips Hue Bridge I was searching for alternatives less phoning home. 
Conbee seemed to be the solution. From the homepage [https://phoscon.de/en/conbee2/](url) :
![grafik](https://user-images.githubusercontent.com/11378643/140646152-b7a54e14-f1ee-4422-9eb0-dbe58c6646a2.png)
![grafik](https://user-images.githubusercontent.com/11378643/140646185-f49bcd53-9117-471f-9331-7a7ea0c2d068.png)
But...
a) There is a (publicly accessible?) discovery service (temporarily) storing ip and mac addresses.
Maybe this feature can be disabled, see [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2423#issuecomment-582514610](url). But on the one hand it is opt-out and not well documented and on the other hand I'm not 100% sure if it is really working because I still observe updates to the discovery service.
b) The app runs, despite the advertising promise "Local control of devices, without Internet", on the link [http://phoscon.de/app](url) which is not even a secured https link. There is the option to access the app with local ip, but this is not well documented, too. And for the beta there is no local option, as far as I know.
I would appreciate a (official) statement to this concerns and an outlook how this is handled in future releases.

**Comment by Mimiix** [comment]
I think its better to post on the forums as this github isn't looked at a lot (afaik).

**Comment by ChrisHae** [comment]
There is no data exchanged between the gateway and the internet the internet when using the online app. It acts only as a GUI for visualisation purposes (The javascript code runs localy in the browser on your PC). And it is the same functionality as when you run the app localy with the ip of your host system. The only data transmitted is a request to the discovery server to determine the ip address of the gateway in your local network. This communication can be disabled with a Rest API request to the gateway (`PUT /api/<apikey>/config` parameter: "discovery:false" see: https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/configuration/#modify-configuration)
The feature to disable this will be added to the Phoscon app in one of the next releases.
