### ISSUE TITLE
Not able to link switch to scene anymore?

### ISSUE THREAD

**Issue by widert** [dresden-elektronik/phoscon-app-beta#434]
I am not able to link switch to scene anymore...? This used to work but it is now not working, i.e. when going through the Switch editor -> link switch -> select switch- select action for button then switch is not assigned to the scene....
![Switch linking](https://user-images.githubusercontent.com/29115503/141191794-28faf326-e65d-404e-8803-00231920b392.PNG)
?

**Comment by kaidebrick** [comment]
I'm having the same issue. Ending up in a loop. Tested with differen Philips and IKEA switches
