### ISSUE TITLE
Aqara Double Rocker v 2018 

### ISSUE THREAD

**Issue by Sturmhorst** [dresden-elektronik/phoscon-app-beta#44]
Hey folks,

I have a problem. I can’t pair the Aqara Doublerocker with my phoscon gateway. Right now I tryed all common way to do that. 

Thanks for helping ✌🏼

**Comment by manup** [comment]
Which deCONZ version are you using? With 2.05.55 they should join and be visible in the Phoscon App.

There are many double rocker switches, what is the switch model printed on the back (like WXKG02LM)? 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#supported-wireless-switches

**Comment by Sturmhorst** [comment]
I habe this Version:

Hersteller dresden elektronik
Produkt RaspBee
Version 2.05.40 / 14.1.2019
Firmware 26240500

And yes! It is the WXKG02LM

**Comment by manup** [comment]
Ah ok please update to **2.05.55**, by following steps 1–3 from here:

https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz

**Important** make a backup first (we had some issues with firmware 26240500) 

Backup is described here: https://doc.phoscon.de/app/doc.html#settings-gateway-general-de
