### ISSUE TITLE
No access via reverse Proxy (nginx)

### ISSUE THREAD

**Issue by boehser-enkel** [dresden-elektronik/phoscon-app-beta#443]
Hey there,

i have problems to access the Phoscon webinterface over nginx Proxy Manager. (direct access is fine)
When i access it over my hostname (routed through nginx) i get to the phoscon page but there is either:
- no gateway shown
-  gateway shown but nothing happens when i click it

How to route correctly?

greetz

**Comment by tannyl** [comment]
This might be related to the same problem in #215

I have been trying to fix a similar problem for the Ingress (more or less also an reverse proxy) solution in Home Assistant.

You may be able to get it to work by "helping" Phoscon App find the gateway, by using the sub_filter in Nginx. Take a look at the PR I made for the HA addon. https://github.com/home-assistant/addons/pull/2325/files#

**Comment by boehser-enkel** [comment]
Thank you but i have no clue how i implement it with Nginx Rev Proxy config

**Comment by tannyl** [comment]
I tried installing Nginx Proxy Manager. You can add your own custom config (to some degree) via the GUI.

![billede](https://user-images.githubusercontent.com/11209600/147468395-53d6381e-acd9-4712-8f17-892d63476968.png)

Adding something like this (replacing the ip address of course)

```
location / {
  proxy_pass http://192.168.1.150/;
  proxy_redirect default;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
  proxy_set_header Accept-Encoding "";
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Host $http_host;
  proxy_set_header X-NginX-Proxy true;

  sub_filter_once off;
  sub_filter_types *;
  sub_filter ',-1!==document.location.hash.indexOf("nocache")' ',app.probeWorker.postMessage({add:[document.location.host]}),app.probeWorker.postMessage({scan:!0}),true';
}
```

I have not tested this against a Phoscon App, but did test that the "sub_filter" replacing worked as it should. So there might need to be set even more options to get the rest to work. Especially websockets. But give it a try and see how it goes. :)
