### ISSUE TITLE
Cannot Edit Multi sensor

### ISSUE THREAD

**Issue by bennyryan** [dresden-elektronik/phoscon-app-beta#445]
Running the docker instance.
Cannot edit 2 of my new sensors but can on my third.

There are reported errors in the console on the Sensors screen.

- Uncaught TypeError: sg is null
- Firefox can’t establish a connection to the server at ws://192.168.86.200:443/.
- Uncaught TypeError: this.versionLabel is undefined

![image](https://user-images.githubusercontent.com/7296570/147751575-6cb55a8d-4111-4dfb-b427-60fc9d725fd1.png)

**Comment by simontegelid** [comment]
I also have this issue, pasting my console. The error appears when clicking one of my multipurpose sensors.
![image](https://user-images.githubusercontent.com/891850/147769880-8a75fe49-c378-4e57-bc7a-9e1ff44c7c10.png)

Running Google Chrome Version 96.0.4664.110 (Official Build) (64-bit) and an unknown version of Phoscon app (how do I know this?). Deconz 2.13.4.

**Comment by simontegelid** [comment]
Removing the failing statement seems to work:
![image](https://user-images.githubusercontent.com/891850/147770476-45776384-e9ce-4f2d-bf9c-8fea9b10cea8.png)

**Comment by bennyryan** [comment]
Nice work @simontegelid, did a quick override and could rename my devices :D
