### ISSUE TITLE
Unable to log in to Phoscon App

### ISSUE THREAD

**Issue by dme8a8** [dresden-elektronik/phoscon-app-beta#448]
Unable to login.
![image](https://user-images.githubusercontent.com/47527153/150330281-b2a85244-82d0-4e65-8856-1abc097e738e.png

Tried to enter my password

Tried uninstalling deCONZ and restarting computer - no luck

Tired reading all the old issues - none are relevant

Works if I use another computer, although syncing with IKEA was a nightmare.

**Comment by italian84** [comment]
any luck on sorting it out? I have exactly the same issue
