### ISSUE TITLE
how to withdraw api key

### ISSUE THREAD

**Issue by netzbus** [dresden-elektronik/phoscon-app-beta#45]
I unfortunately gave Amazon Alexa access to the API. How can I withdraw the API Key from Alexa?

**Comment by manup** [comment]
You can delete the API key with the REST-API or with apps like Hue Essentials.

http://dresden-elektronik.github.io/deconz-rest-doc/configuration/#deleteapikey

**Comment by netzbus** [comment]
Thanks, that worked

**Comment by rufinus** [comment]
sorry to warm this up.
@netzbus how do you found the apikey which is used by alexa?

**Comment by netzbus** [comment]
I did it this way.:
Go to your Browser and open:
http://IP.of.your.deconz/api/{apikey}/config/
under whitelist delete everything except {apikey}

**Comment by lanwin** [comment]
I did that and the API key is not longer listed under whitelist. But Alexa still discovers my devices...is there anything else todo?
