### ISSUE TITLE
Tradfri GU10 400lm model not pairing, any advice?

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/phoscon-app-beta#46]
Just bought today, and it does not show in phoson app. Also in deCONZ-GUI I think I do not see it (I have so many nodes now (64), that, maybe  .. is somewhere.

Any advice on what to do?

**Comment by Klagio** [comment]
Yep I was able to. Thanks

**Comment by manup** [comment]
Guess the issue can be closed now?
