### ISSUE TITLE
Added, easily, my first Tradfri remote. Second one, it's not pairing, any advice? 

### ISSUE THREAD

**Issue by Klagio** [dresden-elektronik/phoscon-app-beta#47]
First paired immediately, second doesn't, what can that be?

**Comment by manup** [comment]
Does the led blink when doing the setup wizard?

We've tested with all known versions of the remote so it should work.

**Comment by Klagio** [comment]
After pressing 4 times it blinks yes, after that nothing

**Comment by manup** [comment]
Do you have by any chance multiple tabs open of the Phoscon App, perhaps on an other device?
Especially the device pages are currently tricky since they will close the Zigbee network when search is not running. Hence it's best to only have the Phoscon App open in just one Tab while adding devices.

Further do you use the Ikea Tradfri switch wizard to add the switch?

**Comment by leolobato** [comment]
I've just purchased a RaspBee and have it configured on Hassio using the deCONZ Addon, so I could add the Ikea Tradfri 5-button remote to my home automation.

I was able to pair to remote once to the Ikea hub, but even after it being reset, I can not get it paired on Phoscon... I try to add the device but it gets stuck on the screen which tells "Open device on the back and press the button 4x within 5 seconds.".

I do that, the remote blinks 4 red and stops, the "next" button on the Phoscon UI doesn't get enabled. I've tried far and close to the Raspberry Pi.

Anything else I should try?

**Comment by manup** [comment]
Since this is a new RaspBee, have you already updated it to the latest Firmware version 0x26330500?
Shipping firmware doesn't contain all needed functionality to interact with the IKEA remote.

Normally the update should be visible in *Phoscon App > Menu > Settings > Gateway*.
If not you can manually update the firmware as described here:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by leolobato** [comment]
I've realised Phoscon shows the firmware as "Not connected" under Gateway, so that should be my problem (which I'll keep investigating).

But to stay relevant to the github issue, maybe there should be an alert when trying to pair a device and the Raspbee doesn't show as connected?

**Comment by manup** [comment]
>I've realised Phoscon shows the firmware as "Not connected" under Gateway, so that should be my problem (which I'll keep investigating).

For the RaspBee please make sure that you have selected the right device in the Hassio configuration: `/dev/ttyAMA0`

>But to stay relevant to the github issue, maybe there should be an alert when trying to pair a device and the Raspbee doesn't show as connected?

Indeed, we already have something like that on the todo list, basically it affects all functions which rely on a Zigbee connection.

**Comment by leolobato** [comment]
> For the RaspBee please make sure that you have selected the right device in the Hassio configuration: `/dev/ttyAMA0`

I did. I'm running Hassio on a Raspberry Pi 3B, so I've also modified `config.txt` to include 

    enable_uart=1
    dtoverlay=pi3-disable-bt

So I'm not sure what else could be wrong.

**Comment by manup** [comment]
You may try step 1) from the official documentation to configure the serial port.

https://phoscon.de/en/raspbee/install#raspbian

**Comment by leolobato** [comment]
I'm using the latest build from Hass.io, which uses HassOS--and apparently there is no `raspi-config`. Is there any other way to enable the serial port? I do see it listed under `/dev`.

**Comment by leolobato** [comment]
I've flashed the [Raspbian Stretch Headless](https://phoscon.de/en/raspbee/sdcard) image on another Raspberry Pi and when I plugged the Raspbee, I can at least confirm that it is working (the firmware was updated automatically).

Anything else I should try? Just to confirm: I'm not running Raspbian, but HassOS.

**Comment by leolobato** [comment]
OK, the issue was solved. On `config.txt` for the Raspberry Pi 3B, instead of `pi3-disable-bt` I had to use `pi3-miniuart-bt`.
