### ISSUE TITLE
Switch editor - toggle not working as expected

### ISSUE THREAD

**Issue by runger1101001** [dresden-elektronik/phoscon-app-beta#48]
In the switch editor, I have set up a Aqara 2016 WXKG02LM wall switch to control the lights in my "workshop".

I have connected the left button and set it to "toggle".

When I change the light with the switch, everything works as expected.
But if I change the light with the Phoscon app, or use Homekit to change it, then I have to press the switch 2 times to change the light's state the next time I use the switch.

In other words, it seems like the switch maintains an internal "state" when set to toggle, and toggle between its internal state, meaning one press is on, the next press is off, the next press is on, etc...

But this is not what users expect. If I set a switch to toggle a light, then I expect the light's state to change each time I press the button. No one cares that the Phoscon app was used in between, if a user presses the switch they expect the light to change.

So it seems to me that the "toggle" function needs to be implemented to take the current state of the light into account.

Thanks and regards from Vienna,

Richard

**Comment by Elvys8** [comment]
Same issue here. Any solution?

**Comment by tommi0013** [comment]
Same here with Aqara Switch WXKG11LM 2016.

**Comment by stakanov** [comment]
I have same issue.

Vendor dresden elektronik
Product RaspBee
Version 2.05.64 / 22/4/2019
Firmware 262F0500

Switch:
Vendor Xiaomi
Product Smart Switch WXKG01LM

**Comment by ausminternet** [comment]
Why was this issue closed without any comment? I still have the same problem...
