### ISSUE TITLE
Individual light control - not working or user error?

### ISSUE THREAD

**Issue by runger1101001** [dresden-elektronik/phoscon-app-beta#49]
Having problems with my phoscon setup, and trying to figure out if the problem is me or the software...

I have different rooms, which I have created as groups in Phoscon, eg "Living Room" and "Workshop". Each room has several lights.

I have bought wall switches, and am trying to set up control of the lights with the switches. One switch is a dresden electronics scene switch (3 buttons), the other is a Aqara 2 button rocker switch.

What I am trying to achieve is "standard lights control", nothing fancy. I just want each button on the switch to control a light... just like my old non-Zigbee wall switches did.

I am not understanding how to set this up...

1. It seems to me with the Aqara switch, which shows up in the switch editor, I could set one button to on, and the other to off, for the whole group. But I want each button to control a single light in toggle mode, e.g. like a normal 2 channel wall switch ... how can I set this up?

2. The dresden switch shows up as its own group, rather than in the switch editor. Why? Can dresden scene switches also be used in the switch editor or do they always form their own group?

3. Dresden scenes: how can I enable the dresden switch to control individual lights? I am trying to control 3 lights individually using the 3 buttons on the switch. I have set each scene using the "individual light" toggle, and this is working for light A (top button), but not the bottom button. When I press the bottom button to switch on light B, light A goes off. I haven't managed to set it in a way that controls the lights separately. Is it possible?

I'm using Raspbee with DeCONZ 2.05.55, so that's pretty up to date.

Regards from Vienna,

Richard

**Comment by runger1101001** [comment]
Hi, I think this issue is partially resolved.

I was thinking of "groups" as being rooms, but groups are really just sets of lights to be controlled together. Is that correct?
So to switch individual lights I have to make a group for each individual light to be separately controlled, plus additional groups if I want to control all the lights of a room.

So far so good, that solves my issue with the Aqara switch.


But my Dresden scene switch is showing up as its own group. Why is it different from the Aqara switch in this regard?

**Comment by capstan1** [comment]
I just ran into the same issue with controling individual lights. I also went the same rout: creating groups with individual lights and add the switch to it. 
But this leaves me with a lot of groups with only individual lights which will result in a huge mess if I add more switches.
So I'd like to request a feature to choose whether a button should act a) on the whole group or b) on (an) individual light(s). Could this be implemented?

**Comment by manup** [comment]
>I was thinking of "groups" as being rooms, but groups are really just sets of lights to be controlled together. Is that correct?

Yes that's correct.

>So to switch individual lights I have to make a group for each individual light to be separately controlled, plus additional groups if I want to control all the lights of a room.

Jep, just keep in mind some lights only can be put in max. 8 groups.

>So far so good, that solves my issue with the Aqara switch.

>But my Dresden scene switch is showing up as its own group. Why is it different from the Aqara switch in this regard?

It can be configured to control it's own group directly by assigning lights to it. This allows to control the lights even when the gateway is offline (but is limited to basic commands). And as alternative it cn be configured via switch editor for multiple groups, like the Xiaomi switches. More flexible but it required the gateway to be operational all the time.

The most important thing is not to mix these two modes.

**Comment by StephanStS** [comment]
@runger1101001: Is this issue fixed for you? Or are things open?
If fixed, please would you close it?
@YKO-de: FYI.

**Comment by runger1101001** [comment]
This issue was never really an issue I guess. It was more confusion on my side about how things worked. I now have the 2 lights I wanted to control separately in 2 groups, and everything is fine.

However, reading back on the issue and thinking about the experience I think there are some UX issues to consider:
- maybe each light should also be part of an automatic 1-light group, if the user is trying to control only a single light with his switch
- or maybe every switch should behave like the Dresden Scene Switch or Tradfri Scene Switch: automatically create it's own group.
At the moment I think there is confusion because some switches have their own automatic groups while others do not, which means in some cases you can just "directly" control a single light, while in other cases you have to first create a group for it...

In any case, I will close the issue.
