### ISSUE TITLE
landing-page shows hue-bridge and asks for password

### ISSUE THREAD

**Issue by Somberland** [dresden-elektronik/phoscon-app-beta#5]
the phoscon-app shows me my hue-bridge and asks me for my password.
I tried to use my defined username (via hue api) but this won't work. is this a display error? does the phoscon-app think the hue-bridge is an other deconz/raspbee? or how do I get the password?

thanks 👍 

<img width="573" alt="bildschirmfoto 2018-01-05 um 09 08 19" src="https://user-images.githubusercontent.com/5808345/34600480-05f6feea-f1f8-11e7-8acc-79cfcdf14ece.png">

**Comment by jonathanweinberg** [comment]
I feel like you're best off raising this issue over here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues

At least that's how I took the readme.md for here re: support.

**Comment by manup** [comment]
The support for the hue bridge is in very early alpha state and beside light and group control most features of the Phoscon App are not working with it. The hue bridge doesn't have a password but you can log in by pressing the physical bridge button and click on 'Login / Einloggen'.

**Comment by chrisvella** [comment]
@manup thanks for the hint. One thing to note: you must type something in the password field before the login button becomes clickable. I put in "a" and it worked.
