### ISSUE TITLE
Sensors and Alex

### ISSUE THREAD

**Issue by Adam198912** [dresden-elektronik/phoscon-app-beta#50]
Hello i can find my lights via the alexa connection but the sensors are not appering? is this normal or is there any special way to add phoscon connected sensors to alexa?

**Comment by manup** [comment]
I'm afraid only the lights and control outlets are working.
Since deCONZ doesn't have a own skill the echo native hue compatible function is used which has restricted capabilities.

**Comment by StephanStS** [comment]
@YKO-de: I propose to close this issue. Possibly a label like "won't be fixed" or "enhancement" could be added.
