### ISSUE TITLE
Can not add IKEA Floalt LED Panel to Phoscon App

### ISSUE THREAD

**Issue by Godsplan** [dresden-elektronik/phoscon-app-beta#53]
Hello!
I have two IKEA Floalt LED Panels and usually activate those by motion sensor.
Now I have a Conbee 2 and want to hub the panels and motion sensor via HomeKit.

I tried to bring the float panels into light searching mode but it did not worked (switched on 6 times like on the bulbs). However, its not working. Do you have any idea how to connect IKEA Floalt to Phoscon?

**Comment by manup** [comment]
Please try the steps from the support page in the FAQ entry: *IKEA TRÅDFRI lights cannot be paired*

https://phoscon.de/support

Note each step and the order is very important.

**Comment by Godsplan** [comment]
Hi manup,

many thanks for quick reply. It works - thank you.
