### ISSUE TITLE
Mobile device friendly version cuts out information from sensor view

### ISSUE THREAD

**Issue by mickejo** [dresden-elektronik/phoscon-app-beta#6]
When using Phoscon on a mobile phone, the sensor view is more or less useless since no sensor values are shown and the button for adding a new sensor is hidden. When I am using Phoscon on my phone I always choose to show the desktop version to get all the information. It would be alot better if the mobile friendly version could handle to show it all directly.

**Comment by manup** [comment]
Yes the phone view is limited in various ways, we're working on it. Sensor values should be visible though, which phone are you using?

https://github.com/dresden-elektronik/phoscon-app-beta/issues/6

**Comment by mickejo** [comment]
I am using a Oneplus 2. It is necessary to select a sensor to get the sensor value. In the sensor list, only the names are shown.

**Comment by ooii** [comment]
I rotate the phone to landscape view to have the "Add sensor" button.
