### ISSUE TITLE
Group not controllable on mobile

### ISSUE THREAD

**Issue by marcelmu** [dresden-elektronik/phoscon-app-beta#61]
When selecting a group in the phoscon app on desktop, the sliders are shown and I can control all those lights simultanously.

In the mobile version these sliders are missing and are only showing, when selecting a single light.

Or am I missing something?

**Comment by lanwin** [comment]
@YKO-de why did you closed this issue? 

I think its valid. Currently its not possible to control an a lights in a group within the mobile view. But from my point of view this is the second main action I want to from mobile (first is on/off).

**Comment by marcelmu** [comment]
Would be nice to get feedback here again!

It's still an absolute blocker in my opinion...
