### ISSUE TITLE
Support for Xiaomi YTC4040GL

### ISSUE THREAD

**Issue by fl0wfr** [dresden-elektronik/phoscon-app-beta#63]
Hi,

I just bought a Xiaomi switch model YTC4040GL but I cannot pair it. Pressed Link button for 5 seconds but no luck.
deCONZ logs:
20:14:39:718 Current channel 11
20:14:39:726 Device TTL 2037 s flags: 0x7
20:14:52:064 Search sensors done
20:14:53:205 send permit join, duration: 59

Any idea?

Best,

**Comment by StephanStS** [comment]
Sometimes it helps to press a link button for only 1 second.
