### ISSUE TITLE
Support of Osram Smart+ Mini switch

### ISSUE THREAD

**Issue by waazdakka** [dresden-elektronik/phoscon-app-beta#64]
Hello Phoscon team !
Will you add the support for the Osram Smart+ Mini switch ?

It will be sooooo nice 👍 

Thanks !!

**Comment by waazdakka** [comment]
Closed without any resolution track ? :(

**Comment by YKO-de** [comment]
I'm sorry. Forgot to comment. Should work with the next release. Otherwise create an issue again.

**Comment by waazdakka** [comment]
> I'm sorry. Forgot to comment. Should work with the next release. Otherwise create an issue again.

Can't wait ;)

**Comment by 7wells** [comment]
Hello, I still have problems with the Osram Smart+ Mini Switch in Phoscon version 2.05.81 / 14.9.2020 (FW 26610700):

The 2 switches are shown under devices => switches:
Manufacturer: Osram
Product: Lightify Mini
Version: e.1.11.0M

But when I go to the main menu and select a group of lights => edit group => edit switches => link switch, under available switches, no mini switches are shown.

They are visible in Deconz and also shown via `http://IP:PORT/api/API_KEY/sensors`. I was surprised that while using the trailing `/sensors` in the link, also switches are shown, but maybe this is intended?

Please see below the output (I cut off other stuff like the "daylight" virtual sensor and redacted serial/MAC numbers by x):
```
10	
config	
battery	null
group	"19"
on	true
reachable	true
ep	1
etag	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
lastseen	"2020-09-20T07:19Z"
manufacturername	"OSRAM"
mode	1
modelid	"Lightify Switch Mini"
name	"Mini-Schalter_Grau"
state	
buttonevent	1002
lastupdated	"2020-09-19T19:10:45.291"
swversion	"e.1.11.0M"
type	"ZHASwitch"
uniqueid	"xx:xx:xx:xx:xx:xx:xx:xx-01-0006"
11	
config	
battery	100
group	"20"
on	true
reachable	true
ep	1
etag	"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
lastseen	"2020-09-20T04:03Z"
manufacturername	"OSRAM"
mode	1
modelid	"Lightify Switch Mini"
name	"Mini-Schalter_Blau"
state	
buttonevent	1002
lastupdated	"2020-09-19T19:11:00.175"
swversion	"e.1.11.0M"
type	"ZHASwitch"
uniqueid	"xx:xx:xx:xx:xx:xx:xx:xx-01-0006"
```
Do you see anything unusual about this? Thanks for your help!

**Comment by 7wells** [comment]
Is there really nobody who knows if/how the Osram Smart+ Mini Switch works in Phoscon? I can see it there under switches, but I cannot see it when going to a group and trying to assign the Mini Switch to that group (the Mini Switch does not appear in that menu).

**Comment by 7wells** [comment]
Partial progress - thanks to a hint from @Smanar there:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/881#issuecomment-696869254

So I used the old (2016) web app, where the Osram Smart+ Switch Mini appears as "Lightify Switch Mini" under `Control` and under `Groups`. And under `Groups` I could assign lights as members that I can now switch on/off (buttons 1/up and 3/down) and I can cycle through the colours (they are RGBW lights) with button 2/middle.

Now I wonder why the new Phoscon GUI cannot assign lights to this switch (switch does not appear when going to a group)? Can some of the developers please look into this? Or please let me know what else I could provide, e.g. logs etc.? Thank you!

Why "partial" progress? The Mini Switch just switched also other lights not assigned to it. This is odd.

**Comment by the-rene** [comment]
I have the same problem as described bei 7wells - The switch shows up in the list of switches but can't be used to control anything. 

I just found this issue and wondered, why it is closed.

I use Version 2.05.84 in the Home Assistant Plugin, the Firmware of my Conbee II is 26660700. I'd like to hear, if there is any progress.

**Comment by Smanar** [comment]
It s because you need to use HA to make scenario, not phoscon.

**Comment by the-rene** [comment]
In HA, the device only has a battery indicator and the buttons are not recognized, that's why I tried directly in Phoscon. The Old web app is not accessible via the HA Plugin.

**Comment by 7wells** [comment]
You can access the old web GUI via a link from within the new phoscon GUI => help. And there, you can assign lights to the mini switches etc. After that, they work without problems, but they still do not show up in the new phoscon GUI when you try to (re-)assign (other) lights to them. If you need that, you have to do it in the old GUI.

**Comment by YKO-de** [comment]
The switch editor currently only works for the Mini in the beta url. Since I don't have it myself, please give me a feedback if it worked, if you try it.

**Comment by the-rene** [comment]
Thanks, using the switch Editor in the Beta URL worked. 

It shows the Switch as generic 4 Buttom Switch with these mappings:

* Button 1 - Up (big arrow) - mapped to brighter/on
* Button 2 - Down (small arrow) - mapped to darker/off
* Button 3 - Dot (middle button) - mapped to on/off
* Button 4 - not existant (i guess)

The corresponding buttons flashed in the Editor, so it is easy to map them. 

The mapping itself does not work as expectetd. When I press the ON/OFF button once, Phoscon shows, that the connected group is on, but acutally the lights are still off. If I press again, the group in phoscon turns off. Another press later, the light does turn on, but not consistently. The Up and Down buttons also act as incosistent as the middle button.

Can I anyhow help debugging? I tried the connection with two switches, both show a similar behavior.

**Comment by YKO-de** [comment]
Hmm, okay. Which lights are in the group? So which manufacturer?

**Comment by Smanar** [comment]
Oups sorry for my misplaced answer, I haven't see I was on phoscon app github

**Comment by YKO-de** [comment]
Okay. Can you tell me what key events the switch has? I had assumed the same as the four button switch. But maybe that's incorrect.

**Comment by 7wells** [comment]
> 
> 
> Okay. Can you tell me what key events the switch has? I had assumed the same as the four button switch. But maybe that's incorrect.

I can help as well, I think, but am not sure what you mean with "key events". Where can I see these? In deconz or in phoscon? I have 2 of the Osram Smart+ Mini Switches and several lights which I can successfully control with the 2 mini switches.

**Comment by YKO-de** [comment]
@7wells I have added the "Mini" to the switch editor under phoscon.de/pwabeta This is done with a generic image with 4 buttons. Just ignore key 4 for now. Maybe you could also try to use the beta to assign different rules to the switch, like the-rene did. And tell me afterwards how the switch behaves. If it works as expected.

**Comment by the-rene** [comment]
@YKO-de 
> Okay. Can you tell me what key events the switch has? I had assumed the same as the four button switch. But maybe that's incorrect.

How do I get the key events? I couldn't find any reference to a log in the documentation. Just back home, sorry for the late reply.

**Comment by dcjona** [comment]
Hello i have problem for pairing. What's the minimal version to be recognised please?

**Comment by kkoenders** [comment]
Any news on this issue? 
I am running deCONZ v2.07.01 with ConBee II fw 26660700 in homeassistant v0.118.5 with deCONZ addon v6.0.0. 
I still have the issue that the Ledvance/Lightify Switch Mini is not shown correctly: it is recognized by the ConBee (Lightify Switch Mini), but shown as a generic switch. When linked to a light group in Phoscon web app, you are able to select an assignment for 4 buttons (as YKO-de mentioned on 22 Oct), of which 3 are configurable (1=up arrow, 2=down arrow, 3=middle circle). The images of the key assignment do not indicate what button is dowing what action. Also, the middle button (button 3) is not responding as expected: it seems to do the click action twice sometimes when set to toggle on/off (lights goes on and off again).

**Comment by danzbox** [comment]
@YKO-de Great to see some progress in the phoscon app. Finally undusting the unused Smart+ Switch Mini and after pairing it just works fine as you described it. (Phoscon 2.07.01)
1. There is a great 2D black and white image available from Lightfy as inspiration for the Phoscon icons so that we don't need 4 button generic https://dammedia.ledvance.info/media/resource/450x450/asset-1895087/SMART+-Switch-Mini.jpg 
...even as [EPS](https://dammedia.ledvance.info/media/resource/hires/asset-1895087/SMART+-Switch-Mini.eps)
2. For the name I would suggest Osram SMART+ Switch Mini
3. Using all three buttons and works as expected
![image](https://user-images.githubusercontent.com/46283463/103714993-b9d4a200-4fbf-11eb-85a8-3cfb5fd92ff8.png)
