### ISSUE TITLE
new device request: Temperature Humidity Sensor Tuya/Blitzwolf

### ISSUE THREAD

**Issue by kaybau** [dresden-elektronik/phoscon-app-beta#68]
Hello,
the device is well described in this issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2442 
It is connected to phoscon App, all device parameters are shown in deconz-Adapters, but the device itself is not shown and visible in phoscon app.

Would be good, making it visible as well
Thanks
Kay

**Comment by SwoopX** [comment]
Please move that one over to Phoscon repository.

**Comment by kaybau** [comment]
Hi @SwoopX I got this link directly from dreseden-elektronik-support. Can you move it or tell me the link?

**Comment by YKO-de** [comment]
Hi @SwoopX The device should be visible with the next release.

**Comment by SwoopX** [comment]
@YKO-de Super fast serve!!!

**Comment by renne** [comment]
Same issue here. Phoscon app detects a new sensor. I can also see messages from TS0201 via node-red-contrib-deconz.
But no sensor shown in "Connected sensors" in Phoscon App.

Install-image: Phoscon_Gateway_2020-07-03
Phoscon-GW version: 2.0.5.77/22.5.2020 -> 2.0.5.78/22.5.2020
Conbee II-Firmware:   264A0700 ->  26580700

**Comment by kaybau** [comment]
Hi, 
I started beta-app http://phoscon.de/pwabeta/index.html?  today and my Heiman Sensors are visible as TS0201
Cheers,
Kay

**Comment by renne** [comment]
@kaybau 
Thanx for the great tip! :-)
