### ISSUE TITLE
Phoscon App: Undermost group cannot be selected

### ISSUE THREAD

**Issue by StephanStS** [dresden-elektronik/phoscon-app-beta#69]
Issue is valid for Phoscon App ["stable"](http://phoscon.de/pwa) and also ["beta"](http://phoscon.de/pwabeta). 
If you switch in the Mainpage to the undermost group, it cannot be selected. All other groups are selectable.
Workaround: Select undermost group and then select "Scenes" or "Lights" beside the "Edit" selection.

<img src="https://user-images.githubusercontent.com/57687516/83264506-76f85380-a1c0-11ea-889d-7ee67c800c41.png" title="Mainpage" width="300" />

(Remark: Graphics upload problem to this issue which I reported before was caused by a too strong pihole rule. Upload is working fine. -> PEBCAC).

**Comment by YKO-de** [comment]
Yes send a description to the support. I just tried to reenact it. The error does not occur with me.

**Comment by StephanStS** [comment]
Clearification: The group is selectable, but the upper description in the headline, which should be "Kueche" in the screenshot above, shows the last selected group ("Flur EG" in the screenshot).

**Comment by YKO-de** [comment]
Is the problem still relevant? It still doesn't happen to me.

**Comment by StephanStS** [comment]
@YKO-de: To give (late) respond: Problem is fixed. Thx.
