### ISSUE TITLE
cannot add more IKEA Tradfri motion sensors

### ISSUE THREAD

**Issue by phsdv** [dresden-elektronik/phoscon-app-beta#7]
using: deCONZ 2.05.02
with conbee in raspberry pi 3

I have already 2 tradfri motion sensors connected. While trying to add a third and a forth, I am out of luck they are not recognized. In the meantime the version of deCONZ was update to 2.05.02 could be the cause but not sure.  

Are there any log files I should check? Any idea what to do to get them connected?

**Comment by chrisvella** [comment]
I am now having a similar issue adding more xiaomi sensors.

**Comment by manup** [comment]
Can you please provide more details on your setup?

deCONZ versions, how many lights, IKEA lights, type of the sensors?

**Comment by chrisvella** [comment]
Hi @manup. I will assume that was also directed at me :)

I am running deconz from docker. This [build](https://hub.docker.com/r/joch/deconz/).

I have a USB conbee device:
`Bus 005 Device 002: ID 0403:6015 Future Technology Devices International, Ltd Bridge(I2C/SPI/UART/FIFO)`

Phoscon Version: 2.05.01 / 05/02/2018

I have the following xiaomi devices: 1x multi sensor, 2x motion sensors, and 2x door sensors. I have  attempted to add 3x door sensors but none of them will pair. 

To debug this problem I have rebuilt the docker instance. I also tried to dump the logs from inside the docker container but had no luck:
```
deCONZ --dbg-info=2 --dbg-zdp=1 --dbg-zcl=1 --db-aps=1 --dbg-http=1
QXcbConnection: Could not connect to display 
Aborted (core dumped)
```

**Comment by manup** [comment]
Please try version 2.05.07, also it's highly recommended to update the ConBee firmware to 0x261e0500.
When I recall correctly firmware updates in Docker are not working yet (?) so you may need to do this outside Docker.

> I have the following xiaomi devices: 1x multi sensor, 2x motion sensors, and 2x door sensors. I have attempted to add 3x door sensors but none of them will pair.

How many lights do you have? With latest firmware more end devices are supported per ConBee but it's always a good idea to have more mains powered devices like lights in the network.
Battery devices always need a parent to register to.

**Comment by chrisvella** [comment]
Hi @manup. I am using joch's build because it supports firmware upgrades.

For the record I had firmware 0x261d0500 and software 2.05.01. I now have firmware 0x261e0500 and 2.05.7. I have successfully paired one more device, but can't test further for the next couple of days. I can tentatively say the upgrade fixed the problem!

I have a couple of Philips Hue White and Colour Ambiance bulbs. Phoscon doesn't recognise them so I assumed they couldn't form a mesh with my xiaomi sensors... is that correct? If not can I change the channel in the hue app and it will be working?

Thanks for your assistance

**Comment by manup** [comment]
> I have a couple of Philips Hue White and Colour Ambiance bulbs. Phoscon doesn't recognise them so I assumed they couldn't form a mesh with my xiaomi sensors... is that correct? If not can I change the channel in the hue app and it will be working?

Oh, well the bulbs can't be connected to multiple gateways at the same time since they are part of a particular ZigBee network. If you wan't to control them with ConBee you need to factory reset them first and connect them via Phoscon App (not sure but it might be sufficient to delete a bulb in Philips gateways and it will leave the network). But be aware then they won't be part of the hue bridge anymore.

**Comment by phsdv** [comment]
I just installed version 2.05.08 but I am still not able to add a 3rd ikea motion sensor.
Connetced to the deCONZ are:
* 2 ikea motion sensors
* 2 lights, one FLS-CT from Dresden-Electronics and 1 Ikea FLOALT panel WS 30x30.
* 3 ikea remote controls and 1 philips dimmer switch connected.

Further there is a HUE bridge with many more lights and both gateways/bridges are connected to Home Assistant. If everything works fine with deCONZ I will move all lights to deCONZ.

**Comment by chrisvella** [comment]
@manup Apologies for the delayed reply. I can confirm the update fixed my issues with adding xiaomi sensors.

No luck with the hue bulbs so I created [issue 10](https://github.com/dresden-elektronik/phoscon-app-beta/issues/10)

**Comment by phsdv** [comment]
Today I managed to add one more Ikea motion sensor. Not sure why it worked. I have now installed version 2.05.19

**Comment by phsdv** [comment]
I found out why! It is kind of stupid. In the Phoscon app when you click on Add new sensor, a new page will follow where you select which type of sensor, I click on IKEA. The next screen opens with a nice picture of the Ikeas sensor. At that moment I am trying to connect the sensor, but that is not working.... You first have to select that sensor and only than you are able to connect. Although it says "SELECT SENSOR" I did miss that, as is it in the top left of the screen. Would be better to add a similar message below the picture of the sensor (as well)

**Comment by mariusmotea** [comment]
I upgrade today deconz to latest version and then the rasbee firmware and i still cannot pair my 3rd motion sensor. I tried from both old web interface and phoscon, but every time the pair process fail.

**Comment by manup** [comment]
Does the 3rd motion sensor appear in deCONZ GUI?

**Comment by mariusmotea** [comment]
no, it is working just with tradfri gateway.
