### ISSUE TITLE
Switch editor: Xiaomi smart switch Aqara WXKG12LM button mapping problem

### ISSUE THREAD

**Issue by StephanStS** [dresden-elektronik/phoscon-app-beta#70]
In the switch editor the configuration of the button mapping seems to be not correct: 
***Short Single Press*** leads to ***No Operation***, ***Double Button Select*** leads to ***Single Button Operation***, ***Shaking Select*** leads to ***Double Button Operation***. 

## Boundary conditions
- Conbee II
- Phoscon App Version 2.05.75 / 8.3.2020 (264A0700)
- Sensor Xiaomi Smart Switch Aqara WXKG12LM, Version 20180629
- Readout from RESTful API:
o	manufacturername: LUMI
o	modelid: lumi.sensor_switch.aq3
o	swversion: 20180629
![grafik](https://user-images.githubusercontent.com/57687516/83325745-0ceab780-a26f-11ea-9180-3b7597b6b5fc.png)

## Basic information about WXKG12LM smart switch codes
The Xiaomi smart switch emits the following codes (e.g. if used in node-red msg.payload.buttonevent):
- Short Single Press: 1002
- Long Single Press: 1001
- Long Single Release: 1003
- Double Press: 1004
- Shaking: 1007

From these five gestures the switch editor shall be able to map the three gestures *short single press*, *double press*, *shaking*. 
<img src="https://user-images.githubusercontent.com/57687516/83325788-6bb03100-a26f-11ea-9d89-86b2aeead957.png" title="Button select" width="300" />

### Example 1: *Short single press* leads to *No operation*
Select the single press operation:
<img src="https://user-images.githubusercontent.com/57687516/83325939-92bb3280-a270-11ea-916a-3bcb12bfc804.png" title="Short single press" width="300" />

Then select e.g. operation *toggle*:
<img src="https://user-images.githubusercontent.com/57687516/83325910-4ec82d80-a270-11ea-8f26-b3a11248c11c.png" title="Action select" width="300" />

Then the following is shown:
<img src="https://user-images.githubusercontent.com/57687516/83326048-4290a000-a271-11ea-86f7-c1e3ec67dff8.png" title="No operation" width="300" />
The button (end of arrow) shows no "1" for a short single press operation and also nothing happens when pressing the button.

### Example 2: *Double press* leads to *Short single press*
Similar to example 1.
<img src="https://user-images.githubusercontent.com/57687516/83326791-0d874c00-a277-11ea-8ae1-934d35a79e07.png" title="Double press" width="300" />

Also assigning a toggle leads to:
<img src="https://user-images.githubusercontent.com/57687516/83326814-2a238400-a277-11ea-93ab-2385fc708987.png" title="Short single press" width="300" />

As can be seen, a *short single press* is assigned, the system also behaves as a single press.

**Comment by StephanStS** [comment]
It seems that this is the same: [Phoscon app Aqara button mapping is wrong #1895](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1895)

**Comment by YKO-de** [comment]
This problem should be solved with the next release.

**Comment by StephanStS** [comment]
Remark: Tested successful with phoscon 2.05.86 / 15.10.2020.
Tested with phoscon.de/pwa and phoscon.de/pwabeta from 25.10.2020.

**Comment by psaggiomo** [comment]
Hi, I have the same issue with WXKG11LM. Short single press leads to No operation

**Comment by StephanStS** [comment]
> Hi, I have the same issue with WXKG11LM. Short single press leads to No operation

@psaggiomo: Did you test it with the newest phoscon software bundle (phoscon software and also conbee stick firmware)?

**Comment by psaggiomo** [comment]
> > Hi, I have the same issue with WXKG11LM. Short single press leads to No operation
> 
> @psaggiomo: Did you test it with the newest phoscon software bundle (phoscon software and also conbee stick firmware)?

Yes. I have 2.07.00 with 26680700 firmware on Synology Docker.
