### ISSUE TITLE
Tradfri up/down switch cant be used in switch-editor

### ISSUE THREAD

**Issue by yabbah** [dresden-elektronik/phoscon-app-beta#71]
Hi, the remote for IKEA FYRTUR blinds, the up/down button cant be choosed as switch in the switch editor for the group with the blinds. Would be nice to use Phoscon to conf the remote and not HA automations or node-red :)

**Comment by StephanStS** [comment]
Hello @yabbah: Do you mean this button:
<img src="https://user-images.githubusercontent.com/57687516/83336369-2ada0b80-a2b3-11ea-9c28-995af6e94093.png"  width="100" />

If yes, please try the beta app: http://phoscon.de/pwabeta

There is a new switch dialog (Switches *beta*) where you can import more switches:

![grafik](https://user-images.githubusercontent.com/57687516/83336409-6f65a700-a2b3-11ea-90d0-60df607c19a8.png)

**Comment by yabbah** [comment]
Hi, yes I mean that one. I can see the up/down switch in the switch-area, and the switch-beta-area. But when I go to the group where my blind is, chose switch-editor those ones isn't there. Just the round and square on/off. Not the up/down.

**Comment by TheJawa05** [comment]
Same issue as yabbah, Phoscon recognizes the switch but does not list it as available for grouping.

**Comment by YKO-de** [comment]
Hi. I'm working on a roller blind control system. That's why I locked the switch for the editor. I would like to avoid, for the time being, that it is used for other things and that errors occur when I release the roller blind control. So this is intentional.

**Comment by yabbah** [comment]
Any ETA of the control system @YKO-de ?

**Comment by YKO-de** [comment]
It hasn't been decided yet.
