### ISSUE TITLE
Xiaomi Aqara 1-button wireless switch missing "hold" & "double press"

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#72]
ConBee II on Intel x64
Firmware: 264A0700
Version: 2.05.77 / 22.5.2020
OS: DietPi (Debian Buster)
Switch: Xiaomi Aqara  WXKG03LM Rev.2 - (1 button) - 2018 Revision

Phoscon app only displays option to configure a "single press". 

Should also support "double press" and "long single press/hold" conditions.

**Comment by YKO-de** [comment]
Double should work by now. A long was omitted because the switch does not provide a release event.

**Comment by tomillr** [comment]
I'm sorry to reopen this again, but I still haven't found a way to set a double-press action on either the one-button or two-button version of the Aqara switches.

Do you have to first re-setup the switches for this option to show up?
