### ISSUE TITLE
Xiaomi Aqara 2-button wireless switch missing "hold" & "double press"

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#73]
ConBee II on Intel x64
Firmware: 264A0700
Version: 2.05.77 / 22.5.2020
OS: DietPi (Debian Buster)
Switch: Xiaomi Aqara WXKG02LM Rev.2 - (2 button) - 2018 Revision

Phoscon app only displays option to configure a "single press" for the 3 buttons (2 physical buttons + pressing 2 physical buttons at the same time)

Should also support "double press" and "long single press/hold" conditions.

**Comment by YKO-de** [comment]
Double should work by now. A long was omitted because the switch does not provide a release event. If it does not work, please open a new issue.

**Comment by tomillr** [comment]
I've just tried to setup a double-press action. Unfortunately, I couldn't find a way to actually select a double-tap as an action in the Conbee web interface. Do I have to updated the software first to be able to set this action?
