### ISSUE TITLE
IKEA TRÅDFRI slider for color temperature doesn't show selected values

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#74]
ConBee II on Intel x64
Firmware: 264A0700
Version: 2.05.77 / 22.5.2020
OS: DietPi (Debian Buster)
Switch: IKEA TRÅDFRI E14 LED 600 lm 

Phoscon app provides slider to adjust color temperature but doesn't indicate precise value. 

App should display current level, to help users to set multiple lights to identical color temperature.

**Comment by morfei1** [comment]
+1. I agree. It would be very helpful if the slider shows the current white temp in kelvin. If I have to setup specific scene in phoscon, now, I have to use Hue Essential or HA to set up the exact white tempreture I want.

Regards!

**Comment by stocker85** [comment]
+1 it is nice we have the full option to set light as we want but I find it too hard to actually just find the 3 preset colors ikea has e.g 
warm glow - 2200 Kelvin
warm white - 2700 Kelvin
cold white - 4000 Kelvin

**Comment by YKO-de** [comment]
Thank you for pointing that out. We will include the idea in the future planning of the app.
