### ISSUE TITLE
Turn on the light at a specific time (wake-up light)

### ISSUE THREAD

**Issue by AndRe5575** [dresden-elektronik/phoscon-app-beta#75]
Will this function be available in the near future? It should be not so complicated because the oposite is available since a long time (shut of at a specific time including fade time).

**Comment by YKO-de** [comment]
Thank you for pointing that out. We will take it on board and consider it for future development.

**Comment by YKO-de** [comment]
Hey, I was thinking again. You could create a scene with a fade time and then call it up in the timer at a specific time.

**Comment by wschoot** [comment]
As far as I found out (I was looking for the same), it can only be used to fade OUT, not to fade IN (if that's even a word :)

**Comment by YKO-de** [comment]
You could work with two scenes. One to turn on and one to turn off. And you give both a fade time.

**Comment by letszb** [comment]
There is no "turn on" for the schedules but you can call scenes. If there is no scene you see the only option "Turn off group".

**Comment by mgrn0** [comment]
Will there be a "turn on" eventually for schedules? I think it would really make sense to have it form a UX perspective.

**Comment by YKO-de** [comment]
We will take it into account in future planning. Thank you for the hint.
