### ISSUE TITLE
Switch editor: Assign button to specific light in a group

### ISSUE THREAD

**Issue by tomillr** [dresden-elektronik/phoscon-app-beta#77]
The switch editor should provide an option, to select which specific lights should respond to a button press.

As far as I can gather from the [documentation](https://phoscon.de/en/app/doc), one can only program a button to control only ALL lights of a given group or ALL lights connected with the system regardless of its group.

This could work similarly to how it is already done to manually control lights from the main group menu:

![image](https://user-images.githubusercontent.com/1507977/83753767-29ba2d00-a66b-11ea-8c8c-5ae8f4571760.png)

**Comment by YKO-de** [comment]
This is not planned for the time being. But I will include it as a reference for later developement.

**Comment by widert** [comment]
I would also very much like to see this kind of functionality!
