### ISSUE TITLE
Phoscon: Linking a switch button to "Change color temperature" does not do anything

### ISSUE THREAD

**Issue by criemen** [dresden-elektronik/phoscon-app-beta#79]
When linking a button of my Ikea Tradfri remote control to the change color temperature action
(with either toggle, cold or warm), nothing happens when pressing the assigned  button.
This is regardless whether I press it for a long or short time.

**Comment by StephanStS** [comment]
@Cornelius-Riemenschneider: An option could be to add a Node-RED instance on another Pi and connect to the remote control (i.e. receiving all status messages of the remote control).
I use Node-RED for special automation purposes where phoscon is limited in functionality. And with the phoscon nodes *node-red-contrib-deconz* I can monitor/diagnose the nodes quite good and it's easy.

**Comment by Cornelius-Riemenschneider** [comment]
I'll have a look at that, but right now my needs are satisfied if the advertised functionality of phoscon would work, thus this bugreport :)

**Comment by YKO-de** [comment]
Is the problem still there?

**Comment by hetti72** [comment]
I´m facing the same issue. I tried different Tradfri remotes with various Tradfri and Hue Lights, it didnt work. 
I´m currently running Deconz 2.05.78 with a Connbee2 Stick

**Comment by Cornelius-Riemenschneider** [comment]
Yes, I just pulled from marthoc/deconz:latest, and the problem still persists.

**Comment by jdeluyck** [comment]
Can confirm this problem is still present with Deconz 2.05.79.
I tried yesterday to rebuild my automation from HA with just Phoscon, but the light temperature buttons don't do anything.

**Comment by truidix** [comment]
Hey all, 

I do have the same problems (Ikea e27 980 lm). As I’m using the tradfri remotes, with an old firmware I thought that’s the problem. So updates all of my remotes firmware today to 2.3.014, but still not working. As you guys having the trouble I would guess it is not a remote problem.


Im on phoscon 2.05.80.

Any ideas how to address that? 

Thx

**Comment by YKO-de** [comment]
We are working on finding out what it is. As there are several issues on this problem I would like to close this one now. 

https://github.com/dresden-elektronik/phoscon-app-beta/issues/176
