### ISSUE TITLE
Phoscon doesn't find my deCONZ instance

### ISSUE THREAD

**Issue by Kane610** [dresden-elektronik/phoscon-app-beta#8]
Even when running Phoscon from http://<ip-address>:<port>/pwa it doesn't find my deCONZ instance. It finds my Hue Bridge and it found deCONZ when it was running on my raspberry.

**Comment by manup** [comment]
Can you please provide more details:
* Ubuntu or Windows?
* How is deCONZ started &mdash; systemd or directly commandline?


If discovery is enabled (default) it might be listed at:
http://www.dresden-elektronik.de/discover/

**Comment by Kane610** [comment]
Discover works and find deCONZ.
Im running deCONZ on an x86 Debian machine
Im running deCONZ using systemd, with ExecStart=/usr/bin/deCONZ --auto-connect=1 -platform minimal --http-port=8088 --ws-port=8090 --dbg-error=1

**Comment by manup** [comment]
So `http://<ip-address>:8088/pwa` does work too? The port must be specified in browser if not 80.

**Comment by Kane610** [comment]
No, unfortunately http://<ip-address>:8088/pwa doesn't help in Phoscon finding the gateway

**Comment by manup** [comment]
So the Phoscon site open at http://:8088/pwa but gateway isn't listed?
If so, it's because Phoscon @ /pwa does look for gateways at port 80 and 8080.

You can try a workaround:

    http://<ip-adress>:8088/pwa#host/<ip-address>:8088

**Comment by Kane610** [comment]
That didn't work. Can't phoscon take the full path magically?

**Comment by manup** [comment]
I thought it does by extracting the ip and port from the url. Not sure why it doesn't work in this case. I'll check during weekend.

**Comment by manup** [comment]
The port was missing in local host url parsing.
Please try again with latest version 2.05.07 it should work now in the local Phoscon App.

    http://<ip-address>:8090/pwa

http://www.dresden-elektronik.de/rpi/deconz/beta/deconz-2.05.07-qt5.deb

**Comment by Kane610** [comment]
Cant test it out since ubuntu version isn't available yet

**Comment by manup** [comment]
It's online now:

http://www.dresden-elektronik.de/rpi/deconz/beta/deconz-2.05.07-qt5.deb

**Comment by Kane610** [comment]
Great! Will try it out tomorrow. I've had enough frustration for this evening. New energy and I can continue. Will also get an extension cord to try to move the conbee around

**Comment by Kane610** [comment]
It does indeed work on the latest release. Thanks!
