### ISSUE TITLE
missing feature - disconnected sensor notification

### ISSUE THREAD

**Issue by elpaso666** [dresden-elektronik/phoscon-app-beta#82]
Hello,

would it be possible to add directly to phoscon app and email notification when sensor gets disconnected?

it would be very nice to avoid manual scripting/monitoring and have this feature avaibale directly in the central ZigBee gateway.

thank you
Jakub

**Comment by StephanStS** [comment]
@Sjonnie2018: An option could be to use a Node-RED instance on another Pi, then using the nodes from node-red-contrib-deconz. With this you could do a battery monitoring or a communication monitoring to the zigbee devices.
Only to show that the battery level is able to be given in Node-RED:
![grafik](https://user-images.githubusercontent.com/57687516/83884580-5d698580-a745-11ea-9a4a-c4790a560477.png)

**Comment by SwoopX** [comment]
Point is, zigbee is stateless, it has no keep-alive. What you see in deconz is routes instead, so ways of possible communication. That being said, you cannot notify on non-availability as you probably would like.

For sensors, they switch to non-reachable after 24h of not receiving any reports or commands. For lights, that timeframe is way shorter as I recall. So disregard of your intention, just wanted to make sure you get some insights for the mechanisms.

**Comment by StephanStS** [comment]
In case of a sensor or switch you are able to trigger the communication flow via a different node:
![grafik](https://user-images.githubusercontent.com/57687516/83886856-ee416080-a747-11ea-999a-2d34bb5e2d65.png)

But it is unsure, whether this trigger only gets a buffered value from phoscon or whether it tries to communicate with the node.
@YKO-de: Possibly you can answer this.

But look at the whole message of such a cyclic triggered node (example Xiaomi smart cube):
![grafik](https://user-images.githubusercontent.com/57687516/83887149-542de800-a748-11ea-8315-35e51c22f46b.png)
The properties *lastseen* or *lastupdated* would be an option. 

Sometimes also a property *reachable* is present (example Philips motion sensor):
![grafik](https://user-images.githubusercontent.com/57687516/83887601-f77efd00-a748-11ea-862d-b2fc84f30b23.png)

**Comment by YKO-de** [comment]
A communication to the outside. For example email is not provided in the phoscon app. Possibly once in the later planning.
