### ISSUE TITLE
Hue Go did not connect

### ISSUE THREAD

**Issue by Piccar** [dresden-elektronik/phoscon-app-beta#84]
I tried to connect the the Philips Hue Go to the conbee II stick via the Phoscon Web-App. I tried multiple time to reset the Lamp(hold the button ca. 10sec until blue flashes) even drain all the Power from it. But the Web-app could not find it. Since the Website marked it as compatible I made myself a goaround: The only way for me to connect is was via the android app hue essentials. Once I was logged in the Lamp was found via Phlips hue bluetooth in secounds. Maybe somebody needed this tipp(Or it could be added in the wiki?)

**Comment by YKO-de** [comment]
Is the problem still relevant? Should be fixed with deCONZ 2.05.77 and FW 26580700.

**Comment by Piccar** [comment]
Well I can't reepoduce the problem right now... seems fine now!

**Comment by lillaeriika** [comment]
Had problems with adding my Hue Go to deConz but i worked after I did a factory reset via HUE BT app.

1. Connect with the Hue Go in the Hue Bluetooth app, and with your phone close to the Hue Go.
2. Verify that it works by controlling the color of the light.
3. From the Hue Bluetooth app, reset the light by going into Settings, then Select the light, then Reset to make it Factory New.
