### ISSUE TITLE
Phoscon/Deconz Issues

### ISSUE THREAD

**Issue by meremortals70** [dresden-elektronik/phoscon-app-beta#85]
Hi there

On a couple of recently added devices to Deconz having some issues.

First Issue

When the SZ-ESW01 plugs are added to Deconz, they have different names. This normally isn't an issue as when you change the name in Phoscon it updates in Deconz. However, when these plugs which are detected as lights, are renamed in Phoscon the names are either not updated in Deconz or are updated but not persistent so when Deconz is restarted the names revert.

![](https://user-images.githubusercontent.com/52735978/83985134-5461f980-a97b-11ea-95c4-f3cd71c614ad.png)

Second Issue

When the SZ-DWS04 are added the don't appear in Phoscon however will appear under the Deconz Integration in HA, they don't appear in Phoscon. They cannot be renamed here which normally propagates up to HA and down to Deconz. When renamed in the HA Deconz integration this does not propagate down to Deconz. when Deconz is restarted they reset their names and as a consequence become unavailable in HA as I have renamed them there.

![](https://user-images.githubusercontent.com/52735978/83985315-08fc1b00-a97c-11ea-9781-5cb71c98de47.png)

This is the same for some Tuya Temperature/Humidity Sensors.

![](https://user-images.githubusercontent.com/52735978/83985338-2f21bb00-a97c-11ea-9638-5891bb7b4890.png)

I have downgraded deconz to .75 due to the issues with .76 and .77

**Comment by YKO-de** [comment]
Does the problem still exist. Then please reopen the issue.

**Comment by meremortals70** [comment]
I no longer use Deconz, I dumped it and went to ZHA thanks
