### ISSUE TITLE
[DEVICE REQUEST] Smartthings/Sanjin Water Leak Sensor 2016 (STS-WTR-250)

### ISSUE THREAD

**Issue by Polyknikes** [dresden-elektronik/phoscon-app-beta#87]
Hello all,

I have a number of these smartthings water sensors (the 2016 model) and although they are supported as of deCONZ version 0.65 and are added to the mesh and visible as nodes/clusters under the deCONZ VNC viewer they do not add as sensors in the phoscon app. I am new to this world so forgive me if my terminology is off. Please let me know if there is any further information needed.

Thanks

**Comment by Polyknikes** [comment]
> Can you tell me your software version? Basically there is only a date behind the version at Gateway. Because it should be supported and visible.

Version 2.05.75 / 3/8/2020
Firmware 264A0700

**Comment by YKO-de** [comment]
Can you tell me the modelid of the sensor?
