### ISSUE TITLE
First run without online connection

### ISSUE THREAD

**Issue by iwezig** [dresden-elektronik/phoscon-app-beta#9]
"The app is loaded from our web server but runs just locally in your browser and communicates directly with the gateway (no cloud)."

"The app works offline once loaded for the first time (via HTML5 AppCache)."

-> Would be nice if Raspeegateway could  serve the discovery-page instad of an online source to archive easier deployment (similar to webapp).

**Comment by manup** [comment]
I need to update the description.
Beside the internet served version, the Phoscon App can be opened in local network too: `http://<raspberrypi-ip>/pwa`

**Comment by iwezig** [comment]
Thank you for quick support.
