### ISSUE TITLE
Sensors and Switches not visible in Phoscon

### ISSUE THREAD

**Issue by nunoary** [dresden-elektronik/phoscon-app-beta#90]
All my sensors and switches disappeared from Phoscon, but they are accessible via the Deconz GUI, and they seems to communicate normally. The lights are visible.

This happen with version 2.05.77 after adding a new switch (IKEA ON/OFF), reverted to 2.05.75 but still not showing. Have already tried several browsers.
I run Deconz under Windows 10. My Conbee 1 is updated to 26350500.

I get one Javascript error. These are the errors from the page:

DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/underscore-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/backbone-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

global.js?70da81:3 apikey = xxxxxxxxxxx
global.js?70da81:3 activated theme Bright
poll.js?5bcca9:3 add poll repeated sensors
open-beta.js?78d500:3

GET http://MyIPxxxxxx/pwa/developer.js 404 (Not Found)
(anonymous) @ open-beta.js?78d500:3
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/underscore-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://MyIPxxxxxx/pwa/library/js/backbone-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
websocket.js?e9ddc6:3 websocket connected: ws://MyIPxxxxxx/
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
poll.js?5bcca9:3 poll error {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}

**Comment by duffbeer2000** [comment]
http://192.168.178.13:8189/api/80CB2B2AF7/sensors

**Comment by duffbeer2000** [comment]
What you get if you open: http://XXX.XXX.XXX.XXX/api/YYYYYYYYYYY/sensors
Replaxe the XXX with the ip-address of deconz and YYY with your API-Key.

**Comment by nunoary** [comment]
[Phoscon.txt](https://github.com/dresden-elektronik/phoscon-app-beta/files/4753924/Phoscon.txt)

Hi @duffbeer2000 

Attached the file with the information i get.

**Comment by duffbeer2000** [comment]
I found the problem, it's the same I had a few days ago:
"manufacturername":"KE","mode":1,"modelid":"TRADFRI open/close remote","name":"Comando Persiana Sala 1","state":{"buttonevent":null,"lastupdated":"none"},"swversion":"2.2.008","type":"ZHASwitch"

The manufacturername is the problem, because it has bad characters in it. That's what firefox says if you open the file you provided: "SyntaxError: JSON.parse: bad control character in string literal at line 1 column 39245 of the JSON data"

So, here is how I solved it with help from @ebaauw :
1. open Deconz
2. Search the Switch and click on the right bubble
3. click on Basic
4. on the left side open the "Cluster Info" tab
5. under Attributes click on read and press a button from the switch (that's needed because it's battery powered)
6. after that there should be informations filled like manufacturername
7. if it's still "[]KE" then double click on manufactrername in the Cluster Info and click read in the attribute editor which opens and press again a button on the switch to activate it
8. if it's still not "IKEA" than go in phoscon search for a new switch and reset the switch to factory defaults (without deleting it before), after that start again with the first step.

**Comment by nunoary** [comment]
@duffbeer2000 

Thanks, that solved the problem. The sensors and switches have returned, despite having lost the names I assigned to almost everyone. I never thought the solution would be to read the cluester :) Thank you very much.

**Comment by duffbeer2000** [comment]
@nunoary Perfect! Did you reset to factory defaults or was reading the manufacturername enough?
And please close the ticket after the answer ;)

**Comment by nunoary** [comment]
I have to reset to factory defaults. Thanks again. Close.
