### ISSUE TITLE
Feature Request: Use different scenes when turning on at different times

### ISSUE THREAD

**Issue by imbaimbaimba** [dresden-elektronik/phoscon-app-beta#96]
I have used deCONZ for years by now, and I remember a long time ago there was talk about this feature, but have not heard anything about it for a long time.
I would like to make it so that when I turn on off my lights, say 20:00-06:00 then they are warm and dim, but 06:00-20:00 they are cold and bright.
Is this something that can be implemented?

**Comment by morfei1** [comment]
Yeah, it would be great, if we can. I have a workaround for this using automations in HA. If a light or group is switch ON between 6:30 - 22:00 it use phoscon scene 4000k / 80% brightness. If the same light or group is switch ON between 22:00 - 6:30 it remembers the last state.

I hope to see this function in phoscon in the near future.

**Comment by YKO-de** [comment]
We are working on it ;)
