### ISSUE TITLE
Question: One of my IKEA Trådfri Remote Control does not generate a group - how to?

### ISSUE THREAD

**Issue by imbaimbaimba** [dresden-elektronik/phoscon-app-beta#97]
Hi everyone,

So I got these 5-button IKEA remote controls that are converted into wall switches all over the house. It all works fine, but there is one of them that does not generate a group inside the Phoscon app by itself. Usually that group is where I go and press "Manage Lights" and choose the lights that the switch will control directly. I tried rebooting etc. but the automatically created group for the switch just does not show up.
Anything I can do to fix that?

![missing](https://user-images.githubusercontent.com/25137998/80530005-ac7b0880-8998-11ea-9a0f-26e5db931c5d.png)

**Comment by morfei1** [comment]
You can use the workaround method to do this. I had this problem with all my 3 tradfri round remotes.

login the the OldWebApp interface.
user: dilight
pass: your current password to log in phoscon.

go to "groups" add a light to the remote you are not able to see in phoscon as a separate group.
Then login back to the phoscon app and you should see the missing remote group.

I did it 3 times in a row, and it's working.

Regards!

**Comment by jbigte** [comment]
Thanks for sharing this workaround method, I had the same issue. There's a small typo in the login instructions you've given, though: the user should be "delight" and not "dilight".

**Comment by YKO-de** [comment]
The removal of the switch groups was intentional. Because many users had problems with using Switch Group and Switch Editor. We are working on a solution. But this will take some time.
