### ISSUE TITLE
Is Philips Go really compatible with Deconz?

### ISSUE THREAD

**Issue by SnaKKo** [dresden-elektronik/phoscon-app-beta#98]
Hi,
Does Philips Go works correctly with Deconz?
I'm reading a lot of issues here on Github about it.

Anyone tried succesfully? Do you have problems with Philips Go/Deconz? Thanks

**Comment by letszb** [comment]
I use the Hue Go 2nd generation with Bluetooth successfully in deCONZ. It was possible to update the firmware via the Hue Bluetooth App. Also the light can be connected and used via Bluetooth and Zigbee at the same time. It was only important to reset the light before it was found in the Phoscon App. This should be done with a long keystroke (?) on the light, with a Hue Dimmswitch or if it is connected to a Hue-Bridge (Zigbee, not Bluetooth) and deleted there.
